### ISSUE TITLE
Dunzo - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#100]
**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/fulfillments/contact/phone must NOT have fewer than 10 characters
- /message/catalog/bpp/providers/items must have required property '@ondc/org/return_window'
- /message/catalog/bpp/providers/items/quantity/unitized/measure/value must be string
- /message/catalog/bpp/providers/items/time must have required property 'label'
- value passed in serviceability tags should be same as passed in location/circle

**search_inc_refresh**

- context/city should be "\*" while sending search_inc_catalog request

**on_search_inc_refresh**

- /message/catalog/bpp~1providers/items/quantity/unitized/measure/value must be string
- /message/catalog/bpp~1providers/items/time must have required property 'label'

**select**

- Timestamp for /on_search api cannot be greater than or equal to /select api

**on_init**

- /message/order must have required property 'tags'

**on_confirm**

- /message/order must have required property 'tags'
- email mismatches in /billing in /confirm and /on_confirm
- Discrepancies between the quote object /on_select and /on_confirm

@Ankush

**Comment by ankush1106** [comment]
@sahil-ondc 
PR for mentioned fixes: https://github.com/ONDC-Official/v1.2.0-logs/pull/586

clarifications:
**on_confirm**
- Discrepancies between the quote object /on_select and /on_confirm
there is no discrepancies, there are two select calls, in one select call the item is unavailable so its price is 0, in next select call the item is removed from cart.

**Comment by BLR-0118** [comment]
Flow 1
====
1. full catalog pull (/on_search):
- for item.quantity.available.count, we use "99" (in-stock) or 0 (out-of-stock); can we pls follow this?
- for item.quantity.maximum.count, we use "99" (no cap per order) or any other non-zero value for cap per order; can we pls follow this?
- everything else looks ok;

2. incremental pull:
- item details for item (5bc87ae10d298a283c296d32) being sent in incremental pull & full pull are exactly the same; what's changed for this item for it to be sent in incremental pull?
- same for item 5bc87ae10d298a283c296de1;
- are you supporting incremental push (will be required to significantly reduce attempt-to-confirm errors)?

Flow 2
====
1. /on_init:
- pls add provider.locations (similar to /on_select);
- pls remove provider_location;
- pls remove everything from bpp_terms except tax_number (to be enabled with static terms);

2. /on_confirm:
- pls add TAT to fulfillment (similar to /on_select);
- pls remove everything from bpp_terms except tax_number;

3. /on_status:
- seller invoice should be added at "Order-picked-up" fulfillment state;

4. /on_track:
a. tracking.location.time.timestamp identifies the "as of" timestamp for gps coordinates;
b. tracking.updated_at identifies when this was updated in the system;
c. hence, by definition, b >= a;
d. to optimize track requests from the buyer app, pls enable the following (thru /on_status) when gps coordinates are enabled as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.mg00vd1pw4r6):
- routing.type to "P2P" (means point-to-point);
- tracking.gps_enabled to "yes" (means gps coordinates are enabled & buyer apps can start making /track requests);

Flow 3
====
1. /on_select (out of stock):
- error.message should be in the format doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

Also, pls share logs for flow 4 & 5 and if possible 6;
Pls start using the RET codes in Context.domain - all RET codes will be enabled for participants are log clearance;

**Comment by BLR-0118** [comment]
@ankush1106 - pls fix the above & resubmit only for the issues mentioned;

**Comment by ankush1106** [comment]
@BLR-0118 as discussed please check this PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/664

## Flow 1
**full catalog pull (/on_search):**

- for item.quantity.available.count, we use "99" (in-stock) or 0 (out-of-stock); can we pls follow this? [DONE]
- for item.quantity.maximum.count, we use "99" (no cap per order) or any other non-zero value for cap per order; can we pls follow this? [DONE]

**incremental pull:**

- item details for item (5bc87ae10d298a283c296d32) being sent in incremental pull & full pull are exactly the same; what's changed for this item for it to be sent in incremental pull? [Item name/description were updated]
- same for item 5bc87ae10d298a283c296de1 [Item name/description were updated]

## Flow 2
**/on_init:**

- pls add provider.locations (similar to /on_select); [DONE]
- pls remove provider_location; [DONE]
- pls remove everything from bpp_terms except tax_number (to be enabled with static terms); [DONE]

**/on_confirm:**

- pls add TAT to fulfillment (similar to /on_select); [DONE]
- pls remove everything from bpp_terms except tax_number; [DONE]

**/on_status:**

- seller invoice should be added at "Order-picked-up" fulfillment state; [DONE]

**/on_track:**

- [fixed the tracking.updated_at and tracking.location.time.timestamp, tracking.location.time.timestamp will be time when runner coordinates were updated and tracking.updated_at will be context.timestamp]
- routing.type to "P2P" (means point-to-point); [DONE]

## Flow 3
**/on_select (out of stock):**
- error.message should be in the format doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl); [DONE]

Flow 4 added

**Comment by BLR-0118** [comment]
Checked flow 4 - all issues mentioned above fixed except /on_cancel;

/on_cancel:
1. quote.breakup shows item_quantity as 0 for both items but total price for item remains the same; this is incorrect as total price = qty * unit price;
2. quote_trail isn't updated for the cancellation fulfillment;

Pls fix /on_cancel & resubmit only this; also, pls share log for flow 5 which is almost similar to flow 4;

Also, pls share timeline for flow 6 (a, c) which are required for grocery

@ankush1106

**Comment by ankush1106** [comment]
fixed flow 4 review comments

**/on_cancel:**

- quote.breakup shows item_quantity as 0 for both items but total price for item remains the same; this is incorrect as total price = qty * unit price; [Fixed]
- quote_trail isn't updated for the cancellation fulfillment; [Fixed]

@BLR-0118

**Comment by BLR-0118** [comment]
flow 4
====
1. /on_init:
- remove provider_location (removed);
- remove payment.collected_by, payment.type, payment.status (filled by buyer app in /confirm for prepaid payment);

**Comment by BLR-0118** [comment]
@ankush1106 - pls have the above fixed & make a note here;
logs for v1.2.0 (RET10) approved;
