### ISSUE TITLE
MyyShopp (lokal.in) SA (RSF) - complaince check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1013]
Flow 1:

 Receiver_recon:

- message.orderbook.orders.updated_at should be greater than settlement timestamp , here settlement_timestamp is settlement_timestamp": "2024-02-20T12:40:10.262Z and updated Timestamp is updated_at": "2024-02-20T12:39:10.262Z

@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Issue fixed and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/1043

**Comment by RupalSingla** [comment]
logs approved for RSF v 1.0.0

@Srinath91

**Comment by RupalSingla** [comment]
logs approved for RSF v 1.0.0
