### ISSUE TITLE
eSamudaay - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#107]
### RET:10

**on_search_full_catalog_refresh**

- /context/action must be equal to constant (on_search)
- /message/catalog/bpp/providers/locations/time must have required property 'label'
- /message/catalog/bpp/providers/locations/time must have required property 'timestamp'
- street and locality should not have same value in /message/catalog/bpp/providers/locations/address
- /message/catalog/bpp/providers/locations/address/gps reverse coding mismatchin with provided with provided area_code
- /message/catalog/bpp/providers/categories/id must be string
- /message/catalog/bpp/providers/items/ must have required property '@ondc/org/return_window'
- category in serviceability construct should be one of the category ids bpp/providers/items/category_id

**search_inc_catalog_refresh**

- Transaction logs for incremental search not provided

**on_search_inc_catalog_refresh**

- Transaction logs for incremental search not provided

**on_init**

- gps coordinates in fulfillments.end.location mismatch in /select & /on_init
- /message/order must have required property 'tags'

**on_init**

- fulfillments.end.location gps is not matching with gps in /select

**common**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

@Namratha102000

**Comment by Namratha102000** [comment]
- /message/catalog/bpp/providers/locations/time must have required property 'timestamp' - **what must this timestamp indicate should it be current timestamp on something else** 
- /message/catalog/bpp/providers/items/ must have required property '@ondc/org/return_window'- **if the product is not reurnable then it is opitonal right**

**Comment by Namratha102000** [comment]
@sharmasahil0331 If the Settlement is done by buyer app should we still have '@ondc/org/withholding_amount'

**Comment by Namratha102000** [comment]
@sharmasahil0331 grocery ONDCRET:10 and incremental search is submitted please review it. We have MSN to onboard and this is becoming a blocker and no much response is seen here

**Comment by Namratha102000** [comment]
- Regarding settlement_basis, settlement_window, etc., if buyer apps include this information in the confirm API, we will also append these details in the on_confirm API.
- /message/order must have required property 'tags' is phase 2 asked Supriyo sir on this.

**Raised a PR with other correction today.**
@sharmasahil0331

**Comment by Namratha102000** [comment]
@sharmasahil0331 Raised a PR again with corrections

**Comment by Namratha102000** [comment]
@sharmasahil0331 Slot delivery and order tracking we are not supporting

**Comment by sharmasahil0331** [comment]
### RET10

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/categories/id must be string
- /message/catalog/bpp/providers/items/ must have required property '@ondc/org/return_window'
- duplicate item id: 23339 in bpp/providers[0]
- 'street' and 'locality' must have unique values in message/catalog/bpp/providers/locations/address

**search_inc_refresh**

- /message/intent/payment/@ondc/org/buyer_app_finder_fee_amount must be string
- context/timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

**on_search_inc_refresh**

- json must have required property 'message'

**select**

- Timestamp for /on_search api cannot be greater than or equal to /select api

**on_select**

- City code mismatch in /search and /on_select

**on_init**

- message/order must have required property 'tags'
- message/order/quote/breakup should be as per the API contract


**confirm**

- /message/order/tags/0/list/0 must have required property 'value'

**on_status**

- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'

@Namratha102000

**Comment by Namratha102000** [comment]
select

    Timestamp for /on_search api cannot be greater than or equal to /select api
    
I've made modifications to the search API and resubmitted it for flow1, which may be causing the current issue. Kindly overlook

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/261 @sharmasahil0331 raised for ondc:ret10 changes

**Comment by Namratha102000** [comment]
message/order/quote/breakup should be as per the API contract
What is missing? @sharmasahil0331

**Comment by Namratha102000** [comment]
Hi please review both grocery and food

**Comment by Namratha102000** [comment]
Hi its been one week please review.

**Comment by Namratha102000** [comment]
- Timestamp for /on_search api cannot be greater than or equal to /select api - I've made modifications to the search API and resubmitted it for flow1, which may be causing the current issue. Kindly overlook

- message/order/quote/breakup should be as per the API contract ......it is as per contract itself please let us know what we are missing

@sahil-ondc

**Comment by bluecypher** [comment]
@Namratha102000, pls reshare the logs. The folder seems missing.

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/327
Resubmitted the logs..in the above PR Please review as early as possible


our logs were deleted by @kunalbharti https://github.com/kunalbharti?tab=overview&from=2023-11-01&to=2023-11-30

**Comment by bluecypher** [comment]
### Please use the log validation utility before submitting the logs

# RET10

## Flow 1

**/on_search**

- Beverages (MTO), Boy's Clothing and North Indian are not a valid subcategories in grocery domain
- invalid location id in /bpp/providers/tags/timing
- Delivery and Self-Pickup is not a valid type in /bpp/providers/tags/timing
- country of origin should be in valid ISO 3166-1 alpha-3 code
- item pizza can't be in "Boy's Clothing" category; invalid item for grocery domain; similar issue with other SKUs
- fssai license no is not required in Grocery domain
- id in categories should be in string format
- attr name in variant_group is not defined correctly
- "Delivery and Self-Pickup" is not a valid fulfillment type in /bpp/providers/fulfillments

**/on_search (incremental)**

- context/timestamp can't be earlier than /search timestamp
- full catalog should not be provided in incremental catalog (refer to the contract for example schemas)
- city code must be \* in incremental refresh
- message_id should be same for one-time incremental refresh

## Flow 2

**/on_select**

- fulfillment category and TAT mapping should be correct; "Immediate Delivery" must be fulfilled within 2 hours
- available and maximum count should not change; the logic is same as in /on_search catalog

**/on_confirm**

- tax numbers are missing in /order/tags
- invoice should only be provided when order is picked and thereafter

**/on_status**

- all the interim fulfillment states must be provided for verification
- actual pickup (/fulfillments/start/time/timestamp) and delivery (fulfillments/end/time/timestamp) timestamps can't be the same

## Flow 3

- OOS scenario must be provided for log verification

## Flow 4

**/cancel**

- invalid cancellation reason id "012", can't be initiated by BNP; should be NACK'd by SNP;

**/on_cancel**

- quote_trail is missing
- quote is not updated

## Flow 5

- RTO flow is missing (/on_cancel should be called initiating the RTO)

# RET11

- similar issues as above

**/on_search**

- invalid values of parent_category_id in /categories
- display rank of all the custom menus can't be same; rank is set as "1" for all the custom menus

**/on_select (OOS)**

- error message should be in stringified JSON format as mentioned in the contract


@Namratha102000

**Comment by Namratha102000** [comment]
fssai license no is not required in Grocery domain
**Packaged meat or diary items have fssai number** @sahil-ondc

**Comment by bluecypher** [comment]
@Namratha102000, Yes,  FSSAI license no. can be shared for prepackaged food. However, there is a significant discrepancy in the grocery catalog itself, particularly concerning the listing of F&B products.

**Comment by Namratha102000** [comment]
@sahil-ondc please merge https://github.com/ONDC-Official/v1.2.0-logs/pull/355 this also and please do review updated flows

**Comment by Namratha102000** [comment]
Please review this

**Comment by bluecypher** [comment]
@Namratha102000, please fix all the previously identified issues. There are some repeated issues in the submitted payloads.

**Comment by bluecypher** [comment]
# RET10

## Flow 1

**/on_search**

- Boy's Clothing is not a valid category in grocery domain
- "Unit" is not a valid enum for quantity/unitized/measure/unit; should be "unit" ('u' in lower case)
- definition of variant groups missing in /categories; eg: item: "21290" is mapped to the variant group: "15999" but the definition is missing
- definition of custom menu missing in /categories eg: item: "21290" is mapped with custom menu "4009" but the definition is missing
- placeholder images of items should not be sent; if image is not available, SNP should not send image; eg: "https://media.test.esamudaay.com/user-media/BCK3_3T7EEy3.jpg" consists of placeholder image
- items must be mapped to valid category; eg: "paneer chilly powder" can't be mapped to "Eggs, Meat & Fish" while this item falls in veg category, veg= "yes"
- item "Pizza powder" can't be in "Boy's Clothing" category; invalid item for grocery domain; similar issue with other SKUs
- attr name in variant_group is not defined correctly; please check the contract (should be a valid path to the item attribute)
- fulfillment_id is not mapped correctly in /items; "3" is not a valid fulfillment id

**/on_search (incremental)**

- full catalog should not be provided in incremental catalog (refer to the contract for example schemas)

## Flow 2

**/on_select**

- tax should not be added for grocery products; item prices are tax inclusive; tax levied on fulfillment should have quote type = "fulfillment" (pls check tax calculation here as well: delivery charges are Rs 40/-, convenience charges are Rs 25.04/- while tax = Rs 21.75/-)

**/on_confirm**

- "provider_id" is not a valid attribute in /fulfillments

**/on_status**

- invoice should only be provided when order state is Order-picked-up and thereafter
- on_status with "Order-picked-up" and Order-delivered state is missing;
- invalid acutal pickup timestamp; pick up time should be captured from "Order-picked-up" state instead of "Out-for-delivery" state

## Flow 3

**/on_select (OOS)**

- available count in quote/breakup/item/quantity should be "0" for OOS item

## Flow 4

**/on_cancel**

- quote breakup is not updated; quantity should become 0 for cancelled item
- why is fulfillment related charges (delivery/convenience fee) charged when order is still in Pending state?

## Flow 5

**/on_status (picked)**

- actual pickup timestamp is missing
- agent/phone should be a valid 10 digit number (+91 should be removed)

**/on_cancel (RTO)**

- quote/breakup should be updated; quantity of item will be "0", other charges should be updated accordingly as per the quote_trail
- "002" is not a valid RTO triggering cancellation reason id

#### RTO should either be disposed or delivered through /on_status

# RET11

- similar issues as above

**/on_search**

- serviceability definition should be feasible; 15000 km is defined for F&B category. Is this intended?

**/select**

- no custom groups and customizations defined in the catalog; same catalog should be used for cart selection


@Namratha102000, please fix these issues as well.

**Comment by Namratha102000** [comment]
@bluecypher We dont have two different states for pickup and out for delivery. We have only one that is out for delivery so timestamp captured during that time

**Comment by Namratha102000** [comment]
@bluecypher placeholder images of items should not be sent; if image is not available, SNP should not send image; eg: "https://media.test.esamudaay.com/user-media/BCK3_3T7EEy3.jpg" consists of placeholder image. **We don't use placeholder images all images are unique as you can see. This image testing team as put as its just a test store and not live store.**. Kindly overlook

**Comment by Namratha102000** [comment]
serviceability definition should be feasible; 15000 km is defined for F&B category. Is this intended? yes its intended...we had set this for few other testing purposes.
@bluecypher

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/384 @bluecypher Hi raised PR for food only. Please review **as its hyperlocal two different states for pickup and out for delivery are not present. 15000 km was set for some testing purposes.** @bluecypher

**Comment by Namratha102000** [comment]
Please merge and review this.

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/384 please and merge and review this

**Comment by bluecypher** [comment]
## Please use log validation utility before log submission

## Please test with reference buyer app or any other verified buyer app in pre-prod

**/on_search**

- context should be updated as per the API call;
  - action should be on_search
  - bpp_id/bpp_uri missing
  - timestamp is not updated
- items and their associated category mapping (for some of the items) is not accurate; please use generic "F&B" as category_id; eg: honey is mapped to Chips category
- 150000 km is not a feasible range for hyperlocal delivery; avoid using test values
- enable/disable timestamp in bpp/providers can't be future dated; should be <=context/timestamp
- placeholder images of items should not be sent; if image is not available, SNP should not send image; eg: "https://media.test.esamudaay.com/user-media/cartoon_vegetables_01_vector_156329_GSLDNSm.jpg" consists of placeholder image (not an image of a sandwich)

**/on_search (incremental)**

- "3" is not a valid fulfillment_id in /items

**/on_select**

- price of customization "36347_757_480" mismatches in catalog and quote/breakup
- max(time to ship) of items provided in catalog (@ondc/org/time_to_ship ) can't be the same as delivery TAT "@ondc/org/TAT"; time_to_ship < TAT
- tax line item should be present in quote/breakup for F&B category items

**/on_init**

- order/provider_location is not required; the key is deprecated
- /fulfillments/start is not required in /on_init

**/on_confirm**

- bap tax_number missing in /tags/bap_terms

**/on_status**

- ttl should be PT30S
- "Order-picked-up" state must be provided

**/on_track**

- tracking should be supported for hyperlocal RET11 fulfillments

## Flow 3

**/on_select (OOS)**

- error.message should be as per the contract; for customizable items, following format must be used:
  "[{dynamic_item_id:DI1,item_id:I1,error:40002}, {dynamic_item_id:DI2,customization_id:C15,customization_group_id:CG3,error:40002}]"

## Flow 4

**/on_cancel**

- total price of item (quote/breakup/price) should be 0 when count=0
- quote/price should be = sum of (quote/breakup/price)
- why is convenience fee being charged from the buyer when cancellation is performed before order is packed

## Flow 5
- similar issues as above
- check previously identified issues; repeated issues in the submitted logs


@Namratha102000

**Comment by Namratha102000** [comment]
@bluecypher I raised a pull request, tested it with the utility, and addressed appropriate errors.

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- why is min customization selection set as 99 in custom group configuration?
- certain items from grocery category; eg: "36345", shouldn't be provided in F&B catalog; prices are tax inclusive for grocery SKUs

**/search (inc)**

- timestamp can't be the same as full catalog search
- The item: "38833" is disabled, but the timestamp for the disabling is not updated.

## Flow 2

**/on_select**

- fulfillment category and TAT mapping should be correct; "Immediate Delivery" must be fulfilled within 2 hours

**/on_init**

- fulfillments/start is an optional attribute
- provider_id is not required in /fulfillments

**/on_status**

- invoice should only be provided when order is picked and thereafter

## Flow 3

**/on_select (OOS)**

- message in /error should be in stringified JSON format: eg- [{"dynamic_item_id":"DI0","item_id":"36347","error":"40002"},{.....}]

## Flow 4

**/on_cancel**

- tags are missing for items mapped to the "Cancellation1" fulfillment id in /items
- code= "type" is missing in the quote_trail where subtype="customization"
- quote_trail should only be provided for adjusted values and not for the charges where value=0; eg: "-0" is invalid value in quote_trail

## Flow 5

- similar issues as in above flows
- message_id should be unique for unsolicited calls; (/on_cancel (RTO) and /on_status (rto disposed))


@Namratha102000

**Comment by Namratha102000** [comment]
@bluecypher https://github.com/ONDC-Official/v1.2.0-logs/pull/507/files#diff-949619afa89f51417c38b7a29d7d0310639d465508cf007cdeb8c06a86ea13bc Raised a PR with fixes

**Comment by Namratha102000** [comment]
@bluecypher @BLR-0118 Please help us to close this quickly. We have 4 MSN's in preprod waiting to be onboadered.  Three of them are for F&B.

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full):
- for custom_group "36345_758", code="min" is missing?
- curious what max of "99" means for custom group?
- no use case for base item price of 0 but customizations having non-zero price (for which either the default selection price of range of upper/lower needs to be sent?

2. /on_search (inc):
- do you support incremental update using push?
- do you support merchant store open / close / disable, etc, which are more common in F&B?

Flow 2
====
1. /on_init:
- fulfillment.start.location shouldn't be sent in /on_init;
- payment should exclude everything except buyer finder fee / settlement details;

Flow 3
====
1. /on_select (oos):
- customization 36347_757_479 is missing from items array & quote.breakup, even though error.message says it's out of stock;

Flow 4 & 5
=======
1. /on_cancel:
- request to add precancel_state to Fulfillment1;

Also:
- tracking is true in Flow 2 but no track, /on_track APIs?
- plans to support flow 6 (scenario 1, 3)?

**Comment by BLR-0118** [comment]
@Namratha102000 - pls resubmit log for flow 2 (tracking), flow 3, make the other changes & respond to other queries raised;

**Comment by Namratha102000** [comment]
**FLOW1**

for custom_group "36345_758", code="min" is missing? - **FIXED**
curious what max of "99" means for custom group? - **FIXED** [It will be in the range of customizations that this custom_group has]
no use case for base item price of 0 but customizations having non-zero price (for which either the default selection price of range of upper/lower needs to be sent? - Can you please elaborate

do you support incremental update using push? - **YES**
do you support merchant store open / close / disable, etc, which are more common in F&B? **WE support only enable and disable**
**Flow 2**

    /on_init:

    fulfillment.start.location shouldn't be sent in /on_init; - **FIXED IN RESUBMITTED LOGS**
    payment should exclude everything except buyer finder fee / settlement details; **FIXED IN RESUBMITTED LOGS**

**Flow 3**

    /on_select (oos):

    customization 36347_757_479 is missing from items array & quote.breakup, even though error.message says it's out of stock; **FIXED IN RESUBMITTED LOGS**

**Flow 4 & 5**

    /on_cancel:

    request to add precancel_state to Fulfillment1 - **FIXED**

plans to support flow 6 (scenario 1, 3) - **Yes will update during phase 2 changes implementation**

**Comment by Namratha102000** [comment]
Please review this

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_track:
- to optimize /track requests from buyer apps, pls set:
- fulfillment.tags.routing.type to "P2P";
- fulfillment.tags.tracking.gps_enabled to "yes" when tracking is enabled & buyer apps can start making /track requests;

Flow 3
====
1. /on_select_error:
- error.message should be jsonified string as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.sug2402chw6z);

**Comment by BLR-0118** [comment]
@Namratha102000 - pls resubmit log for flow 3 with on_select (out of stock)

**Comment by Namratha102000** [comment]
Flow 3

/on_select (OOS)

    message in /error should be in stringified JSON format: eg- [{"dynamic_item_id":"DI0","item_id":"36347","error":"40002"},{.....}]

Hi this was the comment we got from Sandeep(Above)........ before it was so changed it to this format below
  "message": [
      {
        "dynamic_item_id": "DI0",
        "item_id": "36347",
        "error": "40002"
      },
      {
        "dynamic_item_id": "DI0",
        "customization_id": "36347_757_479",
        "customization_group_id": "36347_757",
        "error": "40002"
      }
    ]
  },


Originally it was has per the contract 
  User
"[{dynamic_item_id":DI0,item_id:36347,error:40002},{dynamic_item_id:DI0,customization_id:36347_757_479,customization_group_id:36347_757,error:40002}]"
@bluecypher

**Comment by BLR-0118** [comment]
@Namratha102000 - error.message is a string, not array

**Comment by Namratha102000** [comment]
**https://github.com/ONDC-Official/v1.2.0-logs/pull/565 Resubmitted the logs** @BLR-0118 
**Flow 2** 

/on_track:

to optimize /track requests from buyer apps, pls set: -- **FIXED AND RESUBMITTED**

1. fulfillment.tags.routing.type to "P2P";
2. fulfillment.tags.tracking.gps_enabled to "yes" when tracking is enabled & buyer apps can start making /track requests;

**Flow 3**

/on_select_error: -- **FIXED AND RESUBMITTED**

1. error.message should be jsonified string

**Comment by BLR-0118** [comment]
flow 3
====
1. /on_select (oos):
- quote.breakup for 36347_757_479 is wrong: unit price (222) * qty (0) should be total price (0) but total price shows as 222???

**Comment by BLR-0118** [comment]
@Namratha102000

**Comment by Namratha102000** [comment]
@BLR-0118 Yeah.. Resubmitting only OOS select and on_select call with correction.

**Comment by BLR-0118** [comment]
@Namratha102000 - can you pls justify why such a basic error at this stage? pls resubmit all logs for flow3 which I'll need to verify.

**Comment by Namratha102000** [comment]
"price": {
  "currency": "INR",
  "value": "403.77"
},
@BLR-0118 
order.quote.price is correct we are not inculding any add on price or item price here. You can check. only in addon_quote if add on price is not present. price was not changes. Apologies
Hi this is correct and we are not inculding any addon

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/582 Resubmitted the logs please check. @BLR-0118

**Comment by BLR-0118** [comment]
flow 3
====
1. /on_select:
- why is fulfillment tracking.gps_enabled being set to "yes" here?? this should be set only after tracking has been enabled (i.e. from this point on, the buyer will be able to track the order);
- this should be set thru some /on_status call;

**Comment by BLR-0118** [comment]
@Namratha102000 - pls fix & resubmit flow 3

**Comment by Namratha102000** [comment]
Resubmitted the logs please check For flow 3. @BLR-0118

flow 3  -- **FIXED AND RESUBMITTED**

/on_select:
why is fulfillment tracking.gps_enabled being set to "yes" here?? this should be set only after tracking has been enabled (i.e. from this point on, the buyer will be able to track the order);
 this should be set thru some /on_status call;

**Comment by Namratha102000** [comment]
Please review this.

**Comment by Namratha102000** [comment]
@BLR-0118 Please review this

**Comment by BLR-0118** [comment]
@Namratha102000 - v1.2.0 logs cleared subject to the above being fixed;

**Comment by Namratha102000** [comment]
fixed
