### ISSUE TITLE
Nobroker RSF - complaince check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1071]
Receiver_recon

- "context.bpp_uri" is required
 - "message.orderbook.orders[].provider.name.code" must be a string
 - "message.orderbook.orders[].payment.@ondc/org/settlement_details[0].settlement_status" is required
 - "message.orderbook.orders[].payment.@ondc/org/settlement_details[0].beneficiary_address" is required
 - "message.orderbook.orders[].payment.@ondc/org/settlement_details[0].settlement_reference" is required
 - "message.orderbook.orders[].receiver_app_uri" is not allowed

@Rajkumar1994sof

**Comment by Rajkumar1994sof** [comment]
@RupalSingla message.orderbook.orders[].receiver_app_uri is mentioned in the document , Are you saying the format is wrong ?

**Comment by Rajkumar1994sof** [comment]
@RupalSingla i have corrected all the issues

**Comment by rudransh-ondc** [comment]
on_receiver_recon.json :
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03

receiver_recon.json :
 - "message.orderbook.orders[].receiver_app_uri" is not allowed  

corrected/
receiver_recon.json :
 - "message.orderbook.orders[].receiver_app_uri" is not allowed
 - "message.orderbook.orders[].issue_type" is not allowed
 - "message.orderbook.orders[].issue_subtype" is not allowed
 - "message.orderbook.orders[].order_id" is not allowed
 - "message.orderbook.orders[].order_amount" is not allowed
 - "message.orderbook.orders[].order_correction_amount" is not allowed
 - "message.orderbook.orders[].order_state" is not allowed
 - "message.orderbook.orders[].previous_settled_amount" is not allowed
 - "message.orderbook.orders[].prev_settlement_reference_no" is not allowed


@Rajkumar1994sof

**Comment by RupalSingla** [comment]
Logs approved for the version 1.0.0 @Rajkumar1994sof
