### ISSUE TITLE
CSC SA (IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#109]
Kindly provide a Fulfilment catagory complaint flow

FLOW 1

/on_issue

* Adjacents  API's needs to have difference in the timstamps
* updated_at is less than created_at

**/on_issue_status**

- Message  ID mismatch in /issue_status and /on_issue_status
- 'created_at' should match issue's 'created_at'
- resolution_provider.respondent_info.type  should be transcation counterparty

@Ashish0120

**Comment by insphere-ashish** [comment]
@Rishabh-ondc Logs after feedback changes have been pushed. [IGM PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/198)

**Comment by RupalSingla** [comment]
FLOW 1 

issue_status
context.action should be issue_status..

@insphere-ashish
