### ISSUE TITLE
Shipyaari - LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1098]
## Delivered Flow

**/search**

- @ondc/org/collection_amount should be sent for COD orders only.

**/on_search**

- bpp_terms to be removed as static terms are not enabled yet
- categories/time/timestamp refers to date (vis-a-vis Context.timestamp) for which this TAT (P3D) is provided

**/confirm**

- Pickup code (start/instructions/short_desc) is not required for P2H2P shipments as shipping label is provided by LSP

**/on_status**

- call for 'Searching-for-agent' will be triggered before 'Out-for-pickup'
- start/time/timestamp is the timestamp when order is picked up, should not be recorded for 'Out-for-pickup' or other states before pickup

## RTO Flow

- similar issues as above

**/on_cancel**

- RTO line item should be added in /items when RTO is initiated
- fulfillments/tags are required in case of RTO (rto_event, pre_cancel_state)
- RTO Pickup (fulfillments/start/time/timestamp) time is missing for fulfillment state - RTO-Initiated
- order/updated_at is not updated correctly

**/on_status**

- RTO line item is missing in /items when RTO is delivered
- order must have required property 'cancellation' when RTO is delivered
- start/time/timestamp should not be provided (or null) before order is picked up
- why are rto charges removed from quote for 'RTO-Delivered'
- Fulfillment of type RTO is missing, fulfillment of 'Delivery' should be in 'Cancelled' state

## Cancellation Flow

**/on_cancel**

- is the LSP charging cancellation fee even if the fulfillment is in Pending state? (in case not, quote price should be zero)

@aakashkanojiya91299

**Comment by aakashkanojiya91299** [comment]
@abhinavv245 

1. @ondc/org/collection_amount is required if **payment.type** is ON-FULFILLMENT Right? but if the logistics buyer sends this collection_amount in all the **payment.type** Do we accept the order or send them ACK **OR**  We respond to them by sending  NACK telling them collection_amount is only required if the payment type is ON-FULFILLMENT. 

2. Pickup code  (start/instructions/short_desc)  if the logistics buyer sends this on /confirm  request  Do we accept the order or send them ACK **OR**  We respond to them by sending  NACK telling them start/instructions/short_desc is not required for P2H2P shipments?

Both The questions are schema validation I want to know either accept the order or reject the order

**Comment by abhinavv245** [comment]
@aakashkanojiya91299 

Ideally, collection amount needs to be provided for ON-FULFILLMENT  (COD)orders, for others you may choose to ignore it or NACK it. It's a business call you can take. 

Same for PCC, you can ignore it, pickup verification will be done through shipping label only.

**Comment by aakashkanojiya91299** [comment]
@abhinavv245 can you please explain this 
`categories/time/timestamp refers to date (vis-a-vis Context.timestamp) for which this TAT (P3D) is provided`

**Comment by aakashkanojiya91299** [comment]
@abhinavv245 and @BLR-0118 

Any update on this

**Comment by BLR-0118** [comment]
Delivered
======
1. /search:
- /search is supposed to go thru gateway, so how is bpp_id, bpp_uri here & bpp_uri here is different from what's in /on_search;

2. /on_search:
- TAT for delivery (categories[].time.duration is 3 days), so how can average pickup time (fulfillment.start.time.duration) also be 3 days?

3. /on_confirm:
- based on 2 above, pls also adjust pickup slot (fulfillment.start.time.range.*);

4. /on_update:
- mapping of fulfillment state ("Pending") to order state ("In-progress") is incorrect as per [contract](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.3w3fzq2n426i);

5. "@ondc/org/linked_order".order.id suddenly changed between /on_confirm & /on_update?

6. Hope all fulfillment states are handled in on_status, as per [this](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.3w3fzq2n426i) list;

Cancellation
========
1. /cancel:
- reason code "003" is invalid (only valid reason for LBNP, as per [this](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031) list, is 007);
2. /on_cancel:
- pls add precancel_state;

RTO
===
1. /on_cancel (RTO initiated):
- invalid value ("Out for delivery") for precancel_state."fulfillment_state" - should be "Out-for-delivery";
- tax shown separately for forward fulfillment, not for RTO?

**Comment by BLR-0118** [comment]
@aakashkanojiya91299

**Comment by aakashkanojiya91299** [comment]
@BLR-0118 

### **Cancellation**

/cancel 

```
"message": {
        "order_id": "26CCCB143CE68326B58E518DE9A4D3BD",
        "cancellation_reason_id": "003"
    }
```

the Logistics Buyer App sent this request so as LSP do we need to map them with LSP code or what?
Please help us with this

**Comment by BLR-0118** [comment]
actually, if LBNP sends invalid cancellation reason code, you should NACK /cancel with error code 60009;

**Comment by aakashkanojiya91299** [comment]
@BLR-0118 
Sorry for asking this sir  

if the cancellation reason code 
belong to this then ACK the request or else NACK
  
"002", ---> SNP
"005", --> SNP
"007", ---> Logistics Buyer NP (LBNP)
"011", --> LSP / SNP (for self-fulfillment) 
"012", --> LSP / SNP (for self-fulfillment)  
"013", --> LSP / SNP (for self-fulfillment)
"014", --> LSP / SNP (for self-fulfillment)
"015", --> LSP / SNP (for self-fulfillment)
"018",  --> SNP
"019", --> SNP
"020", --> SNP

we are the Logistics seller and Logistics Service Provider (LSP)
It helps me to understand the [Reason code](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031) Please sir

**Comment by BLR-0118** [comment]
since you're an LSP, you can receive cancellation request only from LBNP (logistics buyer NP); the only valid reason code for LBNP currently is "007"; as LSP, you can use any of the reason codes under LSP/SNP when you initiate an unsolicited /on_cancel; 

@aakashkanojiya91299

**Comment by AbinayaMaran** [comment]
> since you're an LSP, you can receive cancellation request only from LBNP (logistics buyer NP); the only valid reason code for LBNP currently is "007"; as LSP, you can use any of the reason codes under LSP/SNP when you initiate an unsolicited /on_cancel;
> 
> @aakashkanojiya91299

@BLR-0118 Here the cancel is triggered by buyer. So we are passing the same cancel reason code to LSP, that we received from buyer. 

Even if cancel is triggered from both the seller or the buyer, are we supposed to provide "007" to the LSP?

**Comment by BLR-0118** [comment]
@AbinayaMaran - for now, pls follow the cancellation reason codes applicable for LBNP ("007"); you can however pass both reason_id & cancelled_by in the reverse direction (i.e. from LSP to retail buyer);

**Comment by aakashkanojiya91299** [comment]
> # Delivered
> 1. /search:
> 
> * /search is supposed to go thru gateway, so how is bpp_id, bpp_uri here & bpp_uri here is different from what's in /on_search;
> 
> 2. /on_search:
> 
> * TAT for delivery (categories[].time.duration is 3 days), so how can average pickup time (fulfillment.start.time.duration) also be 3 days?
> 
> 3. /on_confirm:
> 
> * based on 2 above, pls also adjust pickup slot (fulfillment.start.time.range.*);
> 
> 4. /on_update:
> 
> * mapping of fulfillment state ("Pending") to order state ("In-progress") is incorrect as per [contract](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.3w3fzq2n426i);
> 
> 5. "@ondc/org/linked_order".order.id suddenly changed between /on_confirm & /on_update?
> 6. Hope all fulfillment states are handled in on_status, as per [this](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.3w3fzq2n426i) list;
> 
> # Cancellation
> 1. /cancel:
> 
> * reason code "003" is invalid (only valid reason for LBNP, as per [this](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031) list, is 007);
> 
> 2. /on_cancel:
> 
> * pls add precancel_state;
> 
> # RTO
> 1. /on_cancel (RTO initiated):
> 
> * invalid value ("Out for delivery") for precancel_state."fulfillment_state" - should be "Out-for-delivery";
> * tax shown separately for forward fulfillment, not for RTO?

Pls merge this https://github.com/ONDC-Official/v1.2.0-logs/pull/1225 and review our logs again.
@BLR-0118 @abhinavv245

**Comment by BLR-0118** [comment]
Delivered
======
1. /on_status_SFA:
- provider.id was "2354" up to /on_update but changed to "9008" here & all other /on_status APIs?

**Comment by BLR-0118** [comment]
@aakashkanojiya91299 - clearing logs for v1.2.0 but pls make sure the above issue is fixed ASAP;
