### ISSUE TITLE
Magicpin - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1106]
## All Flows

**/search**

- order prep time (provider/time/duration) is required for hyperlocal

**/init**

- message/order must have required property 'payment'
- street is not required in billing/address 
- billing/tax_number should be valid

**/confirm**

- ttl is missing in context
- fulfillments/end/instructions/code must be equal to one of the allowed values (1,2,3)
- billing/created_at and updated_at mismatches in /billing in /init and /confirm
- linked_order/order/weight/value Payload weight mismatches from /search
- order/tags not to be sent as bpp_terms are not applicable yet
- Average Pickup Time (fulfillments/start/time/duration) mismatches from the one provided in /on_search
- instructions/tags to be removed

**/track and /cancel**

- ttl is missing in context

Note: One of the flows should have deferred RTS in /update, and only Group B logs to be submitted

@harshmohta1611

**Comment by harshmohta1611** [comment]
We aren't supporting deferred RTS and will be sending RTS : true in /confirm itself @abhinavv245

**Comment by harshmohta1611** [comment]
Have Resubmitted the logs
https://github.com/ONDC-Official/v1.2.0-logs/pull/1115

**Comment by abhinavv245** [comment]
## All Flows

**/init**

- billing/created_at and updated_at is not recorded correctly w.r.t context/timestamp
- for POST-FULFILLMENT, payment will be collected by BAP, thus settlement details need not be sent by LBNP (will be sent by LSP, though optional)

**/confirm**

- start/instructions/short_desc should not have more than 6 alphanumeric (also for OTP, code will be 4, short_desc will not be provided, OTP will be sent via authorization object later via /update)
- end/instructions/short_desc PCC should not be same as DCC \"87527572\"
- price is not required in /items (already present in quote, refer to example in contract document)

**/update**

- in case of authorization with OTP, LBNP need to provide OTP and its validity via /update call once the order is packed i.e. ready_to_ship=yes, and for delivery OTP to be provided once the LSP is out for delivery (via /update call)

@harshmohta1611

**Comment by BLR-0118** [comment]
Flow 3 - TAT breach
=============
1. /cancel - reason code 010 is invalid for LBNP (only valid code for LBNP is 007 as per [this](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031) current list);

**Comment by BLR-0118** [comment]
@harshmohta1611 - pls fix the above;
clearing LBNP v1.2.0 logs subject to the above fix;
