### ISSUE TITLE
Channelier (Seller App - RET12/13/14/15/16/18) - Compliance check

### ISSUE THREAD

**Issue by NishthaMonga** [ONDC-Official/v1.2.0-logs#1135]
### on_search_full_catalog_refresh
- Size": "The item value can only be of possible values as provided in https://github.com/ONDC-Official/protocol-network-extension/tree/main/enums/retail

### on_init
- items[0].parent_item_id mismatches for Item CU254I0 in /on_search and /on_init

### on_confirm
- mandatory fields like np_type,provider_tax_number,etc  missing in message/order/tags/bpp_terms for ON_CONFIRM

### select_out_of_stock
- Payload incorrect (Flow 3/select_out_of_stock.json)

### on_cancel
- Pre Cancel is mandatory for on_cancel

@itsRajatkumar

**Comment by ravinderTechpvec18** [comment]
@NishthaMonga Flow 1 comment refrences sheet for possible enums for size attribute, In the logs provided values are as per the mentioned sheet, pls look in boys category -> shorts, we have provided the appropriate enums. If that is not the case, pls guide us  in resolving the problem

**Comment by ravinderTechpvec18** [comment]
@NishthaMonga Flow 2 comments mentions parent_item_id mismatch, but according to https://drive.google.com/file/d/15-Mwqbnn_mGJ2t8QJVHmVV0aUdu1muPT/view, retail contract for 1.2 parent_item_id is to be communicated only in case of customizations, which is not applicable in this case. Pls elaborate.

**Comment by NishthaMonga** [comment]
if you have variant group or customisation of your item then parent_item_id will be the item parent id (which variant belongs to) otherwise item_id itself act as parent_item_id

@ravinderTechpvec18

**Comment by ravinderTechpvec18** [comment]
@NishthaMonga, In case of varient then seller app is expecting parent_item_id from buyer app also, but we are not getting it from  https://buyer-app-preprod-v2.ondc.org/application/products, and in case of varient which case is to follow from retail contract as for customizations there is lot more there, how to know what to send and what not

**Comment by ravinderTechpvec18** [comment]
@NishthaMonga I have confirmed from Supriyo sir, that for F&B we have to follow customization examples but for other categories we have to follow examples without customizations, so as per that example i am not able to locate parent_item_id in on_init, pls help

**Comment by sahil-ondc** [comment]
# RET10

## Flow 1

### search_inc

- /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp

## Flow 2

### select

- Buyer selects multiple items (> 1 qty for each item) for checkout as per the roll out sheet
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

### on_select

- invalid price of item provided in /message/order/quote/breakup/item (item_id: CU19I0)

### on_confirm

- message/order/tags/bpp_terms should have only provider_tax_number, tax_number and np_type (no additional properties should be provided)

## Flow 5

- RTO Flow missing

## Flow 6

### on_update_return_init

- @ondc/org/settlement_details should have partial cancellation refund details

@itsRajatkumar

**Comment by itsRajatkumar** [comment]
@sahil-ondc Please Put this Feedback in [RET:10 Issue](https://github.com/ONDC-Official/v1.2.0-logs/issues/879) so that other category issues do not mix in one issue. 
Thanks.

**Comment by NishthaMonga** [comment]
### RET18
## Flow 2
### on_confirm
- mandatory fields like np_type,provider_tax_number,etc  missing in message/order/tags/bpp_terms for ON_CONFIRM


## Flow 5
### on_cancel
- Pre Cancel is mandatory for on_cancel


## Flow 6b
### on_update_approval
- /message/order/fulfillments/3/state/descriptor/code must be equal to one of the allowed values (Cancelled,Pending,Order-delivered,Return_Initiated,Return_Pick_Failed,Return_Approved,Return_Picked,Return_Delivered,Liquidated,Return_Rejected)|
- /message/order/fulfillments/3/start/location must have required property 'id'
- /message/order/fulfillments/3/start/location/address must have required property 'area_code'

@itsRajatkumar

**Comment by ravinderTechpvec18** [comment]
@NishthaMonga Comment on Flow 6b, /message/order/fulfillments/3/start/location must have required property 'id', according to return approved example in retail contract there is no id attribute in fulfillments/3/start/location, pls clarify

**Comment by sandeepshahi** [comment]
@ravinderTechpvec18, you may disregard the "id" related error. In the case of returns, the start location becomes the buyer's location, which does not have an associated ID. Therefore, that information cannot be provided

@NishthaMonga, please rectify this.

@sahil-ondc & @Jagannath-wits, please get this fixed in the utility.

**Comment by BLR-0118** [comment]
RET12
====
1. variant_group definition is invalid (full path for attr name required, seq for attr required);
2. item.quantity.unitized.measure.value should be string;
3. pls use HSN code for item.descriptor.code;

**Comment by BLR-0118** [comment]
RET18
====
1. keys in bpp_terms are invalid;
2. seq for attrs in variant_group reqd;
3. pls use proper value for circle.radius.value;

**Comment by BLR-0118** [comment]
@ravinderTechpvec18

**Comment by itsRajatkumar** [comment]
@BLR-0118  So we need to submit Flow 1 Only Right ?

**Comment by BLR-0118** [comment]
Flow 1 for RET12/18

**Comment by BLR-0118** [comment]
RET12- flow 1: ok;

**Comment by BLR-0118** [comment]
RET13 - flow 1
=========
1. item.quantity.available.count & item.quantity.maximum.count not as per contract;
2. item.quantity.unitized.measure should be properly defined e.g. for item CU270I0, this should be "10 gram" (as in descriptor), not "1 unit";
3. key recover_amount_without_logistics is invalid;

**Comment by BLR-0118** [comment]
RET14 - flow 1
=========
1. item.quantity.unitized.measure.value should be string;

**Comment by BLR-0118** [comment]
RET15 - flow 1
=========
1. pls remove formatting from long_desc (e.g. for item CU1I0);
2. item.quantity.unitized.measure.value should be string;

**Comment by BLR-0118** [comment]
RET16 - flow 1
=========
1. item.quantity.unitized.measure.value should be string;
2. pls include at least 10 items in catalog;

**Comment by BLR-0118** [comment]
RET18 - flow 1
=========
1. only non-prescription medicines can be sold on ONDC now; hence, all items should have prescription_required set appropriately;
2. for item CU259I3, unitized measure should be "10 gram" instead of 1 unit?
3. similarly:
- item CU259I3 - "20 gram";
- item CU259I5 - "15 gram";
- item CU259I6 - "30 gram";
- several other items have same issues

**Comment by BLR-0118** [comment]
@itsRajatkumar

**Comment by itsRajatkumar** [comment]
@BLR-0118 Sir,
we have to submit the flow 1 for all this Categories 
RET13, RET14, RET15, RET16 and RET18

**Comment by BLR-0118** [comment]
RET12 - flow 6
=========
1. /on_confirm:
- pls make sure the pickup & delivery slots are aligned with time to ship & TAT: e.g. all items have time-to-ship of 2 hrs (in catalog), TAT promised is 26 hrs, /on_confirm timestamp is 00:52:50 (27th Mar) -> means pickup slot can't start before 02:52:50 (otherwise, time-to-ship is wrong);

2. /on_update (for return with pickup):
- all /on_update have same message_id;
- return fulfillment should have both start (shown) & end (not shown) locations;

**Comment by BLR-0118** [comment]
RET13 - ok;

**Comment by BLR-0118** [comment]
RET14
====
1. pls use GTIN for item unique code (in lieu of HSN) as in the contract;
2. variant using colour & storage isn't enough, storage unit also reqd?

**Comment by BLR-0118** [comment]
RET15
====
1. all these are branded products, why can't you use EAN?

**Comment by BLR-0118** [comment]
RET16
====
1. for these mattresses, don't you also need l/b/h, weight(?);

**Comment by BLR-0118** [comment]
RET18
====
1. variant defn for attr incorrect - needs complete path from item & up to measure;
2. for item CU259I0 (20 tabs), why don't you put unitized measure val as 20? If there are multiple strips, you can add to item.quantity.unitized.count e.g. 2 straps of 20 tabs each: unitized measure is 20 unit & unitized count is 2;
3. pls note unitized count is in swagger, but not yet in contract & will be included in addendum;

**Comment by BLR-0118** [comment]
@itsRajatkumar @ravinderTechpvec18 - pls fix & resubmit for RET12 (flow 6), RET14/15/16/18

**Comment by itsRajatkumar** [comment]
@BLR-0118 we have raised PR with Fix.
for issue _"return fulfillment should have both start (shown) & end (not shown) locations;"_
as per the contract, there is no end location will be there.

**Comment by BLR-0118** [comment]
@itsRajatkumar - logs cleared for RET14/15/16/18 for v1.2.0;
