### ISSUE TITLE
Tipplr IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1205]
ret_on_issue
 "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
           
"ret_on_issue_status"
  "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"

@punithrj26

**Comment by punithrj26** [comment]
@RupalSingla 
Have Uploaded new IGM logs as per compliance.
The raised PR id #1220 .
Please verify and give feedback.

Thank you.

**Comment by RupalSingla** [comment]
On issue status - processing and refund .
in "respondent_actions object - Values are getting changed in short description and updated _at , which canot be possible
@punithrj26

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @punithrj26
