### ISSUE TITLE
nStore - SA (RET11) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#1206]
RET12
====
1. suggest you use HSN code for item.descriptor.code as this seems to be most common;
2. quantity.unitized.measure.unit of "each" is invalid - pls check valid enums [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json);
3. pls add at least all mandatory attrs, for the category, defined [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843), while checking the mapping from attrs in the sheet to the keys as defined in contract;
4. why are returnable/cancellable/seller_pickup_return set to false for all items?

**Comment by BLR-0118** [comment]
RET13
====
1. suggest you use EAN code for items;
2. while quantity.unitized.measure.unit value is valid, it's not usable here (pls follow same rule as RET10);
3. 3 & 4 above for RET12 also apply here;

**Comment by BLR-0118** [comment]
RET14
====
1. consider using GTIN code for items, as this seems to be the industry standard;
2. 3 & 4 above for RET12 also apply here;

**Comment by BLR-0118** [comment]
RET15, 16 & 18 - pls follow the above as well;

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by BLR-0118** [comment]
RET11 - customization to be supported, logs for all flows required;

**Comment by BLR-0118** [comment]
RET12
====
1. item.tags.attribute.keys wrong:
- should be lowercase, e.g. "gender";
- values should be as per enum defined [here](https://github.com/ONDC-Official/protocol-network-extension/tree/main/enums/retail), e.g. for [gender](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/gender.json);

**Comment by BLR-0118** [comment]
RET13
====
1. same issue as RET12;
2. use proper unitized measure e.g. for item 230376, should be "100 gram";

**Comment by BLR-0118** [comment]
RET14
====
1. same issue as RET12;
2. for attrs like weight / length / breadth / height, values to be defaulted as defined [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=244000021);

**Comment by BLR-0118** [comment]
RET15
====
1. same as RET14;

**Comment by BLR-0118** [comment]
RET16
====
1. same as RET14;

**Comment by BLR-0118** [comment]
RET18
====
1. same as RET13;

**Comment by BLR-0118** [comment]
@nstoretech - request to carefully review contract & submit logs in proper shape;

**Comment by BLR-0118** [comment]
@nstoretech - clearing RET12, RET16 but pls make sure issues mentioned above are fixed for everything; other logs to be resubmitted

**Comment by nstoretech** [comment]
+Ajeeth Boaz ***@***.***> +Arunraj Selvam ***@***.***>
+Sudharsan
Srinivasan ***@***.***> +AdminTeam ***@***.***>

**Comment by BLR-0118** [comment]
RET13
====
1. what does time_to_ship of 100ml for item 246829 mean?
2. what's the difference between items 254473 & 12254473?

**Comment by BLR-0118** [comment]
RET14
====
1. pls also send colour_name;

**Comment by BLR-0118** [comment]
RET15
====
1. pls also send colour_name;
2. considering these are branded items, why aren't you sending EAN codes?

**Comment by BLR-0118** [comment]
RET18
====
1. why aren't you sending EAN codes for items?

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by BLR-0118** [comment]
RET14 - ok;

**Comment by BLR-0118** [comment]
RET15 - ok;

**Comment by BLR-0118** [comment]
RET18
====
prescription_required has values "yes", "no";

**Comment by BLR-0118** [comment]
logs for RET13/14/15 cleared for v1.2.0;
pls fix RET18 & update here;

**Comment by BLR-0118** [comment]
@nstoretech

**Comment by BLR-0118** [comment]
@nstoretech - before deploying in Prod, pls make sure you also send "@ondc/org/statutory_reqs_packaged_commodities" for all categories (as doc in the contract); without this, many buyer apps may not show your catalog;

**Comment by arunraj-nstore** [comment]
@BLR-0118 - We have updated the value of the "prescription_required" attribute and also included the "@ondc/org/statutory_reqs_packaged_commodities" as suggested.

Here is the payload with updated 'prescription_required' field.
http://jsonblob.com/1239820012834643968

**Comment by BLR-0118** [comment]
RET11 flows:

Flow 1
====
1. /on_search:
- bpp/providers.categories.id max length is 12;
- category_id should be F&B;
- remove item.descriptor.code;
- item.price.range & item.price.default_selection reqd only if base price is 0;
- structure for multiple customizations for item 111 is wrong;
- count of "max" customizations for "customization1" should match the no of customizations assigned to this custom group (i.e. 8);

**Comment by BLR-0118** [comment]
2. /on_search_incremental:
- since incremental updates are thru push, use different message_id for each push update (diff from message_id in search_incremental);

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- since you have 2 fulfillment options, the charges for fulfillment specified for one of the options should also be specified for the other e.g. delivery charge of 0 for F1, but no delivery charge for F2;

**Comment by BLR-0118** [comment]
2. /on_init:
- pls add provider_tax_number to bpp_terms;

**Comment by BLR-0118** [comment]
3. others:
- pickup & delivery slots are provided in /on_confirm when order isn't yet accepted by store; this is incorrect as the sequence should be: store accepts order -> starts prep -> packs etc.;
- order accepted state not shown anywhere, i.e. goes from Created to In-progress directly; is this auto-accept based on timer or store manually accepts each order?
- tracking is shown as false, even though it's mandatory for F&B orders;

**Comment by BLR-0118** [comment]
Flow 3 - is there example where customization is out-of-stock?

**Comment by BLR-0118** [comment]
flow 5 - not really RTO (cancel_request missing addl rto attributes) but looks ok;
flow 6:
- /on_update shared is for 1.1;

**Comment by BLR-0118** [comment]
@nstoretech - pls resubmit logs for flows 1 & 1/2 additional flows where all the above issues can be checked (flow 5/6 or anything else?)

**Comment by arunraj-nstore** [comment]
@BLR-0118 

###### count of "max" customizations for "customization1" should match the no of customizations assigned to this custom group (i.e. 8);
- The term "max" refers (a) the maximum number of items that the user can select under the customization group. (b) the total number of items available within the group. which one to follow ?

###### since you have 2 fulfillment options, the charges for fulfillment specified for one of the options should also be specified for the other e.g. delivery charge of 0 for F1, but no delivery charge for F2;

 - Fulfillment 'F2' is designated for Self-Pickup and no delivery charge is applicable. Do we really need to add the delivery charge even if it is not applicable ?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search_full_catalog_refresh:
- 7 customizations (113, 115, 116, 117, 118, 119, 120) are assigned to custom group CM1 but "max" for CM1 is 5?
- some items need to be created as customization for better UX e.g. items 106, 109;

2. /on_search_incremental_refresh:
- item structure is different from what's in full catalog refresh e.g. descriptor.code, invalid custom menu id ("menu1")?

Flow 3
====
1. /on_select:
- quote.breakup[] should include delivery cost for all fulfillments; currently, showing for F1, not for F2;

2. /on_select_out_of_stock:
- error.message invalid: check the format [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.sug2402chw6z);

Flow 6
====
1. /on_update_part_cancel:
- cancellation reason code "010" is not valid for part cancel;
- if there is no change in value for a quote line item, it shouldn't be a part of quote_trail e.g. tax line items in "C3008";

2. /on_update_liquidated:
- I'm assuming you're sending solicited /on_update response (for Return_Initiated);
- otherwise, looks ok but 2nd point above needs to be handled;

**Comment by BLR-0118** [comment]
@nstoretech - I'm clearing the logs, but pls make sure the above are fixed before deploying to Prod;
