### ISSUE TITLE
Globallinker(SA : RET10) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#1247]
# Flow 2
### Select

- **schemaErr0**: /message/order/items/0/quantity/count must be integer
- **schemaErr1**: /message/order/items/1/quantity/count must be integer

### Init

- **schemaErr0**: /message/order/items/0/quantity/count must be integer
- **schemaErr1**: /message/order/items/1/quantity/count must be integer

### On Init

- **tmpstmp**: context/timestamp difference between /on_init and /init should be less than 5 sec

### Confirm

- **schemaErr0**: /message/order/items/0/quantity/count must be integer
- **schemaErr1**: /message/order/items/1/quantity/count must be integer
- **schemaErr2**: /message/order/fulfillments/0/tracking must be boolean
- **schemaErr3**: /message/order/quote/breakup/0/@ondc~1org~1item_quantity/count must be integer
- **schemaErr4**: /message/order/quote/breakup/1/@ondc~1org~1item_quantity/count must be integer

### On Status Packed

- missing payload

### On Status Picked

- **pickUpTime**: picked timestamp is missing

### On Status Out For Delivery

- missing payload

# Flow 3

- since item 5775276_6459958_9621832 was not available as given in on_select out of stock how can you select(in_stock) 2 of the same item.
- same as flow 

# Flow 5

### On Cancel

- **invldQuotePrices**: item quote breakup prices for on_cancel should be equal to the total price.

# Flow 6-a

### On Update

- **invldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm

# Flow 6-b

### On Update Interim

- **message/order.payment**: why are there 2 objects in @ondc/org/settlement_details, please refer to contract

### On Update Approval

- **message/order.payment**: Same as above
### On Update Picked

- **message/order.payment**: Same as above
- **invldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm

### On Update Delivered

- **message/order.payment**: Same as above
- **invldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm

# Flow 6-c

-missing flow

@Tjsvaradhan

**Comment by sandeepshahi** [comment]
Duplicate issue board; Pls check the latest updates here: https://github.com/ONDC-Official/v1.2.0-logs/issues/805
