### ISSUE TITLE
MyyShopp (lokal.in) - SA (RET10) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#1255]
# Flow 1

### On Search Full Catalog Refresh

- **schemaErr**: /message/catalog/bpp~1providers/items/category_id Invalid category ID found for item for on_search using deprecated category id 'Snacks & Branded Foods’; Please refer to [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)
- **bpp/descriptor/accept_bap_terms**: accept_bap_terms is not required in bpp/descriptor/tags for now
- **bpp/descriptor/collect_payment**: collect_payment is not required in bpp/descriptor/tags for now
- **prvdr0loctime0**: Either one of fixed (range) or split (frequency and times) timings should be provided in /bpp/providers[0]/locations[0]/time

### On Search Inc Refresh

- **schemaErr0**: /context/action must be equal to constant (on_search)
- **action_err**: context.action should be on_search

# Flow 2

### On Status Delivered

- **deliveryTime**: Delivery timestamp should match context/timestamp and can't be future dated; as delivery timestamp is 2024-03-26T08:20:19.707Z and context timestamp is 2024-03-26T07:40:19.764Z
- **updatedAt**: Order/updated_at timestamp can't be less than the delivery time

# Flow 3

### On Select Out Of Stock

- **msgId**: Message Id for /select and /on_select api should be same

# Flow 4

- How can there be on-status delivered when entire order is cancelled
### On Cancel

- **schemaErr0**: /message/order must NOT have additional properties (tags)
- **ffID 2024-03-27-223946**: Fulfillment id 2024-03-27-223946 does not exist in /on_cancel items.fulfillment_id
- **ordrupdtd**: Order.updated_at timestamp should be greater than order.created_at timestamp

# Flow 5

### On Cancel

- **schemaErr0**: /message/order must NOT have additional properties (tags)
- **ordrupdtd**: Order.updated_at timestamp should be greater than order.created_at timestamp

# Flow 6
- Please provide complete flow 6 with labels/sequence for each scenario

@Srinath91

**Comment by sandeepshahi** [comment]
Duplicate issue board; For further updates, please refer: https://github.com/ONDC-Official/v1.2.0-logs/issues/120
