### ISSUE TITLE
Sabhyasha - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1261]
## All Flows

**/search**

- order preparation time (provider/time/duration) is needed for hyperlocal (indicates approx timing for logistics ready_to_ship)
- Holiday date '2024-01-26' should not be past dated",
- Reverse Geocoding for `start` failed. Area Code 560059 not matching with 20.27731880, 85.86221050 Lat-Long pair.",
- CityCode 06755 should match the city for the fulfillment start location 560059, 080,
- Reverse Geocoding for `end` failed. Area Code 560066 not matching with 20.261921346135264,85.84367395262824 Lat-Long pair.

**/init**

- context/city must be equal to constant (std:06755)",
- Item Id '65' does not exist in /on_search

**/confirm**

- Average Pickup Time (fulfillments/start/time/duration) mismatches from the one provided in /on_search",
- Total order weight '200' does not match the total unit weight of items '100' in linked order
- why are multiple items selected in /items? items object should be same as in /init 
- payment/type mismatches in /payment in /on_init and /confirm
-  @ondc/org/collection_amount is required only for payment/type 'ON-FULFILLMENT'
- Is the seller indicating that they do not wish to have the product returned? Is the value of "return_to_origin" set to "no"?

**/update**

- fulfillments/end/instructions empty object not required
- order/@ondc/org/linked_order must have required property 'provider' (linked order to be sent in /update if there is some change in the linked order)

Note: Please provide cancellation flow in case of TAT breach

@SatyaranjanSwain

**Comment by SatyaranjanSwain** [comment]
- In the "confirm" call, what should be the value of 'return_to_origin' in our case?
- In the "update" call the key 'provider' is not there in the contract document for 'order/@ondc/org/linked_order'. 

 @abhinavv245, can you please check it?

**Comment by abhinavv245** [comment]
@SatyaranjanSwain it should be 'yes' in case the logistics buyer wants the product to be returned to origin.

- you can ignore the provider comment, however linked order to be sent in /update if there is some change in the linked order.

Also, in the Flow 2, tracking value should be 'true' (not 'True')

**Comment by BLR-0118** [comment]
Flow 1
====
1. /search was sent for shipping between 560066 & 560066 pin codes, with order prep time of 7 days, for which LSP sent quote & TAT; however, /init uses different pin codes for start & end but using the quote sent in /search. This is inconsistent;

Flow 2 (TAT breach)
============
1. /cancel should use cancellation reason codes valid for LBNP;

**Comment by BLR-0118** [comment]
@SatyaranjanSwain

**Comment by SatyaranjanSwain** [comment]
TAT Breach is in Flow 3. Am I right?

@BLR-0118

**Comment by BLR-0118** [comment]
Flow 1
====
1. /search:
- why is bpp_id/bpp_uri in /search & is this sent through gateway? (/search should go thru gateway to be broadcast to all LSPs, hence, Context should not have bpp_id, bpp_uri);

2. /init:
- fulfillment.start.location.address & fulfillment.end.location.address have issues:
- pin code is for Bengaluru but address is for Bhubaneshwar;
- address fields like fulfillment.start.location.address.name incorrect (should be store name, not aggregator name), fulfillment.end.location.address.name & building should be house no / building name as per contract;

**Comment by BLR-0118** [comment]
flow 3 - ok;

**Comment by BLR-0118** [comment]
Flow 1
====
1. /search:
- provider.time.duration denotes the order preparation time; setting this to 3 days when pickup & delivery codes are same (means hyperlocal) isn't correct; it has to be precise (for hyperlocal) as LSP will make rider available around that time;

2. /track:
- how do you know when to call /track?

**Comment by BLR-0118** [comment]
@SatyaranjanSwain - while flow 1 logs are ok (& don't need to be resubmitted), pls answer the above questions before I can clear;

**Comment by SatyaranjanSwain** [comment]
/track can be called only after the rider/agent is assigned.

@BLR-0118

**Comment by BLR-0118** [comment]
@SatyaranjanSwain:
- pls make sure you use correct values for 1 & 2 in Prod;
- for /track, you should call only after getting gps_enabled="yes" or "url_enabled" + "url" from LSP, in /on_status; if this is URL tracking, you can just use the url which comes, without needing to call /track;

**Comment by BLR-0118** [comment]
clearing logs for v1.2.0
