### ISSUE TITLE
Udyamwell (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1273]
flow 1
on_receiver_recon.json :
 - "message.orderbook.orders[0].counterparty_recon_status" is required
 - "message.orderbook.orders[0].counterparty_diff_amount" is required
 - "message.orderbook.orders[0].state" is not allowed
 - "message.orderbook.orders[0].provider" is not allowed
 - "message.orderbook.orders[0].payment" is not allowed
 - "message.orderbook.orders[0].withholding_tax_gst" is not allowed
 - "message.orderbook.orders[0].withholding_tax_tds" is not allowed
 - "message.orderbook.orders[0].deduction_by_collector" is not allowed
 - "message.orderbook.orders[0].payerdetails" is not allowed
 - "message.orderbook.orders[0].settlement_reason_code" is not allowed
 - "message.orderbook.orders[0].recon_status" is not allowed
 - "message.orderbook.orders[0].created_at" is not allowed
 - "message.orderbook.orders[0].updated_at" is not allowed
 - "message.orderbook.orders" must contain at least 5 items
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03

receiver_recon.json
 - "message.orderbook.orders[1].invoice_no" is not allowed to be empty
 - "message.orderbook.orders[1].withholding_tax_gst.value" must be a string
 - "message.orderbook.orders[1].withholding_tax_tds.value" must be a string
 - "message.orderbook.orders[1].deduction_by_collector.value" must be a string
 - "message.orderbook.orders[1].order_recon_status" is not allowed to be empty

flow 2 ~ correction
on_receiver_recon.json :
 - "message.orderbook.orders" must contain at least 5 items

receiver_recon.json :
 - "message.orderbook.orders[0].correction" is not allowed
 - "message.orderbook.orders" must contain at least 5 items

flow 2
on_receiver_recon.json :
 - "message.orderbook.orders" must contain at least 5 items
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03

receiver_recon.json :
 - "message.orderbook.orders" must contain at least 5 items
 @udyamwell1

**Comment by udyamwell1** [comment]
@RupalSingla , thank you for your feedback. 

We have reviewed the issues you raised and found that our processes already incorporate most of the elements you mentioned. The only discrepancy is with "message.orderbook.orders," which currently contains 3 items instead of 5; we're addressing this issue. 
Could you please review the other points once more? Our evaluation indicates that everything else aligns with our flows.

Thanks.

**Comment by udyamwell1** [comment]
@RupalSingla Can you please check this?

**Comment by udyamwell1** [comment]
@RupalSingla please check this as soon as possible.

**Comment by RupalSingla** [comment]
Logs cleared for RSF @udyamwell1

**Comment by udyamwell1** [comment]
Thanks a lot @RupalSingla
