### ISSUE TITLE
Crofarm (BA)	RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1275]
crofarm > on_receiver_recon.json :
 - "message.orderbook.orders[].counterparty_recon_status" is required
 - "message.orderbook.orders[].counterparty_diff_amount" is required
 - "message.orderbook.orders[].receiver_app_uri" is not allowed
 - "message.orderbook.orders[].state" is not allowed
 - "message.orderbook.orders[].provider" is not allowed
 - "message.orderbook.orders[].payment" is not allowed
 - "message.orderbook.orders[].withholding_tax_gst" is not allowed
 - "message.orderbook.orders[].withholding_tax_tds" is not allowed
 - "message.orderbook.orders[].deduction_by_collector" is not allowed
 - "message.orderbook.orders[].payerdetails" is not allowed
 - "message.orderbook.orders[].settlement_reason_code" is not allowed
 - "message.orderbook.orders[].recon_status" is not allowed
 - "message.orderbook.orders[].created_at" is not allowed
 - "message.orderbook.orders[].updated_at" is not allowed
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03

receiver_recon.json :
 - "message.orderbook.orders[0].payment.uri" must be a valid uri
 - "message.orderbook.orders[0].payment.@ondc/org/return_window" must be a string
 - "message.orderbook.orders[0].payerdetails.payer_account_no" must be a string
 - "message.orderbook.orders[0].receiver_app_uri" is not allowed

Success /

on_receiver_recon.json :
 - "message.orderbook.orders[0].counterparty_diff_amount" is required

receiver_recon.json :
 - "message.orderbook.orders[0].payment.uri" must be a valid uri
 - "message.orderbook.orders[0].payment.@ondc/org/return_window" must be a string
 - "message.orderbook.orders[0].payerdetails.payer_account_no" must be a string
 - "message.orderbook.orders[0].receiver_app_uri" is not allowed

@harshitCrofarm

**Comment by vipul-jn** [comment]
Hi @RupalSingla, I am not able to understand the comments you have made..
"message.orderbook.orders[].withholding_tax_gst" is not allowed
"message.orderbook.orders[].withholding_tax_tds" is not allowed
"message.orderbook.orders[].deduction_by_collector" is not allowed
"message.orderbook.orders[].payerdetails" is not allowed

these all are mandatory fields and present in the api docs reference payload.

**Comment by RupalSingla** [comment]
Logs approved for version 1.0.0 @vipul-jn
