### ISSUE TITLE
Mappls (BA)	IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1290]
"issue"
                "schemaErr0": "/context/core_version must be equal to constant (1.0.0)",
                "schemaErr1": "/message/issue/order_details must have required property 'provider_id'",
                "org_name": "Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID"
           
 "issue_CLOSE":
                "schemaErr0": "/context/core_version must be equal to constant (1.0.0)",
                "schemaErr1": "/message/issue must have required property 'rating'",
                "org_name": "Organization's Name for /issue_close api mismatched with bap id"
            
 "issue_status"
                "schemaErr0": "/message/issue_id must match format \"uuid\""
            
  on_issue_status"
                "schemaErr0": "/message/issue/id must match format \"uuid\""
 
   "on_issue_status_unsolicited
                "schemaErr0": "/message/issue/id must match format \"uuid\""

@kalaivanansundaram

**Comment by kalaivanansundaram** [comment]
Thank you for the feedback.We have made the changes and added the updated logs for the same. Please review and let us know.  @RupalSingla 

https://github.com/ONDC-Official/v1.2.0-logs/pull/1368

**Comment by RupalSingla** [comment]
on_issue_status": {
                "igmIssueMsgId": "Message  ID mismatch in /issue_status and /on_issue_status"
            },
 "on_issue_status_unsolicited": {
                "schemaErr0": "/message/issue/issue_actions must have required property 'respondent_actions'",
                "action_err": "context.action should be on_issue_status",
                "Phn": "Phone Number for /on_issue_status api is not in the valid Range"

@kalaivanansundaram

**Comment by kalaivanansundaram** [comment]
@RupalSingla I have updated the logs. Please check it once. 
https://github.com/ONDC-Official/v1.2.0-logs/pull/1437

**Comment by RupalSingla** [comment]
logs cleared for version 1.0.0 @kalaivanansundaram

**Comment by kalaivanansundaram** [comment]
@RupalSingla Thank you so much, I reallly appreciate your support on this.
