### ISSUE TITLE
QWQER (LSP)	IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1311]
issue_close
                "schemaErr0": "/message/issue must have required property 'rating'",
                "schemaErr1": "/message/issue/issue_actions/complainant_actions/0 must be object",
                "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in issue",
                "created_at": "context timestamp should be greater than or equal to updated_at in issue"
      
   issue_status"
                "schemaErr0": "/context must have required property 'ttl'",
                "bpp_id": "Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider",
                "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider"

            on_issue_status
                "schemaErr0": "/message/issue/resolution/action_triggered must be equal to one of the allowed values (REFUND,REPLACEMENT,RETURN,CANCEL,NO-ACTION)",
                "bpp_id": "Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider",
                "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider",
                "updated_at": "updated_at of last respondent_action should be the same in the message/issue/update_at in the on_issue_status",
                "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
                "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
           
@sajithjayaram

**Comment by iamsajith** [comment]
Those issues are from LBNP/Retail seller

**Comment by iamsajith** [comment]
New [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/1365)

@abhinavv245 @sandeepshahi @RupalSingla

**Comment by iamsajith** [comment]
waiting for approval
@RupalSingla @sandeepshahi @BLR-0118 @abhinavv245

**Comment by RupalSingla** [comment]
Logs Cleared for version 1.0.0 @iamsajith
