### ISSUE TITLE
Sellersetu IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1312]
FLow 2 &Flow3 
"on_issue_status": 
                "igmIssueMsgId": "Message  ID mismatch in /issue_status and /on_issue_status",
                "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID",
                "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[3]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status"

2 on_issue_status": {
                "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
                "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID"

Pls send log once you  verified by utility

@Rahuljagwani

**Comment by Rahuljagwani** [comment]
Sure @RupalSingla,
Give me some time.
Thanks for pointing out.

**Comment by Rahuljagwani** [comment]
@RupalSingla 
I have corrected flow 2 and 3.
Please review PR: #1369

**Comment by RupalSingla** [comment]
FLow 2 &Flow3

respondant_action in on_issue and on_issue_status are having different values inside updated_at .
And trail for respiondant action needs to be maintained 

@Rahuljagwani

**Comment by RupalSingla** [comment]
SellerSetu (SA)
FLOW 1
ret_on_issue_status
Message  ID mismatch in /issue_status and /on_issue_status
FLOW 2
ret_on_issue_status
Message  ID mismatch in /issue_status and /on_issue_status
lsp_on_issue_status
Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context
Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID

@aagman945

**Comment by Rahuljagwani** [comment]
@RupalSingla 
![image](https://github.com/ONDC-Official/v1.2.0-logs/assets/83580404/b3d3681f-49fa-4cde-b0dc-b376047fc73c)

Utility is showing the above, for same `message_id`
Please look into it.

Moreover,
The logs which are currently merged for Sellersetu, have been approved by utility,
Screenshots below,

**Flow 2**

![image](https://github.com/ONDC-Official/v1.2.0-logs/assets/83580404/f837899e-1961-4276-b564-4c51ea7bd988)


**Flow3**

![image](https://github.com/ONDC-Official/v1.2.0-logs/assets/83580404/ab1ea242-29df-43d8-b915-55a21b2a6b4e)

**Comment by sellersetu-hub** [comment]
@RupalSingla  can you clarify this, utility is giving no errors,

**Comment by sellersetu-hub** [comment]
PR with changes https://github.com/ONDC-Official/v1.2.0-logs/pull/1820 
@RupalSingla

**Comment by sellersetu-hub** [comment]
@RupalSingla Please review and provide feedback

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @sellersetu-hub
