### ISSUE TITLE
GlobalLinker (RSF) - compliance checks

### ISSUE THREAD

**Issue by extedcouD** [ONDC-Official/v1.2.0-logs#1328]
GlobalLinker RSP Logs
- on_receiver_recon:
  - schemaErr0: /message/orderbook/orders must NOT have fewer than 5 items

@Tjsvaradhan

**Comment by RupalSingla** [comment]
receiver_recon:
  - schemaErr0: /message/orderbook/orders/0/payment must have required property 'uri'
  - schemaErr1: /message/orderbook/orders/0/payment must have required property 'tl_method'
  - schemaErr2: /message/orderbook/orders/0/payment/params/amount must be number
  - schemaErr3: /message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_type must be equal to one of the allowed values (percent,amount)
  - schemaErr4: /message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_amount must be number
  - schemaErr5: /message/orderbook/orders/0/payment/@ondc1org1buyer_app_finder_fee_amount must be number
  - schemaErr6: /message/orderbook/orders/0/payment/@ondc1org1return_window must match format "duration"
  - schemaErr7: /message/orderbook/orders/0/payment/@ondc1org1settlement_basis must be equal to one of the allowed values (Collection)
  - schemaErr8: /message/orderbook/orders/0/payment/@ondc1org1settlement_window must match format "duration"
  - schemaErr9: /message/orderbook/orders/0/payment/@ondc1org1settlement_details/0/settlement_amount must be number
  - schemaErr10: /message/orderbook/orders/0/withholding_tax_gst/value must be number
  - schemaErr11: /message/orderbook/orders/0/withholding_tax_tds/value must be number
  - schemaErr12: /message/orderbook/orders/0/deduction_by_collector/value must be number

@Tjsvaradhan

**Comment by RupalSingla** [comment]
@Tjsvaradhan  all the issues are utility generated issues , for now u can avoid these errors

**Comment by Tjsvaradhan** [comment]
Hi Rupal,



Based on your comment below, I understand the RSP logs have been approved.
Can you please confirm my understanding.



Thanks
