### ISSUE TITLE
SellerSetu (RSF) - compliance checks

### ISSUE THREAD

**Issue by extedcouD** [ONDC-Official/v1.2.0-logs#1344]
In receiver_recon action cannot be "collector_recon"
@Rahuljagwani

**Comment by Rahuljagwani** [comment]
Solved #1408 @extedcouD

**Comment by aagman945** [comment]
There's an ongoing RSF compliance check happening here #1520

**Comment by sandeepshahi** [comment]
Duplicate issue board: For updates pls refer https://github.com/ONDC-Official/v1.2.0-logs/issues/1520
