### ISSUE TITLE
Airpay (BA: RET 12, 15) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#1346]
### RET 15

**/on_search**

- /message/catalog/bpp/providers/items/ must have required property '@ondc/org/return_window' 
- /message/catalog/bpp/providers/items/quantity must have required property 'unitized'

BNP must respond with a NACK; schema issues must be handled at BNP side

**/search (inc)**
- transaction_id and message id can't be same

@amultamse

**Comment by BLR-0118** [comment]
logs cleared for RET12/13/15/18
