### ISSUE TITLE
Mappls (BA) - RET11/18

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#1374]
RET11
====
- pls see comments [here](https://github.com/ONDC-Official/v1.2.0-logs/issues/985);

**Comment by BLR-0118** [comment]
@kalaivanansundaram

**Comment by BLR-0118** [comment]
pls test your buyer app with SNPs already in production in these domains:
RET11 - Uengage / EkSecond;
RET12 - Vidyant (Shopcircuit) / Fynd;
RET13 - SellerApp / Shopalyst;
RET14 - Shopalyst / Mystore;
RET15 - Shopalyst / Mystore;
RET16 - SellerApp / Shopalyst;
RET18 - MedPay/ITC;

You should check for the following:
1. all catalogs, both full & incremental, are processed, with appropriate flagging of errors;
2. variants / customizations are processed and displayed to buyer correctly;
3. product detail page shows appropriate info for buyer to make a decision, e.g. colour hex code is mapped to name, etc.;
4. order flows work successfully end-to-end with customizations;

**Comment by BLR-0118** [comment]
@kalaivanansundaram - if you need help connecting with any of the above teams, pls let me know

**Comment by kalaivanansundaram** [comment]
Sure and thank you for the guidance sir

**Comment by BLR-0118** [comment]
@kalaivanansundaram - logs cleared for RET11/18;
