### ISSUE TITLE
Addble (SA): RET10 - compliance checks

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#1375]
Flow 1
====
1. /on_search:
- pls use definition of item.quantity.available.count as per contract: "0" - out-of-stock, "99" - in-stock;
- pls use definition of item.quantity.maximum.count as per contract: "99" - no cap per order, any other value - applicable cap per order;
- no support for variants?

2. /on_search_inc:
- after considering 1 above, not sure what's the incremental change being pushed for the catalog?
- pls share use case for items out of stock;

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- fulfillment.type is required;
- pls fix the issue with item max/avail qty as explained above;

2. /on_init:
- tax_number & provider_tax_number required in bpp_terms;

3. /on_confirm:
- fulfillment.start.location.address required;
- tax_number & provider_tax_number required in bpp_terms;
- why is invoice attached here - this should be when state changes to Order-picked-up as there could  be part cancellations between order confirm & pickup;
- remove rateable;

Flow 3 - ok;

Flow 4
====
1. /on_cancel:
- curious why is delivery charge not refunded even though order hasn't been packed yet (precancel state is Pending);

**Comment by BLR-0118** [comment]
Flow 5
====
1. /on_cancel:
- both RTO-Initiated & RTO-Delivered events need to be generated;

**Comment by BLR-0118** [comment]
Flow 6a
=====
1. /on_update:
- items[] entry for forward shipment fulfillment (*79f15a) should have count 2;
- order changes for part cancel (as reflected in /on_update) are not showing in /on_status, which should have the complete order trail;

**Comment by BLR-0118** [comment]
Flow 6b
=====
1. /on_update_liquidated:
- quote_trail entry for item should have -ve value & quote updated accordingly;

**Comment by BLR-0118** [comment]
@yaikhomba - pls fix the above & resubmit for flows 1, 2, 6 (also respond to pts on 4 & 5 above) ASAP;

**Comment by yaikhomba** [comment]
@BLR-0118 
Flow 4 - this is configurable and can be moved.
Flow 5 - yes, RTO-Initiated and RTO-Delivered will be generated when auto accepting of returns and dispose is not turn on. This is configurable.

**Comment by BLR-0118** [comment]
Flow 6b
=====
1. In response to /update (for return request), SNP should send /on_update (with return fulfillment state of Return-Initiated);
2. Subsequent unsolicited /on_update will have Return-Liquidated (with new message_id);

In your case, you've merged 1 & 2;

**Comment by BLR-0118** [comment]
@yaikhomba - clearing logs for v1.2.0 (RET10), but pls make sure the above is fixed;

**Comment by BLR-0118** [comment]
RET10
====
flow 6a - ok;
flow 6b:
- return request has solicited response with state Return_Initiated;
- Liquidated is unsolicited response sent after seller has verified images, etc. for return request;

**Comment by BLR-0118** [comment]
AGR10 - ok, clearing logs for v1.2.0

**Comment by BLR-0118** [comment]
@yaikhomba - pls fix the issue for 6b above;
