### ISSUE TITLE
Crofarm (Otipy) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1386]
issue_CLOSE:
 "created_at": "context timestamp should be greater than or equal to updated_at in issue_close"

@harshitCrofarm

**Comment by vipul-jn** [comment]
Hi @RupalSingla, I am not understand this comment. can you pls explain a bit on it.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @vipul-jn
