### ISSUE TITLE
NDHGO (RET: 18/16/13) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1395]
### on_search (full_catalog)

- /message/catalog/bpp/providers/items/descriptor/code should be of valid length as per provided code
  ` 'type:code' where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others`
- contact number provided in '@ondc/org/contact_details_consumer_care' should be valid (provided: 2576256969)
- /message/catalog/bpp/providers/items/tags/attributes/material must values one of the following
  `https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/material.json`
- unicode formatting should not be provided in /message/catalog/bpp/providers/items/descriptor
- contact number provided in /message/catalog/bpp/providers/fulfillments should be valid (provided: 2576256969)
- Delivery timing construct should be provided in the /message/catalog/bpp/providers/tags as delivery is supported in fulfillments
- if for everyday timing are same, then it should not be sent in different blocks, kindly send in same block

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@sahil-ondc Have fixed the issues. Please review.

**Comment by rajib-senrysa** [comment]
@sahil-ondc Any update on this?

**Comment by sahil-ondc** [comment]
# RET 13, RET 16

## Flow 1

### on_search

- @ondc/org/fssai_license_no should not be provided
- /message/catalog/bpp/providers/items/descriptor/code should be provided
  'type:code' where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- in case of having timing same for delivery and order, it can be defined as 'All'

## Note

- Categories should be provided

@rajib-senrysa

**Comment by bmonish** [comment]
@sahil-ondc By Categories do you mean like we define for F&B? All the categories and In the product we provide the item sequence in that category?

**Comment by rajib-senrysa** [comment]
@sahil-ondc Can you please check the logs and update?

**Comment by rajib-senrysa** [comment]
@sandeepshahi @BLR-0118 Can we please get this verified?

**Comment by sandeepshahi** [comment]
## RET 13

- radius value should be feasible in /locations/circle
- EAN code should be used for SKUs in BPC
- message_id should be unique for incremental /on_search (unsolicited call)
- item/descriptor/code must be provided in incremental call
- are all types of incremental scenarios supported?

## RET 16

- similar issues as above
- GTIN code should be used for SKUs in H&K
- colour hex code should be in upper case


@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@sandeepshahi Yes we support all types of incremental search.

**Comment by rajib-senrysa** [comment]
@sandeepshahi @BLR-0118 @sahil-ondc We have submitted the updated logs. Please merge and review!

**Comment by BLR-0118** [comment]
RET13 - ok;

**Comment by BLR-0118** [comment]
RET16
====
1. use of GTIN is inappropriate for H&K (we're only using for electronics);
2. pls also send colour_name, along with colour;

RET18
====
1. Use of type 5 (other) for item descriptor code, for all items, is incorrect; why can't you use EAN for well known brands e.g. Volini / Himalaya?

**Comment by BLR-0118** [comment]
@rajib-senrysa - pls resubmit for RET16, RET18;

**Comment by BLR-0118** [comment]
@rajib-senrysa - logs cleared for RET13/18 for v1.2.0;

**Comment by bmonish** [comment]
@BLR-0118 I hope it's RET16 and RET18. RET13 is already cleared.

**Comment by BLR-0118** [comment]
@bmonish - correct, updated;
@rajib-senrysa - before deploying in Prod, pls make sure you also send "@ondc/org/statutory_reqs_packaged_commodities" for all categories (as doc in the contract); without this, many buyer apps may not show your catalog;
