### ISSUE TITLE
SellerApp (RET15/18) - compliance checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1411]
# RET 15

### on_search (full_catalog)

- 'parent_item_id' should be provided in case of categories provided
- /message/catalog/bpp/providers/items/descriptor/images should be publically accessible
- unicodes should not be provided in /message/catalog/bpp/providers/items/tags
- /message/catalog/bpp/providers/items/quantity/unitized/measure is not mapped correctly

### search (inc_catalog)

- Transaction logs should be provided

### on_search (inc_catalog)

- Transaction logs should be provided

# RET16

### on_search (full_catalog)

- @ondc/org/contact_details_consumer_care should be in format 'name, email, phone'
- value of prescription_required provided in /message/catalog/bpp/providers/items/tags should be in smallcase (yes or no)
- /message/catalog/bpp/providers/items/descriptor/code item/descriptor/code should be in this format - \"type:code\" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- /message/catalog/bpp/providers/items/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)
- item.quantity.unitized.measure.value should be greater than 0 (item_id: 45aa77b3af8645b2)
- /message/catalog/bpp/providers/items/descriptor/images should be publically accessible
- 'parent_item_id' should be provided in case of categories provided

### search (inc_catalog)

- Transaction logs should be provided

### on_search (inc_catalog)

- Transaction logs should be provided

@rajasellerapp

**Comment by sahil-ondc** [comment]
Yes @rajasellerapp , you will need to submit incremental logs

**Comment by sahil-ondc** [comment]
# RET 15

## Flow 1

### on_search (full_catalog)

- /message/catalog/bpp/providers/items/quantity/unitized/measure is not mapped correctly
- /message/catalog/bpp/providers/items/descriptor/code item/descriptor/code should be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- /message/catalog/bpp/providers/items/descriptor/images should be publically accessible
- /message/catalog/bpp/providers/items/descriptor/symbol should be publically accessible

### search (inc_catalog)

- Transaction logs should be provided

### on_search (inc_catalog)

- Transaction logs should be provided

# RET 18

## Flow 1

### on_search (full_catalog)

- /message/catalog/bpp/providers/locations/address/area_code should be provided as per provided gps
- formatting should not be provided in /message/catalog/bpp/providers/items/descriptor/long_desc (provided: '/n')
- /message/catalog/bpp/providers/items/descriptor/code item/descriptor/code should be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others

### search (inc_catalog)

- Transaction logs should be provided

### on_search (inc_catalog)

- Transaction logs should be provided

## Note

- categories should be provided

@rajasellerapp

**Comment by BLR-0118** [comment]
RET15
====
1. pls change item unitized measure to 1 unit, as weight is already defined in item.tags.attribute; item unitized measure can have the weight/volume wherever the category attrs don't have this metric (e.g. RET10, RET13, RET18);
2. item ad42e3d8f3538d05 is egg cooker; shouldn't this be "Kitchen Accessories"?

RET18
====
1. pls remove formatting e.g. for item b34149066b69b467, remove "\n" from long_desc;
2. for all items, can you give a count for each e.g. item 2fb1552fc15c2489, price 2799: what am I getting? e.g. 12 pieces => "12 unit", 120 pieces => "10 dozen", etc;

**Comment by BLR-0118** [comment]
@rajasellerapp

**Comment by rajasellerapp** [comment]
RET15
1. We have changed it. Will make note and collect the data from sellers like this now on.
2. That was an error. Fixed it.

RET18:
1. Removed.
2. This is the data given by the seller. Its been given as 1 unit for a packet. We will try getting the exact number of units.

@BLR-0118

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
