### ISSUE TITLE
Ecomm Express (LSP)	IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1423]
"issue":
-  "schemaErr0": "/message/issue/order_details/items/0/quantity must be number",
-  "org_domain": "Domain of organization for /issue api mismatched with domain in context"           
 "on_issue":
-  "bpp_id": "Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider",
-  "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider"

   issue_close":

-                 "schemaErr0": "/message/issue must have required property 'rating'",
-                 "org_domain": "Domain of organization for /issue api mismatched with domain in context",
-                 "created_at": "context timestamp should be greater than or equal to updated_at in issue"

   issue_status":
                "schemaErr0": "/context must have required property 'ttl'",
                "bpp_id": "Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider",
                "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider"
    "on_issue_status": {

-                 "bpp_id": "Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider",
-                 "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider",
-                 "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
-                 "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID"

Please send the logs once you verify it by utility.

@AryanSinghEcom

**Comment by AryanSinghEcom** [comment]
@RupalSingla 

I assume these are the logs generated from the IGM's Log verification utility. I had already informed this in the daily developers meet that the utility's log verification output has some bugs as it is producing a lot of false positives.

Here is the explanation for the errors that the utility has suggested:

**on_issue_status**
- "bpp_id": "Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider",
**FALSE POSITIVE, Please check Logs. The bap id is that of the seller app.**

-  "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider",
**FALSE POSITIVE, Please check Logs. The bap id is that of the seller app.**

-  "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
   **FALSE POSITIVE: This should not have been an error from utility in the first place as it is the nature of contract. If a call is cascaded to logistics, context will have the domain of logistics. Respondent action holds the trail of actions so this is bound to happen**

-  "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID"
**FALSE Positive: The bpp id and respondent_actions.org.name are same. We also have to append the domain name with '::' symbol after the bpp id which has been done and could be the case for this error.**

**Comment by RupalSingla** [comment]
@AryanSinghEcom Pls avoid the above errors that are false positive and do resolve all the errors that are  present in
 issue _close

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0
 @AryanSinghEcom
