### ISSUE TITLE
Thrive IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1429]
"issue": 
   "respTime": "Time of creation (created_at) and time of updation for /issue api should be the same",
    "created_at": "context timestamp should be greater than or equal to updated_at in issue"
            
on_issue:

- "schemaErr0": "/message/issue/issue_actions/respondent_actions/0 must have required property 'respondent_action'",
-   "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue",
-  "created_at": "'created_at' should match issue's 'created_at'"
on_issue_status:

-                 "schemaErr0": "/message/issue/issue_actions/respondent_actions/0 must have required property 'respondent_action'",
-                 "action_err": "context.action should be on_issue_status",
-                 "igmIssueMsgId": "Message  ID mismatch in /issue_status and /on_issue_status",
-                 "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
-                 "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status",
-                 "created_at": "'created_at' should match issue's 'created_at'"

**Comment by sandeepshahi** [comment]
@amitkbadheka

**Comment by RupalSingla** [comment]
FLOW1
issue
"respTime": "Time of creation (created_at) and time of updation for /issue api should be the same
on_issue
"action_err": "context.action should be on_issue",
"org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
issue_status
"igmTxnId": "transaction ID mismatch in /issue and /issue_status"
on_issue_status
"schemaErr0": "/message/issue/issue_actions/respondent_actions/0 must have required property 'respondent_action'",
"schemaErr1": "/message/issue/issue_actions/respondent_actions/2/respondent_action must be equal to one of the allowed values (PROCESSING,CASCADED,RESOLVED,NEED-MORE-INFO)",
"igmIssueMsgId": "Message ID mismatch in /issue_status and /on_issue_status",
"org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with domain in context",
"org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID",
"created_at": "'created_at' should match issue's 'created_at'"
FLOW2
issue
"respTime": "Time of creation (created_at) and time of updation for /issue api should be the same"
on_issue
"action_err": "context.action should be on_issue",
"org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
"created_at": "'created_at' should match issue's 'created_at'"
issue_status
"igmTxnId": "transaction ID mismatch in /issue and /issue_status"
on_issue_status
"schemaErr0": "/message/issue/issue_actions/respondent_actions/0 must have required property 'respondent_action'",
"igmIssueMsgId": "Message ID mismatch in /issue_status and /on_issue_status",


@amitkbadheka

**Comment by madlad33** [comment]
@RupalSingla For IGM -> Flow 1 -> "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context". 

* I don't see any key named org_domain in the docs, does it mean the  object 
* "org": {
                "name": "ondc-preprod.hashtagloyalty.net" } ?
Also for the name, it should match the domain of the context? The domain in the context is ONDC:RET11

**Comment by madlad33** [comment]
@RupalSingla @sandeepshahi Can you please help with this?

**Comment by RupalSingla** [comment]
@madlad33 Please avoid this error 
org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context", your understanding is correct .

@madlad33

**Comment by RupalSingla** [comment]
Flow 2 : 
created_at": "'created_at' should match issue's 'created_at' there is a difference in created_at timestamp

@amitkbadheka

**Comment by amitkbadheka** [comment]
Hi @RupalSingla  is that the only issue?

**Comment by amitkbadheka** [comment]
Hi @RupalSingla  we have fixed the issue. Can you get review it?

**Comment by RupalSingla** [comment]
Logs cleared for  1.0.0 @amitkbadheka

**Comment by amitkbadheka** [comment]
Thank you @RupalSingla
