### ISSUE TITLE
Sabhyasha (SA IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1431]
issue"
"respTime": "Time of creation (created_at) and time of updation for /issue api should be the same",
 "created_at": "context timestamp should be greater than or equal to updated_at in issue"
_issue_CLOSE
"created_at": "context timestamp should be greater than or equal to updated_at in issue_close"

@SatyaranjanSwain

**Comment by SatyaranjanSwain** [comment]
issue and issue_close APIs are called by the buyer. So I can't change the payload from my side. 

@RupalSingla

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @SatyaranjanSwain
