### ISSUE TITLE
Thrive RSF - compliance  check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1432]
Flow 1
on_receiver_recon:
  - schemaErr0: /context/domain must be equal to one of the allowed values (ONDC:NTS10)

receiver_recon:
  - schemaErr0: /context/domain must be equal to one of the allowed values (ONDC:NTS10)

**Comment by sandeepshahi** [comment]
@amitkbadheka

**Comment by RupalSingla** [comment]
Flow 1
- **receiver_recon**
Additional properties (payments) must not be present.
Within @ondc/org/settlement_details, the following attributes are absent: settlement_amount, upi_address, and beneficiary_address.
payment/params transaction_status is not provided.
Regarding @ondc/org/buyer_app_finder_fee_type, it should be defined as "Percentage" according to retail specifications.
Several attributes such as @ondc/org/collected_by_status, @ondc/org/withholding_amount, @ondc/org/withholding_amount_status, @ondc/org/return_window, @ondc/org/return_window_status, @ondc/org/settlement_basis, @ondc/org/settlement_basis_status, @ondc/org/settlement_window, and @ondc/org/settlement_window_status are expected but missing.
The created_at and updated_at timestamps are required to be identical.

@amitkbadheka

**Comment by RupalSingla** [comment]
Logs cleared @amitkbadheka

**Comment by amitkbadheka** [comment]
Thanks @RupalSingla
