### ISSUE TITLE
EkSecond (SA)	IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1433]
issue
-  "respTime": "Time of creation (created_at) and time of updation for /issue api should be the same",
-   "updatedTime": "created_at for /issue api should be less than context.timestamp",
-    "created_at": "context timestamp should be greater than or equal to updated_at in issue"
issue_CLOSE":
-      "created_at": "context timestamp should be greater than or equal to updated_at in issue_close"

@NajeebMohammed

**Comment by Syed12work** [comment]
/issue api calls comes form the buyer app. the seller app cannot apply any changes to the incoming /issue api. We revert back with the /on_issue and /on_issue_status calls to the buyer app.

**Comment by RupalSingla** [comment]
Logs cleared @Syed12work for version 1.0.0
