### ISSUE TITLE
Unizap IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1449]
Flow 1
issue
Time of creation (created_at) and time of updation for /issue api should be the same
FLOW2
issue
Time of creation (created_at) and time of updation for /issue api should be the same
issue_closed
context timestamp should be greater than or equal to updated_at in issue_close
ret_on_issue_status
Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
ret_on_issue_status_unsolicited
Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID
lsp_issue
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
Organization's Name for /issue api mismatched with bap id
lsp_on_issue
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider
lsp_issue_close
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
lsp_issue_status
Transaction Id should be the id from the logistics transaction in /issue_status api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider
lsp_on_issue_status
Transaction Id should be the id from the logistics transaction in /on_issue_status api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider
Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context

issue
Time of creation (created_at) and time of updation for /issue api should be the same
context timestamp should be greater than or equal to updated_at in issue
ret_issue_CLOSE
context timestamp should be greater than or equal to updated_at in issue_close
ret_on_issue_status
Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
ret_on_issue_status_unsolicited
Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID
lsp_issue
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
lsp_on_issue
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider
lsp_issue_close
Transaction Id should be the id from the logistics transaction in /issue api. It should not be of the retail transactions that is being used for retail
lsp_issue_status
Transaction Id should be the id from the logistics transaction in /issue_status api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider
lsp_on_issue_status
Transaction Id should be the id from the logistics transaction in /on_issue_status api. It should not be of the retail transactions that is being used for retail
Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider
Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider
Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/1506
@RupalSingla Please review our updated IGM logs as per the above mentioned compliance check.

**Comment by rajib-senrysa** [comment]
@RupalSingla Can you please review and provide feedback on the updated IGM logs.
https://github.com/ONDC-Official/v1.2.0-logs/pull/1506

**Comment by sharique-zafar** [comment]
FLOW 1
issue
    Time of creation (created_at) and time of updation for /issue api should be the same
issue_closed
    context timestamp should be greater than or equal to updated_at in issue_close
ret_on_issue_status_unsolicited
    MessageId should not match in /issue_status and /on_issue_status(unsolicited)

Flow 2
issue
    Time of creation (created_at) and time of updation for /issue api should be the same
     created_at for /issue api should be less than context.timestamp
ret_issue_CLOSE
     Context timestamp should be greater than or equal to updated_at in issue_close
ret_on_issue_status
      Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
ret_on_issue_status_unsolicited
      MessageId should not match in /issue_status and /on_issue_status(unsolicited)
      Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID
lsp_issue
     Organization's Name for /issue api mismatched with bap id
lsp_on_issue
     Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider
     Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider
lsp_issue_status
    Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider
    Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider
lsp_on_issue_status
     Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider
     Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider
     Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
     Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context

FLow 3
 issue
      Time of creation (created_at) and time of updation for /issue api should be the same
ret_issue_CLOSE
      Context timestamp should be greater than or equal to updated_at in issue_close
ret_on_issue_status
     Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
ret_on_issue_status_unsolicited
      MessageId should not match in /issue_status and /on_issue_status(unsolicited)
      Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[3] mismatched with BPP ID
lsp_issue
      Organization's Name for /issue api mismatched with bap id
lsp_on_issue
       Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider
       Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider
lsp_issue_status
       Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider
       Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider
lsp_on_issue_status
       Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider
       Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider
      Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID
       Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context
       
       
@rajib-senrysa

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @rajib-senrysa
