### ISSUE TITLE
Globallinker (SA)	IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1454]
FLOW 1
issue
Time of creation (created_at) and time of updation for /issue api should be the same
context timestamp should be greater than or equal to updated_at in issue
issue_CLOSE
context timestamp should be greater than or equal to updated_at in issue_close
FLOW 2
issue
Time of creation (created_at) and time of updation for /issue api should be the same
context timestamp should be greater than or equal to updated_at in issue
FLOW 3
issue
Time of creation (created_at) and time of updation for /issue api should be the same

@Tjsvaradhan

**Comment by Tjsvaradhan** [comment]
Hi Rupal,



We have investigated the comments from you and please refer to our
responses below:



a)       GlobalLinker is a Seller NP (MSN)



b)       Hence, all the feedback given below are for the APIs Triggered
from the Buyer App. (Mostly on the timestamp values assigned at the Buyer
App end.)



c)       There are no issues reported for the “on_” calls and hence they
seem to be compliant.



Based on the above, I would appreciate it if you can close the IGM Logs for
GlobalLinker.




*Note: *We are using Plotch.ai’s IGM solution, Node Desk, which has already
been certified.



Thanks

**Comment by RupalSingla** [comment]
on_issue_status:
schema errors - objects like Resolution And Resolution Provider are not part of on_issue _status.

@Tjsvaradhan

**Comment by RupalSingla** [comment]
Logs cleared for 1.0.0 @Tjsvaradhan
