### ISSUE TITLE
FutureSoft IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1459]
Flow 1
issue
* Time of creation (created_at) and time of updation for /issue api should be the same
issue_CLOSE
* context/core_version must be equal to constant (1.0.0)
* message/issue must have required property 'rating'
IGM/FLOW2
issue
* Time of creation (created_at) and time of updation for /issue api should be the same
issue_CLOSE
* context/core_version must be equal to constant (1.0.0)
* message/issue must have required property 'rating'
on_issue_status_unsolicited
* context/domain must be string
* context/domain must be equal to one of the allowed values (nic2004:52110,nic2004:60232,ONDC:RET10,ONDC:RET11,ONDC:RET12,ONDC:RET13,ONDC:RET14,ONDC:RET15,ONDC:RET16,ONDC:RET17,ONDC:NTS10,ONDC:NTS11,ONDC:TRV10,ONDC:FIS10,ONDC:FIS11)
* Domain for /issue api should be equal to /on_issue_status api
* Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context
* Domain code provided should be the same across all APIs.

@satyasaiatmakuri

**Comment by GeetaVerma2797** [comment]
> Flow 1 issue

> * message/issue must have required property 'rating'
>   IGM/FLOW2
>   issue
>   issue_CLOSE
> * message/issue must have required property 'rating'

- If we get rating in /issue api then we can send it in the /on_issue api. Also please in which section we need to send.

> @satyasaiatmakuri

**Comment by GeetaVerma2797** [comment]
> Flow 1 issue

>   issue_CLOSE
> * message/issue must have required property 'rating'
>   IGM/FLOW2
>   issue_CLOSE
> * message/issue must have required property 'rating'


- Only after receiving a rating from the issue's api can we send a rating using the /on_issue api. We are not receiving ratings in the /issue api in our case.  Please let us know which section we should send rating object if we receive as well?
- 
@RupalSingla

**Comment by RupalSingla** [comment]
Flow 2 :
on_issue_status and on_issue 
"complainant_actions": should not be part of these 2 api 


@GeetaVerma2797

**Comment by fsgithub2024** [comment]
> Resubmitted the logs 2 weeks before. Please review the new logs
> @RupalSingla

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @fsgithub2024
