### ISSUE TITLE
Retailware (SA)  IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1460]
FLOW1
issue
* Time of creation (created_at) and time of updation for /issue api should be the same

on_issue and on_issue_status:
Respondent_action  is having different values in timestamp , which is not possible

@Retailware

**Comment by Retailware** [comment]
Latest corrections

FLOW1
issue

  *   Time of creation (created_at) and time of updation for /issue api should be the same

on_issue and on_issue_status:
Respondent_action is having different values in timestamp , which is not possible

@Retailware<https://github.com/Retailware>

________________________________
From: RupalSingla ***@***.***>
Sent: Tuesday, April 23, 2024 3:25 PM
To: ONDC-Official/v1.2.0-logs ***@***.***>
Cc: Manoj Hogale ***@***.***>; Mention ***@***.***>
Subject: [ONDC-Official/v1.2.0-logs] Retailware (SA) IGM - compliance check (Issue #1460)


FLOW1
issue

  *   Time of creation (created_at) and time of updation for /issue api should be the same

@Retailware<https://github.com/Retailware>

**Comment by Retailware** [comment]
FLOW1
issue
Time of creation (created_at) and time of updation for /issue api should be the same
**---> this issue from buyer side.**

on_issue and on_issue_status:
Respondent_action is having different values in timestamp , which is not possible
**-- We have made changes as per the compliance checks and created a new PR.**

**Comment by RupalSingla** [comment]
Logs cleared fopr version 1.0.0 @Retailware
