### ISSUE TITLE
Kiko Live - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1484]
Multiple issues identified. Kindly run the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b) before submitting the logs. You may submit only group B logs.

@vijendrapatidar

**Comment by abhinavv245** [comment]
## TAT breach

**/cancel**

- 006 is not the correct cancellation reason code to be used by LBNP (use 007)

@vijendrapatidar

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
