### ISSUE TITLE
Xpressbazaar - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1485]
Multiple issues identified. Kindly use the [log verification utility](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b) before submitting the logs. Also, please test with a verified LSP in pre prod environment.

@ShippuYadav

**Comment by abhinavv245** [comment]
@Pawan-ens

**Comment by abhinavv245** [comment]
## All Flows

**/search**

- fulfillmet/type should be 'Delivery' 
- provider/schedule/times is not required

**/init**

- how is BPP (LSP) collecting payment post fulfillment?

**/confirm**

- order/tags (bpp_terms and bap_terms) - from where are you receiving bpp_terms? and whose acceptance is being provided?
- in fulfillments/start/instructions - why is additional_desc and images provided? as fulfillment type is Delivery, it is not a return order

**/update**

- deferred RTS via update call should be implemented

@Pawan-ens

**Comment by ensservices** [comment]
@abhinavv245 Any update on the logs

**Comment by BLR-0118** [comment]
1. fulfillment start/end contact phone must be 10 digits (in most flows);

**Comment by BLR-0118** [comment]
@Pawan-ens - pls fix & resubmit;

**Comment by Pawan-ens** [comment]
Subject: Issue Resolution

Hii Sir,

I hope this message finds you well. I want to inform you that the issue has
been successfully solved.

Best regards,
Pawan Kumar Maurya

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (LBNP);
