### ISSUE TITLE
Chattybao (RET10) - Compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#150]
**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/0/items/8/tags/2 must have required property 'list'
- /message/catalog/bpp~1providers/1/items/4/quantity/unitized/measure must have required property 'value'
- value passed in serviceability tags should be same as passed in location/circle

**on_init**

- City code mismatch in search & on_init
- item.price.value mismatches for item passed in breakup[0] with on_select
- tax object missing in on_init but present in on_select

**on_confirm**

- invalid area_code provided in /message/order/fulfillments/start/address with respect to provided GPS

@venkat77777

**Comment by venkat77777** [comment]
@sharmasahil0331 fixed the issues and submitted new PR, please check

**Comment by venkat77777** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/154

**Comment by venkat77777** [comment]
@sharmasahil0331 flow 4 and flow 5 logs are submitted for verification. Please check https://github.com/ONDC-Official/v1.2.0-logs/pull/171

**Comment by sharmasahil0331** [comment]
**on_search_full_catalog_refresh**

- category should be a valid in serviceability (invalid category = Kirana / Provision store)

**on_select**

- tax breakup to be included only if tax is not 0, as per the API contract

 @venkat77777

**Comment by venkat77777** [comment]
@sharmasahil0331 i have fixed above mentioned issues and have captured logs for all flows from flow 1 to flow 5 and updated the current PR.

Please check and share feedback

**Comment by sharmasahil0331** [comment]
**on_search_inc_refresh**

- Message Id for /search_inc_refresh and /on_search_inc_refresh api should be same
- Similar Item as in /on_search_full_catalog_refresh api call, item id- be497f40-b340-11ed-b67d-b356d861831b:MR8mcezPPQEA-r8EhP6UN9

**init**

- value of address.name, address.building and address.locality should be unique

**on_status**

- delivery timestamp (/end/time/timestamp) can't be less than or equal to the pickup timestamp (start/time/timestamp)

@venkat77777

**Comment by venkat77777** [comment]
@sharmasahil0331 if possible can you please review all the logs and share feedback at once?

**Comment by venkat77777** [comment]
@sharmasahil0331 have made the feedback changes and submitted PR https://github.com/ONDC-Official/v1.2.0-logs/pull/214

**Comment by sharmasahil0331** [comment]
**on_search_inc_refresh**

- message Id for /search_inc_refresh and /on_search_inc_refresh api should be same

**on_search_full_catalog_refresh**

- message/catalog/bpp/descriptor/images should have valid https image url
- message/catalog/bpp/providers/images cannot have property '@ondc/org/return_window' be 'NA'

**select**

- timestamp for /on_search api cannot be greater than or equal to /select api

**on_confirm**

- order.updated_at timestamp should not be greater then the context.timestamp

@venkat77777

**Comment by sahil-ondc** [comment]
## Flow 1

**search_full_catalog_refresh**

- bap_terms should not be provided as static terms aren't enabled yet

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/items/code should be unique code for item which will be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- /message/catalog/bpp/providers/items must have property '@ondc/org/statutory_reqs_packaged_commodities' in case of category_id 'Foodgrains'

**search_inc_catalog_refresh**

- context/city should be '\*' while sending search_inc_catalog request
- bap_terms should not be provided as static terms aren't enabled yet

**on_search_inc_catalog_refresh**

- in on_search_full_catalog_refresh location with id '15b5f8a0-29b5-11ed-93b0-8d73fff38901' was enabled, then in on_search_inc_catalog_refresh why its provided with label 'open'

## Flow 2

**on_select**

- /message/order/items should have properties as mentioned in api contract

## Flow 4

**on_cancel**

- invalid quote trail provided as per the item price provided in on_search_full_catalog_refresh

## Note

- Please use the same buyer NP to submit the logs
- Kindly submit categories in on_search in case you are supporting variants

@venkat77777

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- close_timing to be sent only if the store was previously sent as closed using full or incremental pull;
- remove accept_bap_terms (as static terms aren't yet enabled);
- for grocery packaged items (e.g. item ded21392-1a41-11ee-8ddd-2bac5af1417f:MlepomA3E7XUC_7MpLJgjn), pls also send EAN code in item.descriptor.code;
- item unitized measure should show 10 kg for the above item;
- pls use updated categories from [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0) list;

2. /on_search_incremental:
- pls share logs for common grocery use cases such as item out of stock, change in price;

Flow 2
====
1. /on_init:
- remove provider_location, cancellation_terms;

2. /on_confirm:
- structure for bpp_terms is invalid;

Flow 5
====
1. /on_cancel_rto:
- for grocery, item costs are generally refunded in full and items are sent back to the store for resale; why not make your RTO fulfillment, quote trail & quote realistic?

for all flows with quote trail, pls check that there is no object with 0 value;

Flow 3, 4, 6 - ok;

**Comment by BLR-0118** [comment]
@venkat77777

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- item.quantity.available.count of "0" means out-of-stock & "99" means in-stock; similarly, item.quantity.maximum.count of "99" means no order cap and any other non-zero value means there's an order cap; so, what does max count of "0" for item e54e3fc0-944c-11ee-848d-2d2b8538311e:MR8mcezPPQEA-r8EhP6UN9 mean?

2. /on_search (incremental):
- for item "f862b941-1a41-11ee-8ddd-2bac5af1417f:MR8mcezPPQEA-r8EhP6UN9", how can maximum_value (MRP) change?
- same with item "e3007b00-1a41-11ee-8ddd-2bac5af1417f:MR8mcezPPQEA-r8EhP6UN9";

Flow 2
====
1. /on_init:
- pls remove everything from payment except settlement_details, buyer finder fee (as these will be filled up by buyer app in case of prepaid payment collection by them);

2. /on_confirm:
- why is provider.locations.id null?
- pls also add "provider_tax_number" to bpp_terms for the buyer NP to verify that you're an MSN;

**Comment by BLR-0118** [comment]
@venkat77777 - pls resubmit logs only for issues above;
also, need timeline by which item unitized quantity will be correctly filled up & when do you plan to enable variants?

**Comment by venkat77777** [comment]
@BLR-0118 Have done the feedback changes and submitted the required logs in the PR https://github.com/ONDC-Official/v1.2.0-logs/pull/491

Please review and share your feedback.

Item Unitized quantity correction will be done by Feb 15th and regarding Variants, we are planning to do them by Feb 28th or F&B category inclusion whichever is earlier

**Comment by BLR-0118** [comment]
@venkat77777 - Feb 15th for item unitized quantity correction is too late. I can have the QA process initiated (assuming your logs are ok) but you need to have this fixed within the next 2 weeks

**Comment by venkat77777** [comment]
@BLR-0118 understand. We'll try to finish it within this month itself Supriyo. I'll update you as soon as it is done

**Comment by BLR-0118** [comment]
@venkat77777
