### ISSUE TITLE
Gupshup (BA: RET11) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#1521]
Flow 1
====
1. Buyer finder fee (BFF) is 0% in full search & 3% in incremental search request sent just few mins later;
2. Are you supporting incremental push?

Flow 2
====
1. can't verify flows as Items used in /select aren't a part of the catalog logs shared for flow 1;
2. if you're creating a make-to-order product using item & customization e.g. (biryani + gulab jamun), you also need to create a dynamic item id for this make-to-order product which is assigned to order.items[].parent_item_id & passed as part of /select, as shown [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.a0m67mluxbww);

**Comment by BLR-0118** [comment]
@anilSinghgupshup - pls fix & resubmit for all flows

**Comment by BLR-0118** [comment]
logs are largely ok, few questions:
1. when do you plan to support tracking? (EkSecond has enabled tracking but there aren't logs for tracking);
2. typically, buyer cart selection is an iterative process, resulting in multiple /select requests e.g. flow 3 out-of-stock scenario; it is required to use the same transaction_id in these /select requests;
3. flow 4 - when do you plan to support buyer cancel?

**Comment by BLR-0118** [comment]
@anilSinghgupshup - 2 is an issue that needs to be fixed, pls also update on 1 & 3; after that, I can move you to the next stage;

**Comment by anilSinghgupshup** [comment]
@BLR-0118 

Please find below comment:

1) We will implement text updates for riders distance from the customer and approximate ETA to deliver using the GPS coordinates received
	a) We already have this in the roadmap and will prioritize and implement once we go live
2) We have fixed the same transaction ID based for multiple carts and handling out_of_stock items. We will keep the cart valid as per TTL received for the quote from the seller app
3) If the order is not accepted within 5 mins we will cancel the order from our side (we will publish this as part of our sorting criteria for the sellers)
	a) Allowing buyer to cancel the order is also in our roadmap and we will implement this once we go live

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0;
