### ISSUE TITLE
Dailybee (SA: RET18) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#1525]
**/on_search**

- "Delivery and Self-Pickup" is not a valid fulfillment type in /bpp/providers/fulfillments; separate fulfillment object should be created for each one fo them and items must be mapped to the default one
- fulfillment ids and type mismatch in /bpp/fulfillments and bpp/providers/fulfillments
- "All" enum can be used for timing block if the timings are same for Delivery, order etc
- GTIN code should be provided in item/descriptor/code for H&W categories
- mfg_license_no must be provided in "@ondc/org/statutory_reqs_packaged_commodities"
- categories in bpp/providers should be used for defining variants; aren't variants supported?

**/on_search (inc)**

- provider id doesn't exist in the full pull

@a-satyateja

**Comment by sahil-ondc** [comment]
### On Search
- If the ‘Self-Pickup’ is not present in the bpp/providers/fulfillments, then it shouldn’t be provided in bpp/fulfillments
- Kindly provide valid values instead of empty strings in ‘statutory_reqs_packaged_commodities’ for the items
- Invalid EAN code provided for the item_id : ‘661ba21390f45674e0c303af’. Kindly check for others as well

@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc 

Please merge and verify the logs. 

https://github.com/ONDC-Official/v1.2.0-logs/pull/2566

**Comment by Jagannath-wits** [comment]
## Flow 1
### On Search
- If timing is same for 'Order/Delivery', Kindly use enum 'All' 
- Why there is tags.iming for 'Self-Pickup' is provided if it's not present in the fulfillments ?

### On Search Inc
- Why the timestamp of an item is not update in the On Search Inc call ?

@a-satyateja

**Comment by a-satyateja** [comment]
@Jagannath-wits 
Please check the latest logs : https://github.com/ONDC-Official/v1.2.0-logs/pull/2660

**Comment by sandeepshahi** [comment]
Duplicate issue board; Refer https://github.com/ONDC-Official/v1.2.0-logs/issues/2629 for the latest updates
