### ISSUE TITLE
eComviser (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1584]
Success Flow
on_receiver_recon
Context/Action Differentiation: Action should be  on_receiver_recon.
"message" must be a string.
"details" path: /message/orderbook/orders/0/diff_amount/value.
receiver_recon
"message" must be a string.
Details: /message/orderbook/orders/0/order_recon_status.
"message" must be equal to one of the allowed values (01,02,03).
Details: /message/orderbook/orders/0/order_recon_status.
"message" must be a string.
Details: /message/orderbook/orders/0/payerdetails/payer_account_no.
"message" must be an object.
Details: /message/orderbook/orders/0/diff_amount.
"message" must be a string.
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be equal to one of the allowed values (01,02,03,04).
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be an object.
Details: /message/orderbook/orders/0/counterparty_diff_amount.
Correction Flow
on_recon_status
Context/Action Differentiation: Action is wrong it should be on_receiver_recon.
"message" must be a string.
Details: /message/orderbook/orders/0/diff_amount/value.
counterparty_recon_status can't be "01" in case of correction flow
receiver_recon
"message" must be a string.
Details: /message/orderbook/orders/0/payerdetails/payer_account_no.
"message" must be an object.
Details: /message/orderbook/orders/0/diff_amount.
"message" must be a string.
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be equal to one of the allowed values (01,02,03,04).
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be an object.
Details: /message/orderbook/orders/0/counterparty_diff_amount.
receiver_recon_failed
"message" must be a string.
Details: /message/orderbook/orders/0/payerdetails/payer_account_no.
"message" must be an object.
Details: /message/orderbook/orders/0/diff_amount.
"message" must be a string.
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be equal to one of the allowed values (01,02,03,04).
Details: /message/orderbook/orders/0/counterparty_recon_status.
"message" must be an object.
Details: /message/orderbook/orders/0/counterparty_diff_amount

@dheerajwebkul

**Comment by dheerajwebkul** [comment]
@RupalSingla 
Fixed all and created PR.
https://github.com/ONDC-Official/v1.2.0-logs/pull/1631
Please check.

**Comment by JyotiSharma0711** [comment]
Ecomviser

**correction flow**

**receiver_recon**

- If message/orderbook/orders/payment/collected_by BAP, then the settlement counterparty specified in @ondc/org/settlement_details/settlement_counterparty should be buyer-app.
- @ondc/org/buyer_app_finder_fee_type" enum should be "Percentage", (enum as per retail specs)
- created_at and updated_at should be greater than message/orderbook/orders/payment/@ondc/org/settlement_details/settlement_timestamp

**normal flow**

**receiver_recon**

- If message/orderbook/orders/payment/collected_by  BAP, then the settlement counterparty specified in @ondc/org/settlement_details/settlement_counterparty should be buyer-app.
- @ondc/org/buyer_app_finder_fee_type" enum should be "Percentage", (enum as per retail specs)
- created_at and updated_at should be greater than message/orderbook/orders/payment/@ondc/org/settlement_details/settlement_timestamp

@dheerajwebkul

**Comment by RupalSingla** [comment]
orderbook needs to have atleast 5 orders , for both correction and success flow.
on_receiver_recon
receiver_recon need not to be provided in on_receiver_recon

@dheerajwebkul
