### ISSUE TITLE
eComviser (SA) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1587]
@dheerajwebkul 
 Can you please check , payload inside the on_issue_status and  on_issue_status (unsolicited) is same . which is not possible .

**Comment by dheerajwebkul** [comment]
@RupalSingla 
Fixed all and created PR.
https://github.com/ONDC-Official/v1.2.0-logs/pull/1631
Please check.

**Comment by amitsinha07** [comment]
@dheerajwebkul 

Inside on_issue_status and on_issue_status (unsolicited)  created_at, updated_at and timestamp are same. Which is not possible. Kindly update it

**Comment by dheerajwebkul** [comment]
@amitsinha07 
fixed please check,
https://github.com/ONDC-Official/v1.2.0-logs/pull/1639

**Comment by dheerajwebkul** [comment]
@amitsinha07 'created_at' must be same as issue created time, so it will be same in all json as per the validator
```
"ret_on_issue_status": {
                "created_at": "'created_at' should match issue's 'created_at'"
            }
```
so its same.

**Comment by RupalSingla** [comment]
@dheerajwebkul  there is no resoltion that is provided inthe on_issue_status _unsolicoted call , without that issue cannot be closed

**Comment by dheerajwebkul** [comment]
@RupalSingla ok, we are checking

**Comment by RupalSingla** [comment]
eComvisor (SA)
FLOW 1
      issue
           1. created_at and updated_at should be same 

      on_issue_status
           1. There should be only one "PROCESSING" respondent_actions

       on_issue_status (Unsolisated)
           1. There should be only one "PROCESSING" respondent_actions

FLOW 2
     issue
           1. created_at and updated_at should be same

     on_issue_status
           1. There should be only one "PROCESSING" respondent_actions

     on_issue_status (Unsolisated)
           1. There should be only one "PROCESSING" respondent_actions

@dheerajwebkul

**Comment by dheerajwebkul** [comment]
> on_issue_status
>        1. There should be only one "PROCESSING" respondent_actions

@RupalSingla 
on_issue_status
       1. There should be only one "PROCESSING" respondent_actions
       
So what status will be there if the provider replies with some update like 'we are working' etc. 
Can I use 'NEED-MORE-INFO' for reply like 'we are working on this' or for all replies?
