### ISSUE TITLE
Dailybee - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1605]
Multiple issues identified. Kindly run the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self-verify the logs before submission. 

@a-satyateja

**Comment by BLR-0118** [comment]
Flow 1 - deferred rts
=============
1. /update:
- for OTP, you need to use the authorization block as explained [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit);

**Comment by BLR-0118** [comment]
@a-satyateja - clearing the logs for v1.2.0 but pls make sure the above issue is fixed before deploying to Prod;
