### ISSUE TITLE
Unistack (SA)	RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1612]
Correction Flow:
receiver_recon:
Message/orderbook/orders/"counterparty_diff_amount" is 0 for correction flow.

Normal Flow:
receiver_recon:
Created_at and updated_at should be the same.

@RaiManish3

**Comment by RaiManish3** [comment]
@RupalSingla 

I had few doubts. Please clear them up.
1. the counterparty_diff_amount isn't required in receiver_recon i think.
2. created_at and updated_at should be different i think. Does created_at represent the time at which /collector_recon was invoked?

**Comment by RaiManish3** [comment]
@RupalSingla 
Please clear our doubts.

**Comment by RupalSingla** [comment]
Logs cleared for 1.0.0 @RaiManish3
