### ISSUE TITLE
Addble (RET12/13/16) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1653]
### on_search (full catalog)

- InvldValueforItem[0][0] : Size": "Invalid item value: [Regular]. It must be one of the allowed values
- InvldValueforItem[0][1] : Size": "Invalid item value: [S]. It must be one of the allowed values
- fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/prvdr0/fulfillments
- area_code should be as per provided gps in /message/catalog/bpp/providers/locations
- item/quantity/unitized/measure should be mapped correctly (how item.id: ZxryC1Sy9qjL7st44p1o is 1 gram)

### on_search (full catalog)

- fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/prvdr0/fulfillments

### on_search (inc catalog)

- fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/prvdr0/fulfillments
- Similar Item as in /on_search api call, item id- G6f2i5PuHQK8CtFcaraJ (item should only be provided in case of any delta changes)

### on_search (full catalog)

- fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/prvdr0/fulfillments

### on_search (inc catalog)

- fulfillment_id in /bpp/providers[0]/items[0] should map to one of the fulfillments id in bpp/prvdr0/fulfillments
- Similar Item as in /on_search api call, item id- yEoBDPXwINvJyio47h36 (item should only be provided in case of any delta changes)

## Common

- /message/catalog/bpp/fulfillments/type must be equal to one of the allowed values (Delivery,Self-Pickup)
- code should provided in /message/catalog/bpp/providers[0]/items[0]/descriptor
- accept_bap_terms is not required in bpp/descriptor/tags as those are not enabled yet

## Note

- short and long description should not be same. (provided catalog should be subset of production catalog)

@migrajkumar

**Comment by migrajkumar** [comment]
For RET 12
InvldValueforItem[0][0] : Size": "Invalid item value: [Regular]. It must be one of the allowed values
InvldValueforItem[0][1] : Size": "Invalid item value: [S]. It must be one of the allowed values

which enum should be used?
https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/size.json

OR

https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/fashion/size.json

@sahil-ondc

**Comment by sahil-ondc** [comment]
@migrajkumar 

**Faishon one** https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/fashion/size.json

@sandeepshahi correct me if i am wrong

**Comment by sandeepshahi** [comment]
@migrajkumar, All the enums are available in this [folder](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail).

**Comment by migrajkumar** [comment]
@sandeepshahi - for RET12 (Fashion) there are two options available in the folder. Which one to follow?

https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/size.json

OR

https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/fashion/size.json

**Comment by sandeepshahi** [comment]
@migrajkumar, Please follow this one: https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/size.json

**Comment by yaikhomba** [comment]
@sahil-ondc - could you please review the fixes? Thanks.

**Comment by yaikhomba** [comment]
@sahil-ondc  
RET12, RET13 & RET16, I believe the allowed values for /message/catalog/bpp/providers[0]/items[0]/descriptor/code are as follows - 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others

categories must be present in bpp/providers[0] - noted, we will rectify this miss. Our RET10 is already working, so will not be a problem.

on_search (inc catalog)
why /item/unitized/measure is changing - this was done for testing.

RET16
brand name should not be provided as placeholder (provided: ABC) - this from our test entries, actual brand names will be there in production.

**Comment by sandeepshahi** [comment]
@yaikhomba, 
1. standard item codes should be used. The example payloads in the contract have been updated with the required codes.

For the rest of the points, pls fix.

cc: @BLR-0118

**Comment by BLR-0118** [comment]
RET12
====
1. Use item.quantity.unitized.measure.unit of "unit" (enum [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json)); if you need to provide weight, you can use the attribute as per the taxonomy sheet [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843);
2. enum for "fabric" is in lowercase, as per enum [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/fabric.json);

RET13
====
1. for item llQ95GAsg1cW2RND5thl, unitized measure should be "1 unit"; we say "1 piece razor", not "1 gram razor", right?

RET16
====
1. same issue as RET13:
- item yEoBDPXwINvJyio47h36: should be "1 unit" (means 1 piece toothbrush), not "120 gram" toothbrush, right?
- item kLsNGpdfdm7Tmg4gODSA: should be "1 unit" (means 1 piece lightbulb), not "130 gram" lightbulb, right?

**Comment by BLR-0118** [comment]
@yaikhomba - clearing your logs, but pls make sure the above issues are fixed before deploying in Prod;
