### ISSUE TITLE
Addble - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1654]
## Flow 1 and 2

**/search**

- intent must have required property 'payment'"

**/init**

- order must have required property 'payment'"

**/confirm**

- what bpp_terms are being accepted here (static terms and bpp terms are not enabled yet)
- Average Pickup Time (fulfillments/start/time/duration) mismatches from the one provided in /on_search

**/update**

- order must NOT have additional properties (state)

## Flow 3

- similar issues as above
- Why do /init and /cancel have the same context/timestamp?

**cancel**

- cancellation_reason_id - 006 is not a valid reason code for LBNP

Note: Please run the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self identify the issues before submission

@yaikhomba

**Comment by yaikhomba** [comment]
@abhinavv245 - any feedback for us? Thanks

**Comment by BLR-0118** [comment]
@yaikhomba - logs cleared for v1.2.0
