### ISSUE TITLE
MP2 IGM - compliance check 

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1656]
@Poornima-Aithal

Flow 1
issue
Issue: Domain of organization for /issue API in message/issue/issue_actions/complainant_actions/[0] mismatched with domain in context.
issue_close
Issue: Domain of organization for /issue_close API mismatched with domain in context.
on_issue
Issue: updated_at is not matching with message/issue/issue_actions/respondent_actions/[0]/updated_at.
on_issue_status
Issue 1: 'created_at' should match issue's 'created_at'.
Issue 2: updated_at is not matching with message/issue/issue_actions/respondent_actions/[0]/updated_at.
Flow 2
issue
Issue: Domain of organization for /issue API in message/issue/issue_actions/complainant_actions/[0] mismatched with domain in context.
issue_close
Issue: Domain of organization for /issue_close API mismatched with domain in context.
on_issue
Issue: updated_at is not matching with message/issue/issue_actions/respondent_actions/[0]/updated_a.
on_issue_status
Issue: updated_at is not matching with message/issue/issue_actions/respondent_actions/[0]/updated_at.

**Comment by Poornima-Aithal** [comment]
Mention issues fixed. Please merge this PR @RupalSingla cc: @mherle 
https://github.com/ONDC-Official/v1.2.0-logs/pull/1664

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @Poornima-Aithal

**Comment by mherle** [comment]
@RupalSingla @Rishabh-ondc any update on this ?

**Comment by mherle** [comment]
Thank you @Rishabh-ondc @RupalSingla
