### ISSUE TITLE
Unistack (SA) - IGM - compliance check

### ISSUE THREAD

**Issue by amitsinha07** [ONDC-Official/v1.2.0-logs#1657]
@RaiManish3 

# Unistack

### issue

- **Issue 1**: Time of creation (`created_at`) and time of updation for `/issue` API should be the same.
- **Issue 2**: Context timestamp should be greater than or equal to `updated_at` in issue.
- **Issue 3**: `updated_at` is not matching with `message/issue/issue_actions/complainant_actions/[0]/updated_at`.

### issue_close

- **Issue**: `created_at` and `updated_at` should be the same.

### on_issue_status

- **Issue**: `updated_at` is not matching with `message/issue/issue_actions/respondent_actions/[1]/updated_at`.

### issue

- **Issue 1**: Time of creation (`created_at`) and time of updation for `/issue` API should be the same.
- **Issue 2**: Context timestamp should be greater than or equal to `updated_at` in issue.

### issue_close

- **Issue**: `created_at` and `updated_at` should be the same.

### on_issue_status

- **Issue**: `updated_at` is not matching with `message/issue/issue_actions/respondent_actions/[1]/updated_at`.

**Comment by RaiManish3** [comment]
Hi @amitsinha07 
issue and issue_close are errors at the ref buyer app.

the updated_at for on_issue_status matches with the latest respondent action. can you check again?

**Comment by RaiManish3** [comment]
@amitsinha07
please check this.

**Comment by RupalSingla** [comment]
FLOW 1
    issue
        1. created_at should be same as updated_at
        2. timestamp should be equal or greater than updated at

    issue_close
        1. timestamp should be equal or greater than updated at

FLOW 2
    issue
        1. created_at should be same as updated_at
        2. timestamp should be equal or greater than updated at

    issue_close
        1. timestamp should be equal or greater than updated at

@RaiManish3

**Comment by RaiManish3** [comment]
@RupalSingla
these are issues at the ref-buyer app end.

**Comment by RaiManish3** [comment]
@RupalSingla pls provide an update on this.

**Comment by RaiManish3** [comment]
@RupalSingla 
Is there anything needed here from our side?

**Comment by RupalSingla** [comment]
Logs cleared  for version 1.0.0 @RaiManish3
