### ISSUE TITLE
shopclues retail logs 

### ISSUE THREAD

**Issue by ajayGargSc** [ONDC-Official/v1.2.0-logs#1707]
we did not receive the payment settlement update call on liquidation and partial cancel case. related to that we do not able to send settlement details and getting our logs rejected please check our input via below link and verify what is the issue.
Also confirm the given tag object in our case for seller in on_status picked is fine or not.
{"tags":[{"code":"routing","list":[{"code":"type","value":"P2H2P"}]},{"code":"tracking","list":[{"code":"gps_enabled","value":"no"},{"code":"url_enabled","value":"no"}]}]}
or only tracking object is enough.

https://github.com/ONDC-Official/v1.2.0-logs/blob/master/shopclues/seller-logs/FLOW-6/on_update_liquidated.json
https://github.com/ONDC-Official/v1.2.0-logs/blob/master/shopclues/seller-logs/FLOW-6/on_update_part_cancel.json
pull req :
https://github.com/ONDC-Official/v1.2.0-logs/pull/1667

**Our issue sent on mail were below:**
Shopclues : RET 12
Flow 1
On Search
How is the timestamp for both search and on-search same ?

bpp/provider: "In categories, descriptor name shouldn't be a placeholder i.e instead of naming varient group 0 or 1 ; name it according to the type variant."
On Search Incremental Refresh
How is the timestamp for both search_inc and on-search_inc same ?

on_search_inc_refresh_msgId: "Message id should not be same with previous calls as it's incremental push based call"
Flow 2 and Flow 3
On Status All
why is there "parent_item_id": “1” in items ? Its only required for RET11 i.e when there are dynamic item id generated.

On Status Picked
"Tags are mandatory in Delivery Fulfillment for on_status_picked
On Status Out For Delivery
Same as above
On Status Delivered
Same as above
Flow 5
On Status Picked
"Tags are mandatory in Delivery Fulfillment for on_status_picked"
On Status Out For Delivery
Same as above
On Status RTO Delivered
RTO fulfillment is missing

Flow 6
Settlement details Object of update are not carried forward in entire flow/missing i.e settlement details of update_settlement_part_cancel is not present in on_status, etc.
Update Settlement Part Cancel
Missing payload and is required
On Status Pending
"The start/timestamp can't be there in on_status_pending as it will come in on_status_picked"
"The end/timestamp can't be there in on_status_pending as it will come in on_status_delivered"
On Status Picked
"Tags are mandatory in Delivery Fulfillment for on_status_picked"
On Status Out For Delivery
Same as above
On Status Delivered
Same as above
On Update Delivered
"Missing payment/@ondc/org/settlement_details as compare to update_settlement_reverse_qc i.e. {"settlement_counterparty":"buyer","settlement_phase":"refund","settlement_type":"paylater","settlement_amount":"1660","settlement_timestamp":"2024-05-21T10:53:55.596Z"}"
On Update Interim Liquidated
Same as above
On Update Liquidated
Same as above
Update Settlement Liquidated
Missing payload and is required
Please provide the missing action calls for Flow 6

**Comment by sandeepshahi** [comment]
Invalid Issue board; Please raise your query on the already opened issue board for audit trail

@ajayGargSc
