### ISSUE TITLE
Wits Adapter (BA: RET 10, 11, 12, 13, 14, 15, 16, 18) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#1716]
## Flow 1

**/search (inc)**

- is push based incremental search supported?

## Flow 2

**/on_init**

- provider_tax_number is missing in /tags; must be NACK'd

**/confirm**

- url and tl_method are optional in /payment; placeholder values should not be provided
- "transaction_id" in payment/params can't be same as context/txn id
- invalid attribute: "razorpayPaymentId"; use the value in payment/params/transaction_id

## Flow 3

- order flow with multiple items must be provided

**/on_select (OOS)**

- invalid quote calculation; BNP must respond with a NACK

**/select**

- order flow must be continued with the same transaction id; /select must be called for every change in cart, with the same transaction_id
- why was the OOS item allowed to be added again in the cart?

## Flow 5

- rto terminal state must be provided for verification

**/on_cancel**

- invalid cancellation reason code used by SNP; BNP must validate cancellation reason codes received from SNP and respond with a NACK for invalid/incorrect code;

## Flow 6

**part cancel**

- invalid quote_trail; seller app part cancels all the quantity but adjusted the quote for only 1 count;
- for above point, BNP must respond with a NACK and not intiate refund for part quantity

#### Please answer the following queries too:

- are you using the timestamp at provider / item level for correct versioning while processing the catalogs (full/incremental) concurrently
- while processing unsolicited callbacks, are you ensuring that each such callback response has a unique message_id for a specific transaction_id?
- is retry mechanism enabled for confirm/on_confirm flow as mentioned in the doc?

#### Also, please share a demo of the app with the complete order flow (and variant selection).

@witslab-nikita

**Comment by keertikj** [comment]
1. is push based incremental search supported? - **YES**
2. are you using the timestamp at provider / item level for correct versioning while processing the catalogs (full/incremental) concurrently -  **YES**
3. while processing unsolicited callbacks, are you ensuring that each such callback response has a unique message_id for a specific transaction_id? - **YES**
4. is retry mechanism enabled for confirm/on_confirm flow as mentioned in the doc? - **YES**

**Comment by witslab-nikita** [comment]
5. **demo url:** https://drive.google.com/file/d/1TpR7-anchD2OQn-iQF8R9dAY0waUZX-P/view

@sandeepshahi

**Comment by sandeepshahi** [comment]
@witslab-nikita, please share the demo video for grocery order.

Also, while displaying the color variants, the color name should be displayed instead of the hex code.

**Comment by witslab-nikita** [comment]
demo url : https://drive.google.com/file/d/1UpnBPTT-6em30CDX-3Ul108bB4QLdPBX/view?usp=drive_link
@sandeepshahi

**Comment by sandeepshahi** [comment]
## Flow 1

**/search (inc)**

- payload is missing

## Flow 2

**/on_select**

- timestamp can't be earlier than /select timestamp; similar issues for subsequent APIs

**/confirm**

- missing info in tags/bpp_terms
- "@ondc/org/settlement_basis" is mentioned as "delivery"; is this intended?

## Flow 3

**/select**

- order flow must be continued with the same transaction id; /select must be called for every change in cart, with the same transaction_id

## Flow 5,6
- updated flows must be provided


@witslab-nikita

**Comment by shivang1131** [comment]
## RET 10
- The enums that they are providing are incorrect. How are you injesting this data?

## RET 11
- The parent_item_id should be alphanumeric.

**Flow 4**
- Invalid cancellation reason id. Cannot be cancelled before the breach of TAT.

@witslab-nikita

**Comment by witslab-nikita** [comment]
@shivang1131, Thanks for the feedback
> The enums that they are providing are incorrect. How are you injesting this data?
- Can you please clarify which enums are you referring to ?

**Comment by witslab-nikita** [comment]
@sandeepshahi, @shivang1131 

We have fixed mentioned issues at our end.

**Comment by sandeepshahi** [comment]
Logs cleared for BAP (RET 10, 11, 12, 13, 14, 15, 16, 18) v1.2

@witslab-nikita
