### ISSUE TITLE
Digiledge - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1717]
Multiple issues identified by the [log verification utility](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility). Kindly rectify and resubmit the logs. In case of errors from LSP side, please handle all the errors and send NACK whenever required. 

@shabirahamed

**Comment by abhinavv245** [comment]
## All Flows 

**/on_confirm**

- items/0/time/timestamp mismatch from /confirm (BAP should validate)

**/update**

- Pickup code is not required for P2H2P shipments as shipping label is provided by LSP

## Flow 3 - Cancel

- Incorrect Flow as per context/timestamps - (search,on_search,init,on_init,on_confirm,confirm,on_update,update,on_cancel,cancel)

**/on_confirm**

- order/created_at cannot be future dated w.r.t order/updated_at


@shabirahamed

**Comment by abhinavv245** [comment]
- tracking to be implemented

**/on_confirm**

- items/time/timestamp mismatch from /confirm (BAP should validate)

## Flow 3 - Cancel

**/on_cancel**

- cancellation/cancelled_by should have BAP subscriber id

## RTO fLOW

**/on_status**

- RTO Delivery timestamp (fulfillments/end/time/timestamp) is missing for fulfillment state - RTO-Delivered

@shabirahamed

**Comment by abhinavv245** [comment]
## P2P

## Flow 2

- /on_init payload missing 

## Flow 3 - Cancel

- Cancellation due to TAT breach to be implemented by LBNP

@shabirahamed

**Comment by abhinavv245** [comment]
## All flows

**/search**

- fulfillments/tracking is not required in search 
- order preparation time is missing (provider/time/duration)
- will you be using 'Standard Delivery' for F&B items as well?
- payload_details/weight/unit - is it a valid unit for F&B category?

**/init**

- person object is not required in fulfillments/start (how is a person name : "The Food and Bevarage Store")

@shabirahamed

**Comment by shabirahamed** [comment]
> ## All flows
> **/search**
> * payload_details/weight/unit - is it a valid unit for F&B category?
 - As per the API contract, 'unit' weight is valid for F&B category


@abhinavv245 could you please find the inline comment

**Comment by BLR-0118** [comment]
P2P
==
1. weight unit should be in "kilogram" or "gram" for logistics;

**Comment by BLR-0118** [comment]
@shabirahamed - pls fix & resubmit;

**Comment by BLR-0118** [comment]
1. for hyperlocal order, prep time is 3 days (aligns with time_to_ship in fashion catalog); however, you're selecting LSP option which has pickup time of 20 mins;

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 but pls make sure the above issue is handled correctly in Prod;
