### ISSUE TITLE
Sabhyasha (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1782]
Correction flow

receiver_recon 

orderbook.orders.invoice_no for [order.id](http://order.id/)  2024-03-27-180917 is different in on_receiver_recon
collected_by should be BPP as seller app is collector

on_receiver_recon

provide you are sending lesser amount in orders.message

success flow

receiver_recon

collected_by should be BPP as seller app is collector

@SatyaranjanSwain

**Comment by SatyaranjanSwain** [comment]
**Correction flow**
Why in on_receiver_recon I am getting a different invoice_no? It should be what I have provided in the receiver_recon call.
**on_receiver_recon**
provide you are sending lesser amount in orders.message  ----- I don't have any control over the mock server as it's a callback from the server. Please ask the concerned team to fix this.

@RupalSingla

**Comment by RupalSingla** [comment]
Why in on_receiver_recon I am getting a different invoice_no? It should be what I have provided in the receiver_recon call.
Yes it  needs to be same ..
@SatyaranjanSwain

**Comment by RupalSingla** [comment]
logs cleared for version 1.0.0 @SatyaranjanSwain
