### ISSUE TITLE
Aurikatech (SA)	IGM - complaince check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1791]
FLOW 1
      issue
           1. Time of creation (created_at) and time of updation for /issue api should be the same
           2. context timestamp should be greater than or equal to updated_at in issue

FLOW 2
      issue
           1. Time of creation (created_at) and time of updation for /issue api should be the same
           2. context timestamp should be greater than or equal to updated_at in issue
@vanshraghav

**Comment by vanshraghav** [comment]
Hi @RupalSingla ,

As a seller app, we don't have control over the data sent by the reference buyer app in the /issue call. The errors you mentioned pertain specifically to the /issue call, which falls outside our scope to address. Consequently, these issues cannot be resolved by us as the seller app.

cc - @pareenjain

**Comment by pareenjain** [comment]
@RupalSingla can you please update on the above?
cc: @sandeepshahi @BLR-0118

**Comment by RupalSingla** [comment]
@pareenjain  / @vanshraghav  kindly avoid the above errors as
