### ISSUE TITLE
Oogashop (SA: RET 10,13,16,18) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#1800]
#### Flow 1: on_search_full_catalog_refresh
- `prvdr0item2common_or_generic_name_of_commodity2statutoryReq`: Empty string in `bpp/providers/items` for `/on_search`.
- `item/desc/name`: Incorrect category_id assignment (e.g., baby moist cream in Snacks, Dry Fruits, Nuts).
- `location/address`: Placeholder data used instead of realistic data.
- `short_desc`: `short_Desc` and `long_desc` can't be the same; avoid using "NA".
- `@ondc/org/statutory_reqs_packaged_commodities`: Placeholder data used.
- `tags/timing`: Use 'all' enum if timings for Deliver/Order/Self-Pickup are the same.
- `More checks`: Many placeholders used; use realistic values.
- `images`: Invalid URLs for images provided.
- how can item "Bab Moist Loton " fall in category "Snacks, Dry Fruits, Nuts" ?
- How can only one item have variant "dfghjkl"; There should be atleast 2 items with difference in defined variant for it to be called variant.
- Please dont provide a mock payload and provide proper payload with correct items ,descriptions, images.

##### `on_confirm`: 
  - `fulfillments/address`: Placeholder data in address :
  "address": {
                "street": "nn",
                "locality": "nn",
                "city": "nn",
                "state": "nn",
                "area_code": "560037"
              }.
  - `deliveryFulfillment/start/location/images`: Images can't be inside the location.
##### `on_status_pending`: 
- `on_status_pending` not required when `onConfirm` Order State is 'Accepted'.
##### `on_status_picked`: 
  - `missingRouting/Tag`: RoutingTag object mandatory in Tags of Delivery Object.
  - `invoiceErr`: Invoice and quote_price mismatch compared to `on_confirm`.
##### `on_status_out_for_delivery`: 
- RoutingTag object mandatory in Tags of Delivery Object.
##### `on_status_delivered`: 
- RoutingTag object mandatory in Tags of Delivery Object.

##### on_cancel:
- Return fulfillment : end.time.range is missing and also provide on_status_rto-delivered or disposed after on-cancel_rto with updated end.timestamp for return fulfillment.
- retry_count missing in delivery fulfillment.tags.cancel_request .

##### `on_status_packed`: 
  - `message/order.fulfillments/0/start/location`: Mismatch with `on_confirm` due to images.
  - `message/order.fulfillments/0/start/contact`: Contact number mismatch with `on_confirm`.
  - `message/order.fulfillments/0/end/tags`: Extra attribute in `tags[]` compared to `on_confirm`.
##### `on_status_picked`: 
- Invoice should be provided and updated after part cancel
- Similar issues as `on_status_packed`.
##### `on_update_approval`: 
  - `ReturnFulfillment.end`: Missing in `on_update_approval`.
  - `ReturnFulfillment.start`: Missing in `on_update_approval`.
##### `on_update_picked`: 
 - `ReturnFulfillment.end`: Missing in `on_update_picked`.
-`ReturnFulfillment.start.location` : Missing in `on_update_picked`.
##### `on_update_delivered`: 
- `ReturnFulfillment.end.location`: Missing in `on_update_delivered`.
-`ReturnFulfillment.start.location` : Missing in `on_update_delivered`.

---

#### Flow 1: on_search_full_catalog_refresh
- `location/address`: Placeholder data used instead of realistic data.
- `short_desc`: `short_Desc` and `long_desc` can't be the same; avoid using "NA".
- `fulfillments`: Self-pickup option not provided; should not be present if unsupported.
- `images`: Invalid URLs for images provided.

---

#### Flow 1: on_search_full_catalog_refresh
- `location/address`: Placeholder data used instead of realistic data.
- `bpp/providers[0]/items[0]/descriptor/code`: Code should have `1:EAN` as a value.
- `short_desc`: `short_Desc` and `long_desc` can't be the same; avoid using "NA".
- `fulfillments`: Self-pickup option not provided; should not be present if unsupported.
- `images`: Invalid URLs for images provided (e.g., `nan`).

---

#### Flow 1: on_search_full_catalog_refresh
- `location/address`: Placeholder data used instead of realistic data.
- `categories`: Inappropriate category name (e.g., `amul pro 2`).
- `@ondc/org/statutory_reqs_packaged_commodities`: Placeholder data used.
- `short_desc`: `short_Desc` and `long_desc` can't be the same; avoid using "NA".
- `parle, amul`: Attributes in descriptions unrelated to products.
- `images`: Invalid URLs for images provided.

# Notes:
### - **This looks like a mock payload please submit logs with realistic values in each domain for next iteration for proper verification**

@Gogs @sandeepshahi @oogashop

**Comment by oogashop** [comment]
Hi @Jagannath-wits ,

We have made corrections as per your suggestions and have raised another PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1816 with suggested changes. We have included a file `report_resp.json` in each flow which consists of the response from log utility API. There are some problems there but they are either contrary to your suggestion or does not make sense.

Please review again.
Thanks and regardsh

**Comment by Jagannath-wits** [comment]
## RET10

### Flow 1: On_search_full_catalogue
- **/message/catalog/bpp/providers/items/descriptor/code:** Should be a number and with a length of either 8 to 13 characters.
- `{"code": "attribute", "list": []}` is not required if there are no attributes to be displayed.
- Please don't provide `"@ondc/org/return_window” as “P0D”`; as this also works as the IGM windows, so please provide some duration.
- No need to provide self-pickup in bpp/fulfillments if no provider supports it.
- items.matched is an invalid key and not present in contract.

### Flow 2: on_status_picked
- Invoice URL not accessible: [https://api.aistore.shop/invoices/estimate-5629531313532370102.pdf](https://api.aistore.shop/invoices/estimate-5629531313532370102.pdf).

### Flow 4: on_cancel
- You can’t charge for packing and delivery as the order was canceled preshipment.
- **Issue:** Precancel state not captured properly ("\"Pending\""). Please refer to contract page no. 468 for correct enums.

### Flow 5: on_cancel_rto
- Precancel state not captured properly ("\"Out-for-delivery\""). Please refer to contract page no. 468 for correct enums.
- `return_fulfillment.time` is not required in on_cancel.

### Flow 6:on_status_picked
- Invoice URL not accessible and should be updated: [https://api.aistore.shop/invoices/estimate-8205631369054609776.pdf](https://api.aistore.shop/invoices/estimate-8205631369054609776.pdf).

## RET18
### Flow 1: On_search_full_catalogue 
- Same as RET10
- @ondc/org/statutory_reqs_packaged_commodities or @ondc/org/statutory_reqs_prepackaged_food missing in items; Please refer to examples in contract

@oogashop

**Comment by oogashop** [comment]
Hi @Jagannath-wits 

We have submitted again at https://github.com/ONDC-Official/v1.2.0-logs/pull/1864 with the suggested changes. Please look into the same and let us know.

Thanks and regards

**Comment by sineshashi** [comment]
Hi @Jagannath-wits  please review our recent logs which have already been merged.

**Comment by Jagannath-wits** [comment]
> Hi @Jagannath-wits please review our recent logs which have already been merged.

Sure will update today

**Comment by Jagannath-wits** [comment]
## Oogashop Ret10

### on_search_full_catalog_refresh
- `bpp/providers[0]/items[0]/descriptor/code`: "code provided in `/message/catalog/bpp/providers[0]/items[0]/descriptor/code (8978798767)` should be a number with a length of either 8 or 13."
- `bpp/providers[0]/items[1]/descriptor/code`: "code provided in `/message/catalog/bpp/providers[0]/items[1]/descriptor/code (962600364053)` should be a number with a length of either 8 or 13."
- `bpp/providers[0]/items[3]/descriptor/code`: "code provided in `/message/catalog/bpp/providers[0]/items[3]/descriptor/code (901764012914)` should be a number with a length of either 8 or 13."
- `@ondc/org/statutory_reqs_packaged_commodities`: Cannot be dummy values; correct values must be provided. If not available, use 'NA' or provide `back_image` with realistic information. `back_image` tag must be present for this purpose.
- Images should be accurate; dummy images are not permitted.

### inc_on_search
- How is the `descriptor.code` type different in `on_search_inc`?
- Apart from `descriptor.code`, I see no other changes in item.
- What is this 'matched key' provided in item? It's not part of the contract.

## Flow 2
### init
- `order.items.location_id` is not required as per contract.

### on_init
- `Tags.bpp_terms`: Only `tax_number` and `provider_tax_number` are required; others are not enabled yet. `np_type` is not required as it's not in the contract.

### confirm
- Same as above.

### on_confirm
- Same as above.

### on_status_picked
- Why is the quote price $308.25 and the invoice is $308.2? It should be accurate.

## Flow 2
- Same as above.

### on_status_picked
- Quote and invoice mismatch (roundoff is not allowed) for all flows.

## Flow 5
### on_cancel_rto
- Quote trail not captured properly; why are packing and delivery charges in quote trail when you’re charging in quote?
- Value `-0.00` is invalid for quote trail.
- Industry standard retry count is a minimum of 3.

### on_status_rto_delivered
- Same as above.

## Flow 6
- Invoice won’t be updated after `on_status_picked` in the subsequent calls as `update_settlement` was received after `on_status_picked`

@oogashop

**Comment by oogashop** [comment]
Hi @Jagannath-wits 

We have submitted our logs again at https://github.com/ONDC-Official/v1.2.0-logs/pull/1935 with the corrections suggested.  Please review logs and let us know.

Note: The errors mentioned in /confirm, /init are from buyer side, in our case, buyer reference app of preprod environment (1.2.0). All the other changes suggested for seller side APIs have been made.

**Comment by oogashop** [comment]
Hi @Jagannath-wits 

We had submitted our logs as per the suggestions. Please review them.

Thanks and regards
Shashi Kant

**Comment by BLR-0118** [comment]
RET10
====
Flow 1:
1. /on_search (full catalog refresh):
- for item OOGASHOP-ONDC-47098, use proper unitized qty weight/val e.g. 100 gram;
- for variant id (24mantra  Apple Juice 23), use proper unique identifier, preferably without spaces;
- catalog ttl of PT0S means validity is 0 secs: why should buyer apps process this?

2. /on_search (inc refresh):
- pls share payload for item going out of stock;

Flow 2
====
1. /on_confirm:
- TAT is 24 hrs but diff between order confirmation time & end delivery slot is almost 30 hrs; pls check your calculation & fix;
- also, routing.type should be sent when order is accepted, so buyer apps know what fulfillment states to accept;

**Comment by BLR-0118** [comment]
@oogashop - pls resubmit for flows 1 & 2;

**Comment by oogashop** [comment]
Hi @BLR-0118 @Jagannath-wits ,

we have made the appropriate changes and raised PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1983 .

Please review

**Comment by BLR-0118** [comment]
1. All - /on_search - variant id has limit of 12 chars (alphanumeric), so you can't use the UUID in your logs;
2. RET13 - categorization issue:
- item OOGASHOP-ONDC-47493 should be in RET18;
3. RET16 - pls provide proper values for attributes e.g. material="Unknown";
4. since you're in multiple categories, pls ensure unique item ids (for same provider id) across the different RETs, so multi-cart order will work - this seems to have been handled;
5. pls ensure quality of catalog data e.g. lots of typos, descriptions can be improved, etc.;

**Comment by BLR-0118** [comment]
@oogashop - clearing logs for RET10/13/16/18, pls make sure the above issues are taken care of;
