### ISSUE TITLE
Snapbizz (SA: RET10) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#1824]
# Flow 1 

**On_search_full_catalog**

- **categoriesErr**: Variants are not captured correctly in items, `parent_item_id` should be mapped with variants.
- Image URLs should be publicly accessible.
- Short description and long description should not be the same.
- Categories/variants are not captured correctly. Please refer to [contract](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv).
- Why is "@ondc/org/statutory_reqs_prepackaged_food" provided in every item where it is irrelevant? Please refer to this[ sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0) for proper protocol mapping
  
```json
"@ondc/org/statutory_reqs_prepackaged_food": {
  "nutritional_info": "Energy(KCal)-(per 100kg) 420,(per serving 50g)250;Protein(g)-(per 100kg) 12,(per serving 50g) 6",
  "additives_info": "Preservatives,Artificial Colours",
  "brand_owner_FSSAI_license_no": "12345678901234",
  "other_FSSAI_license_no": "12345678901234",
  "importer_FSSAI_license_no": "12345678901234"
}
```

- `categories.tags` will not have serviceability. Why is it there? Please stick to the contract and in case of doubts please reach out to tech support or ask here.
- `"category_id": “Stationery”` is now moved to `ret16`. Please refer to [sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0).
- `"@ondc/org/fssai_license_no": “”` is not required for `ret10`. Please refer to contract as it also has examples and scenarios.
- Please don't provide placeholder values. For example, in `descriptor.code`, `description`, `urls`, etc.
- `bpp/provider.tags` not captured correctly and completely incorrect. For example, why is the object with `"code": “Grocery”`? Timing object is not captured correctly. Please refer to contract and strictly stick to it.
- Please don't provide mock payload.

### on_confirm
```
tags_bap_terms: "Tags should have same and valid gst_number as passed in /confirm”
```
- **Question:** Why is the end and start address the same?

### on_status_pending
```json
errmsg: "When the onConfirm Order State is 'Accepted', the on_status_pending is not required!"
```

### on_status_picked
- Invoice is missing, it should be provided and should be accurate.
- **Start Address:** Start address is missing. Please refer to contract.
- **Timestamps:** Start and end timestamps can't be the same.
- **End Timestamp:** How can you provide end timestamp when the order hasn't been delivered yet?
- **Requirement:** This is only required when fulfillment is self-pickup (optional, may be provided for kerb-side pickup (in self-pickup)).
```json
code: "state"
list:
  - code: "ready_to_ship"
    value: "yes"
```

## Flow 3
- How can utility provide no error when your payload is missing select and on_select
On_select out of stock is missing error
On_select out of stock is showing no difference in the count of items i.e its not reduced even after being out of stock.Please refer to the scenarios provided in the contract

## Flow 5
- Missing on_status rto-delivered or disposed with updated end.timestamp for return fulfillment.

## Flow 6
settlement details have not been carried forward
Invoice should be updated after part-cancel
Quote trail has not been carried forward or captured properly

**@krishna-balasubramanyam-2020 Please refer to contract and not just utility.**
- **The entire logs seem to be manipulated to fix utility errors or contract has not been referenced properly** 
- If you have any doubts you can ask in the community call or this issueboard.
- **Also provide the utility payload you are using from next iteration onwards as the report you are submitting is manipulated.**

**Comment by Jagannath-wits** [comment]
## Snapbizz

### Flow 1

#### search_full_catalogue
- static_terms are not enabled yet so please remove that

#### on_search_full_catalogue
- categories not captured properly. Why is the category for pizza defined in RET10? Please refer to [contract](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv).
- Variants should be supported and provided in the payload. Please refer to [contract](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv).
- Timing object for self-delivery object is missing. If the timing for all is the same, you can use `timing.type` as `all`.
- `bpp/providers.tags.veg_nonveg` is invalid and isn’t provided at the provider level. Please refer to the contract.
- Mapping of attribute `@ondc/org/statutory_reqs_prepackaged_food` and `@ondc/org/statutory_reqs_packaged_commodities` not done properly. Please refer to [sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0).
- `items.tags.veg_nonveg` is optional, only as applicable. Please refer to [contract](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv).
- `@ondc/org/return_window` should be realistic and feasible.

#### search_inc
- static_terms are not enabled yet so please remove that.

#### on_search_inc
- There seems to be no delta change in `on_search_full_catalogue` and `inc_on_search`, and also location is not captured properly.

### Flow 2

#### on_init
- `payment.tags.bpp_collect` is only required when BPP is collecting payment.
- Only `@ondc/org/buyer_app_finder_fee_type`, `@ondc/org/buyer_app_finder_fee_amount`, and `@ondc/org/settlement_details` are required in payment object when the buyer is collecting money.
- If BPP is collecting payment, then the payment details will be provided in `on_init` and carried forward. If only BAP is collecting, then "collected by" should be BAP in `Confirm` as provided, and the rest will be the same as currently provided.
- `Tags.bpp_terms`: Only `tax_number`, `np_type`, and `provider_tax_number` are required; others are not enabled yet, so please remove the others.

#### on_confirm
- Instruction object is not provided in `on-confirm` unless the order is accepted. Also, the instructions are invalid as you have only selected delivery fulfillment.

### On Status Picked
- Invoice URL should be publicly accessible and accurate.

#### on_status
- `@ondc/org/provider_name` changed compared to `on_confirm`; there won’t be any change in fulfillment details.
- The `end.address` has updated compared to `on_confirm`, which shouldn't happen.

### Flow 3

#### on_select_oos
- `on_select_oos` not implemented correctly. Multiple items should be collected as defined in the rollout [plan](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit?gid=1367601795#gid=1367601795).
- `messsage.order.error` is missing, please refer to [contract](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv).
- Item with ID `32041007-19f4-42dc-8a25-bf153c9e12ae` is not reduced or out-of-stock.

#### select
- How is item `32041007-19f4-42dc-8a25-bf153c9e12ae` available again when it's supposed to be out of stock in `on_select_oos`?

### Flow 4

#### on_confirm
- How is `order.state` created in Flow 2 and accepted in Flow 4? If the order is accepted, routing should be provided.

#### cancel
- Invalid `reason_code` used as in Flow 4, the order is cancelled pre-shipment. Please refer to reason codes [sheet](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit?gid=1095388031#gid=1095388031).

#### on_cancel
- Quote sum incorrect as count of item with ID `32041007-19f4-42dc-8a25-bf153c9e12ae` is 0.
- `quote.price` should be 0 as the order is cancelled pre-shipment.
- `igm_request` is only required when an `igm_request` has been actually raised.
- `precancel_state` has not been captured correctly as Flow 4 order is cancelled pre-shipment. How can precancel state be `Order-picked-up`?

## Flow 5

#### on_cancel
- Same as above.
- `precancel_state` has not been captured correctly as Flow 5 order is cancelled after its shipment. How can precancel state be `Order-picked-up`? It should be `out-for-delivery`.
- Invalid reason code used i.e., 009 as the order is cancelled before it's delivered and initiated by LSP/SNP. Please refer to reason code [sheet](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit?gid=1095388031#gid=1095388031).

#### on_status_rto_delivered
- `on_status_rto_delivered` is required after `on_cancel_RTO` where the `end.timestamp` of RTO fulfillment will be updated.

## Flow 6
### On Update Part Cancel
- **Question:** Why is `on_update_part_cancel` sent before order is accepted?
- update_settlement seems mocked and is incorrect please share original logs and not manipulated logs.
- settlement details have not been carried forward
- quote trail has not been captured properly for any scenario please refer to contract and make sure the settlement details, fulfillment, quote has been carried forward.
- invoice should be accessible and updated after part_cancel

@krishna-balasubramanyam-2020
- Please fix all issues before next submission
- **Please submit the utility payload in the repo for each flow.**

**Comment by Jagannath-wits** [comment]
## Flow 1
#### on_search
Please provide atleast 5 items in catalogue.
the provider only supports delivery fulfillment so why is there self-pickup in bpp/fulfillments ?
How is the timestamp of catalogue being updated? It should be updated whenever there is a change at that level i.e eg: if there is a change at item level then it’s timestamp should update and not at each on_search
invalid ean code used 
image url should be accessible. Eg: https://snaporder-v2.sgp1.digitaloceanspaces.com/uploads/banners/default-banner.jpg

## Flow 2
#### on_confirm
How are you getting time.range for start and end before order is accepted?
Time.range for start and end should be calculated accurately, how come the the start of range for both pickup and delivery be same as context.timestamp
tracking status cant change in on_confirm as tracking was not supported in on_select

#### on_status
@ondc/org/TAT changed from 3H to 60M; it should remain same
how did delivery charges get 0 in on_status?


#### on_status_packed
fulfillment.start.time.timestamp is updated at on_status_picked when order is picked and not before that.

## Flow 3
#### select_oos
incorrect payload, please refer to contract and run utility before submission

#### on_select_oos
The count remained the same and didn’t change comapared with select_oos

#### select
Same item which was supposed to be out of stock is selected

#### on_select
The count remained same here too.

## Flow 4
#### on_cancel
fulfillment 43271e58-a44c-4272-a6ab-39b15c6d2b7f doesn’t exist in on_cancel i.e not carried forward.
incorrect payload, please refer to contract and run utility before submission.

## Flow 5
same as above

## Flow 6
Please run utility and fix errors before resubmission 

# Please dont submit false utility report. Eg:Flow 3
# Please submit utility payload used in next iteration.
# @krishna-balasubramanyam-2020 Please don't send mock payloads and false reports positively

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
Variants are not captured properly
@ondc/org/statutory_reqs_prepackaged_food is not required for the category_id : ‘Tea and Coffee’, ‘Masala & Seasoning’, ‘Oil & Ghee’ and ‘Rice and Rice Products’

## Flow 2

### On Select
If the time is less than or equal to 2H, then it should be treated as ‘Immediate Delivery’


## Flow 5

### On Cancel
precancel_state.fulfillment_state of on_cancel is not equal with the on_confirm fulfillment state

## Flow 6

### On Status Picked
Tags are not allowed in the items

@krishna-balasubramanyam-2020

**Comment by krishna-balasubramanyam-2020** [comment]
@sahil-ondc Further update done and committed here - https://github.com/ONDC-Official/v1.2.0-logs/pull/2230

**Comment by Jagannath-wits** [comment]
@krishna-balasubramanyam-2020 Please resubmit the logs with complete payload for flow 6 and 5.
Currently on_status_rto_delivered in flow 5 and the entire flow of reverseQC and/or Liquidated is missing as mentioned in previous iterations.

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits precancel_state.fulfillment_state of on_cancel is not equal with the on_confirm fulfillment state So it is supposed to be pending.
> 
> But in log validator, it's asking for out-for-delivery state for precancel_state.fulfillment_state. Plz clarify!
- It will be out-for-delivery only


> We are not handling reverseQC flow as we only ask for Liquidated/settlement. ie All our merchant requirements is that we don't accept returns. We had already been fulfilling several orders in v1.1. with just Liquidated.
- Please get an exceptional approval for the same.

> on_status_rto_delivered flow, I had asked our team to submit.
- If you support liquidation then why is the liquidation flow also missing in flow 6 ?


> Is it possible to reach out to anyone in your team over Whatsapp to clarify or discuss some of the final points and clear this?
- You can reach out to tech support team or drop a mail for the same

@krishna-balasubramanyam-2020

**Comment by krishna-balasubramanyam-2020** [comment]
@Jagannath-wits Thanks for the comments.

We already got approval for the same.
Our team will submit the liquidation flow also.

Pinky Rawat called to clarify and help. Thanks.

**Comment by Jagannath-wits** [comment]
# Snapbizz

## Flow 1

### on_search
- In `statutory_reqs_packaged_commodities`, the value should either be the information about the product (if available), "NA" (if info not available), or "refer to back image" with the image URL provided in `item.tags.back_image`.
- Escape characters should not be provided, e.g., '\r\n'.

### on_search_inc
- Only delta changes should be populated in `on_search_inc`; there are no changes in `bpp_providers.descriptor`.
- `bpp_providers.tags` updates cannot be provided in `on_search_inc`.

## Flow 2

### on_confirm
- Are `pickup` and `delivery` time.range calculated dynamically?

### on_status
- Invoice is inaccessible.

## Flow 5

### On_status_rto_delivered
- Invalid key `email` in `delivery.end.person`.
- Audit trail not carried forward; please check the quote.

**Please run utility before submission.**

## Flow 6

### on_update_interim_liquidated
- `Order.items` object not captured correctly.
- `return_request` not carried forward from `update liquidated`. Trail must be maintained.
- Invoice is inaccessible.

### on_update_liquidated
- `return_request` not carried forward from `update liquidated`. Trail must be maintained.
- `Order.items` object not captured properly; please check item `ef751f3f-462d-4119-99da-e38eedb96b33`.
- Fulfillment ID (`e26317a0-7125-4d3c-97ab-7400597649b8`) not mapped with item in `order.items`.
- Why is fulfillment ID in `order.item` the same for part-canceled and liquidated items?
- How is the settlement detail of liquidated provided before `update_settlement` is received? Please explain how this was handled.

@krishna-balasubramanyam-2020

**Comment by krishna-balasubramanyam-2020** [comment]
@Jagannath-wits Some of the questions from our previous comments where not addressed.

Many of these comments are coming up newly and more questions are being asked.
So can we get on a call?

Also some comments are invalid like:
Invoice is inaccessible.
We can access from incognito also => https://snapmerchant-preprod.snapbizz.com/invoice/2024-08-13-237892
It takes about 1 or 2 seconds to load.

Is there a reference seller app logs that we can refer?
I had asked for a reference multiple times now. But no reply.

Also utility logs - New errors are coming up that were passed earlier. (I asked this question in previous comment)
Not sure if there are issues with utility logs! Or some parts are broken!

Shall we get on a call to discuss the questions from both sides?
Because the review and submit and question/answers cycle is taking too long.
Our team is available to get to Prod as soon as possible.

Our intend is to close this soon given it's already been 4 or 5 iterations.

**Comment by Jagannath-wits** [comment]
## Flow 1
#### on_search
- bpp/providers.fulfillments.id and bpp/fulfillments.id should match
- in statutory_reqs_packaged_commodities, the value should either be the information about the product (if available), "NA" (if info not available), or "refer to back image" with the image URL provided in item.tags.back_image.(repeated issue)


## Flow 5
- Why is there a cancel call provided here ? is this mocked ? Flow 5 is unsolicited cancellation from seller side or logistics. Please refer to contract and cancellation reason sheet (https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit?gid=1095388031#gid=1095388031).

#### on_cancel
- cancel_request.initiated_by should be seller(in case of off network logistics) or seller.
- delivery_fulfillment.start.timestamp mismatch with on_status_picked

#### on_status_rto_delivered
- rto_fulfillment.start.timestamp not carried forward from on_cancel

@krishna-balasubramanyam-2020

**Comment by Jagannath-wits** [comment]
## Flow 1
#### on_search
- /message/catalog/bpp~1providers/0/categories/0/id must match pattern \"^[a-zA-Z0-9-]{12}$\ i.e alphanumeric upto 12 characters"
- discrepancy in locations/time and providers/tags/timing
- in statutory_reqs_packaged_commodities, the value should either be the information about the product (if available), "NA" (if info not available), or "refer to back image" with the image URL provided in item.tags.back_image.(repeated issue)

#### on_confirm
- pickup and delivery ranges should be calculated dynamically, why do both have same start time range.

## Flow 5
#### on_cancel_rto
- How is end.timestamp provided in rto_fulfillment ?

#### on_status_rto_delivered
- rto_fulfillment.start.time.timestamp not carried forward 
- why is rto_fulfillment.start.time.timestamp and rto_fulfillment.end.time.timestamp same ?

## Flow 6
#### on_status_picked
- incorrect invoice generated, the invoice should be generated at on_status_picked as one item is part cancelled before pickup and it should not be updated once generated.

@krishna-balasubramanyam-2020

**Comment by shivang1131** [comment]
- Is catalog rejection framework implemented?
- Share a demo video of incremental refresh, RTO and Return flow
- Remove the other redundant folder from the repo and only keep the required one
- Timestamps are not captured correctly for on_action apis.
- estimated pickup and delivery time ranges can't be overlapping

## Flow1
**on-search**
- Discrepancy in timing. Use range instead of frequency.
- Daawat Rozana Gold Basmati Rice, 1Kg is named as 1kg but has measure of 500gm.

**inc_on_search**
- Nothing changed in the item which is being sent in incremental request.


## Flow 2
**on_status out for delivery**
- Invoice is not loading, the page is going blank after certain time

## Flow 4

**/on_confirm**

- estimated pickup time range can't be earlier than context/timestamp; check start/time/range/start

**/on_cancel**

- delivery TAT should not change in cancelled forward shipment: "86d30bc2-4ce9-4070-948e-383c1f2ae009"

**/on_status**

- invoice is not loading, the page is going blank after certain time

## Flow 6

- reverseqc is not supported; but for RTO, the items are getting delivered back to the seller. How?

**Comment by sandeepshahi** [comment]
- Please answer/address all the pending feedback mentioned earlier;
- Demo Videos:
  - result of incremental changes should be rendered on the buyer app
  - RTO Initiation call is missing; Isn't RTO cancellation allowed to be performed from the UI?
  - Return flow seems to be missing from the seller app UI side;


@krishna-balasubramanyam-2020

**Comment by Vishal-CT** [comment]
- Flow 1 - We're receiving an ACK response for the search incremental changes, but the updates are not appearing in the buyer app.

- Flow 5 - [](https://drive.google.com/file/d/1ULuLnuktDKsp5wixE_JVaq2g8EAXtFCb/view)

- Flow 6  - [](https://drive.google.com/file/d/1T0NNI4pcTOtpK6ijCb72J-Amtz7MNeJ_/view)

@sandeepshahi

**Comment by sandeepshahi** [comment]
1. The buyer app takes around 5 minutes to render the changes. Please check;
2. The issue still persists; Why is the order automatically moving to Cancelled state?
3. Return is getting directly liquidated with no interim state (Return Initiated)
@Vishal-CT

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET10)

@Vishal-CT @krishna-balasubramanyam-2020
