### ISSUE TITLE
Zoho - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#1826]
Multiple issues identified. Please use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self identify and rectify the issues before submitting the logs. For TAT breach appropriate error code to be used. Only submit Group B logs.

@sherinkishana27

**Comment by SherinShafa27** [comment]
Hi @abhinavv245 eventhough TAT breach means buyer cancel before pickup internally to logistics seller we need to use cancel code 996 as per this doc:https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit?gid=1095388031#gid=1095388031

**Comment by abhinavv245** [comment]
Hi @SherinShafa27 TAT breach refers to logistics buyer cancelling the logistics order as the order has not been delivered by LSP within the S2D TAT.

007 | Order / fulfillment not received as per buyer app TAT SLA

**Comment by SherinShafa27** [comment]
yes as a LBNP but this cancel is before RTS hence we used this 996 and confirmed this case with @BLR-0118 through mail last month. 

996 -LBNP cancelling logistics order in draft stage, i.e. without RTS (ready-to-ship) acceptance by LSP;

**Comment by abhinavv245** [comment]
Hi @SherinShafa27 this is a different scenario, however as per test case scenarios, you have to submit logs for a TAT breach, where logistics buyer NP cancels the order due to buyer app TAT SLA.

**Comment by aki1an** [comment]
> you have to submit logs for a TAT breach, where logistics buyer NP cancels the order due to buyer app TAT SLA.

Hi @abhinavv245 , this scenario where the order is getting cancelled with code : 007 is not possible, 

as the order should be greater than the fulfillment sla promised. before RTS if we receive this error, this has to be owned by the seller as the seller has not packed the order yet so we cancel the logistics order with 996.

`(1. LBNP cancelling logistics order in draft stage, i.e. without RTS (ready-to-ship) acceptance by LSP)` as mentioned in the contract.

 After RTS if we receive this code, we will propagate the same to logistics sellerapp but the [reference buyer app]( https://buyer-app-preprod-v2.ondc.org/) doesn't allow cancellation post shipment. so we couldn't generate the logs for the same.

please suggest any.

**Comment by SherinShafa27** [comment]
> Multiple issues identified. Please use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self identify and rectify the issues before submitting the logs. For TAT breach appropriate error code to be used. Only submit Group B logs.
> 
> @abhinavv245 We have fixed ourside LBNP issue and most of the issues were from logistics seller App. Awaiting for ur reply for TAT breach case to resubmit our LBNP logs.

**Comment by abhinavv245** [comment]
Hi @SherinShafa27 @aki1an , you can still cancel the order from your end in case of TAT breach with 007, even if you are not getting it from the buyer app. Please submit the logs as per the test case scenario.

**Comment by abhinavv245** [comment]
Please handle all the issues from LSP side as required. You may need to send NACK due to some errors. Also, communicate to the LSP regarding it.  @SherinShafa27

**Comment by SherinShafa27** [comment]
@abhinavv245 our side LBNP were closed and have checked in log validtation utility also. Can yu review and confirm.?

**Comment by akilan-m-18661** [comment]
@abhinavv245 , we located the rc of the issues we were receiving proper requests from LSP and while logging few fields were tampered. now submitted the correct ones.

**Comment by akilan-m-18661** [comment]
#1873

**Comment by subbaiyana** [comment]
@abhinavv245 , Please review these logs on priority and share your feedback.

**Comment by abhinavv245** [comment]
## All flows

**/search**

- order preparation time is missing (provider/time/duration)
- start/location object to be sent as per the contract (location/id is not required, only area_code is required in address) 

**/confirm**

- why is rto_action in fulfillments/tags marked 'no' for Grocery items (LSP might dispose the items in case buyer is not available)

@SherinShafa27

**Comment by SherinShafa27** [comment]
@abhinavv245 fixed above and updated group B all flows. please review and approve us. [https://github.com/ONDC-Official/v1.2.0-logs/pull/1885](url) cc: @subbaiyana

**Comment by SherinShafa27** [comment]
@abhinavv245 we havve discussed with @BLR-0118 . can yu update the status for logistcis logs and close it?

**Comment by SherinShafa27** [comment]
@BLR-0118 can yu please approve our logistics logs?

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
