### ISSUE TITLE
zoho (SA: RET10) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1844]
#### on_search
- /message/catalog/bpp~1descriptor must have required property 'tags'
-long_desc and short_desc can't be same
- Images are not publicly accessible, for example: 'https://ondc-connect.localzoho.com/api/v1/getimage?doc_id\u003d1013f69870aa4bf604686b7a25beebe871839fcc3622275ccfdda7e92c937dbf232628a6697039358a86d9d9c5ede8cf\u0026type\u003ditem_image'
- A unicode shouldn't be provided in the category_id, for example: item_id: '207214000000330009' and category_id: 'Oil \u0026 Ghee'
- This 'net_quantity_or_measure_of_commodity_in_pkg' field is not required in the @ondc/org/statutory_reqs_packaged_commodities

#### on_search_inc_refresh
- For the item id - 3000002577537, there are no changes as compared to the on_search. Why it's being sent in the on_search_inc

#### select
- /message/order/items/0/quantity/count must be integer

#### on_select
- Warning: Quoted Price in /on_select INR 392 does not match with the total price of items in /select INR 420 i.e. price for the item mismatch in on_search and on_select because the price for the item_id: 3000002326257 is being changed from 99 to 85 and why it's being changed?

#### init
- /message/order/items/0/quantity/count must be integer

#### confirm
- /message/order/items/0/quantity/count must be integer
- /message/order/fulfillments/0/tracking must be boolean, shouldn't provide in a string form

#### on_confirm
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
- np_type of on_search is not same to np_type of on_confirm

#### on_status_pending
- When the onConfirm Order State is 'Accepted', the on_status_pending is not required!

#### on_status_packed
- Created At timestamp for /on_status_packed.message.order should be equal to context timestamp at confirm
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
- Fulfillment Tracking mismatch with the on_select call

#### on_status_picked
- RoutingTag object is mandatory in Tags of Delivery Object for on_status_picked
- Created At timestamp for /on_status_picked should be equal to context timestamp at confirm
- order/updated_at timestamp can't be less than the pickup time
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
-  Fulfillment Tracking mismatch with the on_select call
-  Invoice should be publicly accessible, kindly provide a valid link

#### on_status_out_for_delivery
- RoutingTag object is mandatory in Tags of Delivery Object for on_status_out_for_delivery
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
- Created At timestamp for /on_status_out-for-delivery should be equal to context timestamp at confirm
- **ffTracking**: Fulfillment Tracking mismatch with the on_select call

#### on_status_delivered
- RoutingTag object is mandatory in Tags of Delivery Object for on_status_delivered
-Created At timestamp for /on_status_delivered should be equal to context timestamp at confirm
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
- delivery timestamp is missing
- Fulfillment Tracking mismatch with the on_select call

### Flow 3

- Similar as above

#### select_out_of_stock
- /message/order/items/0/quantity/count must be integer

#### on_cancel
- /start/range has invalid timestamp format for "Delivery" Fulfillment
- /end/range has invalid timestamp format for "Delivery" Fulfillment
- /message/order/fulfillments/1/start shouldn't be present in 'Cancel' fulfillment
- precancel_state.updated_at of on_cancel is not equal with the on_confirm order.updated_at

#### on_status_packed
- Created At timestamp for /on_status_packed.message.order should be equal to context timestamp at confirm
- /start/range/start_time "2024-06-10T06:56:32.254Z" of on_confirm mismatched with /start/range/start_time "2024-06-10T06:56:32.489Z" of on_status_packed for "Delivery" Fulfillment
- /start/range/end_time "2024-06-10T07:56:32.254Z" of on_confirm mismatched with /start/range/end_time "2024-06-10T07:56:32.489Z" of on_status_packed for "Delivery" Fulfillment
- /end/range/start_time "2024-06-12T07:56:32.254Z" of on_confirm mismatched with /end/range/start_time "2024-06-12T07:56:32.489Z" of on_status_packed for "Delivery" Fulfillment
- /end/range/end_time "2024-06-12T08:56:32.254Z" of on_confirm mismatched with /end/range/end_time "2024-06-12T08:56:32.489Z" of on_status_packed for "Delivery" Fulfillment
-  Invoice should be publicly accessible, kindly provide a valid link

#### on_status_picked

- Similar as above
- RoutingTag object is mandatory in Tags of Delivery Object for on_status_picked
- Created At timestamp for /on_status_picked should be equal to context timestamp at confirm
- order/updated_at timestamp can't be less than the pickup time

#### on_status_out_for_delivery

- RoutingTag object is mandatory in Tags of Delivery Object for on_status_out_for_delivery
- start and end time range mismatched as compared to on_confirm for 'Delivery' Fulfillment as shared above
- **tmpstmp**: Created At timestamp for /on_status_out-for-delivery should be equal to context timestamp at confirm
- **ffTracking**: Fulfillment Tracking mismatch with the on_select call

#### on_status_delivered
- **missingRouting/Tag**: RoutingTag object is mandatory in Tags of Delivery Object for on_status_delivered
- **tmpstmp**: Created At timestamp for /on_status_delivered should be equal to context timestamp at confirm
- start and end time range mismatched as compared to on_confirm for 'Delivery' Fulfillment as shared above
- **deliverytime**: delivery timestamp is missing
- **ffTracking**: Fulfillment Tracking mismatch with the on_select call

### Flow 6
- Same errors for on_status flows as stated above
- For 'Delivery' fulfillment, 'start/location/id' has been added from on_status_packed onwards which is missing in on_confirm call
- on_status_delivered, the context.action was on_update, which is incorrect
- Many of the payloads have been missing in the flow6, Kindly refer to this docs `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795` for more information

@sherinkishana27

**Comment by SherinShafa27** [comment]
@sahil-ondc for **flow 2** select,init,confirm were from reference buyer app. For **Flow 6** we have supported return reject and liquidation as discussed with @BLR-0118

**Comment by sahil-ondc** [comment]
## Flow 2
### init
- /message/order/fulfillments/0/end/location/address/building must NOT have fewer than 3 characters

### on_confirm
Why settlement_details are missing in payment object ?

### on_status_packed
- Empty object for time shouldn't be provided in the fulfillment delivery/end

### on_status_picked
- Invoice should be publically accessible

#### If tracking is enabled, track and on_track must be provided

## Flow 3, 4, 5
- Similar as flow 2

### on_status_pending
- When the onConfirm Order State is 'Accepted', the on_status_pending is not required!

### on_cancel
- quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm 

### Flow 6
- `update_settlement_part_cancel` is missing
- Instead of `Rejection` in liquidation. Kindly provide case for the 'Approval'
- Kindly refer to retail contract for flow 6:- https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.mg00vd1pw4r6

@SherinShafa27

**Comment by SherinShafa27** [comment]
@sahil-ondc 
**Invoice should be publically accessible** -As many of the buyer apps arent consuming this field and due to privacy reasons as this url has no authentication we are sending the dummy url.

**quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm** - As for rto case,we may have rto delivery charge hence quote price wont be same as on_confirm

**update_settlement_part_cancel is missing** - This update call request we didnt get from buyer ref app.

**Instead of Rejection in liquidation. Kindly provide case for the 'Approval'** -- Already @subbaiyana discussed with @BLR-0118 for proceeding with this. 

can we have a call/meeting to close this? @sahil-ondc pls revert asap

**Comment by SherinShafa27** [comment]
Apart from above needs to discussed, fixed flow 2 issues and updated logs here [https://github.com/ONDC-Official/v1.2.0-logs/pull/1886](url) .Pls review and approve. @sahil-ondc cc: @subbaiyana

**Comment by SherinShafa27** [comment]
@sahil-ondc any update???

**Comment by BLR-0118** [comment]
Flow 2:
if "url_enabled" is "yes" in /on_status*, pls also make sure "url" is correctly populated;

**Comment by BLR-0118** [comment]
clearing logs for v1.2.0 (RET10), subject to the above being fixed;
