### ISSUE TITLE
kiko live (SA: RET11) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1845]
### on_search_full_catalog_refresh

- Support for variants is mandatory, categories must be present in bpp/providers[0]
- long_desc and short_desc can't be same
- Ean code can’t be use here for example: "code": "1:JS001", you can use others
- You can use enum 'All' in timing construct if the timings are same for 'Order' and 'Delivery'

### on_search_inc_refresh

- Message id should not be same with previous calls as it's incremental push based call

### on_select

- How the TAT is less than the time_to_ship
- If '@ondc/org/TAT" <= 2hr, the category should be 'Immediate Delivery'
- There shouldn't be extra space in the title for item_id 660c369b207085ef1155dda1

### init

- In the end/contact/email is optional

### on_init

- If the settlement_type is neft, the upi_address field is not required

### on_status_pending

- How the item_id and quote price is changed in quote as compared to on_confirm
- How the start/time/range/start is greater than start/time/range/end for the 'Delivery' fulfillment
- How the end/time/range/start is similar to end/time/range/end for the 'Delivery' fulfillment
### on_status_packed

- Why the start/time/timestamp is provided in 'Delivery' fulfillment before on_status_picked
- Why the end/time/timestamp is provided in 'Delivery' fulfillment before the on_status_delivered

### on_status_picked

- Invoice should be publically accessible
- Why the start/time/timestamp is not in range as provide for the 'Delivery' fulfillment

### on_status_delivered

- Why the end/time/timestamp is not in range as provide for the 'Delivery' fulfillment

### on_cancel

- fulfillment type rto end/time should not be present in /on_cancel when state/desc/code is RTO-Initiated
- terminal state of RTO (delivered/disposed) must be provided through /on_status call

## Flow 6

- The flow 6 is incomplete, kindly provide the required calls for part_cancel, reverse_qc and liquidated

@vijendrapatidar

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search (full catalog)

- categories should be defined in construct as defined in API contract
- if timing is same for delivery and order, use All instead
- if back_image is not provided then image for back_image tag should not be provided
- customization flow should be provided
- why only 1 item is provided in full catalog
- why item in F&B is named as vishal

### on_search (inc catalog)

- Does item changes supported ?
- store was already enabled in full catalog, why it has been enabled again

## Flow 2

### select

- Buyer selects multiple items (> 1 qty for each item) for checkout
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit?gid=1367601795#gid=1367601795`

### on_init

- only @ondc/org/buyer_app_finder_fee_type, @ondc/org/buyer_app_finder_fee_amount should be provided in payment object

### on_confirm

- provided pickup and delivery range should be as per provided TAT in on_select
- why np_type, and provider_tax_number has been provided repeatedly in bpp_terms
- payment/transaction_id should not be same as context/transaction_id

## Flow 3

### select

- multiple items should be selected and flow should proceed with item which is in stock
- How the item which was out of stock is selected again in the select action call ?

## Flow 4

- Same as Flow 2

### on_cancel

- actual precancel_state should be provided instead of cancelled
- why delivery and other charges are not refunded even when order was in pending state

## Flow 6

### on_update (part-cancellation)

- why /message/order/payment/params/amount got changed as compare to confirm
- Kindly provide the required unsolicited on_status calls and calls for liquidation. You can also provide reverse_qc as well (if supported)

@vijendrapatidar

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search (full catalog)

- category_id provided in /message/catalog/bpp/providers/items should be F&B
- item/quantity/unitized/measure should be mapped correctly (for ex: item_id: '65ceebe9fa759b16650a0800' named as Aloo paratha is mapped as 250 unit)
- veg_nonveg should be correctly mapped as item_id: '65ceebe9fa759b16650a0800' named as Aloo paratha is mapped as non_veg

### Customizations should be provided so that we can proceed with other flows for validation

@vijendrapatidar

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- category_id should be only 'F&B' in case of RET11
- category should be 'F&B' in 'Serviceability in case of RET11
- Invalid category_ids : 'q8RSHHJpP3NF:23' for the item_id '66e1029b59d6f75602e1ae96'. Kindly check for others as well
- How the default_selection maximum value can be '250' for the item_id : '66b30f66d736a1f0f5784db6' as there is no customization is default : 'yes' 
- Why any customizaton related to custom_group is not set to default: yes as the config.min is '1' for the custom_group : 'kF1k5olnHFnV' ?Kindly check for others as well
- upper range for the item_id : '66b30f66d736a1f0f5784db6' is not collected  properly. Kindly provide how you are calculating the upper.range. Kindly check for others as well
-  Only 1 'Serviceability should be provided in case of RET11 with category: 'F&B'

## Flow 2
### On Init
- Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object

### Confirm / On Confirm
- Extra attribute Quantity provided in quote object i.e not supposed to be provided after on_select so invalid quote object

## Flow 3
- Same as Flow 2

## Flow 4
- Same as Flow 2
### On cancel
- tags should be there in forward and backward fulfillment for the customization and customizable item

## Flow 5
- Same as Flow 2
### On cancel
- If the value is 0 for any item or tax, should not be provided in the quote_trail
- If you are charging for the delivery, packing and convinience fees should not be added in the quote_trail

### On Status Rto Delivered
- fulfillment type rto end/time is missing in /on_status_rto_delivered

## Flow 6
- Same as Flow 2
### On Update Part Cancel
- If the value is 0 for any item or tax , should not be provided in the quote_trail

### On Update Liquidated
- If the value is 0 for any item or tax, should not be provided in the quote_trail
- Quantity count can't be -1 in the items for for id: '66da90a090ee16c10a00b603'
- Packing charges have been added in the quote-trail. Are you not charging for the packing as the items is already delivered ?

@vijendrapatidar

**Comment by vijendrapatidar** [comment]
***@***.***

**Comment by vijendrapatidar** [comment]
***@***.***@kiko.live

**Comment by sahil-ondc** [comment]
### Flow 1
#### On Search
- Invalid `category_ids[]` for the `item_id`: ‘66b6088c8d03b74fdbc2a436’ associated with the `custom_menu_id`: ‘aAF23sfFwgzx’. It should start with [“aAF23sfFwgzx:1”], not directly from 9. Kindly check others as well.
- If the maximum value for the `item_id`: ‘66b30f66d736a1f0f5784db6’ is ‘849’, how can the `default_selection` maximum value be ‘269’?
- An incorrect upper range is provided for `item_id`: ‘66b30f66d736a1f0f5784db6’. How is the upper range calculated? Could you please provide the calculations for the same?

### Flow 2
#### On Status Picked
- The invoice amount doesn’t include the ‘tax amount’. How is the total amount calculated in the invoice?

### Flow 4
#### On Cancel
- Tags are missing in the forward and backward fulfillment for the customizable item and its customization.
- If the `quote_trail` is ‘0’ for any item, it should not be added to the `quote_trail`.

### Flow 5
#### On Cancel
- Tags are missing in the forward and backward fulfillment for the customizable item and its customization.

### Flow 6
#### On Update Liquidated
- The `quote.breakup.count` isn’t reduced for the `item_ids`: ‘66b30f66d736a1f0f5784db6’, ‘66b30f66d736a1f0f5784db9’, and ‘66b30f66d736a1f0f5784dba’, which were liquidated.

@vijendrapatidar

**Comment by Gururaj-KikoLive** [comment]
**Flow 1
On Search**

- If the maximum value for the item_id: ‘66b30f66d736a1f0f5784db6’ is ‘849’, how can the default_selection maximum value be ‘269’?
- The default value is set to the base price of the product without any add-ons or customizations. Therefore, the default value is 269, while the maximum price with customizations can reach 849. For the default, we always use the base item price.

- An incorrect upper range is provided for item_id: ‘66b30f66d736a1f0f5784db6’. How is the upper range calculated? Could you please provide the calculations for the same?
- The upper range is calculated based on the selections made for the product, specifically the size (Large) and up to two add-ons. The base value is 269. If the Large size is selected for 450, and two add-ons worth 35 and 95 are chosen, the total will amount to 849. Therefore, the item's price cannot exceed 849. Please refer to the image below for clarification.
![image](https://github.com/user-attachments/assets/bfc3fd4c-fc9f-4749-a78b-5efc827883ae)


**Flow 4
On Cancel**

- Tags are missing in the forward and backward fulfillment for the customizable item and its customization.
- We are not receiving clear requirements in this feedback. Could you please elaborate on the expectations for the tags fulfillment?

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- Invalid category_ids[] for the item_id: ‘66b6088c8d03b74fdbc2a436’ associated with the custom_menu_id: ‘aAF23sfFwgzx’. It should start with [“aAF23sfFwgzx:1”], not directly from 2. Kindly check others as well.
- Invalid default_selection value and maximum value provided for the item_id : '66b30f66d736a1f0f5784db6'
- Upper range for the item is wrongly calculated for the item_id : '66b30f66d736a1f0f5784db6'
 
## Flow 3
- Kindly use customizable item for the out of stock scenario
 
## Flow 4
### On Cancel
- In case of customizable item and customizations you need to use tags and parent_item_id in the forward and backward fulfillment like for the 'Delivery' and 'Cancel' fulfillment in the order.items
 
## Flow 5
### On Cancel 
- In case of customizable item and customizations you need to use tags and parent_item_id in the forward and backward fulfillment like for the 'Delivery' and 'Cancel' fulfillment in the order.items

**Comment by BLR-0118** [comment]
1. item.category_ids defines the display order in custom menu - has 2 values separated by ":"; 1st part is the custom menu id & 2nd part is display sequence within custom menu;
2. wherever base item price is 0, you need to provide either default selection value (value for default customization for the custom group) or upper/lower range (min & max values for customizations in custom groups assigned to item);
3. for all forward & reverse flows, items with customizations should have the entire breakup as shown in /select, /on_select;

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- Invalid category_ids[] for the item_id: ‘66b6088c8d03b74fdbc2a436’ associated with the custom_menu_id: ‘aAF23sfFwgzx’. It should start with [“aAF23sfFwgzx:1”], not directly from 2. Kindly check others as well.
- Invalid default_selection value and maximum value provided for the item_id : '66b30f66d736a1f0f5784db6'
- Upper range for the item is wrongly calculated for the item_id : '66b30f66d736a1f0f5784db6'

## Flow 3
- Kindly use customizable item for the out of stock scenario

## Flow 4
### On Cancel
- In case of customizable item and customizations you need to use tags and parent_item_id in the forward and backward fulfillment like for the 'Delivery' and 'Cancel' fulfillment in the order.items

## Flow 5
### On Cancel 
- In case of customizable item and customizations you need to use tags and parent_item_id in the forward and backward fulfillment like for the 'Delivery' and 'Cancel' fulfillment in the order.items
@Gururaj-KikoLive

**Comment by Gururaj-KikoLive** [comment]
Hi @sahil-ondc We have fixed and raised another PR - https://github.com/ONDC-Official/v1.2.0-logs/pull/2738

Please check above and let us know your feedback

**Comment by shivang1131** [comment]
## Flow 1
### on_Search
- Context.timestamp in search is greater than on_search.
- Seq number passed incorrectly for category with id - SGxEXU9Nb0Sx.
- Maximum value of base item in items.price.maximum_value is maximum price of base item and not with added customisations.
- Maximum value in default_selection tags also captured incorrectly.
- Why does fried rice have quantity.unitized.measure as 200 units?

## Flow 3
- The idea of this flow is to choose a different item when an item which was previously sent is out of stock. Please resubmit this flow and choose a different item which was previously not chosen.

## Flow 4
### Cancel
- Invalid cancellation_reason_id.

## On_cancel
- Invalid item sent in quote.breakup for delivery, misc and packing.

**Comment by Gururaj-KikoLive** [comment]
Hi @shivang1131, Are these the only changes required, or are there other issues in the submitted logs? Some of these issues were not highlighted earlier.

**Comment by Gururaj-KikoLive** [comment]
Hi @shivang1131 

Could you please provide us with examples for the points listed below?

1. Flow 1
on_Search
Maximum value in default_selection tags also captured incorrectly.
- What is expected here? We are sending a default selection value with the tag; what value is expected?

2. Flow 4
Cancel
Invalid cancellation_reason_id. 
- Cancellation reason ID is initiated by the buyer app itself; this is the same cancellation reason ID we are using, as shown in the image below. Should we change the cancellation ID or use another cancellation ID from the buyer app itself?
![image](https://github.com/user-attachments/assets/75368236-f8c6-4888-8fa3-ad763568fc70)

3. On_cancel
Invalid item sent in quote.breakup for delivery, misc and packing.
- Could you please provide more details on the feedback regarding what values should be included in the quote breakup?

**Comment by shivang1131** [comment]
Hi @Gururaj-KikoLive,

The maximum value that you send in the default_selection tag is the sum of the maximum values of the default items and not the maximum of the customisable item.

For the cancellation reason id, ignore that error as that was an error from my side.

In the on_cancel api, in the quote breakup, you had added an extra item object in the quote breakup which should not be there. 

{
                        "@ondc/org/item_id": "fulfillment-661fa1f12d4fd379f825e293",
                        "title": "Delivery charges",
                        "@ondc/org/title_type": "delivery",
                        "price": {
                            "currency": "INR",
                            "value": "0"
                        },
                        "item": {
                            "price": {
                                "currency": "INR",
                                "value": "20.00"
                            }
                        }
                    }
                    
 The item object would not be present here for the objects mentioned in the issues.

Please ask if you have any other issues.

**Comment by Gururaj-KikoLive** [comment]
Hi @shivang1131 Can you please confirm only above points are required to be corrected from our side or are there any other issues in logs?

**Comment by shivang1131** [comment]
HI @Gururaj-KikoLive,
The  calculation of default_selection tags have incorrect values in the catalog. Please fix

**Comment by Gururaj-KikoLive** [comment]
Hi @shivang1131 

We are sending below in default selection tags, Where 269 is MRP and 269 is selling price of the item,
"default_selection",
                                        "list": [
                                            {
                                                "code": "value",
                                                "value": "269"
                                            },
                                            {
                                                "code": "maximum_value",
                                                "value": "269"
                                            }
                                        ]
                                    }

as mentioned in the document we referred,
![image](https://github.com/user-attachments/assets/6ce8bab4-27fa-49a6-bf14-78c9a278bdf4)

Can you please suggest which values are incorrect in this catalog if it has same MRP and Selling price? 


Also, If any changes are required can we submit only this one flow for the further approvals?

**Comment by shivang1131** [comment]
Hi @Gururaj-KikoLive ,
The value that you send in default_selection is the sum of prices of the base item and all the default customizations of that item. The screenshot that you have attached has value equal to the base item because all default customizations of that item have 0 extra price which is not the case in your catalog. Please feel free to ask any other questions.

Yes, please resubmit this flow only for further approvals.

Regards

**Comment by Gururaj-KikoLive** [comment]
Hi @shivang1131 

Please check this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/2763

We have now added all default customisation prices in selection value.

**Comment by sandeepshahi** [comment]
Logs approved for RET11 (v1.2)

@Gururaj-KikoLive
