### ISSUE TITLE
Wits Adapter (SA: RET 10, 12, 13, 14, 15, 16)

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#1851]
## RET 10

**/on_search**

- if timings for Order/Delivery/Self-Pickup are same, use "All" enum
- mapping of item description and statutory reqs seems incorrect; eg: Tea is mapped with Ashirvaad Atta
- month_year_of_manufacture_packing_import should be in correct format
- The EAN codes seem to be incorrect and not related to the item; Non-branded products usually don't have any EAN codes
- grocery products must be cancellable

**/on_search (inc)**

- time/timestamp can't be future dated

## RET 12

**/on_search**

- invalid value of HSN code provided
- fashion products must be returnable and cancellable
- placeholder values of statutory reqs should not be provided
- can variant_group be created based on multiple attributes? eg: size and colour
- since unitized measure is also changing for variants belonging to group: "9049830785323", variant group should be created using that attribute as well
- description of variant group must be valid; "BULLMER" is mentioned in the group while variants belong to "Peter England" brand

**/on_search (inc)**

- HSN code should be provided for RET 12 SKUs
- why is colour and other attribute values (units etc.) changing in inc refresh?

## RET 13

**/on_search**

- similar issues as above
- variant grouping is not defined correctly; how can seq be 2 when the group is based on single attribute

**/on_search (inc)**

- similar issues as above

## RET 14, 15, 16

- similar issues as above

### For item/descriptor/code, pls follow the rules:

- for branded packaged products (across grocery, BPC, H&W), use EAN;
- for fashion, use HSN;
- for electronics, use GTIN;
- H&K could have EAN or Other;

@witslab-nikita

**Comment by sandeepshahi** [comment]
@witslab-nikita, Dummy search requests are not allowed. The buyer app does not send full or incremental pulls at the timestamp provided in the /search calls.

**Comment by NishthaMonga** [comment]
#RET 10
## On Search
- Gps doesn’t match with the given area code

#RET 12
## On Search
- Gps doesn’t match with the given area code

## On Search Inc
- item.quantity.unitized.measure.value should be greater than 0
- category_id can’t be changed from in the incremental call

#RET 13
## On Search
- Gps doesn’t match with the given area code
- variants are not captured properly for category_id : ‘9446576193835’, ‘9446604439851’

#RET 14
## On Search
- Gps doesn’t match with the given area code

## On Search Inc
- item.quantity.unitized.measure.value should be greater than 0

#RET 15
## On Search
- Gps doesn’t match with the given area code
- Back Image doesn’t match with the given itemd_id `49378718187819` 
- Variants are not captured properly as only 1 item is provided

#RET 16
## On Search
- Gps doesn’t match with the given area code

## On Search Inc
- Mandatory tag field [colour_name] missing for Home & Kitchen item[0]
- code should have 1:EAN as a value in /message/catalog/bpp/providers[0]/items[0]/descriptor/code
- item.quantity.unitized.measure.value should be greater than 0


@witslab-nikita

**Comment by shivang1131** [comment]
## RET 10
### onsearch- 

GPS address in location does not match the area code provided in address.
Placeholder image in item.
no url in tags of item with code image.
Placeholder values should not be put in code as EAN numbers.
maximum_value of 10kg aata is less than maximum_value of 5kg aata.

### on_search inc
back image attribute not provided in tags in incremental search which was provided in full catalog refresh.


## RET 12
Same issues as Above.
colour of item in on_search and in on_search_inc is different.
quantity.unitized.measure.value is not supposed to be zero in case of out of stock in on_search_inc.

## RET 14
Same errors as previously mentioned. 
Attributes of commodities change in on_search_inc.


## RET 15
Only one item in a variant group. 
item.tags.attribute.capacity is non existent but is added as a differentiator in the variant group.

## RET 16
item.tags.attribute.colour are same for both the items. There is no differentiating factor of the variant group.


@witslab-nikita

**Comment by witslab-nikita** [comment]
@shivang1131, Thanks for the feedback, we have some queries regarding the feedback. 

**As it's pre-production environment we are testing with dummy data, below mentioned issues should not be any blocker** 
1. Placeholder image in item.
2. Placeholder values should not be put in code as EAN numbers.
3. maximum_value of 10kg aata is less than maximum_value of 5kg aata.

**Comment by shivang1131** [comment]
Since this is the final stage of testing, please ensure that the data across api's is syntactically correct and not manipulated. 
Please provide correct values that would be used in the prod environment.

@witslab-nikita

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET 10, 12, 13, 14, 15 and 16)

@witslab-nikita
