### ISSUE TITLE
Zoho IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1990]
Zoho
General:
- item based flow is missing
- Flow 3 and Flow 2 both are fulfillment based and both are cascaded to LSP

FLOW 1
     issue
         1. Time of creation (created_at) and time of updation for /issue api should be the same
         2. context timestamp should be greater than or equal to updated_at in issue
     
     on_issue_status (Unsolisated)
           1. /message/issue/resolution_provider/respondent_info/organization/person must have required property 'name'
           2. /message/issue/resolution/action_triggered must be equal to one of the allowed values (REFUND,REPLACEMENT,RETURN,CANCEL,NO-ACTION)
           3. resolutionI_info/type should be TRANSACTION-COUNTERPARTY-NP in this flow

FLOW 2
     issue
           1. Time of creation (created_at) and time of updation for /issue api should be the same

FLOW 3
     issue
          1. Time of creation (created_at) and time of updation for /issue api should be the same
@sherinkishana27

**Comment by SherinShafa27** [comment]
@RupalSingla https://docs.google.com/document/d/1tx86sypacIRXgL9nlNBdvHz7cYQjQoyC/edit 

Flows taken as per above usecase mentioned. For flow 1- item/fulfillment and for flow2 &3- fulfillment flow only asked in above usecase

**Comment by SherinShafa27** [comment]
@RupalSingla for all the flow /issue api is from buyer reference app. They need to fix it. 

` on_issue_status (Unsolisated)
       1. /message/issue/resolution_provider/respondent_info/organization/person must have required property 'name'
       2. /message/issue/resolution/action_triggered must be equal to one of the allowed values (REFUND,REPLACEMENT,RETURN,CANCEL,NO-ACTION)
       3. resolutionI_info/type should be TRANSACTION-COUNTERPARTY-NP in this flow`
       
From our side above 3 issues were fixed.And submitted item flow. Please review and approve. cc: @subbaiyana

**Comment by subbaiyana** [comment]
@RupalSingla , We have planned to go-live by tomorrow, we require your help to certify and close the logs as soon as possible.. After the log verification, we should connect with QA team to get the certificate.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @subbaiyana
