### ISSUE TITLE
zoho (RET13) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2000]
### on_search (full catalog)

- back_image should be publically accessible in /message/catalog/bpp/providers/items
- EAN code provided in /message/catalog/bpp/providers/items/descriptor/code should be valid, and should not be placeholder
- range should not be zero in /message/catalog/bpp/providers/locations/circle/range
- area_code should not as per provided gps in /message/catalog/bpp/providers/locations

### on_init

- np_type should be defined in bpp_terms in /message/order/tags

### on_confirm

- /message/order/fulfillment/start/range/start should not be less than context/timestamp
- measure should not be provided in /message/order/items/quantity

### on_status (packed)

- routing and tracking information should be provided only if the fulfillment is agent-assigned

### on_status (out-for-delivery)

- tracking_url should be publically accessible

### on_status (delivered)

- time should not be provided in payment object

### on_cancel (rto)

- precancel_state should be captured correctly

### on_status (rto-delivered)

- why precanceL_state updated_at got changed as compared to on_cancel (rto)

### Flow 6

- @ondc/org/settlement_details should have updated settlement details whenever refund has been raised
- Reverse QC flow should be provided
- update_reject is empty

@sherinkishana27

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @sherinkishana27

**Comment by SherinShafa27** [comment]
@sahil-ondc 

Flow 1 

**EAN code provided in /message/catalog/bpp/providers/items/descriptor/code should be valid, and should not be placeholder** This is just a test dataset so sending dummy values in production it will be valid one.Cant we ignore this?

Flow 2

**tracking_url should be publically accessible** - This is shared by logistics partner
**time should not be provided in payment object** - In contract its given as mandatory. Kindly check the contract.

Flow 5
**precancel_state should be captured correctly** - It is sent correctly only.

cc: @subbaiyana @aki1an

**Comment by SherinShafa27** [comment]
apart from above ,others fixed in this https://github.com/ONDC-Official/v1.2.0-logs/pull/2075 @sahil-ondc

**Comment by NishthaMonga** [comment]
### Flow 1
## on_search_full_catalog_refresh
- ttl = PT30S as per the API Contract

### Flow 2
## on_status_pending
- When the onConfirm Order State is 'Accepted', the on_status_pending is not required!

### Flow 3
## on_init
- Only @ondc/org/buyer_app_finder_fee_type, @ondc/org/buyer_app_finder_fee_amount, and @ondc/org/settlement_details are required in the payment object when the buyer is collecting money; and currently only buyer is collecting money on network.

### Flow 4
## on_cancel
- payment settlement_details mismatch in /on_init & /on_cancel
- fulfillment type delivery end/time is missing in /on_cancel

### Flow 5
## confirm call missing

## on_status_out_for_delivery
- RoutingTag object is mandatory in Tags of Delivery Object for on_status_out_for_delivery
- order/state should be \"In-progress\" for /on_status_out-for-delivery
- fulfillments/state Should be out-for-delivery for /on_status_Out-for-delivery 
 
## on_cancel
- fulfillment type delivery end/contact/email is missing in /on_cancel
- Order Id mismatches in /on_cancel and /on_confirm
- payment settlement_details mismatch in /on_init & /on_cancel
- precancel_state.updated_at of on_cancel is not equal with the on_status_out_for_delivery order.updated_at

### Flow 6b 
- Missing calls for on_update


@SherinShafa27

**Comment by SherinShafa27** [comment]
Only @ondc/org/buyer_app_finder_fee_type, @ondc/org/buyer_app_finder_fee_amount, and @ondc/org/settlement_details are required in the payment object when the buyer is collecting money; and currently only buyer is collecting money on network.

@NishthaMonga Can you explain? On network means? Currently buyer app is collecting prepaid order amount.So what do yu expect here?

**Comment by akilan-m-18661** [comment]
@NishthaMonga -

1. ttl = PT30S as per the API Contract - its need not to be 30 seconds, it denotes the expiry its sellerapp wish to configure time to live of that payload.

**Comment by shivang1131** [comment]
## Flow 1 
### on-search

- Category id should but alphanumeric and upto 12 characters.
- Variants cant depend on the the same attribute twice.
- Maximum value of item cannot be greater than 99.
- Unitized.measure.value incorrectly mapped for 3000005816567
- Return window cannot be zero seconds.
- If time greater than 24 hours, convert into days and hours. Check "PT120H".


Please share your latest incremental catalog refresh also.

**Comment by akilan-m-18661** [comment]
@shivang1131 

>  If time greater than 24 hours, convert into days and hours. Check "PT120H".

PT120H is also a valid ISO-8601 duration format, both P5D & PT120H corresponds to same only.

**Comment by SherinShafa27** [comment]
@shivang1131 **Variants cant depend on the the same attribute twice.**
u mean color and color_name attributes? Variants cant depend on the the same attribute twice.

**Comment by SherinShafa27** [comment]
@shivang1131 any update on the above???

**Comment by shivang1131** [comment]
@SherinShafa27,
Its in gram only whats incorrect?
3000005816567 is 3.75 oz but is put in as 3 grams which is  logically incorrect.
u mean color and color_name attributes?
Yes

**Comment by SherinShafa27** [comment]
@shivang1131 if we provide only color it will be incovenient to buyers to choose the color hence we are providing both and it wont impact the variants as its optional only. attached ss for ref. if we didnt send the color name means user cant choose the item only with color code.
![Uploading Screenshot 2024-09-09 at 11.44.10 AM.png…]()

**Comment by SherinShafa27** [comment]
@shivang1131 have u checked above? also raised new PR for updated logs .please check and approve.

**Comment by shivang1131** [comment]
Hi @SherinShafa27,
I am not able to open the screenshot that you have sent.
When we define multiple variants, we offer the buyer a more specific set of items to choose from. In your case, color and color_name change with every item. This defeats the purpose of a variant and is not feasible. colour and colour name serve the same purpose.

**Comment by SherinShafa27** [comment]
![Uploading Screenshot 2024-09-09 at 11.44.10 AM.png…]()

**Comment by SherinShafa27** [comment]
![Screenshot 2024-09-09 at 11 44 10 AM](https://github.com/user-attachments/assets/fb4d4002-1010-447b-90a8-da572a82183e)

**Comment by SherinShafa27** [comment]
@shivang1131 CHECK ABOVE

color_name is an optional one if we send only color it wont be convenient to users to choose it.

**Comment by shivang1131** [comment]
Hi @SherinShafa27,
Every color is associated with a specific name and unique hex code. Since each hex code corresponds to one specific color, passing it as a second parameter in the variant might not be the most effective approach. Variants typically provide multiple options, but in this case, the hex code only maps to one color. It might be worth reconsidering how this is structured.

Please provide logs with variants based on unrelated attributes.

**Comment by shivang1131** [comment]
Hi @SherinShafa27,
There seems to be no other issue in your logs. The only underlying issue now is the variant grouping.

Regards

**Comment by SherinShafa27** [comment]
@shivang1131 > There seems to be no other issue in your logs. The only underlying issue now is the variant grouping.

since its optional we send both color and color_name. we will send only color and will send color_name in specifications. can we go ahead for onboarding? pls update.

**Comment by SherinShafa27** [comment]
hii @shivang1131 kindly check this [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/2414) for above variant issue and approve us to proceed onboarding.

**Comment by SherinShafa27** [comment]
any update @shivang1131 awaiting for ur approval to proceed with seller onboarding. cc: @subbaiyana

**Comment by shivang1131** [comment]
Hi @SherinShafa27,
I will verify your logs by tomorrow.

Regards

**Comment by SherinShafa27** [comment]
@shivang1131 only one issue need to be verified right? pls update by today so that we can go ahead with implementation. cc: @subbaiyana

**Comment by SherinShafa27** [comment]
@sandeepshahi have uploaded RET16 aswell . pls approve that too @sandeepshahi
