### ISSUE TITLE
KNS Rsf - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2006]
flow 1

receiver_recon

/message/orderbook/orders/0/payment/@ondc1org1settlement_details/0/settlement_amount must be number

on_receiver_recon

-/context must have required property 'transaction_id'",
-/message/orderbook/orders/0 must have required property 'receiver_app_id'
-"counterparty_recon_status" is 2 if amount is "Overpaid" and you have mentioned it's equally paid
refer this for enums: https://github.com/ONDC-Official/protocol-network-extension/blob/main/specifications/rsp/enums/counterparty_recon_status.json

flow 2

-updated_at should not be equal to message/order book/orders/payment/@ondc/org/settlement_details/settlement_timestamp
@VirajjKAS

**Comment by VirajjKAS** [comment]
Hey @RupalSingla, as we are seller application, we cannot handle create reciever_recon so flow2 review could you please guide what we can do for this ?

**Comment by RupalSingla** [comment]
KNS Retail

common error

receiver_recon

message.orderbook.orders.payment.@ondc/org/settlement_details.settlement_timestamp  cannot be greater than  

message.orderbook.orders.created_at

on_receiver_recon

"/message/orderbook/orders/0 must NOT have additional properties (invoice_id)" it's invoice_no"


@VirajjKAS

**Comment by RupalSingla** [comment]
Logs cleared @VirajjKAS
