### ISSUE TITLE
Protean (BA: RSF) - compliance checks

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2008]
Protean(buyer_app)

Success flow 

receiver_recon

context timestamp should be greater than updated_at
"/message/orderbook/orders/payment must have required property 'uri'"
"/message/orderbook/orders/payment must have required property 'tl_method'",
"/message/orderbook/orders/payment must have required property '@ondc/org/collected_by_status'"
"/message/orderbook/orders/payment must have required property '@ondc/org/withholding_amount_status'"
"/message/orderbook/orders/2/payment must have required property '@ondc/org/return_window_status'"
"/message/orderbook/orders/2/payment must have required property '@ondc/org/settlement_basis_status'"       
"/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_amount must be number"
@ondc/org/buyer_app_finder_fee_type" enum should be "Percentage", (enum as per retail specs)
       
Correction flow 

Same as Success flow

@RaviV-Protean

**Comment by RaviV-Protean** [comment]
Resubmitted the logs
https://github.com/ONDC-Official/v1.2.0-logs/pull/2015

**Comment by RupalSingla** [comment]
logs cleared  @RaviV-Protean
