### ISSUE TITLE
Protean (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2009]
Success flow 

For both seller_app and buyer_app bpp is Protean only Improvise it on your end

receiver_recon

context timestamp should be greater than updated_at
"/message/orderbook/orders/payment must have required property 'uri'"
"/message/orderbook/orders/payment must have required property 'tl_method'",
"/message/orderbook/orders/payment must have required property '@ondc/org/collected_by_status'"
"/message/orderbook/orders/payment must have required property '@ondc/org/withholding_amount_status'"
"/message/orderbook/orders/2/payment must have required property '@ondc/org/return_window_status'"
"/message/orderbook/orders/2/payment must have required property '@ondc/org/settlement_basis_status'"       
"/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_amount must be number"

Correction flow 

Same as Success flow

@RaviV-Protean

**Comment by RaviV-Protean** [comment]
@RupalSingla  submitted the logs.

https://github.com/ONDC-Official/v1.2.0-logs/pull/2015

pls review.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @RaviV-Protean
