### ISSUE TITLE
BuyNxt (SA : RET10, RET13) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2022]
#### on_search
- support for variants is mandatory 
- category_id used are deprecated, please refer to [sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0)

## Note: Please fix the rest of the issues as provided in [RET14](https://github.com/ONDC-Official/v1.2.0-logs/issues/1827)

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## Flow 1
#### on_search
- How is the timestamp of catalogue being updated? It should be updated whenever there is a change at that level i.e eg: if there is a change at item level then it’s timestamp should update and not at each on_search
- support for variants is mandatory for ret13 as well
- invalid EAN code used in all domains

#### inc_search and inc_on_search
- missing payload for ret13

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## Ret10 
#### on_search
- Please answer the previously asked question.
- Varaints should be made on items and not on categories. Eg: if you want to make variant on namkeen, it should be for the same individual type of namkeen i.e in your case different varaints will be made on corn mixture and namkeen mixture so the varaints dont have same value i.e the unitized.measure of 1. Value defined on variant path should not be same either i.e 1 in your case it should be different for it to be called variant.

#### Please provide an example of each 
- on_search_incremental_provider_disable.json
- on_search_incremental_store_closed.json
- on_search_incremental_store_reopen.json
- on_search_incremental_store_disable.json
- on_search_incremental_catalog.json

## Ret13
- Same as above

**Comment by sahil-ondc** [comment]
## RET10

 
### on_search
- Code should provided in /message/catalog/bpp/providers[0]/items[3]/descriptor/code(836710359284) should be number and with either length 8 or 13
- Variants are not captured properly

## RET13

 
### on_search
- Variants are not captured properly for the given category_ids
- Images are not accessible for the given item_id : ‘24937_12394941’
 
### on_search_inc
- Kindly provide the scenario for item or provider changes in the incremental call

@pranav-buynxt

**Comment by pranav-buynxt** [comment]
We have addressed the recent feedback for RET10 and RET13 as follows:

1. **RET10:**
   - The code `836710359284` has been updated with the correct GTIN-13 for the item.
   - Variants have been updated accordingly. For items with only one variant, no variant group was created, and a `parent_item_id` with an empty string (`"parent_item_id":""`) has been added as suggested.

2. **RET13:**
   - Variants have been corrected for the given category IDs.
   - All images are now updated and accessible.
   - An incremental call for item changes in RET13 has also been provided.

I understand that the standard TAT is 4 days, but given that these are minor updates and we are already live on 1.2 for RET14, I would greatly appreciate it if you could review these logs at your earliest convenience. Approving them quickly will allow us to go live with these categories as well.


![WhatsApp Image 2024-08-18 at 13 36 10_c7b7f5ce](https://github.com/user-attachments/assets/10f9d283-7652-4341-9731-dfa350c29d68)
![WhatsApp Image 2024-08-18 at 13 35 14_794e94df](https://github.com/user-attachments/assets/21df0288-b104-42da-8417-021136335ef2)


@sahil-ondc @sandeepshahi

**Comment by sahil-ondc** [comment]
# RET 13
## Flow 1
### On Search
- category in serviceability construct i.e. Shaving and Grooming’ is not present in one of the category ids in bpp/providers[0]/items/category_id
- Extra serviceability construct provided in the tags

### Search Inc
- ttl = PT30S as per the API Contract

### On Search Inc
- Message id should not be same with previous calls as it's incremental push based call

**Comment by pranav-buynxt** [comment]
are **RET:10** logs approved?

@sahil-ondc

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET 10 and RET 13)

@pranav-buynxt
