### ISSUE TITLE
Futuresoft (SA: RET10) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2058]
#### On_search
There should be at least 2 items linked with the associated variant for it to be called a variant.

#### On_select
quote.breakup.item.tags type item is not required for standalone SKUs.

#### On_init
Only @ondc/org/buyer_app_finder_fee_type, @ondc/org/buyer_app_finder_fee_amount, and @ondc/org/settlement_details are required in the payment object when the buyer is collecting money. Currently, only the buyer is collecting money on the network.

#### On_status
@ondc/org/time_to_ship should be reasonable and calculated so the pickup range is accurate. For example, if time_to_ship is 3 days, but the pickup range is only 2 hours.

#### On_status_rto_delivered
Payload missing (terminal state for on_cancel_rto should be provided).
on_status_rto_delivered is required after on_cancel_RTO where the end.timestamp of RTO fulfillment will be updated.

#### On_status_picked
Invoice not updated after part-cancel.

#### On_update_approval
return_fulfillment.end.time and range are not required in on_update_approval. Please refer to the contract.

@Geeta

**Comment by sahil-ondc** [comment]
## Flow 5
### On Cancel
- cancellation object is not required in the message.order
 
## Flow 6
### On Update Liquidated
- quantity in the forward fulfillment is not reduced for the item_id : ‘gid://shopify/ProductVariant/46069366653183'

**Comment by sahil-ondc** [comment]
## Flow-1
## On_search-
- [categories.descriptor.name](http://categories.descriptor.name/) should be relevant for variants. Eg: if the variant is based on unitized.measure, [descriptor.name](http://descriptor.name/) should not be ‘orange 1’.
- bpp/providers.location.gps - there shouldnt be any space between comma separated longitude and latitude.
- Invalid EAN code for item with id 46069368881407, please check for others.
- invalid item_id format- gid://shopify/ProductVariant/46069366653183. It should be either uuid or 32 characters long - - alphanumeric without any special characters
- @ondc/org/contact_details_consumer_care not captured correctly, please refer to contract

@geeta

**Comment by fsgithub2024** [comment]
> ## Flow-1
> ## On_search-
> * Invalid EAN code for item with id 46069368881407, please check for others.

> **Are you highlighting the item's descriptor code?**


> * invalid item_id format- gid://shopify/ProductVariant/46069366653183. It should be either uuid or 32 characters long - - alphanumeric without any special characters

> **Would like to inform you previous logs has been verified with the above mentioned product id. It is Shopify Id which we are passing.**
> 
> @sahil-ondc

**Comment by shivang1131** [comment]
## Flow 1
### on_Search
- Timing cannot be 0000 to 2359 when store is open from 8 to 5.
- There should be at least 2 items linked with the associated variant for it to be called a variant.

## Flow 2
- Invoice is not accessible for any of the further flows.


@fsgithub2024

**Comment by sandeepshahi** [comment]
Logs approved for RET 10 v1.2 (subject to above fixes)

@fsgithub2024

**Comment by fsgithub2024** [comment]
@sandeepshahi The above issues are fixed. Please share the next step.
