### ISSUE TITLE
NDHGO (SA:RET14) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2068]
### on_search
- invalid key parent_item_id in categories
- bpp/fulfillments has self-pickup but the provider doesnt support self-pickup
- please keep circle.radius between 50 and 500km even if servicability is PAN India
- invalid attribute `@ondc/org/statutory_reqs_prepackaged_food` for `ret14` domain.
- invalid attributes: "net_quantity_or_measure_of_commodity_in_pkg" and "imported_product_country_of_origin" in "@ondc/org/statutory_reqs_packaged_commodities"

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@sahil-ondc 

> invalid key parent_item_id in categories

Can you clarify this please?

> bpp/fulfillments has self-pickup but the provider doesn't support self-pickup

We NDHGO has an MSN BPP we support Delivery and Self-Pickup. That's why we have included it in the `bpp/fulfillments`. But the fulfillment serviceability is different for each providers, right?

> please keep circle.radius between 50 and 500km even if servicability is PAN India

Would the buyer apps consider 500km as PAN Radius serviceability?

**Comment by rajib-senrysa** [comment]
@sahil-ondc Any update on this?

**Comment by bmonish** [comment]
@sahil-ondc Can you please clarify these doubts?

**Comment by sahil-ondc** [comment]
1. parent_item_id should not be provided in categories as per contract. 
2. ACK
3. They can consider, its upto different buyer app logic. 

@bmonish

**Comment by rajib-senrysa** [comment]
@sahil-ondc 

1. I believe you're referring to the `parent_category_id` right?
```
{
  "id": "263",
  "parent_category_id": "",
  "descriptor": {
      "name": "Speaker",
      "short_desc": "Speaker",
      "long_desc": "Speaker",
      "images": [
          "https://ndhcustomerdocumentsbucket.s3.ap-south-1.amazonaws.com/ndh-assets/img/no_image.png"
      ]
  },
  "tags": [
      {
          "list": [
              {
                  "code": "type",
                  "value": "custom_menu"
              }
          ],
          "code": "type"
      },
      {
          "list": [
              {
                  "code": "rank",
                  "value": "4"
              }
          ],
          "code": "display"
      }
  ]
}
```

**Comment by rajib-senrysa** [comment]
@sahil-ondc Kindly clarify!

**Comment by sahil-ondc** [comment]
Hi @rajib-senrysa, 
Yeah i am refering to parent_category_id. 
In custom_group that is mentioned in API contract, but not in variant_group

**Comment by rajib-senrysa** [comment]
@sahil-ondc Kindly check we haven't included the `parent_category_id` in `variant_group`. We have included it only in the `custom_menu`

### Custom Menu
```json
{
  "id": "263",
  "parent_category_id": "",
  "descriptor": {
      "name": "Speaker",
      "short_desc": "Speaker",
      "long_desc": "Speaker",
      "images": [
          "https://ndhcustomerdocumentsbucket.s3.ap-south-1.amazonaws.com/ndh-assets/img/no_image.png"
      ]
  },
  "tags": [
      {
          "list": [
              {
                  "code": "type",
                  "value": "custom_menu"
              }
          ],
          "code": "type"
      },
      {
          "list": [
              {
                  "code": "rank",
                  "value": "4"
              }
          ],
          "code": "display"
      }
  ]
},
```

### Variant Group
```json
{
    "id": "8e79c66c2acf",
    "descriptor": {
        "name": "Apple iPhone 15 Pro Max (256 GB) - Blue Titanium - variant_group"
    },
    "tags": [
        {
            "list": [
                {
                    "code": "type",
                    "value": "variant_group"
                }
            ],
            "code": "type"
        },
        {
            "list": [
                {
                    "code": "name",
                    "value": "item.tags.attribute.colour"
                },
                {
                    "code": "seq",
                    "value": "1"
                }
            ],
            "code": "attr"
        }
    ]
}
```

**Comment by sahil-ondc** [comment]
@rajib-senrysa, Acknowledged.

**Comment by rajib-senrysa** [comment]
@sahil-ondc We have submitted the revised logs. Kindly merge and review.

**Comment by rajib-senrysa** [comment]
@sahil-ondc Any update on this?

**Comment by sahil-ondc** [comment]
### on_search 

- If the fulfillments are not provided in the bpp/providers/fulfillments, It should not be present in the bpp/fulfillments

@rajib-senrysa

**Comment by bmonish** [comment]
We NDHGO has an MSN BPP we support Delivery and Self-Pickup. That's why we have included it in the bpp/fulfillments. But the fulfillment serviceability is different for each providers, right?

So for all the on_search response we include the fulfillment types we support in the `bpp/fulfillments`

Kindly clarify this @sahil-ondc

**Comment by rajib-senrysa** [comment]
@sahil-ondc @BLR-0118 Kindly clarify this!

**Comment by BLR-0118** [comment]
bpp/fulfillments is the superset & bpp/providers.fulfillments is for specific provider;

**Comment by bmonish** [comment]
Thanks for the clarification @BLR-0118.

@sahil-ondc This is what we are doing, `bpp/fulfillments` will be the superset of the fulfillments we support, and `bpp/providers.fulfillments` is specific to the provider.

Please check and let us know if there are any other issues with the logs.

**Comment by bmonish** [comment]
@sahil-ondc @BLR-0118 @sandeepshahi If there aren't any other issues, can you kindly please approve the logs and close this issue. Thanks!

**Comment by bmonish** [comment]
@sahil-ondc @BLR-0118 @sandeepshahi Kindly please check and approve the logs.

**Comment by bmonish** [comment]
@sandeepshahi @BLR-0118 If there are no issues, kindly please approve the logs. Thanks!
