### ISSUE TITLE
Ninja cart AGRI (IGM) - complaince check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2072]
Flow 1 : IGM for deliverd state 
Unneccesary calls like select /on_select /confirm are present in the folder please remove them.
Pls check the payload for igm with the IGM utility that is currently live 
https://github.com/ONDC-Official/log-validation-utility - link for utilty (will tell about schema error , attribute error .
Flow 2 : 
Unneccesary calls like select /on_select /confirm are present in the folder please remove them.

@RaunakGandhi

**Comment by RaunakGandhi** [comment]
Please check [updated PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/2069), have removed the unneccesary calls , and validated the logs as well through log-validation-utility.
@RupalSingla

**Comment by RupalSingla** [comment]
no need to provide resolution.action ..
Logs cleared 1.0.0 @RaunakGandhi
