### ISSUE TITLE
Xpressbazaar (SA: RET1A) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2162]
### on_search (full catalog)

- timestamp provided for items can't be greater than context.timestamp
- store enable/disable timestamp (/bpp/providers/time/timestamp) should be less then or equal to context.timestamp
- timestamp provided in locations cannot be greater than context.timestamp
- area_code provided in /message/catalog/bpp/providers/locations/street cannot be different as compare to /message/catalog/bpp/providers/locations/area_code
- area_code should be provided as per provided gps
- category_id provided in /message/catalog/bpp/providers/items should not have empty spaces
- provided attributes should be valid attribute as per sheet
  `https://docs.google.com/spreadsheets/d/1zmZDOoP0P9p9icEuYjs8m5lfuubib6Qx/edit?gid=1181161273#gid=1181161273`

@shouryaEns

**Comment by yogita888** [comment]
@sahil-ondc  , please review the PR https://github.com/ONDC-Official/v1.2.0-logs/pull/2165,
logs as per feedback for ONDC:RET1A

**Comment by sahil-ondc** [comment]
@yogita888, All issues must be rectified before log submission. 

There are still some open points
- provided attributes should be valid attribute as per sheet
`https://docs.google.com/spreadsheets/d/1zmZDOoP0P9p9icEuYjs8m5lfuubib6Qx/edit?gid=1181161273#gid=1181161273`

**Comment by sandeepshahi** [comment]
**/on_search (inc)**
- message_id should be unique for unsolicited call
- unicode literals should be avoided in the payload; eg: \"

@yogita888

**Comment by yogita888** [comment]
@sandeepshahi  sir , logs as per the feedback for ONDC:RET1A , please review and merge
https://github.com/ONDC-Official/v1.2.0-logs/pull/2214

**Comment by sandeepshahi** [comment]
**/on_search**

- entire address should not be provided in /locations/address/street; other attributes must be utilized for the same

**/on_search (inc)**

- time/timestamp in /items should be in valid RFC3339 UTC format


@yogita888

**Comment by yogita888** [comment]
@sandeepshahi  Sir , Logs as per the feedback please review the PR 
https://github.com/ONDC-Official/v1.2.0-logs/pull/2237
