### ISSUE TITLE
Digiit - LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2169]
Multiple issues identified, kindly use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self verify the logs and resubmit. Also, test with a verified LBNP in preprod environment.

@vignesh-arvind

**Comment by vignesh-arvind** [comment]
Hi @abhinavv245 

this link shows Logistics for B2B ?? could you pls confirm

**Comment by abhinavv245** [comment]
It is for b2c logistics and b2b retail both. Please go through the
readme.md file for more details.

**Comment by vignesh-arvind** [comment]
@abhinavv245  Thanks

**Comment by abhinavv245** [comment]
- Kindly test with a verified LBNP in pre prod environment

## Delivery Flow

**/search**

- ON-ORDER is currently not enabled on network, please use POST-FULFILLMENT

**/on_search**

- is OTP based authorization supported by LSP

**/init**

- how is buyer app providing seller app's settlement details in /payments

**/confirm**

- in fulfillments/start/instructions, for code 4, OTP to be sent via authorization object in /update API

**/on_update**

- 'Packed' is not a valid fulfillment state used by LSP

**/on_status**

- url is not required when url based tracking is marked as 'no' in fulfillments/tags (tracking)

## RTO Flow

- similar issues 

**/on_cancel**

- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Cancelled
- in RTO fulfillment, start and end location to be added

## TAT Breach

- similar issues 

**/on_cancel**

- on_cancel/0/message/order must have required property 'created_at'
- quote should reflect the updated value of logistics order (is LSP charging full delivery fee)

@vignesh-arvind

**Comment by BLR-0118** [comment]
flow 1
====
1. /on_search:
- separate fulfillments should be created for each category (Immediate Delivery / Same Day Delivery) as the estimate pickup time could be different;
- static terms should point to GitHub location (as specified in contract);
2. /on_init:
- static terms location shown here is different from /on_search;
3. /on_confirm:
- Context.timestamp is 10:06:45 & estimate pickup time is 20min; with ready_to_ship = "yes", how's the pickup slot showing 15:46:45-16:16:45? shouldn't this be 10:26:45-10:56:45 instead?

flow 2
====
1. /on_status_rto_disposed:
- fulfillment.end.time.timestamp reqd for RTO fulfillment;

flow 3
====
- not sure how this is different from flow 1?

- also, log for deferred RTS (i.e. not in /confirm) is missing;

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
