### ISSUE TITLE
Sellersetu (SA : RET10,12,13,14,15,18) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2199]
---
### on_search
- `@ondc/org/time_to_ship` & `@ondc/org/return_window` cannot be `P0D`.
---
### on_search_inc
- There is no difference at any level except timestamp.
—
### on-search
- GTIN code should be valid. Eg: 194252656740 is invalid. please validate it on https://www.gs1india.org/gtin-validation/

### on_search_inc
- timestamp should be updated at the time of change in item.
—--
### on-search
- GTIN code should be valid. Eg: 8801643708540 is invalid. please validate it on https://www.gs1india.org/gtin-validation/

### on_search_inc
- How is `items.time.timestamp` future dated when compared with `context.timestamp`?
---
### on_search && on_search_inc
- `@ondc/org/time_to_ship` cannot be `P0D`.
- circle.gps can’t be ‘,’.
---

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
@Jagannath-wits Please review.

**Comment by Jagannath-wits** [comment]
---

## Ret10
### `on_search`
- Only "@ondc/org/statutory_reqs_packaged_commodities" is required for `category_id` ‘Oil & Ghee’.
- Is `time_to_ship` the same for all domains? i.e., 15 minutes.

---

## Ret14
### `on_search`
- Variants not captured properly. Items with `variant_id` 0644650988327 have the same number of units in each item; also, variants in electronics are usually based on item specs such as RAM, Storage, etc.
- The variant `e0350180-84b6-4168-9b93-fde05ee54d07` is not used anywhere.

---

## Ret15
- Multiple variants not used in the catalog.

---

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
> Is time_to_ship the same for all domains? i.e., 15 minutes.

**Comment by sellersetu-hub** [comment]
@Jagannath-wits What does this mean "Multiple variants not used in the catalog."  . Do we have to add products with multiple variants of different attributes ?

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits What does this mean "Multiple variants not used in the catalog." . Do we have to add products with multiple variants of different attributes ?

@sellersetu-hub If a variant has been declared then it should be associated with atleast 2 items, in the above scenario 3 variants were declared but only one was used.

**Comment by sellersetu-hub** [comment]
@Jagannath-wits  There's no variant with id `0644650988327` in our payload.

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits There's no variant with id `0644650988327` in our payload. Though Point 2 `The variant e0350180-84b6-4168-9b93-fde05ee54d07 is not used anywhere` is correct, will fix this.

- items associated with variant id b5e83345-4d59-45ad-b72c-ec688b0fcc5b both have same unitized.measure 
- e0350180-84b6-4168-9b93-fde05ee54d07 is not used anywhere

Updating the same above

**Comment by Chaitanya-Keyal** [comment]
@Jagannath-wits Raised PR #2252
Please review

**Comment by sellersetu-hub** [comment]
@Jagannath-wits PR is merged. Please review

**Comment by sellersetu-hub** [comment]
@Jagannath-wits @sandeepshahi awaiting reviews here

**Comment by sahil-ondc** [comment]
# RET 10
 
## Flow 1
### On Search
- gps doesn’t match with the given area_code
- descriptor/code is not provided for the item_id : ‘f73bb596-affe-4692-847a-c30a1cdc4bc1’
- back_image is invalid and doesn’t  have the info for ‘@ondc/org/statutory_reqs_prepackaged_food’ for the item_id ‘ce2fc33f-0e88-4856-8eb9-2f79244c39cf’, ‘3a298610-53d5-4aa8-b9ee-bde571f8b9c8’
 
### Search Inc
- ‘req_path’ is invalid attribute provided in context
 
# RET 12
 
## Flow 1
### On Search
- variants are not captured properly for the given category_id : ‘af58a6e3-7d31-4f10-aded-ecf5fdab0905’
- gps doesn’t match with the given area_code
 
### Search Inc
- ‘req_path’ is invalid attribute provided in context
 
 
# RET 13
 
## Flow 1
### On Search
- gps doesn’t match with the given area_code
- variants are not captured properly for the given category_id : ’11789550-5bdb-47f6-83dd-bb89572cb387’
 
### Search Inc
- ‘req_path’ is invalid attribute provided in context
 
 
# RET 18
 
## Flow 1
### On Search
- gps doesn’t match with the given area_code
 
### Search Inc
- ‘req_path’ is invalid attribute provided in context
 
### On Search Inc
- No incremental changes are observed for the given item_id: ‘12f31b5a-9042-414e-a829-dd48f4ca55d1’

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
@sahil-ondc 

> gps doesn’t match with the given area_code

This matches,

**Comment by sahil-ondc** [comment]
## RET 14

 
### search (increment)
- ‘req_path’ is invalid attribute provided in context
 
 
## RET 15

### on_search (full catalog)
- gps doesn’t match with the given area_code
 
### search (increment)
- ‘req_path’ is invalid attribute provided in context

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
@sahil-ondc We have corrected logs and raised PR

**Comment by sahil-ondc** [comment]
## RET 10, 12, 14, 15
### On Search 
- gps doesn’t match with the given area_code

## RET 13
### On Search
- gps doesn’t match with the given area_code
- How time_to_ship can be 0 days ? 

## RET 18
### On Search
- gps doesn’t match with the given area_code
- How time_to_ship can be 0 days ? 
- Why the fields have been left empty in the ‘@ondc/org/statutory_reqs_packaged_commodities’  ?

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
hi @sahil-ondc , RET18 and RET13 issues were identified and fixed by team on 25th and are raised in this PR, https://github.com/ONDC-Official/v1.2.0-logs/pull/2303 ,

**Comment by sellersetu-hub** [comment]
Also @sahil-ondc , I am able to match area code and gps from reverse geocoding, 
![image](https://github.com/user-attachments/assets/a3aaf283-2da6-4cff-bba5-7875ee159ec3)

**Comment by sellersetu-hub** [comment]
@sahil-ondc Changes have been merged please review.

**Comment by sellersetu-hub** [comment]
Hi @sahil-ondc @sandeepshahi  Awaiting revert here

**Comment by sellersetu-hub** [comment]
@sahil-ondc @sandeepshahi  Please review.

**Comment by shivang1131** [comment]
## RET 13
### on-search
- EAN code cannot be same for multiple items. Refrain from passing placeholder values.

### inc on_search
- What changed here for the item that you are sending in the incremental refresh?

## RET 18
### on-search
- EAN code cannot be same for multiple items. Refrain from passing placeholder values.
- Prescription based medicines are not yet supported on the network.

**Comment by shivang1131** [comment]
@sellersetu-hub

**Comment by Chaitanya-Keyal** [comment]
@shivang1131 
> EAN code cannot be same for multiple items. Refrain from passing placeholder values.

The codes are same only for variants, variants aren't supposed to have different EAN codes right?

**Comment by shivang1131** [comment]
No issues for this case then
@Chaitanya-Keyal

**Comment by sandeepshahi** [comment]
@sellersetu-hub, please ensure the category_id is followed as per the updated [taxonomy sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0)

**Comment by sandeepshahi** [comment]
Logs approved for SA v1.2 (RET 10, 12, 13, 14, 15 and 18)

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
> @sellersetu-hub, please ensure the category_id is followed as per the updated [taxonomy sheet](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0)
