### ISSUE TITLE
ShopEG ( SA: RET16,18 ) - compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2207]
### On_search_full_catalog
- Timing object with type ‘All' should be used if timing is the same for both delivery and order.
- Variants not captured properly; both items with variant path have the same values.
- Instead of "see package" you can use "refer to back image" in month_year_of_manufacture_packing_import and provide back_image in tags.
- ## ret18
### On_search
- `categories.id` is the same in both ret16 and ret18. Variants should be made around individual items to avoid confusion.
- `manufacturer_or_packer_name` and `manufacturer_or_packer_address` should not be the same.

### on_search_inc
- Escape characters should not be used, e.g., `\n`.
@VijaiCPrasad @ShopEG

**Comment by VijaiCPrasad** [comment]
@Jagannath-wits Thanks for your feedback. We are fixing the issues reported but have a question regarding the variant groups.

> categories.id is the same in both ret16 and ret18. Variants should be made around individual items to avoid confusion.
Can you please clarify what's wrong in categories.id? The ids are unique across both domains in the logs. RET16 has category id - vg6 and RET18 has vg7, vg8. 

cc @sandeepshahi @BLR-0118

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0;
