### ISSUE TITLE
Adloggs - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2246]
**/search**

- intent/provider/time must have required property 'schedule'",
- intent/provider/time must have required property 'range'",
- context/city code should match city for fulfillment start location;

**/init**

- fulfillments/start and end /contact/email should not be same

**/confirm**

- order/id should be alphanumeric, up to 32 characters
- why is order/id same as @ondc/org/linked_order/order/id
- why is linked Order ID equal to logistics order Id: \"ce07af02-a463-489a-bb66-59e694f109ebAd0\
- whose bpp_terms are being accepted here (bpp did not send any in on_init)

**/on_status**

- message/order must NOT have additional properties (tags)(tracking tag should be provided in fulfillments/tags)

@vignesh11111

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0

**Comment by vignesh11111** [comment]
Thanks @BLR-0118 @abhinavv245
