### ISSUE TITLE
wits-adapter (IGM) - compliance check 

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#226]
Flow 2 - Complaint raised on a fulfillment is missing 

@SinghSukhchain25

**Comment by SinghSukhchain25** [comment]
@RupalSingla Can you please share the document from where i can find the Flow 2

**Comment by Rishabh-ondc** [comment]
Flow 1
on_issue_status
- respondent_actions.updated_at has changed between on_issue and on_issue_status
- issue.updated_at and created_at is same

on_issue_status
- respondent_actions.updated_at is the same for processing and resolved actions
- chat_link may not be shared if no link is available (avoid placeholder values)

Clarifications
- Please include log for issue close call as well

@SinghSukhchain25

**Comment by Rishabh-ondc** [comment]
on_issue
- respondent_actions.long_desc is an incorrect attribute

on_issue_status
- issue.updated_at changed between on_issue and on_issue_status

on_issue_status unsolicited
- context.message_id same as issue API's context.message_id

@SinghSukhchain25

**Comment by Rishabh-ondc** [comment]
onIssueStatus
- context.message_id has changed, please check

onIssueStatusUnsolicited
- respondent_info.organization.org.name has a different subscriber_id than context, please check
- refund_amount should be string type
- resolution.additional_desc is incorrect attribute

Clarifications
- There is a difference between bpp_id and bpp_uri, please check.

@SinghSukhchain25

**Comment by Rishabh-ondc** [comment]
Logs cleared

@SinghSukhchain25
