### ISSUE TITLE
Easypay (BA:RET14, 15, 16) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2267]
### on_search
- Variants are not captured properly for the given categories_id ‘4f32ae48’
- ‘height’, ‘length’, ‘breadth’ and ‘height’ is not required for the category_id: ‘Earphone’
- ‘connectivity’ is not required for the category_id : ‘Smart Watch’
 
### on_search_inc
- No Incremental changes are observed for the following item_id : ‘5906FA4ED40B395EFA5A5D77F72864A7_44241139794179_default‘

@Jigisha

**Comment by sahil-ondc** [comment]
## Flow 1
 
### On Search
- Variants are not captured properly for the given categories_id ‘4f32ae48’
- ‘height’, ‘length’, ‘breadth’ and ‘height’ is not required for the category_id: ‘Earphone’
- ‘connectivity’ is not required for the category_id : ‘Smart Watch’
 
### On Search Inc
- No Incremental changes are observed for the following item_id : ‘5906FA4ED40B395EFA5A5D77F72864A7_44241139794179_default‘

@jigisha

**Comment by Jagannath-wits** [comment]
# Easy Pay (Buyer App) 
## RET14 Flow 1

### **on_search_full_catalog_refresh**

- `"schemaErr0"`: `/message/catalog/bpp~1providers/0/categories/0/id` must match pattern `^[a-zA-Z0-9-]{1,12}$`
- `"schemaErr1"`: `/message/catalog/bpp~1providers/0/categories/1/id` must match pattern `^[a-zA-Z0-9-]{1,12}$`
- `"missingTagsItem[0][2] : special_feature"`: Mandatory tag field `[special_feature]` missing for Electronics item[2]
- `"InvldValueforItem[0][3] : colour_name"`: Invalid item value: `[#1B1404]`. It must be one of the allowed values or match the regex pattern `^[a-z ]+$`
- `"missingTagsItem[0][3] : special_feature"`: Mandatory tag field `[special_feature]` missing for Electronics item[3]
- `"bpp/providers[0]/items[0]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[0]/descriptor/code`
- `"bpp/providers[0]/items[1]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[1]/descriptor/code`
- `"bpp/providers[0]/items[2]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[2]/descriptor/code`
- `"bpp/providers[0]/items[3]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[3]/descriptor/code`
- `Id-sku-SKU-KWPCZCDJC/tags/attribute`: `colour_name` cannot be `#1B1404`

## RET15 Flow 1

### **on_search_full_catalog_refresh**

- `"schemaErr0"`: `/message/catalog/bpp~1providers/0/categories/0/id` must match pattern `^[a-zA-Z0-9-]{1,12}$`
- `"missingTagsItem[0][0] : type"`: Mandatory tag field `[type]` missing for Appliances item[0]
- `"InvldValueforItem[0][1] : colour_name"`: Invalid item value: `[#283A77]`. It must be one of the allowed values or match the regex pattern `^[a-z ]+$`
- `"missingTagsItem[0][1] : type"`: Mandatory tag field `[type]` missing for Appliances item[1]
- `"bpp/providers[0]/items[0]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[0]/descriptor/code`
- `"bpp/providers[0]/items[1]/descriptor/code"`: `code` should have `3:GTIN` as a value in `/message/catalog/bpp/providers[0]/items[1]/descriptor/code`

### **on_search_inc_refresh**

- `"missingTagsItem[0][0] : type"`: Mandatory tag field `[type]` missing for Appliances item[0]
- `"InvldValueforItem[0][1] : colour_name"`: Invalid item value: `[#283A77]`. It must be one of the allowed values or match the regex pattern `^[a-z ]+$`
- `"missingTagsItem[0][1] : type"`: Mandatory tag field `[type]` missing for Appliances item[1]

## RET16 Flow 1

### **on_search_full_catalog_refresh**

- `"schemaErr0"`: `/message/catalog/bpp~1providers/0/categories/0/id` must match pattern `^[a-zA-Z0-9-]{1,12}$`
- `"bpp/providers[0]/items[0]/descriptor/code"`: `code` should have `1:EAN` as a value in `/message/catalog/bpp/providers[0]/items[0]/descriptor/code` (Check Digit)
- `"bpp/providers[0]/items[1]/descriptor/code"`: `code` should have `1:EAN` as a value in `/message/catalog/bpp/providers[0]/items[1]/descriptor/code` (Check Digit)
- `ID- sku-SKU-1GLACDZDAZ/tags/attribute`: `colour_name` cannot be `#B2A1EA`

@ep-aws Buyer app should have validations for these and issue proper NACKs accordingly

**Comment by sandeepshahi** [comment]
Logs approved for RET 14, 15 and 16 (v1.2)

@ep-aws
