### ISSUE TITLE
Sabhyasha (SA:RET12) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2278]
#### on_search
- hex code and colour_name dont match eg: #FFFFFF: ABBEY.
- variants declared but not used anywhere.
- variants in Fashion are usually made on attributes like colour, size, etc and not just unitized.measure.
@Pratik-ZenithDjangoDev

**Comment by Jagannath-wits** [comment]
#Sabhyasha RET12
## Flow 1 
#### on_search
- item.attributes seems to be same for most of the items.
- colour_name and product colour in images do not match.eg: most items have colour name abbey but it doesnt match with item image.
- size chart provided is not applicable for the provided products.
- parent_item_id is not required if variant is not applicable in a item.
- tags.timing object with type order time_from and time_to should match with locations.time.range

@Pratik-ZenithDjangoDev

**Comment by shivang1131** [comment]
## Flow1
### on_search
- Unicode literals are not allowed in description.
- HSN codes are not mapped correctly (5007)
- item.tags.attribute.color path is an incorrect path
- Refrain from sending placeholder values in attributes.

**Comment by shivang1131** [comment]
## Flow1
### on_search
- Unicode literals are not allowed in description.
- HSN code is not mapped correctly
- item.tags.attribute.color path is an incorrect path
- Refrain from sending placeholder values in attributes.

**Comment by Pratik-ZenithDjangoDev** [comment]
I have made the necessary corrections for the following points:

**Unicode literals are not allowed in description:** This issue has been resolved by ensuring no Unicode literals are present in the description field.
**item.tags.attribute.color path is an incorrect path:** The incorrect path has been fixed, and now the correct attribute path for colour is being used.

However, I need clarification on the following two points:

**HSN Code is not mapped correctly:**
We are pulling the HSN code directly from the government database. Could you please clarify how we should validate the data entered by the seller? Is there a specific process or percentage threshold of ONDC that we need to follow to ensure that the HSN code provided by the seller is accurate?

**Refrain from sending placeholder values in attributes:**
Could you provide more details about this ?

@shivang1131

**Comment by shivang1131** [comment]
Hi Pratik,
**HSN Code is not mapped correctly**

Check for item "Boita Bandana Pattachitra Bomkai Patta Saree". This item has a HSN code of 5007. 5007 stands for Woven Fabrics Of Silk Or Of Silk Waste. However, this item has attirbute.fabric as cotton. This could also be a attribute mapping issue. Please fix this on your end.

**Refrain from sending placeholder values in attributes**

Sarees are passed in as free size. Is the size chart sent applicable here?

@Pratik-ZenithDjangoDev

**Comment by Pratik-ZenithDjangoDev** [comment]
Hi @shivang1131 ,
Thank you for the detailed feedback.
**HSN Code Mapping:** I have analyzed the issue regarding the HSN code. However, if a seller selects the wrong HSN code for his product, how can we map and validate it accurately? Since we are pulling this data from the government side, could you please clarify the validation process for seller-entered data? Is there a specific procedure or percentage threshold defined by ONDC that we should follow to ensure the HSN code provided by the seller aligns with the correct product attributes?

**Size Chart for Sarees:** To confirm, if a seller lists a saree as "free size," there is no need to send the size chart—correct? The current logs utility validation does not allow us to submit fashion catalog items for saree categories with an empty size chart. Could you please confirm if an exception should be made in this case for free-size sarees, or is there another approach we should consider?

**Comment by shivang1131** [comment]
Hi @Pratik-ZenithDjangoDev,
1. There is no specific validation process defined by ONDC to ensure proper HSN mapping. You need to ensure this on your end that the codes are valid and not mapped to incorrect attributes. 

2. As sarees are free size and no size chart is associated, send in a url which redirects to a page stating the same. No need to pass in an actual size chart in this case.

**Comment by Pratik-ZenithDjangoDev** [comment]
Hi @shivang1131 ,

As you pointed out, most of the issues were related to the product details, which we have now fixed. We've also corrected the spelling error from **item.tags.attribute.color** to **item.tags.attribute.colour**.
Could you please confirm if there are any other issues you haven't mentioned yet? If not, shall we go ahead and resubmit the logs today?

**Comment by shivang1131** [comment]
Hi @Pratik-ZenithDjangoDev ,
No other issues, you can resubmit the logs.

**Comment by Pratik-ZenithDjangoDev** [comment]
Thank you @shivang1131 for your response .

**Comment by shivang1131** [comment]
Hi @Pratik-ZenithDjangoDev,

This works.

**Comment by Pratik-ZenithDjangoDev** [comment]
Hi @shivang1131 , we have resubmitted the logs as per your feedbacks any updates?

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET 12)

@Pratik-ZenithDjangoDev
