### ISSUE TITLE
Udyamwell (SA:RET16) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2301]
# Udyamwell
### on_search
- invalid ean code used. eg:7812312354342
- long desc and short desc should not be same
- month_year_of_manufacture_packing_import should only contain date and not time 
- catalog should have alteast 5 items 
- variants should be implemented
- bpp/providers.location.time.range should match with the time range provided in tags.timings object with type order.
- colour_name should be in lowercase
- is time_to_ship should be realistic as it’s not always possible to ship every item in 20 minutes.

@udyamwell1

**Comment by udyamwell1** [comment]
Dear @Jagannath-wits ,
We have worked on the feedback provided by you. Please review the updated logs:
https://github.com/ONDC-Official/v1.2.0-logs/pull/2388

thanks!

**Comment by sandeepshahi** [comment]
**/on_search**
- timestamps at different levels are not captured correctly
  - isn't context/timestamp precise upto milliseconds value?
  - timestamp at provider and location levels have similar milliseconds value as in context/timestamp

**/on_search (inc)**
- timestamp at item level can't be of 1 month older; real time changes should be pushed as part of incremental updates


@udyamwell1

**Comment by udyamwell1** [comment]
Dear @sandeepshahi , 
Thanks for the review. We have found these issue and resolved it. 
Please approve the logs, so that we can proceed accordingly. 

Thanks!

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET16)

@udyamwell1
