### ISSUE TITLE
Sellersetu (BA:RET16) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2328]
### Please use a different seller apart from Sellersetu to check interoperability.

---

### On_search

- `categories.id` should be alphanumeric, up to 12 characters.
- Invalid EAN code `0847321008725` provided for armchairs.

---

### Queries:

1. **Is push-based incremental refresh supported?**
   
2. **Are you using the timestamp at the provider/item level for correct versioning while processing the catalogs (full/incremental) concurrently?**
   
3. **Is `/select` being called for every change in the cart, with the same `transaction_id`?**
   
4. **While processing unsolicited callbacks, are you ensuring that each such callback response has a unique `message_id` for a specific `transaction_id`?**
   
5. **Is the retry mechanism enabled for the `confirm/on_confirm` flow as mentioned in the documentation?**
   
6. **Are the cancellation reason codes received from SNP being validated?**

@Chaitanya-Keyal

**Comment by sellersetu-hub** [comment]
> Please use a different seller apart from Sellersetu to check interoperability.

**Comment by sellersetu-hub** [comment]
@Jagannath-wits  ref buyer app doesn't sent unsolicited call, do you know any selleerapp with whom we can test.

**Comment by turingAlan** [comment]
@Jagannath-wits answering your queries. Yes, we support the following:

1. **Push-based incremental refresh** is supported.
2. **Timestamp-based versioning** is implemented at the provider/item level to correctly process catalogs (full/incremental) concurrently.
3. **/select endpoint** is called for every change in the cart, with the same `transaction_id`.
4. While processing unsolicited callbacks, we ensure that each callback response has a unique `message_id` for a specific `transaction_id`.
5. The **retry mechanism** for the confirm/on_confirm flow is enabled as per the documentation.
6. **Cancellation reason codes** received from SNP are validated.

**Note:** Since we are building on top of the reference buyer app, the entire log verification process will be easier to manage.

**Comment by aagmanbhatt** [comment]
hey,
@Jagannath-wits Can we get review here,

**Comment by FarheenNazQA** [comment]
## Flow-1

### Search
- Static terms are not enabled yet and hence not required.(message/intent/tags[bap_terms])`

### On_Search
- Return window shouldn't be zero, as the item is returnable. (It also serves an igm window.)
- Categories should be present.

### On_Search_inc
- There should be some delta change in Increment apart from the timestamp.

## Flow-2

### On_confirm 
- Time to ship should be within the `fulfilment.start.range`.

### On_status_packed
- Tracking object is missing for `tracking-true`.
- Pickup time range should match with the time to ship.

### On_status_picked
- Invoice should be publicly accessible.

## Flow-5

### On_cancel_rto
- In on_cancel_rto, RTO `fulfillment.end.time` should not be present. (End timestamp is provided in `on_status_rto_delivered` or disposed, and not before that for RTO fulfillment.)

@Chaitanya-Keyal

**Comment by sellersetu-hub** [comment]
@FarheenNazQA @Jagannath-wits Issues mentioned here, are in api from bpp, we also attached pramaan report with this, you can check those too.

**Comment by Jagannath-wits** [comment]
> @FarheenNazQA @Jagannath-wits Issues mentioned here, are in api from bpp, we also attached pramaan report with this, you can check those too.

Please Check issues and validations from buyer end i.e :
1.  Static terms are not enabled yet and hence not required.(message/intent/tags[bap_terms])`
2. Tracking object is missing for tracking-true.
3. In on_cancel_rto, RTO fulfillment.end.time should not be present. (End timestamp is provided in on_status_rto_delivered or disposed, and not before that for RTO fulfillment.)

@sellersetu-hub 
Buyerapp should nack for above conditions

**Comment by sellersetu-hub** [comment]
@Jagannath-wits

**Comment by Jagannath-wits** [comment]
## @sellersetu-hub Please share a link of demo video on the issue board and answer the following questions :

- while processing concurrent catalog updates (full, incremental), are the timestamps at provider / item level being used for correct versioning?
- is /select being called for every change in cart, with the same transaction_id?
- while processing unsolicited callbacks, are you ensuring that each such callback response has a unique message_id for a specific transaction_id?
- is the /confirm & /on_confirm process flow enabled as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wthdzrq1m4ng)?
- is the proper validation of cancellation reason codes in place when initiated by SNP?
- are hyperlocal vs intercity fulfillment states processed using routing.type of "P2P" or "P2H2P";

**Comment by sellersetu-hub** [comment]
@Jagannath-wits here's the product demo [link](https://drive.google.com/drive/folders/1jpCiNNpkPOg2qibFg2KIjedzS9-BfyUV?usp=sharing), 



> - while processing concurrent catalog updates (full, incremental), are the timestamps at provider / item level being used for correct versioning?

- Yes

> is /select being called for every change in cart, with the same transaction_id?

- Yes

> while processing unsolicited callbacks, are you ensuring that each such callback response has a unique message_id for a specific transaction_id?


- Yes


> is the /confirm & /on_confirm process flow enabled as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wthdzrq1m4ng)?


- Yes


> is the proper validation of cancellation reason codes in place when initiated by SNP?

- Yes


> are hyperlocal vs intercity fulfillment states processed using routing.type of "P2P" or "P2H2P";

- Yes

**Comment by shivang1131** [comment]
flow 4:
Number of items are 1 but the quantity is 2 but your interface shows items as 1. It is a little misleading

flow 5:
Just shows order cancelled by the seller. Does not show reason or anything.

flow 6:
Number of items being shown was incorrect.
Number of items in this case were incorrect which were being shown as 4. 

@sellersetu-hub

**Comment by sellersetu-hub** [comment]
@shivang1131 

> Number of items are 1 but the quantity is 2 but your interface shows items as 1. It is a little misleading

This is whatsapp business catalog interface it shows all item quantity counts
for flow 5 and 6 , fixing and sending new product demo

**Comment by sandeepshahi** [comment]
Logs approved for BA v1.2 (RET 16)

@sellersetu-hub
