### ISSUE TITLE
Mystore (SA: RET11) - compliance check

### ISSUE THREAD

**Issue by shivang1131** [ONDC-Official/v1.2.0-logs#2332]
Please fix the issues pointed out by the validation utility.

@dharkum24

**Comment by asifrazastorehippo** [comment]
@sandeepshahi 
1- As discussed over the call for changing the category_ids to 12 alphanumeric characters we would need to change our architecture which would be challenging for us, currently we are sending 24 alphanumeric characters (MongoId).
2- Item id (66b0732fcb5d37002417ccd7) is a standalone item and doesn't have any custom menu so no category_ids 
3- The lower and upper range are optional as per the contract
4- default we are sending for customizable items
5- Extra attribute Quantity issue - In a breakup, it is going so it might be log validity is pointing out the wrong 


There are no issues from our side as we have submitted log utility as well for all flows only challenging part is point -1 #12 character, we need your support on this
cc: @BLR-0118

**Comment by shivang1131** [comment]
# RET 11

TAT for F&B domain should not be 1 day.
time_to_ship should always be less than TAT and it being 59 minutes with TAT being 1 day is not feasible
@ondc/org/category should be "Immediate delivery" instead of "Standard delivery".

## FLOW 1
### on-search 
- Invalid attribute code. Placeholder values should not be provided.
- tax_number and provider_tax_number are incorrect in tags/bpp_terms and whose provider tax number is embedded here?
- close_timing in tags cant be future dated. 
- The timestamp provided in location is greater than that of context.timestamp.
- You also need to pass in default_selection price. This price is the price of the item after applying the default customizations. 
- No need to pass in paragraph tags in short desc and long desc.
- "category_ids": ["66b30e7a4091:1"]. Two items have the same display number in the custom menu of category breakfast.
- No need to pass config in 66b071dfcb5d37002417c2ac. It is only passed when we need to override default configs of the customization group.
- Flow is incorrect to make a customizable item. Please refer to the contract.
- Both customization groups have seq as one when they have been put with the same.
- fssai number is at the provider level and not at item level.

## Flow 2

"ttl": "P1DT0H0M0S" Not the ideal way to send  a timestamp value.
### on-select
- The maximum attribute of customizations change in on-select as compared to on-search.
- No need to send state.descriptor.name in fulfillments.

### on-status order-delivered
- end.timestamp is captured incorrectly.


## Flow 3
### on-select
- Item-id "66b071dfcb5d37002417c2ac" maximum value changes from "99" to "3". When an item is out of stock or partially out of stock, item.available.count cannot be "99".

### on_status out for delivery
- @ondc/org/buyer_app_finder_fee_amount does not match that sent in search request and previous apis.

### on-status order-delivered
- end.timestamp is captured incorrectly.

## Flow 5
### on-cancel
- start.timestamp in the forward fulfillment should be there and the same as on-status order_picked.

### on_status
- rto_id does not match the id of the RTO fulfillment.

- time.range would not be sent in RTO-shipment for both start and end.

- start.timestamp in the forward fulfillment should be there and the same as on-status order_picked.


## Flow 6
Please resend this flow with a cancelled customizable item and a liquidated item.
time_to_ship cannot be 59 minutes with TAT as 1 hour.
### on-select
- P0DT1H0M0S. This is not the ideal way to send timestamp.
### on-confirm
- TAT is 1 hour but end.range is 1 day from start.range

### update
Return fulfillment incorrectly mapped with cancelled item.

**Comment by dharkum24** [comment]
@sandeepshahi @shivang1131 Logs resubmitted as per complaince https://github.com/ONDC-Official/v1.2.0-logs/pull/2373 cc:- @asifrazastorehippo

**Comment by asifrazastorehippo** [comment]
@sandeepshahi as per the discussion added a nested part as well on on_search, please check

**Comment by dharkum24** [comment]
@sandeepshahi @shivang1131 RET11 catalog PR submitted Please review https://github.com/ONDC-Official/v1.2.0-logs/pull/2431

**Comment by shivang1131** [comment]
### Flow 1
## on_search
- Both customization groups have seq as one when they have been put with the same.
- Child customizations have seq as 1.
- Number of defaults greater than the max config of custom group.

@asifrazastorehippo

**Comment by asifrazastorehippo** [comment]
@shivang1131 Fixed 1st and 3rd point.
Could you please explain 2nd point @shivang1131 @sandeepshahi

**Comment by dharkum24** [comment]
@shivang1131 Submitted other FLOWS as per our discussion PR is https://github.com/ONDC-Official/v1.2.0-logs/pull/2512 cc:- @sandeepshahi @asifrazastorehippo

**Comment by asifrazastorehippo** [comment]
@sandeepshahi @shivang1131  please merge PR and validate - [2665](https://github.com/ONDC-Official/v1.2.0-logs/pull/2665)

**Comment by asifrazastorehippo** [comment]
@sandeepshahi @shivang1131 any update?

**Comment by shivang1131** [comment]
## FLOW 2
### on_select
- Fulfillments/@ondc/org/category would be “Immediate Delivery” for F&B domain.
- Quote.breakup."@ondc/org/item_quantity”.count cannot be 3 with item.maximum.count being “1”.

### on_confirm
- No need to send on_status pending if order gets accepted in on_confirm.
- Fulfillments.end.time.range is incorrect. 

### on_status
- fulfillments.descriptor.name is not required in any on_status
- Gps enabled tracking is mandatory.

## Flow 3
- Items like ‘66e4019761db710024a71079’ have quote.breakup.item.quantity.available.count as zero in the on_select ops call  but you’re still picking them in the select call. Please flx these issues.
## On_select out of stock
- Cannot order 2 Mexican pizzas if max.count is 1.
### Select 
- Incorrect “title” key sent in items.

### On-init
- available.count and maximum.count does not match that sent in on_select.

Please resubmit this flow.

## Flow 4
### on_cancel
- Elements mapped with the cancelled fulfillment have incorrect format in the items array.
- Buyer_app finder_fee sent is incorrect.
- Subtype line item should be present in quote_trail for items with customization.

## Flow 5
### on_cancel
- Items with zero price should not be sent in the quote trail. This is applicable for every flow.
- subtype line item should be present in quote_trail for items with customization.

- Previously mentioned issues have not been fixed. 


## Flow 6.
- Please fix previously mentioned issues.

**Comment by asifrazastorehippo** [comment]
@shivang1131 update  logs has been submitted please check and validate PULL- [https://github.com/ONDC-Official/v1.2.0-logs/pull/2727](url)

**Comment by sandeepshahi** [comment]
@asifrazastorehippo, the submitted logs need improvement. While addressing existing issues, please ensure no new ones are introduced. The contract requirements must be strictly followed, such as maintaining a TAT of ≤2 hours for Immediate Delivery, as specified. Additionally, avoid basic errors, like discrepancies between the quote breakup sum, quote price, and the collected amount.

Please resubmit the logs after performing sanity at your end and resolving all the previously mentioned issues.

**Comment by abhay-storehippo** [comment]
@sandeepshahi From my observation, we have sent TAT less than 2 hrs for Immediate Delivery in all flows and there are no quote breakup sum discrepancies, also this was not captured in log utility tool. Can you specify this issue in which flow?

**Comment by asifrazastorehippo** [comment]
cc: @sandeepshahi @shivang1131

**Comment by sandeepshahi** [comment]
@asifrazastorehippo @abhay-storehippo,

Please check below payloads and likewise perform a sanity for all the submitted payloads.

- https://github.com/ONDC-Official/v1.2.0-logs/blob/master/Mystore/SellerAppF%26B/Flow%202/on_init.json
- https://github.com/ONDC-Official/v1.2.0-logs/blob/master/Mystore/SellerAppF%26B/Flow%203/on_select_oos.json

**Comment by asifrazastorehippo** [comment]
@sandeepshahi After conducting sanity checks, we identified issues in flow 2, flow 3, and flow 6. We have addressed these issues, resubmitted them, and request you to please review them. Additionally, could you please check log utility is not up to date.

PULL - https://github.com/ONDC-Official/v1.2.0-logs/pull/2749

**Comment by asifrazastorehippo** [comment]
@sandeepshahi any update?

**Comment by shivang1131** [comment]
## Flow 2
### on_status
- Gps enabled tracking is mandatory.
- Fulfillments.state.descriptor.name is not required.
- The value in invoice does not match the price sent in quote.breakup.

## Flow 3
- Tags and parent_item_id are not being sent for base item in quote.breakup .
### on_select_oos
- Item price would not be zero if item is out of stock. Quote.breakup is incorrectly captured.

### on_select
- A discussion had happened on this before. If an item goes out of stock in the on_select_oos, please choose a different item in the new select call which is not happening here. The same customisation is being used in both out of stock and in stock call.

### on_status
- Invoice link is not working.

## Flow 6
### on_status_packed
- Payment object has incorrect value and refund object has not been added.
- Quote.breakup incorrectly captured.

### on_status_picked
- Incorrect Invoice.

### on_update_liquidated
- Quote.breakup not changed.
- Items are incorrectly mapped in items array.

@asifrazastorehippo

**Comment by sandeepshahi** [comment]
Logs approved for SA (RET 11) v1.2

@asifrazastorehippo
