### ISSUE TITLE
Easypay (SA: RET12,13,14,15,16,18) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2360]
# Easypay Seller App

### **on_search_full_catalog_refresh**

- Implementation of variants is mandatory.
- `items.descriptor.code is invalid; please check for others as well.
- `Item[1]/attr/list/glass_material`: Material cannot be in capital letters (e.g., "Glass").
- colour_name attribute is provided twice in the `items.tags.attribute`. Please check for others.
- Discrepancy in `locations/time` and `providers/tags/timing`.
- `'@ondc/org/statutory_reqs_packaged_commodities’` is mandatory.

## RET-13 ,14, 15, 16, 18

- Same as above.

@ep-aws

**Comment by sahil-ondc** [comment]
## RET12

### On Search
- Radius should be under 500 km in locations
- Atleast 2 variants should be created for the categories.id : ‘2903-1573486’
- serviceability radius should be under 500 km 
 
## RET13

### On Search
- ‘@ondc/org/return_window’ can’t PT0H for the item as it also serves as igm window
 
 
## RET15

### On Search
- Atleast 2 variants should be created for the categories.id : ‘2885-2811812’
 
## RET16

### On Search
- Radius should be under 500 km in locations
- serviceability radius should be under 500 km 
 
## RET18
### On Search
- ‘multiple_products_name_number_or_qty’ and ‘expiry_date’ is missing in the @ondc/org/statutory_reqs_packaged_commodities

@ep-aws

**Comment by Jagannath-wits** [comment]
# Please dont use place holder values for items.descriptor.code, as the logs provided here should be a subset of production logs 

- item.Descriptor.code check in items should be valid as per the domain
  - RET 10,13,16,18: EAN
  - RET 12: HSN
  - RET 14,15: GTIN

- Inc_on_search (RET13)
  - @ondc/org/return_window can not be “PT0H” as it also serves as igm window.
  
  @ep-aws

**Comment by sandeepshahi** [comment]
Logs approved for v1.2

@ep-aws
