### ISSUE TITLE
Paytm GC - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/v1.2.0-logs#239]
GV Case 1
select
- context.timestamp is in incorrect format

on_select
- context.message_id has changed
- context.timestamp is in incorrect format
- items.tags.expriry_period shared is 0 days, please check

init
- context.message_id same as on_select
- context.timestamp is in incorrect format

on_init
- context.message_id has changed
- context.timestamp is in incorrect format
- items.price.minimum_value and maximum_value not required

confirm
- context.timestamp is in incorrect format
- order.created_at and updated_at is in incorrect format
- order.created_at and updated_ar should be same
- order.payments.params.amount should be same as quote.price.value; please check
- items.price.minimum_value and maximum_value not required 

on_confirm
- context.message_id has changed
- context.timestamp is in incorrect format
- order.craeted_at should be same as confirm call
- items.price.minimum_value and maximum_value not required

GV case 2
- same as above 

Clarification
- same item id is mentioned twice in all calls; please check; ideally count should be used for same item being bought multiple times

on_confirm
- order.status should be 'COMPLETED' given on_status is not being ued to provide the completion of the order

@chiragkhannapaytm

**Comment by sumitcn** [comment]
> same item id is mentioned twice in all calls; please check; ideally count should be used for same item being bought multiple times

@Rishabh-ondc  , Could you please point out this inconsistency ? I do not see any duplicacies.

> order.status should be 'COMPLETED' given on_status is not being ued to provide the completion of the order

In the [GV contract](https://docs.google.com/document/d/1pxbDGag8GBzCFXju8YbnIxEFv17DifzyvFI4OsU8oEA/edit) , the status was **ACCEPTED** but we will change it to **COMPLETED**

**Comment by sumitcn** [comment]
> same item id is mentioned twice in all calls; please check; ideally count should be used for same item being bought multiple times

Since these items have different fulfillment Ids [github](https://github.com/chiragkhannapaytm/v1.2.0-logs/blob/master/Paytm/seller_app/GV_Case_2/Confirm.json#L492). Therefore , we have mapped them differently. Otherwise there is no way to differentiate the fulfillment id and item id pair. 
@Rishabh-ondc  , can you please add what should be done here otherwise ?

**Comment by Rishabh-ondc** [comment]
Logs cleared for CUG for v1.0.0

@sumitcn @chiragkhannapaytm @deepalibansal_bitbucket
