### ISSUE TITLE
Costbo - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2399]
## All Flows

**/search**

- authorization object is optional, some LSPs may not respond if they do not support OTP based authorization
- Holiday date should not be past dated

**/init**

- fulfillments/0/start/location/gps does not match start location in search",

**confirm**

- @ondc/org/awb_no is invalid, is mostly provided by LSPs for P2H2P orders.
- start/location/address must have required property 'country'
- linked_order/order/weight/value Payload weight mismatches from /search
- Linked order price value - 2898 cannot be more than the one provided in /search in Payload details - 300.00

**/on_confirm**

- start/time/range is required in /fulfillments when ready_to_ship = yes in /confirm

**/on_status**

- fulfillments/0/start/time must have required property 'range'",
- fulfillments/0/end/time must have required property 'range'",

**/update**

- end/instructions/short_desc cannot be same as PCC - \"0dd4\

Note: Please use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self identify the issues and rectify them before resubmission.

@AnanthBo

**Comment by AnanthBo** [comment]
Have submitted logs after verifying with the tool.  let me know, if we can proceed to next step.

**Comment by AnanthBo** [comment]
@abhinavv245  @BLR-0118     Please let me know the review status for LBNP.   We would like to utilize this festive season to full potential.

**Comment by AnanthBo** [comment]
@abhinavv245     Can i get an update on this please.   I have also submitted. IGM logs (cleared through validation)

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0

**Comment by AnanthBo** [comment]
thanks @BLR-0118 .   @abhinavv245 .    Can i assume  IGM logs also cleared ?   https://github.com/ONDC-Official/v1.2.0-logs/pull/2544
