### ISSUE TITLE
NDHGO RSF - complaince check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2409]
flow 1

receiver_recon

"/message/orderbook/orders must NOT have fewer than 5 items",
"/message/orderbook/orders/0/payment must have required property 'uri'",
"/message/orderbook/orders/0/payment must have required property 'tl_method'",
"/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_type must be equal to one of the allowed values (Percentage,amount)",
"/message/orderbook/orders/0/payment/@ondc~1org~1return_window must match format \"duration\"",
"/message/orderbook/orders/0/payment/@ondc~1org~1settlement_basis must be equal to one of the allowed values (Collection)"
updated_at and created_at should be greater than @ondc/org/settlement_details.settlement_timestamp
updated_at and created_at should be same 

on_receiver_recon
orders.orderbook.message should be define according to payment status

@bmonish

**Comment by rajib-senrysa** [comment]
@RupalSingla, Please check the email by Rishabhnand Singh.

Email Subject: `Feedback Issues from ONDC for RSF Logs`

**Comment by bmonish** [comment]
@RupalSingla Any update on this?

**Comment by rajib-senrysa** [comment]
@RupalSingla Kindly check and update.

**Comment by RupalSingla** [comment]
Logs closed for versin 1.0.0 @bmonish
