### ISSUE TITLE
Dailybee (SA: RET11) - Compliance Check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2424]
### On Search
- if timings are same for Delivery/Self-Pickup/Order. You can use enum ‘All’
- category_id can be used as ‘F&B’ only in the RET11 in items and serviceability

### On Search Inc
- No changes are detected for the categories/id : ‘00000CM76685’ in the incremental changes

### Init
- In case of non-customisable item, tags are not required in the items for item_id : ‘663b45395123b55984298e8f’

### On Init
- In case of non-customisable item, tags are not required in the quote for item_id : ‘663b45395123b55984298e8f’

### On Status Picked
- Invoice is not publically accessible

### Track and On Track
- Kindly provided track and on_track action call as tracking = true

### Select Out Of Stock
- In case of non-customisable item, tags are not required in the items

### FLow 4
- Same as Flow 2

### Flow 5
- Same as Flow 2

### On Cancel 
- RTO fulfillment start location object is missing in on_cancel
- RTO fulfillment end object  is missing in on_cancel

### On Status RTO Delivered
- RTO fulfillment start location object is missing in on_cancel
- RTO fulfillment end location object is missing in on_status_rto_delivered

## Flow 6
- Same as Flow 2

### On Update Part Cancel
- order.state shouldn't be changed from Created to Accepted in on_update_part_cancel

@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc 

Please check the latest set of logs addressing all the above comments. 

https://github.com/ONDC-Official/v1.2.0-logs/pull/2451

**Comment by a-satyateja** [comment]
@sahil-ondc 
@sandeepshahi 
@BLR-0118 


Any update on this please..

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- fulfillment_id ‘2’ for Self-Pickup is not mapped with any of the items in bpp/providers[0].item
 
## Flow 2
### On Select
- tags are missing for the item_id : ‘663b44b15123b55984298e83’ in message.order.items as it was there in there in on_init and on_confirm action call 
 
### On Confirm
- time.ranges can’t be there if the order isn’t yet ‘Accepted’
 
### On Status Picked
- In invoice, tax and delivery charges are missing as compared with the quote
 
## Flow 3
- Same as Flow 2
 
### On Select Out Of Stock
- Kindly use customizable item for out of stock scenario
 
## Flow 4
- Same as Flow 2
 
### On Cancel
- tags are missing for the item_id : ‘663b44b15123b55984298e83’  in message.order.items as it was there in there in on_init and on_confirm action call
 
- item object is not required  for tax and delivery in "item": {"price": {"currency": "INR", "value": "5.00" } }
in the quote.breakup
 
 
## Flow 5
- Same as Flow 2
 
### On Status Rto is missing
 
## Flow 6
- Same as Flow 2
 
### On Update Part Cancel
-  `{“code": "subtype","value": "item”}` in quote trail is allowed for only customizable item
 
### On Status Pending
- settlement_details of part cancellation is not carry forward in the on_status action call
 
### On Status Picked
- Invoice is invalid


@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc 
@sandeepshahi 
@BLR-0118 

Please check the revised logs for RET11

https://github.com/ONDC-Official/v1.2.0-logs/pull/2553

**Comment by shivang1131** [comment]
## Flow 1
### on_search
- Two elements have this value in category_ids 00000CM76685:2.
- to customize a pizza, you would need to add drinks before choosing the toppings which is incorrect.
- 9-9 is the store timing but items have timing from 7 to 11.
- Send add mandatory and default customizations.
- Veg loaded pizza is in the custom menu for chicken.
- Chicken Fillet Nugget Snack has code veg in tags. 

## Flow 2
- Flow 2 is incorrect. You need to pass in a customizable item with customizations.

## Flow 3
### on_init
- np_type in tags is missing.

### on_status pending
- Difference in time ranges cannot be this high when TAT is 1 hour.
### on_status packed
- routing tags in fulfillment is missing.

## Flow 4
### on_init
- np_type in tags is missing.

## Flow 5
### on_cancel
- Quote/breakup is captured incorrectly. Item quantities would also be zero. same issue in on_staus rto_delivered.

## Flow 6

- order flow with base item and customization should be provided for verification
- routing and tracking info should be provided before the order is shipped and thereafter
- invoice should remain the same as in /on_status (picked) state
- reverseqc flow is optional for F&B domain


@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc 
@sandeepshahi 
@BLR-0118 
@shivang1131 

Any update on this please..

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- Message Ids for /search and /on_search api should be same
- Transaction Id for /search and /on_search api should be same
- Placeholder images should not be provided
- invalid list provided for the code:timing for an item_id : ‘663b452a5123b55984298e77’
- Chicken Fillet Nugget Snack has code veg in tags.
- upper range is not collected properly for the item_id : ‘663b44b15123b55984298e83’

## Flow 2
### Select
- If quantity for the item_id : ‘663b44b15123b55984298e83’ is 2 then the default customisation quantity should also be 2.

### On Select
- Item quantity for item_id: ‘663b44b15123b55984298e83’’, ‘663b452a5123b55984298e8e’  does not match in select & on_select

- How you are making the quote.breakup if item.quantity mismatch as compared to select action call

- Warning: Quoted Price in /on_select INR 509 does not match with the total price of items in /select INR 609 i.e price for the item mismatch in on_search and on_select as item quantity was changed in Select action call for item_id : ‘663b44b15123b55984298e83’
 
### Init
- Duplicate item_id : ‘663b452a5123b55984298e8e’ found in the items
- quote.breakup.item quantity for the item_id : ‘663b452a5123b55984298e8e’ of on_select doesn’t matches with the init action call order.items quantity 

### On Status Pending
- How the end.time.range is being calculated as it doesn’t matches with the provided ‘TAT’

## Flow 4
### On Cancel 
- invalid quote_trail object found in On cancel which is not present in on_confirm with id : ‘663b47255123b55984298e92’

## Flow 5
### On Cancel
- Are you not charging for the Delivery of the item ? 
## On Status Delivered is by mistakenly provided or what as it’s having different transaction id then others

## Flow 6
###On Confirm
- Time.ranges can’t be there if order is not yet ‘Accepted’

### On Update Part Cancel
- available and maximum count will not be there in the quote.breakup for the items

### On Update Liquidated
- tax object not captured properly in the quote.breakup, as there will not quantity, count for the the tax 

@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc: The previous version of submitted logs had issues because of merge conflicts resolutions. Please check the latest set of logs, attached is the PR. 

@sandeepshahi
@BLR-0118
@shivang1131

Please check this PR:  https://github.com/ONDC-Official/v1.2.0-logs/pull/2657

**Comment by shivang1131** [comment]
Hi @a-satyateja,
Some previous issues have still not been fixed. Also, the items sent in the flows have incorrect configurations. 
Please send a demo video demonstrating the flows from your seller app.

**Comment by shivang1131** [comment]
## Flow 1
### on_search
- default_selection.maximum_value captured incorrectly. It would be the sum of maximum_values of items that are in the default selection.
- Range.upper also captured incorrectly for veggie supreme pizza. As I can choose 2 toppings, the maximum value would be higher.

## Flow 2
- If item price is 0, no need to provide tax in quote.breakup.


## Flow 4
- Quote trail should not have values with zero value.

## Flow 5
- Same as flow 4
- Parent item id cannot start with ‘/‘.

## Flow 6
- Same as previous flows.


@a-satyateja

**Comment by a-satyateja** [comment]
@shivang1131 

Please verify the latest PR. We have addressed and resolved all the reported issues. 

| Flow  | Issue Description                                                                                  | Status  | Comments |
|-------|----------------------------------------------------------------------------------------------------|---------| ---- |
| Flow 1 | `default_selection.maximum_value` captured incorrectly. Should be the sum of `maximum_values` of selected items. | Closed ✅ | Since the default items are of zero price, the maximum value is same as  the base item value.|
| Flow 1 | `Range.upper` captured incorrectly for Veggie Supreme pizza. Since 2 toppings are allowed, the maximum value should be higher. | Closed ✅ | - |
| Flow 2 | If item price is 0, no need to provide `tax` in `quote.breakup`.                                   | Closed ✅ | -    |
| Flow 4 | `Quote trail` should not include values with zero value.                                           | Closed ✅   |-  |
| Flow 5 | Same as Flow 4.                                                                                    | Closed ✅  |-    |
| Flow 5 | Parent item ID cannot start with `/`.                                                              | Closed ✅  |-    |
| Flow 6 | Same as previous flows (Flow 4 and Flow 5).                                                        | Closed ✅    |- |

**Comment by sandeepshahi** [comment]
Logs approved for SA (RET 11) v1.2.

@a-satyateja
