### ISSUE TITLE
Pidge - LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2445]
## Order Flow

**/search**

- /intent/fulfillment/start and end/location/gps Incorrect gps value, should be atleast six decimal digits

## RTO Flow

**/on_cancel**

- precancel_state/updated_at should be the timestamp at which this state was updated in the database (At-delivery should have been recorded before on_cancel)

**/on_status (RTO Delivered)**

- precancel_state/updated should not be updated once recorded

## Cancel Flow

**/on_cancel**

- precancel_state/updated_at is not correctly recorded

@shabbir-pidge

**Comment by shabbir-pidge** [comment]
Hi @abhinavv245 
Please refer to this PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/2449/files.
It contains fixes for RTO & Cancellation. For /search, i think its from buyer side, that they send coordinates having length less than 6 decimal points, i think that can be skipped.

**Comment by shabbir-pidge** [comment]
Hi @abhinavv245, any updated on fixes ?

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
