### ISSUE TITLE
Pidge - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2488]
**/search**

- why is order preparation time 20 minutes (provider/time/duration), when you are marking order ready to ship at the time of /confirm call?

**/confirm**

- Average pickup time(fulfillments/start/time/duration) provided by LSP (in /on_search) is missing

@shabbir-pidge

**Comment by BLR-0118** [comment]
logs approved for v1.2.0
