### ISSUE TITLE
Pidge RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2496]
"receiver_recon": {
                "schemaErr0": "/message/orderbook/orders/0/state must be string",
                "schemaErr1": "/message/orderbook/orders/0/state must be equal to one of the allowed values (Completed)",
                "schemaErr2": "/message/orderbook/orders/0/payment must have required property '@ondc/org/return_window'",
                "schemaErr3": "/message/orderbook/orders/0/payment/params/amount must be number",
                "schemaErr4": "/message/orderbook/orders/0/payment/type must be equal to one of the allowed values (ON-ORDER)",
                "schemaErr5": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_type must be equal to one of the allowed values (percent,amount)",
                "schemaErr6": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_amount must be number",
                "schemaErr7": "/message/orderbook/orders/0/payment/@ondc~1org~1buyer_app_finder_fee_amount must be number",
                "schemaErr8": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_amount must be number",
                "schemaErr9": "/message/orderbook/orders/0/payment/@ondc~1org~1settlement_details/0/settlement_ifsc_code must match pattern \"^[A-Z]{4}0[A-Z0-9]{6}$\"",
                "schemaErr10": "/message/orderbook/orders/0/withholding_tax_gst/value must be number",
                "schemaErr11": "/message/orderbook/orders/0/withholding_tax_tds/value must be number",
                "schemaErr12": "/message/orderbook/orders/0/deduction_by_collector/value must be number",

@shabbir-pidge

**Comment by shabbir-pidge** [comment]
Hi @RupalSingla, Can you provide more details on this, folder or flow1. Also please share the log verification utility for this.

**Comment by shabbir-pidge** [comment]
Hi @RupalSingla , 
Please find this logs https://github.com/ONDC-Official/v1.2.0-logs/pull/2506

**Comment by JyotiSharma0711** [comment]
**receiver_recon

flow 1**

- payerdetails"."payer_account_no" should be string
- Message/order book/orders/0/payment/settlement_timestamp- cannot be greater than the created at and updated_at
- Message/order book/orders/0/payment/@ondc/org/settlement_window   -field is missing.

@shabbir-pidge

**Comment by shabbir-pidge** [comment]
Hi @JyotiSharma0711 @RupalSingla 
https://github.com/ONDC-Official/v1.2.0-logs/pull/2523
Please check.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @shabbir-pidge
