### ISSUE TITLE
KNS Retail (SA : RET12) - Compliance Check

### ISSUE THREAD

**Issue by FarheenNazQA** [ONDC-Official/v1.2.0-logs#2503]
### on_search

- Variants not implemented properly; provided variant is not assigned to any item.
- Catalog should have at least 2 items. To check for variants.
- Invalid HSN code provided.

@VirajjKAS

**Comment by Jagannath-wits** [comment]
## Flow 1

#### On_search

- [variant.desciptor.name](http://variant.desciptor.name/) is variant on material but the variant is made on colour
- placeholder/ invalid items.descriptor.code should not be provided. eg: 610910 (repeated issue)

@VirajjKAS

**Comment by FarheenNazQA** [comment]
## Flow-1
### On_search
-items.Images not accessible (item id-144).Please check for others.

**Comment by VirajjKAS** [comment]
Hey @sandeepshahi @FarheenNazQA @Jagannath-wits  , it's been a week I had submitted logs can you please provide review on it and tell which stage we're on regarding Fashion Category.

**Comment by sandeepshahi** [comment]
@VirajjKAS, is catalog rejection framework implemented?

**Comment by aniketmishra13122** [comment]
@sandeepshahi yes we have implemented the catalog rejection  API

@VirajjKAS

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET 12)

@VirajjKAS @aniketmishra13122

**Comment by aniketmishra13122** [comment]
@sandeepshahi  Thanks!
