### ISSUE TITLE
Zoho (SA: RET12, 14, 15) - compliance checks

### ISSUE THREAD

**Issue by shivang1131** [ONDC-Official/v1.2.0-logs#2505]
##RET 12 Fashion

### on_search
- Every variant group is based on 3 attributes even though atleast one of these attributes does not change across products. If a variant group is of women's clothing, gender won't be a distinguishing attribute.
For example, The category with id 000000205379 has variants based on size, gender and colour. However, it is named as Women fashion Solid Tops and every item has gender as female. Here, gender wont be a distinguishing attribute.

- Time to ship is 90 minutes. This is not a feasible shipping duration in this domain.

- Size charts for both the genders are the same in some cases.

- Placeholder value for HSN codes are also used.

### on_search
- Time to ship is 4 minutes. Is this a feasible shipping duration in this domain?

### on_search
- Time to ship is 4 minutes. Is this a feasible shipping duration in this domain?
- @ondc/org/return_window missing for some items.
- Elements of the variant id 000000548587 have same values of length, breadth and height despite being different sizes.

@SherinShafa27

**Comment by SherinShafa27** [comment]
@shivang1131 its just an local test data. Do you want to resubmit again? Please help we need to whitelist for tomorrow's release

**Comment by SherinShafa27** [comment]
Thank you so much @shivang1131 @sandeepshahi
