### ISSUE TITLE
Xpress Baazaar ( SA : RET11) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2546]
### On Search
- default_selection and lower.range is not correctly calculated for the item_id : ‘7a1eb7d6-c522-5a69-936d-b9ebbaf88869’. Kindly check for others as well or please explain the calculation.
- Invalid/Placeholder values, eg: fssai licence number, description, etc should not be provided
- Circle radius should be 500 kms max even if serviceability is PAN india
- The veg can’t be ‘yes’ for the non-veg customisation for id : ‘C16’. Kindly check for others
 
### On Confirm
- order.created_at timestamp mismatches in /confirm and /on_confirm
- fulfillment.ranges would only be provided once the ‘Order’ is Accepted. How are you providing ranges before order is accepted ?
 
### On Status Picked
- If ‘url_enabled’ is no then the ‘url’ field must not be provided 
- invoice is not publically accessible 
 
## Flow 3
- Same as Flow 2
### On Select Out Of Stock
- In your case the customization out of stock, and this is incorrect way of providing it. Kindly refer to page no 222 of the Retail Contract; you should also provide the dynamic_item_id along with it. Eg: {\"dynamic_item_id\":\"DI2\",\"customization_id\":\"C15\",\"customization_group_id\":\"CG3\",\"error\":\"40002\"}]
 
## Flow 4
- Same as Flow 2
### On Cancel
- Why are the ‘Delivery Charges’ are being charged when the order is cancelled pre-shipment ?
 
## Flow 5
- Same as Flow 2
### On Cancel
- RTO start timestamp is missing in the ‘RTO’ fulfilment

#### on_status_rto_disposed 
- cancellation object not carried forward from on_cancel.
- rto_fulfillment.end.time.range is not required.
 
## Flow 6
- Same as Flow 2
### On Update Partial Cancel
- order.state shouldn't be changed from Created to Accepted in /on_update_part_cancel
- If the quote_trail for the id : ‘a650004’ is 0,then it shouldn’t be provided in the quote_trail
 
### Update Settlement Partial Cancel
- The timestamp of update settlement is greater than the on_status_pending

 
### On Status Pending
- Update Settlement of the partial cancellation is not carried forward
- Why the start.timestamp is there for ‘Delivery’ fulfilment as the ‘Order’ is not yet picked up
 
### On Status Packed
- Mismatch occurred while comparing 'Delivery' fulfilment object with on_status_pending on key 'start/time'
 
### On Status Delivered
- The end.timestamp is missing for ‘Delivery’ fulfillment

### on Update return initiated
- How are settlement details of part-cancell provided before it was sent from buyer? 
- **Manual manipulation of logs are not allowed**
 
### On Update Interim
- The forward fulfilment item should be reduced in on_update_liquidated and return fulfillment 
should be created in on_update liquidated action call
- quote and item quantity shouldn’t be reduced in the iterim action call for liquidated
 
### On Update Liquidated
- quote_trail is not captured for the return request
- How the update settlement is future dated ?

@purushottamKj 
- Please run the utility for flow 6 as well
- **Manual manipulation of logs are not allowed**

**Comment by purushottamKj** [comment]
@Jagannath-wits 
FLOW 2,3,4,5,6 : Mismatch found for item with item_id 7a1eb7d6-c522-5a69-936d-b9ebbaf88869 while comparing quote object of on_select and confirm.
as you have asked how is the parent_item_id is different
the reason for that we have order same product with different customised way 
As per the docs, parent_item_id will be different.

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits FLOW 2,3,4,5,6 : Mismatch found for item with item_id 7a1eb7d6-c522-5a69-936d-b9ebbaf88869 while comparing quote object of on_select and confirm. as you have asked how is the parent_item_id is different the reason for that we have order same product with different customised way As per the docs, parent_item_id will be different.

ok then that is fine, please proceed with others

**Comment by FarheenNazQA** [comment]
## Flow 1
### On Search
upper range is not collected properly for the item_id : ‘7a1eb7d6-c522-5a69-936d-b9ebbaf88869’.Kindly check for others as well or please explain the calculation.

Custom groups having min- 1 in config should have at least one [default.eg](http://default.eg/) - CG3.

## Flow 2
### On Status Pending
How the ranges for the start and end object is same ?

## Flow 4
### On Cancel
if the quote_trail price is ‘0’, It must not be provided in the ‘Cancel’ Object
Quote trail for ‘Delivery’, ‘Packing’ charges, Convenience Fee are not there 
subtype should be used in the quote_trail in case of customization and customized item


## Flow 6
### On Update Part Cancel
Delivery fulfilment state descriptor is an empty object
quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm.

### On Status Picked
Invoice doesn’t match with the given quote price.

### On Update Liquidated
No changes detected in items and quote.price. On what basis are you doing doing the liquidation and providing quote_trail ?


@purushottamKj

**Comment by sauravkrs1** [comment]
@FarheenNazQA I have some doubt in Flow 1,6 , can we schedule a meeting today if possible ?

**Comment by sauravkrs1** [comment]
@FarheenNazQA  can we schedule a meeting today ?

**Comment by FarheenNaz005** [comment]
@sauravkrs1  Sure! Please send me an invite to connect.

**Comment by sauravkrs1** [comment]
@FarheenNaz005  please join  https://meet.google.com/kmi-nrbv-ahq

**Comment by sauravkrs1** [comment]
@FarheenNaz005 @Jagannath-wits 

please join i have some doubt  https://meet.google.com/ret-ujwq-cue

**Comment by Jagannath-wits** [comment]
### On_Search
- The radius given is 500 km, which is not feasible in the F&B.
- In `message.order.tags`, the serviceability cannot be *Pan India*; it has to be *hyperlocal* for F&B.

---

### On_Select
-  **Delivery Mode**: It should be *Immediate delivery*.
-  **Tracking Requirement**: For F&B, tracking should be set to `true` and supported.
- TAT of 7 days is not feasible for F&B

---

### on_Confirm
In `order.payment`, the following fields are missing:
- `@ondc/org/settlement_basis`
- `@ondc/org/settlement_window`
- `@ondc/org/withholding_amount`

---

### On_Status_Accepted
- If the TAT is set to 7 days, then the fulfillment `end_time_range` should reflect 7 days and not 8 days

---

### Flow 4 - 
#### Cancel
- **Wrong Code Used**: `009` (Wrong product delivered) is incorrect in this context.


### Flow6 

#### update_partial_cancel 
- Do you support part-cancellation before order is accepted ?

@sauravkrs1 @purushottamKj

**Comment by sauravkrs1** [comment]
@Jagannath-wits @FarheenNaz005 

sir please join the meeting i have something to discuss..

https://meet.google.com/zep-namk-uwa

**Comment by purushottamKj** [comment]
Hi @Jagannath-wits, As you have mentioned that tracking should be True and supproted. But we are ot supporting tracking for our preprod environment and it won't be possible for us to generate a tracking url , can we pass a dummy url for testing purpose.

**Comment by sauravkrs1** [comment]
Hi @Jagannath-wits , As you have mentioned that tracking should be True and supproted. But we are not supporting tracking for our preprod environment and it won't be possible for us to generate a tracking url , can we pass a dummy url for testing purpose.

**Comment by sauravkrs1** [comment]
@Jagannath-wits , sir please provide any feedback .

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits , sir please provide any feedback .

GPS tracking is mandatory in f&b and tracking url is not supported

**Comment by sauravkrs1** [comment]
@Jagannath-wits  
![image](https://github.com/user-attachments/assets/7984ab0b-809b-4480-9a93-67c1f67dd1f1)
sir, what we have to pass in the url if gps is enabled ?

**Comment by Jagannath-wits** [comment]
please refer to footers of page 454 of contract as well @sauravkrs1

**Comment by sauravkrs1** [comment]
@Jagannath-wits, can we connect ? i have one doubt 

https://meet.google.com/cqc-khmb-ntm

**Comment by sauravkrs1** [comment]
@Jagannath-wits, sir please join the meeting i have something to discuss..

https://meet.google.com/cqc-khmb-ntm

**Comment by sauravkrs1** [comment]
@Jagannath-wits sir please join the meeting i have something to discuss..

https://meet.google.com/cqc-khmb-ntm

**Comment by sauravkrs1** [comment]
@Jagannath-wits sir, i have submitted the logs as per the feedback and tracking is enabled now please check and try to close this task sir as we have discussed in the meeting .

**Comment by sahil-ondc** [comment]
## Flow-1
## On_search-
- bpp/providers.gps and area_code differ.
- bpp/providers.categories.parent_category_id- if its empty then no need to provide.
- @ondc/org/return_window shouldn’t be 10D,check for others -
     (Item_id- 4f4afe04-f72c-4ce6-a576-176e99a15c50)

## Flow-2
## On_status_accepted-
- fulfillment.start.timestamp & fulfillment.end.timestamp is missing

## on_status
- if tracking is enabled fulfillments.tracking object should also be provided after order is accepted 

### on_select

- TAT mentioned under fulfillments does not fall under the requirements for immediate delivery. (Please refer to the contract for immediate delivery)


### On_track- 
- message.tracking.location.gps- there shouldn't be any gap between long and lat.


## on_status_pending should be provided when order state is not accepted.

@sauravkrs1

**Comment by sauravkrs1** [comment]
@sahil-ondc sir can we connect ? i need to discuss something

**Comment by sauravkrs1** [comment]
@sahil-ondc  sir can you please explain bpp/providers.gps and area_code differ as i have checked for this gps but didn't find anything , please explain me

**Comment by Jagannath-wits** [comment]
Logs approved for SA (RET 11) v1.2.

@sauravkrs1
