### ISSUE TITLE
Dailybee (SA: RET 12, 13,16 ) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2547]
# Dailybee

#### On_search
- If **self-pickup** is not supported by any provider, it **should not** be included in `bpp/fulfillments`.
- `items.descriptor.code` should not be a placeholder value.
- `categories.description` should accurately describe the category. In this case, the description is listed as **qty variant**, but the variant attributes are based on **size** and **color** instead.

---

#### On_search
- Same as above.
- `items.quantity.maximum` should be reasonable, not set to 100. If there are no defined limits, use the enum value `99`.

---

## RET16
- Why is the `categories.id` for **RET18** the same as **RET16**?

@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc
@Jagannath-wits 

Please merge and verify the logs.

https://github.com/ONDC-Official/v1.2.0-logs/pull/2566

**Comment by a-satyateja** [comment]
@sahil-ondc
@Jagannath-wits 

We have submitted a new set of logs for all the RET codes.
Please check the latest PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/2660

**Comment by sandeepshahi** [comment]
Duplicate issue board: Refer https://github.com/ONDC-Official/v1.2.0-logs/issues/2629 for the latest updates
