### ISSUE TITLE
Thrive (LBNP)	RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2577]
receiver_recon:

created_at , updated_at and settlement_timestamp cannot have same timestamp

@madlad33

**Comment by amitkbadheka** [comment]
Hey, will get this checked.

**Comment by amitkbadheka** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/2603

**Comment by RupalSingla** [comment]
Logs cleared for verssion 1.0.0 @amitkbadheka
