### ISSUE TITLE
Zoho (RET18) - compliance check

### ISSUE THREAD

**Issue by shivang1131** [ONDC-Official/v1.2.0-logs#2582]
### on_search
- Prescription based medicines are not yet supported on the network.

@SherinShafa27

**Comment by SherinShafa27** [comment]
@shivang1131 so prescription with true items need not to be sent to network?

**Comment by shivang1131** [comment]
Yes @SherinShafa27 , you dont have to send those items.

Regards

**Comment by SherinShafa27** [comment]
ok @shivang1131 can u approve RET18? we will restrict prescription true items in our end.

**Comment by SherinShafa27** [comment]
@shivang1131 since this is not mentioned in contract we have opened up both .Will restrict this. can u approve the logs to proceed?

**Comment by SherinShafa27** [comment]
@shivang1131 @sandeepshahi pls update on above to proceed.

**Comment by sandeepshahi** [comment]
Logs approved for v1.2

@SherinShafa27
