### ISSUE TITLE
Xpressbazaar (BA : RET13) - Compliance Checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2586]
Buyer should send ‘NACK’ for the following :  
 
### On Search
- if the timing for Delivery/Order is same, should use ‘All’ enum.
- Support for variants is mandatory, categories must be present in bpp/providers[0]
 
### On Search Inc
- How the timestamp of incremental changed item can be future-dated then the context.timestamp ?
 
### On Confirm
- time.ranges should be there when the order is ‘Accepted’
- images shouldn’t be there in fulfillments.state and fulfillments.start.location
 
### On Status Picked
- tracking object is missing in the fulfillments 
## Flow 3
- Same as Flow 2
### On Select Out Of Stock
- available quantity must be reduced for out_of stock item with item_id : ‘CU270I0’
 
## Flow 5
- Same as Flow 2
### Select
- Duplicate forward fulfillment for the same item_id : ‘CU270I2’
 
### On Select
- Item quantity should be selected as 4, instead of selecting duplicate item_id in the quote and fulfillments
 
### On Status RTO
- images shouldn’t be there in fulfillments.state
 
## Flow 6
- Same as Flow 2
#### On Update Interim Reverse Qc
- How the return fulfillment id for the item_id : ‘CU270I4’ which was liquidated is changed from ‘66ed5603eb56fd91735baaa2’ to ‘66ed579aeb56fd91735baae3’ in the items and fulfillments ?
 
### On Update Picked
- Why the reverse_qc forward fulfillment isn’t reduced in the items, and why the backward fulfillment is not created for the reverse_Qc item with item_id : ‘CU270I6’
- Why the quote price and item quantity for the item_id : ‘CU270I6’ isn’t reduced in the quote ?
- quote trail is missing in the Return fulfillment for reverse_qc
- For the Return fulfillment (reverse_qc) start.timestamp is missing 
 
### Update Settlement Reverse Qc
- On what basis you are sending the refund, if the item isn’t reduced in the quote_trail ?
 
### On Update Delivered
- settlement_details for the reverse_qc item id is missing

@purushottamKj

**Comment by FarheenNazQA** [comment]
The buyer should send a ‘NACK’ for the following issues:

## Flow-1
### On_search
- **bpp/providers.locations.gps**: There shouldn't be any gap between longitude and latitude values apart from the comma separator.
- **Variants are not captured properly**: No category ID is linked with items. For example, for category ID “0000bfeae1e0” as a variant group, if it’s a variant group, it should be linked with at least two items. Check for others as well.
- **Item ID**: For `023BF17A1C2BF2BE1B61F1FA53CAF5D5_44662002123011_default` - is it valid?
- **Invalid EAN**: For ID `7C437D1F590AD4583BCD1F3FCF3932C0_44661986459907_default`, the EAN number is invalid. Check for others as well.
- **Domain change in context**: Why has the `context.domain` changed? For example, in `/On_search`, it shows `"domain": "ONDC:RET13"`, while for `search_inc`, it shows `"ONDC:RET14"`.

## Flow-2
### On_select
- **Fulfillments Tracking**: For `Fulfillments.Tracking=true`, there should be both a `/Track` and `/On_track` call.

### On_status_picked
- **Invoice Document URL**: The document URL for the invoice is not accessible.

## Flow-3
### On_select_out_of_stock
- **Item Count Discrepancy**: For `item_id=023BF17A1C2BF2BE1B61F1FA53CAF5D5_44662002123011_default`, the count is zero in the current call, but in the `/On_select` call, the count is 2.

## Flow-6
### On_update_part_cancel
- **Cancel Request Missing**: The ‘Cancel_request’ object is missing in the 'Cancel' fulfillment.
           
@pzed05

**Comment by Jagannath-wits** [comment]
@pzed05 can you please 

> The buyer should send a ‘NACK’ for the following issues:
> 
> ## Flow-1
> ### On_search
> * **bpp/providers.locations.gps**: There shouldn't be any gap between longitude and latitude values apart from the comma separator.
> * **Variants are not captured properly**: No category ID is linked with items. For example, for category ID “0000bfeae1e0” as a variant group, if it’s a variant group, it should be linked with at least two items. Check for others as well.
> * **Item ID**: For `023BF17A1C2BF2BE1B61F1FA53CAF5D5_44662002123011_default` - is it valid?
> * **Invalid EAN**: For ID `7C437D1F590AD4583BCD1F3FCF3932C0_44661986459907_default`, the EAN number is invalid. Check for others as well.
> * **Domain change in context**: Why has the `context.domain` changed? For example, in `/On_search`, it shows `"domain": "ONDC:RET13"`, while for `search_inc`, it shows `"ONDC:RET14"`.
> 
> ## Flow-2
> ### On_select
> * **Fulfillments Tracking**: For `Fulfillments.Tracking=true`, there should be both a `/Track` and `/On_track` call.
> 
> ### On_status_picked
> * **Invoice Document URL**: The document URL for the invoice is not accessible.
> 
> ## Flow-3
> ### On_select_out_of_stock
> * **Item Count Discrepancy**: For `item_id=023BF17A1C2BF2BE1B61F1FA53CAF5D5_44662002123011_default`, the count is zero in the current call, but in the `/On_select` call, the count is 2.
> 
> ## Flow-6
> ### On_update_part_cancel
> * **Cancel Request Missing**: The ‘Cancel_request’ object is missing in the 'Cancel' fulfillment.
> 
> @pzed05

@pzed05 can you please acknowledge the buyer side issues

**Comment by pzed05** [comment]
+Somnath Yadav ***@***.***>

**Comment by ensservices** [comment]
@Jagannath-wits @sandeepshahi We have implemented the NACK, Please approve the logs

**Comment by sandeepshahi** [comment]
Logs approved for BA (RET 13) v1.2.

@ensservices
