### ISSUE TITLE
buyNxt (SA:RET15,18) - compliance check

### ISSUE THREAD

**Issue by FarheenNazz** [ONDC-Official/v1.2.0-logs#2587]
##Flow -1
### On_search

- message/catalog/bpp~1providers/items[2]/descriptor/code- Invalid EAN code (Please check for others as well)
- message/catalog/bpp~1providers/items[4]/descriptor/image- Wrong Image provided with respect to the mentioned item ( Item is induction cooktop and the image is of mixer jar)
- catalog provided should be a subset of production catalog

@pranav-buynxt

**Comment by shivang1131** [comment]
## Flow 1
### on_search
- The variants have been captured incorrectly. Although they have different colours, the models of the items are also changing.
### on_search_inc_store_close
- The range for the closing of store should be future dated.
### on_search_inc
- Why are the hours,minutes, seconds and milliseconds params not changing when the item is getting updated for item 26712_12508772.

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
# RET15
#### on_search
- invalid category_id 'Kitchen Appliances. Please refer to sheet https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=1363803035#gid=1363803035

#### on_search_inc
- context.city should be * in on_search_inc

# RET18
#### On_search
- prescription_required should use enums ‘yes’or ‘no’
- variants should be implemented
- if there are no variants then why is parent_item_id:’1’ provided

## on_search_inc
- How did item.descriptor.code type change from 5:others to 1:EAN ?

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
Buynxt
RET-15

Flow 1
### on_ search
Timestamp for items can't be greater than context.timestamp (please check for other items as well)
store enable/disable timestamp (/bpp/providers/time/timestamp) should be less then or equal to context.timestamp
code should be either 3:GTIN or 5:others (in your case) as a value in message/catalog/bpp/providers/items/descriptor/code in RET 15 and not 1:EAN.


Buynxt
RET-18

Flow 1
### on_ search
Country must be in ISO 3166-1 format (three-letter country code) (please check for all the other items as well)
Please ensure the long and short desc for the items are not same
Gps code does not match with the given address (gps is of Sonipat, Haryana)
Gps coordinates must be specified with at least 6 decimal places for precision.

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
Logs approved for buyNxt SA:RET15,18
@pranav-buynxt
Also please clean-up the repository and remove all backdated logs like other NPs
