### ISSUE TITLE
SellerSetu (BA:RET 16) - compliance check

### ISSUE THREAD

**Issue by FarheenNazQA** [ONDC-Official/v1.2.0-logs#2598]
### Search
-message.intent.tags are not enabled yet.

### On_Search
-Return window shouldn't be zero,as the item is returnable.
-Categories should be present.

### On_Search_inc
-There should be some delta change in Increment apart from timestamp.

### On_confirm 
-time to ship should be within the fulfilment.start.range.
### On_status_packed
Tracking object is missing for tracking-true.
Pickup time range should match with the time to ship.
### On_status_picked
Invoice document is not opening.

### On_cancel_rto
 -In on_cancel_rto; RTO fulfillment.end.time should not be present (end.timestamp is provided in on_status_rto_delivered or disposed and not before that for rto fulfillment )

### Update_reverse_qa
Fulfillment.tags.image - should be relevant.

 @Chaitanya-Keyal

**Comment by sellersetu-hub** [comment]
Related to https://github.com/ONDC-Official/v1.2.0-logs/issues/2328

**Comment by sellersetu-hub** [comment]
@FarheenNazQA Most of the issues here I see are from sellerside `on_*`

**Comment by FarheenNazQA** [comment]
## Flow-1

### Search
- Static terms are not enabled yet and hence not required.(message/intent/tags[bap_terms])`

### On_Search
- Return window shouldn't be zero, as the item is returnable. (It also serves an igm window.)
- Categories should be present.

### On_Search_inc
- There should be some delta change in Increment apart from the timestamp.

## Flow-2

### On_confirm 
- Time to ship should be within the `fulfilment.start.range`.

### On_status_packed
- Tracking object is missing for `tracking-true`.
- Pickup time range should match with the time to ship.

### On_status_picked
- Invoice should be publicly accessible.

## Flow-5

### On_cancel_rto
- In on_cancel_rto, RTO `fulfillment.end.time` should not be present. (End timestamp is provided in `on_status_rto_delivered` or disposed, and not before that for RTO fulfillment.)

@Chaitanya-Keyal

**Comment by sandeepshahi** [comment]
Duplicate issue board; Refer https://github.com/ONDC-Official/v1.2.0-logs/issues/2328 for the updates.

@sellersetu-hub
