### ISSUE TITLE
Uengage (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/v1.2.0-logs#260]
on_issue_status
- complainant_actions trail not required in on_action calls
- respondent_actions trail should capture the trail of previous actions as well
- resolution_support.respondentEmail is an incorrect attribute
- resolution_support.contact.name is an incorrect attribute
- resolution.resolution_action not required

Clarifications
- Please share complaint close call as well
- Hope the on_issue_status call is being developed as an unsolicited call as well
- context.key is not required

@shubhamuengage

**Comment by shubhamuengage** [comment]
hi @Rishabh-ondc  we have implemented the above feedback and resubmitted logs since buyer app was not able to generate issue close request and same is not included.

for fulfillment issue on_issue_status call is unsolicited.

**Comment by Rishabh-ondc** [comment]
Logs cleared. 

Do test with the reference buyer app for the complaint close implementation as well.

@shubhamuengage
