### ISSUE TITLE
Udyamwell (SA: RET 12) - compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#2614]
@udyamwell1, is catalog rejection framework implemented?

**Comment by udyamwell1** [comment]
@sandeepshahi Can you please review and approve our logs for RET:12?

**Comment by udyamwell1** [comment]
@sandeepshahi Please approve our RET:12 logs. 
If is their any issue please let us know.

**Comment by sandeepshahi** [comment]
Logs approved for RET 12 (v1.2)

@udyamwell1
