### ISSUE TITLE
nStore (BA: RET13, 14, 15, 16, 18) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2648]
# Buyer should send 'NACK' for the following :
 
### On Search
- Invalid measure.unit 'each' for item_id : '111'
- Message Id for /search and /on_search api should be same
- code should have 1:EAN as a value in /message/catalog/bpp/providers[0]/items[0]/descriptor/code
- item.quantity.unitized.measure.value should be greater than 0
- Support for variants is mandatory, categories must be present in bpp/providers[0]
- accept_bap_terms is not required in bpp/descriptor/tags for now
- offers and creds array can't be empty in bpp/providers
- Mandatory Attribute 'brand' is missing in tags for BPC item[0]
- circle.radius.unit is missing in the locations
- if timing for order/delivery/self-pickup is same, should use 'All' enum instead
- '@ondc/org/return_window' can't be null in the items
- 'net_quantity_or_measure_of_commodity_in_pkg' is not required in the '@ondc/org/statutory_reqs_packaged_commodities'
 
### Search Inc
- Invalid fields:  status and timestamp in the search inc action call
 
### On Search Inc
- Message id should not be same with previous calls as it's incremental push based call
- item.quantity.unitized.measure.value should be greater than 0
- Invalid measure.unit 'each' for item_id : '111'
- '@ondc/org/return_window' can't be null in the items

@nstoretech

**Comment by Jagannath-wits** [comment]
# nstore BA 

### Buyerapp should check for the following:
## Ret13

### On_search
- `radius.unit` can't be empty 
- `radius.value` can’t be 0 if the provider supports delivery fulfillment
- `locations.days` should be in sequence, e.g., 1, 2, 3, 4, etc.
- `items.attribute.values` should be in lower case for enums, e.g., gender
- An empty array of `creds` and `offers` should not be provided

### On_search_inc
- `items.time.stamp` should be updated in `on_search_inc`, i.e., whenever the item object is updated

## Ret14

### On_search
- Same as above
- If values for `statutory_reqs_packaged_commodities` are not available, then “NA” should be provided and not an empty string “ ”

## Ret15

### On_search
- At least 2 items should be associated with the variants for the variant to be implemented

## RET16

### On_search
- `"net_quantity_or_measure_of_commodity_in_pkg": "Nil"` is invalid

## Ret18
- Same as above

@nstoretech

**Comment by sandeepshahi** [comment]
- invalid attributes status and timestamp in /search (inc); Remove all the unnecessary attributes from the payloads

**Comment by sandeepshahi** [comment]
Logs approved for BA — RET 13, 14, 15, 16, 18 (subject to above fixes)

@nstoretech
