### ISSUE TITLE
Costbo LBNP  (IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#2659]
"issue":
 "respondent_action": "At least one respondent action is required to have actions as CASCADED /issue api."
 on_issue
  "bpp_id": "Seller app's subscriber id should be bap_id in the context of /issue api when on_issue comes from logistics provider",
   "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /issue api when on_issue comes from logistics provider"
   issue_close:
   "respondent_action": "At least one respondent action is required to have actions as CASCADED /issue api."
    issue_status
   schemaErr0": "/message/issue_id must match format \"uuid\"",
  bpp_id": "Seller app's subscriber id should be bap_id in the context of /issue_status api when on_issue comes from logistics provider",
                "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /issue_status api when on_issue comes from logistics provider"
 on_issue_status
   "schemaErr0": "/message/issue/id must match format \"uuid\"",
    "bpp_id": "Seller app's subscriber id should be bap_id in the context of /on_issue_status api when on_issue comes from logistics provider",
   "bpp_uri": "Seller app's subscriber uri should be bap_uri in the context of /on_issue_status api when on_issue comes from logistics provider",
    "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[2] mismatched with BPP ID"

@AnanthBo

**Comment by AnanthBo** [comment]
![image](https://github.com/user-attachments/assets/75502e02-a685-43de-8f26-e2354622ba03)

Pull 2669 has been submitted with the comments .  @RupalSingla

**Comment by AnanthBo** [comment]
@RupalSingla   any update .

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla   Thank you very much
