### ISSUE TITLE
Shopalyst (SA:RET11) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2695]
### On Search
- /bpp/providers[0]/locations/area_code '302019' doesn't match with the gps area_code '335702'
- Serviceability.category in tags should be ‘F&B’ in case of RET11
- category_ids array is empty for the item_id : ‘F95E844ACA857D0B00447F6E814B963F_4537330_default’ 
- item.category_id should be ‘F&B’  in case of RET11
- item.id length is too big for the item provided with item_id :’ F95E844ACA857D0B00447F6E814B963F_4537330_default’, it should be max ’32’
- Is only 1 item is supported in the full_catalog refresh ?
- Is custom_menu is supported for the ‘F&B’ ?
- invalid format of gps as an extra space is provided : ’26.893584, 75.747359’
 
 
### On Search Inc
- No change was detected for the categories.id 
- Invalid attributes for type: ‘customization’ is there like : ‘@ondc/org/returnable’, ‘@ondc/org/seller_pickup_return’, ‘@ondc/org/cancellable’, ‘@ondc/org/available_on_cod’. Kindly check for others as well
 
### Select
- Timestamp for /on_search api cannot be greater than or equal to /select api
- Invalid format for ’TAT’ provided, It should be like ‘PT2H30M’ instead of ‘PT150M’
- tags.parent.id mismatches for the items[1] as compared to on_search. Kindly check for others as well
 
### On Confirm
- Pan_id shouldn't be same in tax_number and provider_tax_number in message.order.tags[0].list in case of ‘MSN’
 
### On Statu Pending
- How the delivery within the same city can ‘P2H2P’ ?
- Invalid format of gps as an extra space is provided after comma : ’26.893584, 75.747359’
 
## On Status Picked
- Kindly provide a valid invoice, which matches with the given quote.price
- tracking object is missing in the Delivery fulfillment tags as tracking is set to ‘true’ already
 
## On Track
- The provided url is invalid, doesn’t showing any type of route
 
### Select Out Of Stock
- Timestamp for /on_search api cannot be greater than or equal to /select api
- Invalid item found in /select id: ‘DB4211A8CAEB70AB8A7A3DD6A6EB577C_4537328_default’ which doesn’t exist in full catalog refresh
 
### On Select Out Of Stock
- Item’s available and and maximum quantity isn’t reduced in quote.breakup for the out of stock item_id
 
### On Cancel
- tags are missing for backward fulfillments in the items for customized item and customization
- if the quote_trail price is 0 for any item, shouldn’t be added in the quote_trail
-  subtype should be use in the quote_trail if the customization is associated either with ‘tax’ or ‘item’ or ‘customization’
 
### On Cancel RTO
- Why two on_cancels are provided, could you please explain this ?
- tags are missing for backward fulfillments in the items for customized item and customization
- if the quote_trail price is 0 for any item, shouldn’t be added in the quote_trail
- Are you not charging any fees, as the order is already out for delivery ?
-  subtype should be use in the quote_trail if the customization is associated either with ‘tax’ or ‘item’ or ‘customization’
 
### On Update Part Cancel
- JSON cannot be empty
 
### Update Settlement Part Cancel
- JSON cannot be empty
 
### On Update Interim Liquidated
- Start and End Object is not required for the interim call in the ‘Return’ Fulfillment
- Return request for the other 2 items are missing in the ‘Return’ Fulfillment tags
- Are you not charging any fees, as the order is already delivered ?
- if the quote_trail price is 0 for any item, shouldn’t be added in the quote_trail
-  subtype should be use in the quote_trail if the customization is associated either with ‘tax’ or ‘item’ or ‘customization’
 
### On Update Liquidated
- Start and End Object is not required for the interim call in the ‘Return’ Fulfillment
- Return request for the other 2 items are missing in the ‘Return’ Fulfillment tags
- quantity.count is not reduced in the forward fulfillment for liquidated items
 
Kindly provide a curl as well along with the api response and also include the scenario of part cancellation in the flow 6

@Deepanjalitr

**Comment by Deepanjalitr** [comment]
Hi @sahil-ondc, I will resubmit the logs after making the necessary changes
Please help me clear a few doubts
1. item.category_id should be ‘F&B’ in case of RET11 , Serviceability.category in tags should be ‘F&B’ in case of RET11 - So for all the F&B products category_id passed should be F&B ?
2. item.id length is too big for the item provided with item_id :’ - Its the same format that we are using for all other domains which are already in PROD.
3. Why two on_cancels are provided, could you please explain this ? - One was for RTO-Initiated and other one for RTO-Delivered

**Comment by Deepanjalitr** [comment]
@sahil-ondc 

Invalid attributes for type: ‘customization’ is there like : ‘@ondc/org/returnable’, ‘@ondc/org/seller_pickup_return’, ‘@ondc/org/cancellable’, ‘@ondc/org/available_on_cod’. Kindly check for others as well ---> Do we have to pass these properties for customizations? It's not mentioned in spec


Is custom_menu is supported for the ‘F&B’ ? --->  Its not mandatory right?

**Comment by shivang1131** [comment]
## Flow 1
### on_search
- “Yes” is not correct. Should be lower case.
- No need to send “origin” tag in F&B domain.
- Customizations of group 1313447 are not being used anywhere. 
- Catalog is sent incorrectly.
- Is return window of 24H intended from your side?

### on_search_inc
- Please send valid changes such as change in price or availability an item.


Flow 2
- The items that you have selected via select call are not possible with this on_search catalog. Please fix the catalog.

### on_status packed
- Url_enabled tracking was no in on_status pending and is changing here.

### on_status picked
- Prices are not adding up in the invoice.


- It looks like you have submitted same payloads for flow 2 and flow 3 as they have the same transaction_ids. Please resubmit these flows separately.

## Flow 4
### on_confirm
- fulfillments.end will not have time range
### on_cancel
- Cancelled shipment will not have TAT
- Time range would not be there for forward shipment in start and end.


## Flow 5
- Previous issues persist here.
- In food and beverages, the food is usually disposed and not delivered back.

### on_cancel
- Convenience fee not being zeroed in the quote.breakup. 
- RTO shipment will not have TAT.
- Subtype missing in quote_trail for type tax.


## Flow 6
Previous issues persist here.

@Deepanjalitr

**Comment by Deepanjalitr** [comment]
@sahil-ondc @shivang1131 
We have updated the flow based on the feedback from the last submission.

A new file, comments.txt, has been added to address specific flows. It includes details on the fixes we've implemented and notes on certain scenarios that require further clarification. Some of the issues mentioned in the feedback may not align with the original specifications, so we'd appreciate guidance on these points to ensure alignment

**Comment by shivang1131** [comment]
## Flow 1
### on_search 
- Upper range incorrectly captured for F95E844ACA857D0B00447F6E814B963F_4537330_default.

### on_search_inc 
-No need to send “origin” tag in F&B domain.

## Flow 2
- Category in this domain should be “Immediate delivery” in fulfillments/@ondc/org/category.

## Flow 3
Same issues as flow 2

## Flow 5
### on_cancel
- Tax with zero price would not be sent in quote.breakup.
### on_status_picked
- Invoice price does not match quote.breakup.


@Deepanjalitr

**Comment by Deepanjalitr** [comment]
Hi @shivang1131 

I have re-submitted the logs after resolving the issues mentioned last time. 
Note: I have re-submitted the logs only for flows 1, 2, 3, and 5 (Issues were mentioned only for these flows)

**Comment by shivang1131** [comment]
Logs approved for v1.2 @Deepanjalitr

**Comment by Deepanjalitr** [comment]
Thanks @shivang1131
