### ISSUE TITLE
Sellersetu (SA: RET11) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#2713]
### On Search
- Invalid category_id for the item_id : ‘d7212b90-9887-41f1-b9b9-d4b60a01c792’. Kindly check for others as well
- Invalid default_selection.maximum_value for the item_id : ‘d7212b90-9887-41f1-b9b9-d4b60a01c792’
- images are not accessible for the item_id : ‘d7212b90-9887-41f1-b9b9-d4b60a01c792’. Kindly check for others as well
- If timing for ‘Delivery/Order’ is same, kindly use ‘All’ enum
- Invalid category ‘F\u0026B’ in the bpp/providers/serviceability

### Select
- For the non-customizable item, tags are not required in the items

### On Select
- For the non-customizable item, tags are not required in the items and quote.breakup

### On Confirm
- Time.ranges should be provided in on_confirm, if order is auto-accepted

### On Status Picked
- tracking object is missing in the tags of 'Delivery' fulfillment as tracking is already set to 'true'

### On Status Delivered
- The order is not yet ‘PAID’, as the order is delivered already

## Flow 3
- Same as Flow 2
## Select and On Select
- Once the item is out stock, shouldn’t be used in the further action call

## Flow 4
- Same as Flow 2
### On Cancel
- For the non-customizable item, tags are not required in the items in backward and forward fulfillment and in quote.breakup
- sub_type should be used in the quote_trail in case of customization
- If the quote_trail is 0, shouldn’t be added in ‘Cancel’ fulfillment tags

## Flow 5 
- Same as Flow 2
### On Cancel
- Why 'cancel_request' is provided in the RTO fulfillment tags ?
- For the non-customizable item, tags are not required in the items in backward and forward fulfillment and in quote.breakup
- sub_type should be used in the quote_trail in case of customization
- If the quote_trail is 0, shouldn’t be added in ‘Cancel’ fulfillment tags

### On Update Part Cancel
- For the non-customizable item, tags are not required in the items in backward and forward fulfillment and in quote.breakup

### On Update Liquidated
- sub_type should be used in the quote_trail in case of customization

**Comment by Chaitanya-Keyal** [comment]
@sahil-ondc We have resubmitted logs (#2728), please review.

**Comment by sellersetu-hub** [comment]
Hi @sahil-ondc awaiting your reviews here.

**Comment by sahil-ondc** [comment]
## Flow-1
### On_search-
-bpp/providers/locations/circle/value- shouldnt be 500 km.
-bpp/providers/tags.serviceability-f&b can't support pan india serviceability.


## Flow-2
### On_confirm-
-Fulfillment.start.timestamp and Fulfillment.end.timestamp should be provided when order is accepted.

## Flow-3
## On_status_packed
-fulfillment.state.descriptor.code ‘Agent-assigned’ is incorrect.

## on_track
-tracking url is broken. Check for other flow as well.

## Flow- 4
## On_cancel-
-Precancel_state.updated_at timestamp should equal to order.updated_at of precancelled state.

## Flow-5
##on_status_rto_delivered
-fulfillment type rto end/time should be present in /on_status_rto_delivered/disposed when state/desc/code is RTO-delivered".

@sellersetu-hub

**Comment by Chaitanya-Keyal** [comment]
@sahil-ondc We have resubmitted logs for flow 1 and 3 (#2743), please review.

**Comment by shivang1131** [comment]
## Flow 1
### on_search
- No need to send lower and upper ranges for items which are not customisable.
- Upper range calculated incorrectly for d7212b90-9887-41f1-b9b9-d4b60a01c792.


@Chaitanya-Keyal

**Comment by Chaitanya-Keyal** [comment]
@shivang1131 We have resubmitted logs for flow 1 (#2753), please review.
