### ISSUE TITLE
Xpressbazaar (SA: AGR10) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2720]
## On_search
- how is the context.timestamp and items.timestamp, locations.timstamps, etc same? the timestamp should be updated whenever there is a change/update at that level.
- Please use full name for location.state
- circle.radius.value cane only be 500kms max even if the servicability is PAN India
- categories.name should be relevant to the variant & item. eg : name could be sizes for tomato seeds, sizes for rose seeds, etc
- placeholder images should not be provided i.e imag should match product description. eg: in you case you have provided image of lettuce seeds in place of rose seeds for item with id 1d8e604a-ebaf-43d3-8590-8429a551472a.

@deathevil0707

**Comment by sandeepshahi** [comment]
Logs approved for AGR10 (v1.2)

@deathevil0707
