### ISSUE TITLE
STS(SYNERGY_TECHNOLOGY_SERVICES)/Buyer_APP/ RSF(2.0.0) - compliance check

### ISSUE THREAD

**Issue by JyotiSharma0711** [ONDC-Official/v1.2.0-logs#2800]
@Praful-Sakpal 

Please resolve these out

**RSF(2.0.0)**

**flow 1(Success flow)**

- Should have settlements where orders are settled

**report**
- message_id should not be equal to settle

**on_report**
- provider.amount is missing
- provider.id is missing

**flow 2**

**recon**
- orders.settlements.commision is incorrect key
- orders.settlements.status is missing
- orders.settlements.settlement_ref_no additional field

**on_recon**
- orders.settlements.commision is incorrect key
- orders.settlements.settlement_ref_no additional field

**Comment by aakashkanojiya91299** [comment]
> @Praful-Sakpal
> 
> Please resolve these out
> 
> **RSF(2.0.0)**
> 
> **flow 1(Success flow)**
> 
> * Should have settlements where orders are settled
> 
> **report**
> 
> * message_id should not be equal to settle
> * provider.amount is missing
> * provider.id is missing
> 
> **flow 2**
> 
> **recon**
> 
> * orders.settlements.commision is incorrect key
> * orders.settlements.status is missing
> * orders.settlements.settlement_ref_no additional field
> 
> **on_recon**
> 
> * orders.settlements.commision is incorrect key
> * orders.settlements.settlement_ref_no additional field

Could you please explain what is meant by "Should have settlements where orders are settled"? Additionally, I noticed that orders.settlements.settlement_ref_no is listed as a field in the [ONDC NTS Specifications](https://ondc-official.github.io/ONDC-NTS-Specifications/#flow). Could you clarify if it’s an additional field or if there’s any update regarding this?

![image](https://github.com/user-attachments/assets/d3943d87-d32c-4f25-b6a7-b39c4ce908ce)

**Comment by JyotiSharma0711** [comment]
Based on the discussion in the community call:
Identify the errors being returned by the mock server and focus on refining only the payloads being sent to it.

**Comment by Praful-Sakpal** [comment]
Hi @JyotiSharma0711 

I made the changes in the following [PR ](https://github.com/ONDC-Official/v1.2.0-logs/pull/2810) please merge and review it.

**Comment by JyotiSharma0711** [comment]
@Praful-Sakpal 

Logs approved for RSF 2.0
