### ISSUE TITLE
Paytm Seller App - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#282]
1. Search_OnSearch:
- location "1031222" is in provider.locations and all items are assigned to this location; however, timing & serviceability is defined for different location "rt4uzx3n";
- short_desc / long_desc / images not defined for custom menu;
- bpp/providers.fulfillments has id "F1" defined for delivery; however, different fulfillment id is assigned to items (100160);
- item 1235217312:
- - unitized is mandatory;
- - difficult to figure out which is base item / customization without tags.type being defined for each item;
- - why is config being redefined for custom groups 159001, 157897 when there's no change in min/max/seq?
- - for item with base price of 0, either default selection price or range (lower/upper) should be defined so buyer app can show a price on the provider listing page;
- - contact_details_consumer_care format is invalid: need name, contact no, email id;
- - serviceability (location.circle), store timing in the old format is required until everyone starts supporting the new formats in 1.2 phase 2;
2. Select_OnSelect:
- can't find customizations 1235193295/1235188643 in on_search catalog;
3. Confirm_OnConfirm:
- default fulfillment state of "Pending" missing;
- bpp_terms duplicated in /on_confirm;
- /confirm should have "bap_terms", with tax no of buyer NP;
4. On_Status:
- pickup time (fulfillment.start.time.timestamp) should be updated only after order is picked up;
- delivery time (fulfillment.end.time.timestamp) should be updated only after order is delivered;
Following are also required:
- search/on_search with variants;
- on_select with out of stock for item / customizations;
- other APIs(cancel, cancel with RTO, return, tracking APIs);
- on_status logs for all state transitions (Pending -> Packed -> Order-picked-up -> Out-for-delivery -> Order-delivered); only Pending / Packed are provided;
- pls submit logs for the "Group B" test scenarios [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795);

**Comment by BLR-0118** [comment]
@Anupam1705

**Comment by Anupam1705** [comment]
2. Select_OnSelect:
can't find customizations 1235193295/1235188643 in on_search catalog; >> Since Search/On_Search logs are between ONDC Buyer Reference App and Paytm Seller App and other transactional api logs are between Paytm buyer and Paytm Seller.
3. Confirm_OnConfirm:
default fulfillment state of "Pending" missing; >> This is already been passed under state.descriptor.code as Pending in on_confirm api
4. On_Status:
on_status logs for all state transitions (Pending -> Packed -> Order-picked-up -> Out-for-delivery -> Order-delivered); only Pending / Packed are provided; >> These are already been provided for all the states under on_status.json file for respective cases
@BLR-0118

**Comment by BLR-0118** [comment]
2 - why can't you send these customizations to ONDC buyer app (like others which you're sending)? without this, it's difficult to follow the flow;
3 - ok;
4 - not clear how the seller app is setting these statuses?
@Anupam1705

**Comment by BLR-0118** [comment]
1. Search_OnSearch:
- tag code "non-veg" is not valid; should be "non_veg";
- contact_details_consumer_care is not consistent - check diff b/w item ids 1235193883, 1235193881;
- what does time_to_ship of PT0M mean - product is ready, packed & ready to ship?
- difficult to figure out which is base item / customization without tags.type being defined for each item;
- why is config being redefined for custom groups 157920 when there's no change in min/max/seq?
- no data for item with base price of 0, either default selection price or range (lower/upper) should be defined so buyer app can show a price on the provider listing page;

**Comment by cheena-jain** [comment]
Search_onSearch

- why is config being redefined for custom groups 157920 when there's no change in min/max/seq?
This we are trying to keep it as close as what the vendor is sending. Since they are sending multiple custom group with same min/max/seq and using it for different products we have to maintain a one to one mapping of both the entities.

- no data for item with base price of 0, either default selection price or range (lower/upper) should be defined so buyer app can show a price on the provider listing page;
We don't have a use case of main item being of price 0 so this case should not occur.

**Comment by BLR-0118** [comment]
1. Search_OnSearch:
- Context.timestamp for /on_search same as /search;
- definition of nested customization group for item 1235222936 incorrect (should be as defined [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.jgj38hso0lnk)); there are other items with this incorrect definition;
- what's the type for item 1235217194 - non-customizable SKU? Name looks more like customization but no type defined; (other similar items such as 1235193827);
- only supported unit for serviceability for hyperlocal is "km";
2. Select_OnSelect [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/Paytm/SellerApp/V1.2%20Paytm%20Seller%20Logs/With%20Customisation%20and%20Variant):
 - inside quote, item unit prices are based on item.price.maximum_value instead of item.price.value;
 - need usecase for customization out of stock / base item out of stock;
 - provider.locations should be added (it's there in order object in all other APIs);
3. /on_status (packed):
- how to interprete Context.message_id here - :SentTimeStamp:1702908054269: as it's the same in /confirm as well?
4. /on_track:
- since time for which gps coords sent will be earlier than when it's updated, tracking.location.updated_at > tracking.location.time.timestamp;
5. /on_cancel (rto initiated & rto delivered):
- order.state of "CANCELLED" is invalid (should be "Cancelled");
- item audit trail is incorrect (should show count of 0 for forward shipment fulfillment) & the entire count assigned to RTO fulfillment;
- since this is due to reason "011", why isn't /cancel from buyer app included in logs?

**Comment by BLR-0118** [comment]
@Anupam1705

**Comment by BLR-0118** [comment]
1. Select_OnSelect (with customisation and variant):
- customization group 157896 is defined with config of 0 min, 1 max in the catalog; however, in /select, the buyer is able to select 2 customizations for this customization group. This is incorrect;
2. Select_OnSelect (normal product -> out of stock - customized product):
- /select includes 2 items & 1 customization (1235220266, 1235188621, 1235193885) and all these items have quantity in /on_select quote exactly the same as in /select; hence, not clear what's out of stock??
- error message for item/customization out of stock should follow the format [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.sug2402chw6z);
3. Merchant Cancel (/on_cancel):
- request you to follow the payload as defined [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec) (exactly same as for RTO);
4. Need customizable item with base price of 0 & customizations with price > 0 as explained in test scenarios [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795);

pls resubmit logs only for the above;

**Comment by BLR-0118** [comment]
@deepalibansal_bitbucket

**Comment by BLR-0118** [comment]
1. Incremental update:
- location.time.timestamp is 2023-12-28T11:06:31.565Z while Context.timestamp is 2023-12-28T11:06:31.005Z, i.e. location disable event is future timestamp, which is invalid;
- product_incremental: not sure what's exactly being updated: items 1235193882, 1235193883, etc. have exactly the same data as in the full catalog pull;

2. Full catalog pull:
- point 4 above is a common usecase in F&B and customizable item(s) corresponding to this has to be shared;
- out_of_stock for customization with correct error format to be shared (ok for item);

3. Cancel_OnCancel:
- quote.breakup format has changed from /on_confirm (parent_item_id, custom group info missing);
- cancel reason code 004 is invalid (use one of the reason codes from [here](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031));

4. Pls share following info:
- Jira ticket no for 1 above;
- Jira ticket for support for location.circle, location.timings;

**Comment by BLR-0118** [comment]
@Anupam1705

**Comment by BLR-0118** [comment]
1. /on_select (out of stock - normal product) [here](https://github.com/ONDC-Official/v1.2.0-logs/blob/master/Paytm/SellerApp/V1.2%20Paytm%20Seller%20Logs/Normal%20Product/Out%20Of%20Stock%20-%20Normal%20Product/Select%3AOn_Select(OOS).json):
- item 1235193883 is out of stock and following details are in quote.breakup:
- qty = 0 (correct);
- item unit price = 60 (correct);
- total price = item unit price * qty should be 0 (shown as 60);

Following are open issues which need to be fixed subsequently (with corresponding jira ticket nos):
- support for serviceability, store timings in provider.location - [PROD-3929](https://ondc-issue-logging-cohort1.atlassian.net/jira/software/c/projects/PROD/issues/PROD-3929);
- support for default selection for customizable item with base price of 0 - [PROD-3931](https://ondc-issue-logging-cohort1.atlassian.net/jira/software/c/projects/PROD/issues/PROD-3931);

**Comment by BLR-0118** [comment]
logs cleared subject to 1 above being fixed

**Comment by BLR-0118** [comment]
@Anupam1705

**Comment by Anupam1705** [comment]
@BLR-0118  Somehow, older payload is being sent here, will update it and send by today, this has already been fixed.

**Comment by Anupam1705** [comment]
@BLR-0118  please do check the PR https://github.com/ONDC-Official/v1.2.0-logs/pull/416 for OOS Price update

**Comment by BLR-0118** [comment]
issue 1 above - verified as fixed;
@Anupam1705
