### ISSUE TITLE
Myy_shop -api.lokal- (SA:RET-10)-Compliance check

### ISSUE THREAD

**Issue by FarheenNazQA** [ONDC-Official/v1.2.0-logs#2839]
### On_search
-Invalid EAN no. for item_id-66b06362dc0e24f612a2c6d2.Check for others.

### On_search_inc
-No such delta found in On_search_inc.

### On_status_pending-
-fulflilment.start.range-how the start and end time difference is too less.,when in On_select TAT is 6H?
-
### On_status_packed-
-Routing should be there.

### On_cancel-
-There should not be delivery charges when order is cancelled in pre-shipment

### On_status_RTO_delivered.
-fulfillment.end.timestamp should be provided in this call.

@Srinath91

**Comment by sandeepshahi** [comment]
Duplicate Issue board; Refer [here](https://github.com/ONDC-Official/v1.2.0-logs/issues/120) for the updates

@Srinath91
