### ISSUE TITLE
Channelier (SA: AGR10, RET1A) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2844]
# Channelier

#### on_search
- How can `accept_bap_terms` be used when the buyer has not provided the static terms?
- `items.parent_item_id` is not required when there are no customizations.
- placeholder values should not be provided. Eg:https://example.com/images/valve1.jpg

#### on_search
- How can `accept_bap_terms` be used when the buyer has not provided the static terms?
- `items.parent_item_id` is not required when there are no customizations.

#### on_search_inc
- no changes found in the item apart from item.timestamp

@itsRajatkumar

**Comment by Jagannath-wits** [comment]
# Channelier

---

## RET1a

### on_search
- **Only `bpp_terms.np_type` should be provided** *(repeated issue)*.
- **Support for variants is mandatory**.
- Must have required property `items.unitized.measure`.
- `items.parent_item_id` is **not required** when there are no customizations *(repeated issue)*.
- **Placeholder values should not be provided**. Example: Images should match the item description *(repeated issue)*.
- `bpp_id` `integrations-test.channelier.com/ondc` is **not a subset of ** in `BppUri` `https://integrations-preprod.channelier.com/ondc`.
- If timing for both delivery and order is the same, then `tags.timings.type` should be set to `'All'`.
- `items.tags.attributes.new_arrivals` should be a **string** and not a **boolean**. Refer to the [attribute sheet](https://docs.google.com/spreadsheets/d/1pl0mOZqFmYsN2YImA5MWkigYOu0kL_qK29GueYqgVcs/edit?gid=599325783#gid=599325783).

### on_search_inc
- `auto_parts_attributes` key is invalid.

---

## AGR10

### on_search
- **Only `bpp_terms.np_type` should be provided**.
- `items.parent_item_id` is **not required** when there are no customizations.
- Images for items are **not accessible** (requires Google Drive authentication).
- Accessible images **do not match the mentioned product**. Example: Agri product contains sport shorts in the image link.

---

### **Note:**  
Please fix all listed issues before resubmission to avoid multiple iterations.

**Comment by itsRajatkumar** [comment]
@Jagannath-wits we have fixed all the issues as you mentioned. please review. 
#2918

**Comment by Jagannath-wits** [comment]
Logs approved for AGR10 & RET1A
@itsRajatkumar
