### ISSUE TITLE
SellerSetu/BPP/RSF(2.0.0) - compliance check

### ISSUE THREAD

**Issue by JyotiSharma0711** [ONDC-Official/v1.2.0-logs#2851]
**SellerSetu/BPP/RSF-2.0**

**common error**
context/bpp_uri, bap_uri of action and on_action call are different

**Flow 2**

**settle**
context.ttl should be P1D for settle call

**recon**
Message/orders/0/settlements/0/updated_at- time is not in ISO 8601 format.

@Chaitanya-Keyal  Please resolve these errors

**Comment by Chaitanya-Keyal** [comment]
@JyotiSharma0711 
> context/bpp_uri, bap_uri of action and on_action call are different

The rsf mock service is responding with different `bpp_id` and `bpp_uri`. Not sure how we can fix this.

## Flow 2
> context.ttl should be P1D for settle call

`context.ttl` is `P1D` for both the settle calls. Could you please check again?

> Message/orders/0/settlements/0/updated_at- time is not in ISO 8601 format.

Will fix this and resubmit logs for Flow 2.

Thanks and do let us know if there's anything wrong in the above conclusions.

**Comment by Chaitanya-Keyal** [comment]
@JyotiSharma0711 PR #2852 raised with fixed flow 2 logs, please review.

**Comment by JyotiSharma0711** [comment]
**SellerSetu/BPP/RSF-2.0**

Resolve this out for all flows

**recon**
Message/orders/0/settlements/0/updated_at- time is not in ISO 8601 format.

**Comment by JyotiSharma0711** [comment]
@Chaitanya-Keyal 
Logs approved for RSF v2.0.0
