### ISSUE TITLE
Shopalyst COD FLOW (SA: RET-14) Compliance Check

### ISSUE THREAD

**Issue by FarheenNazz** [ONDC-Official/v1.2.0-logs#2853]
### On_select
- message/order/quote/breakup/0/item/quantity/available/count: Available count must be either 99 or 0 only.
- message/order/quote/breakup/0/item/quantity/maximum/count must a reasonable amount or use the enum ’99’ for no limit.
- fulfillments[0]/@ondc/org/TAT (P7D) in /on_select can't be equal to @ondc/org/time_to_ship (P7D) in /on_search.

### Init
- How was one item removed in init?

### On_confirm
- provider_tax_number: Must be present for on_confirm as well; audit trail must be mantained.

### On_status_pending
- fulfillment.time.ranges should be provided in the startand end object when the Order state is “Accepted.”

### On_status_picked
- Invoice document is missing.

@adarsh-surendran-sl

**Comment by Jagannath-wits** [comment]
### on_select
- message/order/quote/breakup/0/item/quantity/maximum/count must a reasonable amount or use the enum ’99’ for no limit.

### init
- How was one item removed in init? Audit trail must be mantained.

### on_status_picked
- Invoice document is inaccessible.

@adarsh-surendran-sl Please fix all issues before resubmission

**Comment by adarsh-surendran-sl** [comment]
**on_select issue** - Fixed

**Init Issue**- We were testing from [pramaan](https://pramaan.ondc.org/) We passed the details of two items in on_select but received only one item in init . It is an issue from pramaan's side .

**on_status_picked Issue** - Prod will have right invoice url , preprod invoice urls are inaccessible.

pr : https://github.com/ONDC-Official/v1.2.0-logs/pull/2927
@Jagannath-wits

**Comment by Jagannath-wits** [comment]
> **on_select issue** - Fixed
> 
> **Init Issue**- We were testing from [pramaan](https://pramaan.ondc.org/) We passed the details of two items in on_select but received only one item in init . It is an issue from pramaan's side .
> 
> **on_status_picked Issue** - Prod will have right invoice url , preprod invoice urls are inaccessible.
> 
> pr : #2927 @Jagannath-wits

- Please get the init issue fixed as items getting reduced is a serious issue and you should nack it 
- Invoice issue can be ignored 

@adarsh-surendran-sl

**Comment by adarsh-surendran-sl** [comment]
@Jagannath-wits 
We fixed all the issues.

PR : [https://github.com/ONDC-Official/v1.2.0-logs/pull/2936](url)

**Comment by Jagannath-wits** [comment]
@adarsh-surendran-sl Found no issues in COD Flow SA:RET14
