### ISSUE TITLE
Costbo (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/v1.2.0-logs#286]
Flow 1
on_issue
- context.message_id has changed
- please check updated_by.org.name, different subscriber id from context and extra spaces in between
- There is a variance of upwards of 1.5 hours between respondent_actions.updated_at and issue.updated_at, please check 

on_issue_status
- context.timestamp less than on_issue API's context.timestamp
- issue.updated_at is missing

on_issue_status
- context.message_id is the same as issue OPEN api call
- please check updated_by.org.name, different subscriber id from context and extra spaces in between
- There is a variance of upwards of 1.5 hours between respondent_actions.updated_at and issue.updated_at, please check 
- please check respondent_info.organization.org.name; colons misssing

@AnanthBo

**Comment by AnanthBo** [comment]
@Rishabh-ondc  
Thank you for the comments.  Have fixed the requested comments in the  #297   (has New RSF commit & Retail + IGM fixes)
https://github.com/ONDC-Official/v1.2.0-logs/pull/297
#297 for RSF logs. - New +. Fixed push of #286 & #172 issue comments.

**Comment by AnanthBo** [comment]
@Rishabh-ondc ,   Please give us a good news...if we are through with IGM log ?

**Comment by AnanthBo** [comment]
@Rishabh-ondc  ,  Could you please let us know - any comments on IGM logs.   PR https://github.com/ONDC-Official/v1.2.0-logs/pull/297  has the requested fixes for IGM.

**Comment by Rishabh-ondc** [comment]
on_issue_status
- context.message_id has changed
- issue.updated_at has changed

@AnanthBo

**Comment by AnanthBo** [comment]
@Rishabh-ondc      Issue.updated_at.   <. we are updating the time..when the business/provider updates the record.  Should we keep updated...only for the buyer or client updates only ?   please clarify.

**Comment by AnanthBo** [comment]
@Rishabh-ondc   Thanks for clarification.     below are the logs pushed in PR#370
Below Pull has the IGM logs. requested for recent comments.  Please review & let me know.

https://github.com/ONDC-Official/v1.2.0-logs/pull/370
Has:  Retail latest repush & IGM repush the latest test logs

**Comment by AnanthBo** [comment]
@Rishabh-ondc Could you please review COSTBO IGM flow from PR #286 & comment on issue board #286

**Comment by Rishabh-ondc** [comment]
Please check the on_issue payload provided. It captures details outside of the IGM API schema as well. respondent_actions object being shared twice in two different payloads and issue.updated_at is changing

@AnanthBo

**Comment by AnanthBo** [comment]
@Rishabh-ondc  Thank you very much for your comments.  Have fixed and updated part of PR#445   https://github.com/ONDC-Official/v1.2.0-logs/pull/445

**Comment by AnanthBo** [comment]
@Rishabh-ondc   can you help on this today please.

**Comment by AnanthBo** [comment]
@Rishabh-ondc ,  Rishabh - could you possibly update us  early today.

**Comment by Rishabh-ondc** [comment]
on_issue_status
- issue.updated_at has changed over on_issue and on_issue_status, please check

Clarifications
- cascaded_level should be number type, please check

@AnanthBo

**Comment by AnanthBo** [comment]
@Rishabh-ondc   Could you let us know, when the updated_at should change by the seller NP ? We are trying to change when there is the change in the "respondent_action". ex: ON_issue. (where the state is changing to processing), ON_issue_status unsolicited (when status is changing to Resolved) and ... We are not changing , when there is no "respondent_action" Change.  Please clarify

**Comment by Rishabh-ondc** [comment]
Please check the payloads provided. 'issue.updated_at' has changed between the two payloads of "on_issue" and "on_issue_status" with no change in the trail.

**Comment by AnanthBo** [comment]
Thanks Rishabh for support and clarification.   PR#489 for IGM has been pushed.

**Comment by AnanthBo** [comment]
@Rishabh-ondc Preprod Buyer APPv2 is just fixed.  I have provided video PW & logs i have attached. to PR IGM PR#589. (after buyerapp fix) .  Please review & approve

**Comment by AnanthBo** [comment]
@Rishabh-ondc   Could you please review and approve ?

**Comment by RupalSingla** [comment]
issue
-             "updated_at": "The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in issue"

  on_issue": 
-             "Phn": "Phone Number for /on_issue api is not in the valid Range"

@AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla     

1). Issue comment does not belong to SellerNP.  its a buyer app Issue,  we will send a email to Pratik to fix it. 
2). Phone Format is fixed (removed +91).  Thank you for clarification.    Pushed part of PR#631 

Request to review and approve at the earliest.

**Comment by AnanthBo** [comment]
@RupalSingla ,   Can you please comment on the Logs.  crossed 5+days.   please check

**Comment by Rishabh-ondc** [comment]
Logs cleared. 

@AnanthBo
