### ISSUE TITLE
Aurikatech (BA: RSF 2.0) - compliance checks

### ISSUE THREAD

**Issue by ParneetkaurDev** [ONDC-Official/v1.2.0-logs#2884]
@akhtarmdsaad please fix these issues.
# Flow Analysis Report

### Recon
- `Message/orders/0/amount/value` - **Mismatched** with the value in the `on_recon` call. *(Doubt)*  
- `Message/orders/0/settlements/0/id` - **Mismatched** with the settlement ID in the `on_recon` call.  
- `Message/orders/0/settlements/0/payment_id` - **Value is missing**.  
- `Message/orders/0/settlements/0/settlements_ref_no` - **Value is missing**.  

### ON_Recon
- `Message/orders/0/settlements/0/payment_id` - **Object field is missing**.  
- `Message/orders/0/settlements/0/settlements_ref_no` - **Object field is missing**.  

---

### Recon
- `Message/orders/0/amount/value` - **Mismatched** with the value in the `on_recon` call. *(Doubt)*  
- `Message/orders/0/settlements/0/id` - **Mismatched** with the settlement ID in the `on_recon` call.  
- `Message/orders/0/settlements/0/payment_id` - **Value is missing**.  

### ON_Recon
- `Message/orders/0/settlements/0/payment_id` - **Object field is missing**.

**Comment by akhtarmdsaad** [comment]
Updated logs in PR #2897

**Comment by akhtarmdsaad** [comment]
Thanks parneet for the update. you can close this issue now
