### ISSUE TITLE
ShopEG SA:RET10 - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2960]
Log approved for ShopEG SA:RET10
@bsaha12beyseek

**Comment by bsaha12beyseek** [comment]
@Jagannath-wits Logs were submitted for RET 12 but I see it's approved for RET10, Can you clarify this ??

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits Logs were submitted for RET 12 but I see it's approved for RET10, Can you clarify this ??

Hope its clear now

**Comment by bsaha12beyseek** [comment]
Yes Its clear now
