### ISSUE TITLE
Sabhyasha ( RSF 2.0 ) - Compliance Check

### ISSUE THREAD

**Issue by JyotiSharma0711** [ONDC-Official/v1.2.0-logs#2980]
# Sabhyasha/RSF 2.0

### Settle and On_settle

**Provider ID**: message/settlement/orders/0/provider/id are additional fields according to the API contract.

### Report and On_report

**Provider ID**: message/settlement/orders/0/provider/id are additional fields according to the API contract.

---

### Report and On_report

**Transaction ID**: context/transaction and ref_transaction_id should not match with each other.
**Provider ID**: message/settlement/orders/0/provider/id are additional fields according to the API contract.

---

### Settle and On_settle

**Provider ID**: message/settlement/orders/0/provider/id are additional fields according to the API contract.

### Report and On_report

**Object/Body**: Is an additional field.
**Provider ID**: message/settlement/orders/0/provider/id are additional fields according to the API contract.

---

### Settle and On_settle

**Collector App ID**: message/settlement/collecter_app_id is an additional field.
**Receiver App ID**: message/settlement/receiver_app_id is an additional field.

@Pratik-ZenithDjangoDev

**Comment by Pratik-ZenithDjangoDev** [comment]
Hi @JyotiSharma0711 ,

I would greatly appreciate your clarification on the specific points raised so I can address them correctly.
Below are the issues highlighted, along with my understanding and queries:

Flow 1
Issue: Provider ID (field: message/settlement/orders/0/provider/id) is considered an additional field as per the API contract.
Query: Should the provider part be omitted from my logs for settle, on_settle, report, and on_report?
However, as per the contract, my understanding is that as the MSN, I am required to settle the amount to the Seller on Record. Can you confirm if my interpretation is correct?
Flow 2
Issue: Transaction ID (fields: context/transaction and ref_transaction_id) should not match with each other.
Query: Does this mean I should ensure unique transaction IDs for report and settlement calls?
Flow 4
Issue 1: Object/Body is flagged as an additional field.
Query: Could you please clarify what this refers to and what needs to be corrected?
Issue 2: Provider ID (field: message/settlement/orders/0/provider/id) is flagged as an additional field, similar to Flow 1.
Query: Should this field be removed entirely from the logs?
Flow 5
Issue:
Collector App ID (field: message/settlement/collector_app_id) is flagged as an additional field.
Receiver App ID (field: message/settlement/receiver_app_id) is flagged as an additional field.
Query: Could you please clarify what changes are required here?
I would be grateful if you could confirm whether the logs I submitted are correct or if there are specific changes I need to make. Kindly help me understand these issues better by providing detailed guidance.

**Comment by Pratik-ZenithDjangoDev** [comment]
Hi @JyotiSharma0711 Good Morning , Your quick prompt will help us to resolve the issues and submit the Logs again . Please kindely describe the above points .

**Comment by JyotiSharma0711** [comment]
@Pratik-ZenithDjangoDev 
Approved logs for RSF 2.0
