### ISSUE TITLE
KNS Retail (SA : RET10) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2997]
### on_search
- Fulfillments.creds placeholder values should not be provided in creds; if not enabled at your end please don’t provide. Also, the creds.id is a globally identifiable identity or unique ID provided by seller app; mandatory if creds are provided.
- creds.time_from and time_to should be in rfc3339 datetime format.
- Creds.url should be valid as well
- Either @ondc/org/statutory_reqs_packaged_commodities or @ondc/org/statutory_reqs_prepackaged_food should be provided, both are not required
- Servicability for Fruits and Vegetables can’t be PAN India

@VirajjKAS

**Comment by VirajjKAS** [comment]
Hey @Jagannath-wits , For uat we are sending dummy creds data for logs validation is it necessary to add creds json ? Otherwise, we will remove creds field

**Comment by Jagannath-wits** [comment]
> Hey @Jagannath-wits , For uat we are sending dummy creds data for logs validation is it necessary to add creds json ? Otherwise, we will remove creds field

No as mentioned, creds should only be sent if implemented at your end, else you can skip it.

**Comment by Jagannath-wits** [comment]
@VirajjKAS Why are variants not implemented this time ?
