### ISSUE TITLE
Vidyant - compliance checks

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#3]
1. /search:
- finder_fee_type should be "percent" (lower case);
2. /on_search:
- bpp_id can't have "https" prefix;
- holidays only has the date, not time;
- categories[].id can't be > 12 chars;
- variant group attr name should start with item, i.e. "item.tags.attribute.colour";
- items[].id shouldn't have space;
- only item attributes defined in contract should be a part of the catalog (all item attributes (key/value pair) added should be shared so we can review & add to contract if required);
3. /on_select:
- TAT of 24h should be next day delivery (check applicable enums from [here](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit));
- all title_type are lowercase (check "Delivery");
- item.quantity.available.count is 99 in /on_search but 266 here. We're proposing to use "99" as the default value to indicate inventory is available (& doesn't refer to actual inventory);
4. /on_init:
- remove cancellation_terms, bpp_terms as these aren't in phase 1 (will be finalized shortly);
- remove provider_location (deprecated - everything highlighted in yellow means deprecated);
- finder_fee_type should be lower-case "percent";
5. /confirm:
- remove "user" block;
Also, lots of places, I'm seeing json copied from the contract doc; if you need any help interpreting any sections of the contract, pls let me know

**Comment by BLR-0118** [comment]
@AtitiTranzita @get2abhi

**Comment by AtitiTranzita** [comment]
@BLR-0118 

Thank you for your time and consideration. 

**Point2**: 

- **categories[].id can't be > 12 chars;** - We are using firestore(NoSQL) database that has more than 12 character as documentID.

- **only item attributes defined in contract should be a part of the catalog (all item attributes (key/value pair) added should be shared so we can review & add to contract if required);** - We will share the attribute json map. "Is all the item attributes(key/value pair) are mandatory for a product"? It is not necessary that all the product has same number of attributes.

We will improve the logs and create the PR again.

**Comment by AtitiTranzita** [comment]
**@BLR-0118** 

Hi Supriyo,
We have created new PR after fixing these issues. Please find the link below for your reference.

[https://github.com/ONDC-Official/v1.2.0-logs/pull/4]

Thank You

**Comment by bluecypher** [comment]
#### Note: Incremental catalog should not contain full catalog information; refer to the example scenarios [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wvmzobfqz9zt)

**inc_request**

- city must be "\*" in incremental pull request

**inc_response**

- bpp/fulfillments is required in full catalog pull as part of phase 1
- inaccurate geocoding of gps and address of store location in bpp/providers/locations
- categories/id must be upto 12 characters
- variant group attr name must start with item (instead of items)
- category_id must be one of the category ids defined in [enhanced subcategory list](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843)
- mapping of attributes and category_id must be as defined in the enhanced subcategory list
- serviceability must be defined for the all categories present in /items/category_id

**inc_regular_response**

- context/transaction_id must be the same as in /search request

**inc_regular_response_stop**

- invalid response; unsolicited incremental push must be stopped once mode = "stop" is received in /search reqeust


@AtitiTranzita @get2abhi

**Comment by AtitiTranzita** [comment]
Hi Sandeep,

We have fixed all the points mentiond above except -

   - categories/id must be upto 12 characters  --- We are using
   firestore(NoSQL) database that has more than 12 character as documentID.

And need to more clarification over these points:

   - mapping of attributes and category_id must be as defined in the
   enhanced subcategory list
   - serviceability must be defined for the all categories present in
   /items/category_id

Can we schedule a quick connect to discuss these points?

Thanks and Regards
Atiti Singh
SDE-1
Ph: +91 9129785903

https://seller.shopcircuit.ai/

**Comment by AtitiTranzita** [comment]
Hey Supriyo,

We have fixed all the points mentioned above and created pull request
please find the PR link below:

https://github.com/ONDC-Official/v1.2.0-logs/pull/39

Thanks and Regards
Atiti Singh
SDE-1
Ph: +91 9129785903

https://seller.shopcircuit.ai/

**Comment by bluecypher** [comment]
#### Incremental pull should only contain delta changes; refer to the example scenarios [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wvmzobfqz9zt)

**Changes required in catalog:**

- minimum 6 digit of decimal precision for gps coordinates must be provided in /locations/gps
- duplicate serviceability should not be provided
- attribute enums must be correct (in lowercase and as mentioned in the [enums doc](https://github.com/ONDC-Official/protocol-network-extension/tree/main/enums/retail))



@AtitiTranzita @get2abhi

**Comment by AtitiTranzita** [comment]
Hey Supriyo & Sandeep,

We have fixed all the points mentioned above and created pull request
please find the PR link below:

https://github.com/ONDC-Official/v1.2.0-logs/pull/56


Thanks and Regards
Atiti Singh
SDE-1
Ph: +91 9129785903

https://seller.shopcircuit.ai/

**Comment by bluecypher** [comment]
### Inc Catalog

- bpp/descriptor, bpp/fulfillments, bpp/providers/fulfillments, bpp/providers/descriptor, bpp/providers/locations/gps, bpp/providers/locations/address, bpp/providers/categories, bpp/providers/tags are not required for inc catalog; refer to all the possible scenarios [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.djsf0iwfuobp)
- Hexadecimal notation for attribute/colour should have '#' preceding the colour code


@AtitiTranzita @get2abhi

**Comment by bluecypher** [comment]
@AtitiTranzita, all the previously identified issues should be resolved

- context/city should be "\*"
- full catalog info should not be provided in incremental refresh; only the information that has been modified since the last full pull should be included as per the [scenarios](https://docs.google.com/document/d/1aRzox3_Dq0Q_SicIaKegdU7FpM5q8R1rjrA6vi8qF0E/edit#heading=h.wvmzobfqz9zt).

Payloads must be provided as per the [test case scenarios](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795) defined

**Comment by bluecypher** [comment]
**/search (full_catalog)**

- context/city can't be "\*" in full catalog pull; city-wise search should be initiated

**/on_search (full_catalog)**

- size_chart attribute is missing in /items/tags/attribute

**incremental_on_search (for_store_loc_change)**

- provider 4d9SWhgRiiydZM9gtjr0 is already disabled in the previous call; enabling a particular store is not relevant
- locations/time/range is not required in the case of store enabling

**/select**

- context/city can't be \* in /select and subsequent calls
- provider: "4d9SWhgRiiydZM9gtjr0" and item: "7B3TxEYtHKV5o2APsduU_colour-000000_size-S" are disabled; order should not be processed

**/on_select**

- context/city should be the same as the city in the request call
- "@ondc/org/TAT" in /fulfillments should be in valid ISO8601 duration format; (P5D instead of PT5D)
- "@ondc/org/category" and "@ondc/org/TAT" mapping should be correct (can't use "Next Day Delivery" for a TAT of 5 days)
- order should not be processed for disabled item(s) and provider

**/init**

- context/transaction_id can't change
- fulfillment_id can't change; should remain the same as provided in /on_select
- area_code of location can't change in /fulfillments
- phone number should be of 10 digits in /fulfillments/end/contact/phone and /billing/phone

**/on_init**

- provider_location in /order is missing; should be provided until deprecated

**/confirm**

- payment/params/transaction_id can't be the same as context/transaction_id

**/on_confirm**

- invalid value of order timestamps "created_at" and "updated_at"
- invalid value of estimated pickup (/fulfillments/start) and delivery (/fulfillments/end) timestamps; can't be past dated

### - status updates through unsolicited calls, Flow 3, 4 and 5 are missing


@AtitiTranzita

**Comment by AtitiTranzita** [comment]
@sharmasahil0331 

We have fixed the above mentioned complaince issues, please check it here:
[https://github.com/ONDC-Official/v1.2.0-logs/pull/141]

**Comment by bluecypher** [comment]
**/on_search**

- item.available.count should be either 99 (inventory available) or 0 (out-of-stock)
- item.maximum.count should be either default value 99 (no cap per order) or any other +ve value (cap per order)
- HSN code 120799 is invalid for category_id = "T Shirts"

**/on_search (incremental)**

- unsolicited /on_search calls should have unique context/message_id
- store location disable: range should only be provided for temporary store closure; "disable" is used for permanent closure

**/select**

- inaccurate mapping of gps and area_code in /fulfillments/end/location

**/on_select**

- "5 Day Delivery" is not a valid @ondc/org/category; Standard Delivery can be used instead

**/confirm**

- "static_terms" in /tags are not provided in /search

**/on_confirm**

- instructions in /start and /end can't have placeholder values
- estimated pickup (start/time) and delivery(end/time) time ranges can't be the same

**/on_status**

- all the fulfillment states should be provided through unsolicited calls 
- actual pickup timestamp (start/time/timestamp) and delivery timestamp (end/time/timestamp) can't be provided when state is Agent-assigned
- message_id of unsolicited /on_status calls should be unique
- values can't be dummy in /on_status

**/on_select (OOS)**

- count should be 0 for OOS item in quote/breakup/@ondc/org/item_quantity


@AtitiTranzita

**Comment by BLR-0118** [comment]
Flow 1
====
1. full_catalog_search_1:
- remove bap_terms from here & incremental search) as static terms aren't enabled yet;
2. full_catalog_on_search_2:
- provider (4d9SWhgRiiydZM9gtjr0) has 2 locations (*-location-2, *-location-3) but all items assigned to *-location-3; why is *-location-2 defined & can't the catalog be optimized to only include locations with SKUs?
- can you also include the following deprecated attrs: location.time.days, location.time.range.start & end (for timings in the old format) and location.circle.* (radius-based serviceability in old format) - this will help as the new formats for these (which you've defined will be enabled by all in phase 2 & without these, your catalogs won't show up in some buyer apps);
- search with Context.city is "080", but catalogs returned are for stores in Lucknow; instead of this, why don't you do Context.city as Lucknow ("0522");
3. incremental_on_search(provider_changes_disable_4):
- ttl here should be removed as it doesn't mean anything in any of the incremental catalog responses;
4. incremental_on_search(store_loc_change_close_6):
- what does closing a store (*-location-1) which is not in full catalog pull mean? 
5. incremental_on_search(store_loc_change_enable_7):
- what does enabling a store (4ds*location-1 - isn't in full catalog pull & not disabled previously) mean?

Flow 2
====
1. /on_init:
- "collect_payment" is "Y" in /full_catalog_on_search_2 but payment link is not sent here; for seller NP collecting payment, check flow [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.csk84kocxpjp);
2. /on_confirm:
- order.created_at is immutable after it's set in /confirm. Why is order.created_at/updated_at before the values set in /confirm?
3. /on_status*:
- invoice should be attached only when fulfillment state is packed;
- fulfillment.start.instructions: if code is "2", the pickup confirmation code (PCC) needs to be provided here => you needn't include this here for seller delivery;
- why is pickup time (fulfillment.start.time.timestamp) changing between order-picked-up & order-delivered? (pickup & delivery time should be immutable);

Flow 3
====
1. transaction_id should be the same between /on_select (out of stock) & /on_select;
2. /on_select (out of stock):
- error.message format should be as per [this](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl) - check page 208;

**Comment by BLR-0118** [comment]
@Siddhant-Tranzita @AtitiTranzita

**Comment by BLR-0118** [comment]
Flow 1
====
1. incremental catalog refresh:
- since every message & its response should have an unique message id, each incremental push update should have an unique message_id as it's unsolicited (and not be the same message_id as the incremental search); for incremental pull, the /on_search response can have the same message_id as the /search as it's a solicited response;
Flow 2
====
1. all APIs should have Context.city the same as the fulfillment end location (which is pin code 273407 from /select);
2. /on_confirm:
- fulfillment.start.location will be the location of the seller (as sent in /on_search);
- order.created_at & order.updated_at show an earlier timestamp than /confirm; (order.created_at is immutable after set by buyer app);
- all unsolicited /on_status calls should have new message_id (currently, it's using message_id from /status);
- /on_status_18 shows pickup time as 19:09 but it's changed to 19:11 in /on_status_19;
- all unsolicited /on_status calls showing payment collection time (payment.time.timestamp) as 4th June??
Flow 3
====
1. /on_select_out_of_stock:
- item.quantity.maximum.count shows the default ("99") or specific cap per order; this can' change to 0 if item is out-of-stock;
2. /select_9 and /select_11 should have the same transaction_id;
Flow 4
====
1. /on_cancel:
- items array should maintain the audit trail i.e. zero out the quantity for forward shipment fulfillment & assign the items to the cancel fulfillment;
Flow 5
====
1. /on_cancel_rto: same issue as flow 4;
2. quote trail should show additional value for RTO fulfillment (it's showing id for forward shipment fulfillment);

**Comment by BLR-0118** [comment]
@Siddhant-Tranzita @AtitiTranzita

**Comment by BLR-0118** [comment]
also, pls check the following:
I. all pre-order APIs (/select, /init, /confirm & their callbacks) are received / processed in sequence e.g. as seller NP, you can't process /init without having processed /select and same applies for callbacks;
II. since there may be multiple API calls / callbacks for the same API, a request received, with timestamp earlier than a request for the same API, should be NACK'd with "stale request" error code e.g. /select (with earlier timestamp) received after another /select (with same transaction_id & later timestamp) has been / is being processed;
III. II above applies similarly to callbacks;
IV. confirm flow has been implemented as defined [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wthdzrq1m4ng);

**Comment by AtitiTranzita** [comment]
> since there may be multiple API calls / callbacks for the same API, a request received, with timestamp earlier than a request for the same API, should be NACK'd with "stale request" error code e.g. /select (with earlier timestamp) received after another /select (with same transaction_id & later timestamp) has been / is being processed;

In the documentation context.ttl is PT30S(by default), it is very short time for a request to be alive. What if a user add the items in the cart and wants to make the payment after 2 or 3 days later then he needs to clear his cart first and perform all the operation again from select call?

**Comment by BLR-0118** [comment]
context.ttl defines the validity of the message, i.e. if someone receives the message, they shouldn't process beyond the time limit in context.ttl.
for the use case above, you may want to cache the cart based on the validity of the quote (order.quote.ttl); of course, there will be practical considerations that define how long this should be cached
@AtitiTranzita

**Comment by BLR-0118** [comment]
Flow 1
====
1. full_catalog_on_search_2:
a. same variant grouping (definition - size, colour attrs in sequence) defined 4 times (6914e72e79e1, 6914e72e79e1, d615ab7fe463, 730930211fec); while this isn't a bug, you can optimize by fixing this & having 1 variant grouping definition as it's not based on categories unless the attributes & sequence of these attributes are different;
2. incremental_on_search(for_store_loc_change_close_6):
a. when a store is being temporarily closed (in this case from 30th Dec 1830 - 31st Dec 1830), it'll automatically reopen at 1830 on 31st Dec; if a store is being closed indefinitely (i.e. location.time.range.start is given but not location.time.range.end), it can be reopened by following [this](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.9duk76cmmly);
b. store enabling (incremental_on_search(for_store_loc_change_enable_7)) isn't a valid option for incremental update as of now;

Flow 2
====
1. All APIs:
- use "std:0551" instead of "std:551" for Context.city;
2. /on_init:
- remove provider_location;
- remove everything from bpp_terms except tax_number (as these will be enabled later thru static terms);
3. /confirm & /on_confirm:
- remove everything from bap_terms & bpp_terms, except tax_number (as these will be enabled later);
- order.updated_at should be the timestamp when order is last updated in /on_confirm (hence, can't be same as order.created_at);
- why isn't fulfillment.start.contact using this (provided in full catalog):
              "contact": {
                "phone": "7676580202",
                "email": "support@vidyant.com"
              }
4. /on_status_16 (solicited) shows the same order.updated_at as /on_confirm (other unsolicited /on_status is ok);

Flow 4
====
1. /on_cancel:
- forward shipment fulfillment (c1db3be0-2193-4b09-9299-aae202d712a9) is cancelled and items are reassigned to 2 different fulfillments (3f46a7e4-8946-46cd-ae40-6c0a51171c7f, 9c858760-0ecd-4083-9448-bc64ce9944ae);
- this is wrong as a new fulfillment should be created of type "Cancel" which has the quote trail (i.e. how much should be deducted line-item wise from the original order to determine the new order value);
- quote.breakup should have the individual line items with price of 0;

Flow 5
====
1. RTO flow not fully correct;

**Comment by BLR-0118** [comment]
@AtitiTranzita @Siddhant-Tranzita @get2abhi - let's have a call ASAP to discuss this & close;

**Comment by BLR-0118** [comment]
pls share logs for flow 4, 5 & 6

**Comment by BLR-0118** [comment]
flows 1, 2, 3 - ok;

flow 4:
- why are 2 cancellation fulfillments (with same id) created? Even for an order with multiple forward shipment fulfillments, there should only be 1 cancellation fulfillment created and all items reassigned from the forward shipment fulfillment(s) to the cancellation fulfillment;
- pls don't include any line item in quote trail with 0 value; this is because the quote trail should only have line items showing the delta changes from the previous state of the order;

flow 5:
- same issue as flow 4;

pls resubmit logs for flows 4, 5 & 6
@AtitiTranzita @Siddhant-Tranzita @get2abhi

**Comment by AtitiTranzita** [comment]
> * why are 2 cancellation fulfillments (with same id) created? Even for an order with multiple forward shipment fulfillments, there should only be 1 cancellation fulfillment created and all items reassigned from the forward shipment fulfillment(s) to the cancellation fulfillment;

This is because we have two items objects :
 "items": [
        {
          "quantity": {
            "count": 0
          },
          "id": "daX03blzyFayJEKE6pBS_colour-000000_size-L",
          "fulfillment_id": "0209c277-6ecb-4377-ab21-1b4dc07c3759"
        },
        {
          "quantity": {
            "count": 1
          },
          "id": "daX03blzyFayJEKE6pBS_colour-000000_size-L",
          "fulfillment_id": "e9e5854c-fbe5-453b-8471-12e36cfa3ed5"
        },
        {
          "quantity": {
            "count": 0
          },
          "id": "daX03blzyFayJEKE6pBS_colour-000000_size-XS",
          "fulfillment_id": "0209c277-6ecb-4377-ab21-1b4dc07c3759"
        },
        {
          "quantity": {
            "count": 2
          },
          "id": "daX03blzyFayJEKE6pBS_colour-000000_size-XS",
          "fulfillment_id": "e9e5854c-fbe5-453b-8471-12e36cfa3ed5"
        }
      ]

**Comment by BLR-0118** [comment]
1. whenever there's a change in the order value due to an event e.g. cancel / return / etc., we create a separate fulfillment for every such event;
2. thus, if there's an order cancellation, there is only 1 event for which only 1 separate fulfillment is created;
3. however, if there are returns, I can return different items at different times; hence, a separate fulfillment is created for every such return event (we've simplified this to have a separate fulfillment created for every item return, even if return for multiple items are happening at the same time);
4. this fulfillment created is used to maintain the order trail i.e. what has changed in the order due to which the value is changing;
@AtitiTranzita

**Comment by BLR-0118** [comment]
flows 1 to 4 - ok;
flow 5:
- wherever there's a quote trail, you should only include line items with delta change in price, i.e. don't include line items with 0 price change e.g. for id 0015e366-e46b-46e9-8cb0-3be685d55d2f;
- no need to resubmit logs for flow 1 to 5;

pls share logs for flow 6 (scenario 2);

**Comment by BLR-0118** [comment]
@AtitiTranzita @Siddhant-Tranzita

**Comment by BLR-0118** [comment]
Flow 6
====
1. Merchant Cancel:
- there are 2 items assigned to forward shipment fulfillment "a9e70f72*" but merchant is cancelling only 1 of those items;
- in this case, the fulfillment itself doesn't get cancelled (but remains in the original state);
- also, quote trail for cancellation fulfillment should only include the item daX03**L as the cost for this item is being refunded;

2. Buyer cancel with reverse qc:
- /on_status_18: Context.city shows "std:[object Object]";
- id of the return request should be assigned to the fulfillment object by SNP: correctly done in /on_update_20;
- fulfillment id assigned above should be immutable till completion of reverse flow: not happening as the fulfillment id is changing in /on_update_21, then again in /on_update_22 and /on_update_23;

**Comment by BLR-0118** [comment]
pls resubmit logs for flow 6 use cases;
@AtitiTranzita

**Comment by BLR-0118** [comment]
Flow 6 - cancel by merchant
===================
1. /update - refund amount is 1998, not 899;

Flow 6 - buyer cancel with reverse qc
========================
1. Forward shipment fulfillment is immutable after order is delivered (/on_status_20) - this means the pickup & delivery time should remain the same in all /on_update calls;
2. Pickup & delivery time for the forward shipment fulfillment (6e4cdf68*) changes in all the /on_update calls;
3. For reverse qc fulfillments, start & end locations will be the reverse of the forward shipment fulfillment;

**Comment by BLR-0118** [comment]
pls fix the above; no need to resubmit logs
@AtitiTranzita @Siddhant-Tranzita

**Comment by BLR-0118** [comment]
@AtitiTranzita - I'd mentioned that you can have only 1 variant definition per item category - that's wrong. You can define multiple variant groupings per item category (for different sets of items);

**Comment by AtitiTranzita** [comment]
Hi @BLR-0118 ,
Have fixed all these issues.

**Comment by BLR-0118** [comment]
logs cleared for fashion (RET12)
@AtitiTranzita

**Comment by AtitiTranzita** [comment]
Hi Supriyo,

We have added tech logs for IGM and created a PR. Please find below link
for your reference:
https://github.com/ONDC-Official/v1.2.0-logs/pull/821

Thanks and Regards
Atiti Singh
SDE-1
Ph: +91 9129785903

https://seller.shopcircuit.ai/
ᐧ
