### ISSUE TITLE
Adya LSP (RSP) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#319]
Normal Flow 

collector_recon:
settlement_status is wrong , pls use the correct enums.

 on_collector_recon:
 message_id mismatched with collector_recon

on_receiver_recon
settlement id mismatched with settle and on_settle api.

Correction Flow 
Same issues that are present above 

@saravanamuthu-123

**Comment by RupalSingla** [comment]
Normal Flow

collector_recon:
settlement_status is wrong , pls use the correct enums.

on_collector_recon:
message_id mismatched with collector_recon

on_receiver_recon
settlement id mismatched with settle and on_settle api.

pls check, 
@saravanamuthu-123

**Comment by RupalSingla** [comment]
Receiver_recon:

- orderbook.orders.state is having incorrect enum, needs to be completed,instead od Accepted.
- Null values /empty values inside the payment object are not accepted.
- Please prvide a payload in which Buyer app finder fee is non zero


@saravanamuthu-123

**Comment by Saravanamuthu-Eunimart** [comment]
> Receiver_recon:
> 
> * orderbook.orders.state is having incorrect enum, needs to be completed,instead od Accepted.
We will correct and resubmit.
> * Null values /empty values inside the payment object are not accepted.
In LSP, payment object doesn't have uri,tl_method and params object, so we are sending it empty. 
> * Please prvide a payload in which Buyer app finder fee is non zero
> LSP App doesn't have Buyer Finder Fee, so we are sending it zero.
> @saravanamuthu-123

**Comment by bluecypher** [comment]
**/collector_recon**

- invalid value of settlement_status; should be NOT_PAID

**/receiver_recon**

- order/updated_at timestamp can't be earlier than settlement_timestamp

## Flow 2

**/on_collector_recon**

- order id: "dea33bef-5c6c-4c12-8c22-9a6f0b0db31e" is missing

### Correction Flow

**/collector_recon**

- previous settlement details must be present in "@ondc/org/settlement_details" with the already settled settlement_reference no. and "settlement_status" as "PAID"
- invalid issue_subtype; use the enums as defined [here](https://docs.google.com/spreadsheets/d/1bxVNDzsYLsVPRGwkFZdDCnxA_ueFM1Lu/edit#gid=605622896)


@Saravanamuthu-Eunimart

**Comment by bluecypher** [comment]
Logs cleared for Logistics RSP v1.0.0

@Saravanamuthu-Eunimart
