### ISSUE TITLE
GoFrugal - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#323]
Hello @AbinayaM , there are multiple issues identified in the submitted logs. Please utilize the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to address and rectify the flagged issues.

Note: You may use ONDC [reference logistics app](https://github.com/ONDC-Official/ref-logistics-app-sdk/tree/main) to test the flows.

**Comment by AbinayaM** [comment]
resolved this in [pr](https://github.com/ONDC-Official/v1.2.0-logs/pull/345) @abhinavv245

**Comment by abhinavv245** [comment]
## Flow 1 (Delivery)

**/search**

- placeholder values should be avoided (in dimensions)

**/on_search**

- catalog/bpp/providers/0/items/ need NOT have additional properties (@ondc/org/cancellable, @ondc/org/returnable, @ondc/org/seller_pickup_return, @ondc/org/available_on_cod)

**/init**

- payment/collected_by is not required

**/on_init**

- message/order/payment/type does not match the intended payment type by the logistics buyer (BAP should send NACK)

**/update**

- order/updated_at cannot be future dated w.r.t context/timestamp

## RTO and Cancel Flow

- similar issues as above

**/cancel**

- cancellation/reason/id "007" (Order / fulfillment not received as per buyer app TAT SLA) is not appropriate here

@AbinayaM

**Comment by AbinayaM** [comment]
@abhinavv245  Fixed all the above issues. Here is the [pr](https://github.com/ONDC-Official/v1.2.0-logs/pull/405). Please review it.

**Comment by AbinayaM** [comment]
> Hello @AbinayaM , there are multiple issues identified in the submitted logs. Please utilize the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to address and rectify the flagged issues.
> 
> Note: You may use ONDC [reference logistics app](https://github.com/ONDC-Official/ref-logistics-app-sdk/tree/main) to test the flows.

Hi @abhinavv245 , fixed all the issues and submitted the logistics logs again. Kindly verify it once

**Comment by BLR-0118** [comment]
logs verified with MP2, cleared for v1.2.0
