### ISSUE TITLE
Bizom - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#326]
Hello @Akhil-873  , there are multiple issues identified in the submitted logs. Please utilize the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to address and rectify the flagged issues. Also, submit the logs for RTS (ready to ship) at confirm and RTO (return to origin) Flow. 

Note: You may use ONDC [reference logistics app](https://github.com/ONDC-Official/ref-logistics-app-sdk/tree/main) to test the flows.

**Comment by abhinavv245** [comment]
## Delivery and RTO Flow

**/init**

- fulfillments/0/end/location/gps does not match end location in search (Flow 2)

**/confirm**

- quote need not have additional properties (ttl),
- fulfillments/0 need not have additional properties (tracking, LSP can enable/disable),
- fulfillments/0/tags/code rto_action is missing (duplicate state to be removed) (LSP should validate)
- @ondc/org/linked_order/order/weight/value Payload weight mismatches from /search (how is LSP handling this)
- item/time is missing (S2D TAT; if S2D TAT is different from what was quoted earlier in /on_search, LSP can NACK /confirm with error code 60008)

@Akhil-873

**Comment by samarthpatel-bizom** [comment]
1. fulfillments/0/end/location/gps does not match end location in search (Flow 2) -> The search in the flow 1 was different from the flow 2 and hence the gps change.

2. item/time is missing (S2D TAT; if S2D TAT is different from what was quoted earlier in /on_search, LSP can NACK /confirm with error code 60008) -> These seems to be part of phase 2

**Comment by abhinavv245** [comment]
@samarthpatel-bizom 
1. Flow 2 should be initiated for the same details provided in flow 1 (or you may provide search ,on_search for Flow 2 and 3 as well)
2. You may ignore this issue related S2D TAT for now.

**Comment by abhinavv245** [comment]
## Flow 2

**/confirm**

- fulfillments/0/tags/code rto_action is missing (duplicate 'state' to be removed) (LSP should validate)
- PCC (fulfillment.start.instructions.code & short_desc) are required when order ready_to_ship is "yes"

@samarthpatel-bizom @Akhil-873

**Comment by samarthpatel-bizom** [comment]
1. fulfillments/0/tags/code rto_action is missing (duplicate 'state' to be removed) (LSP should validate) : We have used state tags to pass rto_action info. Will fix this.
2. PCC (fulfillment.start.instructions.code & short_desc) are required when order ready_to_ship is "yes": Bizom does not support auto order acceptance hence always /update is called, in which we are passing PCC. (Also passed in confirm though optional) 

Please let me know if any other porblem is there. Also can we just submit flow 2 with fixing the "rto_action" tag problem ?

@abhinavv245

**Comment by abhinavv245** [comment]
@samarthpatel-bizom Just the above fixes are required. Please submit logs for both the flows.

**Comment by sumitagbizom** [comment]
@abhinavv245 https://github.com/ONDC-Official/v1.2.0-logs/pull/496 please review the pr

**Comment by samarthpatel-bizom** [comment]
@abhinavv245 can you please review this.

**Comment by samarthpatel-bizom** [comment]
@abhinavv245 any update on this ?

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
