### ISSUE TITLE
Krenai_Retail (IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#329]
on_issue:
- "schemaErr0": "/message/issue must have required property 'created_at'"
-  "updated_at": "updated_at of last respondent_action should be the same in the message/issue/update_at in the issue"

@AnchalSharma07

**Comment by Rishabh-ondc** [comment]
on_issue
- context.timestamp has not changed
- context.ttl not required
- Empty complainant_actions object shared; please check, should not be shared

on_issue_status
- context.timestamp has not changed
- context.ttl not required
- respondent_info.organization.org.name should have the domain code as well
- resolution.resolution_action is optional; resolution.resolution_remarks is incorrect attribute

Clarifications
- on_issue for issue close call is not required
- please share 2 logs, one for ITEM and one for FULFILLMENT category
 
@AnchalSharma07

**Comment by Rishabh-ondc** [comment]
on_issue_status
- issue.created_at has changed
- resolution.resolution_action is not required
- resolution.resolution_remarks is an incorrect attribute

Clarifications
- on_issue_status should be developed as an unsolicited call as well; please ensure

@AnchalSharma07

**Comment by Rishabh-ondc** [comment]
on_issue_status
- respondent_actions.updated_at is greater than issue.updated_at; please check

Clarifications
- on_issue not required for issue close call

@AnchalSharma77

**Comment by Rishabh-ondc** [comment]
Logs cleared

@AnchalSharma77
