### ISSUE TITLE
Mappls - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#332]
Flow 1
====
1. /search, /search_incremental:
- Context.timestamp is in UTC (seems correct) in RFC3339 format (3 digits of millisec), e.g. instead of "2023-12-20T12:08:47.000000Z" (in logs), it should be "2023-12-20T12:08:47.000Z" (issue with all API requests from buyer app for all timestamps);
- remove bap_terms as static terms aren't enabled yet; (for all APIs)
- "buyer_app_finder_fee_amount" value should be string (for all APIs);

Flow 2
====
1. /init:
- fulfillment.end.person.name should be sent in /confirm, not here;
2. /confirm:
- order.id shouldn't be same as Context.transaction_id;
- since prepaid payment is being collected by BAP, payment.params.transaction_id should identify the unique transaction ref;

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search - is the log submitted in response to the /search? Can't be as the transaction_id & message_id are different and timestamp is earlier than /search;
2. /on_search - item.descriptor.code is invalid; do you have logic in place to parse the item unique codes as per contract?
3. same issue with timestamp for incremental /search & /on_search (though transaction_id & message_id are same) - is there an issue with your timestamp?

Flow 2
====
1. /confirm - pls remove the entire order.tags (bpp_terms & bap_terms) as those aren't yet enabled;

Flow 3
====
1. /select_out_of_stock timestamp is after /select; this is incorrect as per the test scenario, buyer selected multiple items (of which some are out of stock) and then removes the items out-of-stock & proceeds with checkout;

Flow 5
====
1. RTO flow not captured but flow 4 is ok; hence, RTO flow will also work;

Flow 6
====
1. Why is return shown using /on_status instead of /on_update? Don't you process /on_update?

Other questions for clarification:
1. If you get a response to a request with a timestamp earlier than request, are you responding with error 20002 (cannot process stale request)?
2. Check for unique message_id for every unsolicited call from seller NP (e.g. /on_status, /on_cancel, /on_update)?
3. Are you freezing order, at terminal state, as defined in point 1 [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.dgl40941il62)?

**Comment by BLR-0118** [comment]
@kalaivanansundaram - pls close the above ASAP so we can move forward

**Comment by kalaivanansundaram** [comment]
Thank you for the feedback sir. We will check and get back to you as soon
as possible

**Comment by BLR-0118** [comment]
also, pls check the following:
I. all pre-order APIs (/select, /init, /confirm & their callbacks) are received / processed in sequence e.g. as seller NP, you can't process /init without having processed /select and same applies for callbacks;
II. since there may be multiple API calls / callbacks for the same API, a request received, with timestamp earlier than a request for the same API, should be NACK'd with "stale request" error code e.g. /select (with earlier timestamp) received after another /select (with same transaction_id & later timestamp) has been / is being processed;
III. II above applies similarly to callbacks;
IV. confirm flow has been implemented as defined [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.wthdzrq1m4ng);

**Comment by kalaivanansundaram** [comment]
Sure sir. We will get this checked and update the logs where ever it is
required

**Comment by BLR-0118** [comment]
Flow 1
====
1. Catalog refresh (full & incremental) depends on the timestamp associated with provider / location / item for versioning; if you receive full & incremental refresh at the same time, using the timestamp you can decide which refresh to consider e.g. item disabled in full search & enabled in incremental search as shown to the team today. Pls make sure you're versioning the updates based on the timestamp;

Flow 3
====
1. /on_select - out of stock error is wrong, pls make sure you're able to process message in the correct fomat;

Flow 6
====
1. part cancel (6A) & part return (6B) response - quote trail & quote are invalid as explained to the team today. Pls have this fixed & tested; 

Also, as buyer app, you'll need to monitor catalog quality to make sure correct information is being displayed to the buyer;

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_track:
- location.time.timestamp - gps coords as of this timestamp (hence can't be > Context.timestamp);
- location.updated_at - when were the loc coords updated in system (hence can't be < location.time.timestamp);

Flow 3
====
1. /confirm:
- payment.params.transaction_id (UTR for payment collected from buyer) can't be same as Context.transaction_id;

Also, the seller NP (chattybao) should start sending item.descriptor.code in Catalog to indicate unique identifier for sku (without this, most buyer apps won't ingest the catalog);

**Comment by BLR-0118** [comment]
pls let me know when the above is fixed;
logs don't need to be resubmitted;
@kalaivanansundaram

**Comment by kalaivanansundaram** [comment]
@BLR-0118 sir , we have fixed all the mentioned points. Pls share us the next steps to proceed further.

**Comment by BLR-0118** [comment]
Logs cleared for v1.2.0 (Grocery)
