### ISSUE TITLE
Otipy (RSF) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#342]
Settlement Flow
receiver_recon:
deduction by collector can't be non-zero when BAFF is 0
context timestamp and settlement timestamp cannot be equal

Correction Flow:
counterparty_recon_status is having incorrect value needs to be 03.

@yashCrofarm

**Comment by vipul-jn** [comment]
@RupalSingla : Few things to confirm: 
1. BAFF is configurable and we have set it to flat 20 rupees for this testing. It can be both absolute value or percentage. I couldn't find BAFF 0 in my code or json. Can you pls help me out with this.

2. Correction flow counterparty_recon_status value "03" we have refered from the RSP api doc only. This is the response value with is mentioned in the api doc ::            "counterparty_recon_status": "03", 
You can refer to the image as well.
<img width="697" alt="image" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/122870996/22b07659-2de4-45e7-9343-f6d10c0a7ee9">

**Comment by vipul-jn** [comment]
@RupalSingla Pls refer to this schema json : https://github.com/ONDC-Official/protocol-network-extension/blob/main/specifications/rsp/enums/recon_status.json

recon_status "03" is the only value defined here.

**Comment by yashCrofarm** [comment]
@RupalSingla kindly find the PR of the issues mentioned
https://github.com/ONDC-Official/v1.2.0-logs/pull/365

**Comment by vipul-jn** [comment]
@RupalSingla pls review the logs and proceed it for further stages.

**Comment by vipul-jn** [comment]
@RupalSingla please review the logs .. we did changes as per your comments last time.

**Comment by bluecypher** [comment]
**/receiver_recon**

- “Delivered” is not a valid order/state; pls check the retail contract
- buyer app finder fee is usually deducted as percent by the buyer apps (not as amount); check the payment object in retail contract; no need to send additional attributes in the payment object in RSF
- T5D is not a valid ISO duration format in “@ondc/org/settlement_window”

**/on_receiver_recon (Correction)**

- value in “counterparty_diff_amount” should be in string format


@vipul-jn

**Comment by vipul-jn** [comment]
Hi @bluecypher : regarding your comment on "buyer app finder fee" is percentage, we have enabled both percentage and absolute value.

During testing we created the data with absolute value. Kindly don't consider that as requirement for code change.

Remaining other comments I am going to push it.

**Comment by vipul-jn** [comment]
here is the latest PR link with the changes you suggested (excluding buyer finding fee changes) : https://github.com/ONDC-Official/v1.2.0-logs/pull/510/

**Comment by vipul-jn** [comment]
@bluecypher @RupalSingla please review the RSP logs as well.

**Comment by vipul-jn** [comment]
@RupalSingla @bluecypher pls review them as well.

**Comment by RupalSingla** [comment]
Success Flow

- buyer app finder fee is usually deducted as percent by the buyer apps , in the payload it is mentioned as amount 

@vipul-jn

**Comment by vipul-jn** [comment]
@RupalSingla , we made changes for percent also.. but we forgot to git push it.
You can refer to this git PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/619/files
This has changes for Percent level changes.

**Comment by bluecypher** [comment]
- message_id should be unique for each /receiver_recon call
- inconsistent counterparty_recon_status for certain orders; check order id: K106403902112766
- buyer app finder fee type enum should be "percent" (lower case 'p')

@vipul-jn

**Comment by vipul-jn** [comment]
1. will change the message Id/transaction if for other cases.

**Comment by bluecypher** [comment]
Logs approved for RSF v1.0.0.

@vipul-jn
