### ISSUE TITLE
COSTBO RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#343]
Settlement Flow is missing .

reciver_recon:
context.timestamp cannot be same with settlement_timestamp
deduction_by_collector.value  cannot be in negative 

on_reciver_recon :
please follow a valid ttl for the response 

@AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla ,  Thanks for your feedback.   "On_receiver_recon".  you have mentioned Valid TTL for the response. 

=>. Contract document mentions "ttl": "P2D". & that is similar in our logs.     Can you suggest , what is the problem to be corrected.

**Comment by AnanthBo** [comment]
@RupalSingla    fixed and updated via https://github.com/ONDC-Official/v1.2.0-logs/pull/350

Please review and lets know the comments at earliest.

**Comment by AnanthBo** [comment]
@RupalSingla ,  Please let me know your comments

**Comment by AnanthBo** [comment]
@RupalSingla ,  Can we have a quick call on this please.  My number is 9845570864.   
1).  We have submitted receiver_recon & On_receiver_recon.  as seller MSN.    - acting as receiver
2).  We are alos trying to see if we can be RSP for ourself & trying to submit the settle / On_settle to get the certification from ONDC Team.  This will help us get a access to staging setup of NBBL (SA). where we can send the real settle APIs.     

Could you possible accept our logs for "Receiver side"  for receiver_recon & on_receiver recon.   so we are clear on part 1.    Second part, we can work on this next. 

Please help us understand if we are missing.

**Comment by AnanthBo** [comment]
@RupalSingla  Could you possibly review   receiverrecon & on_receiver_recon.  &. settle/ On_settle   as not connected to each other  As we are a Seller APP ? .    Spoke to Rishabh on this as well and he suggested the same.

**Comment by AnanthBo** [comment]
@RupalSingla ,   lets discuss if you need clarification

**Comment by AnanthBo** [comment]
@RupalSingla ,    could you please review our changes .     Your comment is not valid as per our understanding as the receiver_recon and Settle APIs are in different flow and different timing.  Please call me  9845570864 or  talk to Rishab once please.

**Comment by AnanthBo** [comment]
@RupalSingla ,     Could you please help us with this update.  Let us know, what is that blocking us to move to next step.

**Comment by AnanthBo** [comment]
@RupalSingla ,    Could you provide an update after discussing with Rishabh.   As per us, there is no commit needed.

**Comment by AnanthBo** [comment]
@RupalSingla , Could you provide an update after discussing with Rishabh. As per us, there is no commit needed.

**Comment by bluecypher** [comment]
@AnanthBo, please fix the timestamp related issue and it is applicable to all the participants

**Comment by bluecypher** [comment]
@AnanthBo, if you are an MSN seller app, then /settle and /on_settle have to be implemented as part of RSF construct.

If you want to become an RSP, then all the APIs are mandatory, including the RSF APIs.

**Comment by AnanthBo** [comment]
@bluecypher    Thanks for your clarification.   we have fixed & submitted   RSF  PR #445 has been
 submitted

**Comment by AnanthBo** [comment]
@bluecypher ,   Could you please help on the review.   As per our discussion the settlementtime stamp received from the buyer app (via mock postman ) is updated.

**Comment by AnanthBo** [comment]
@bluecypher ,  could you please ask your team to help us with the comments.

**Comment by AnanthBo** [comment]
@bluecypher , could you please ask your team to help us with the comments.   Its been more than a week.   Also this is blocking the ops team to review the dashboard.

**Comment by RupalSingla** [comment]
Please avoid using placeholder values in the payload 

on_settle :
timestamp between settle and on_settle Api is incorrect.

receiver_recon.
settlement_timestamp mismatched from the settle API
buyer_app_finder_fee_type is having wrong enum.

FLow 2 is missing / correction Flow 

@AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla ,  We are a seller MSN.    so we provide a settle api after the receiverrecon  from the buyer app.    will provide a settle api & on settle API  timing before the  receiver_recon in the next set.     Could you confirm ,  if we should use  receiver_recon >. orderdetails. settlementdetails .  settlement_timestamp  equal to settle > context.timestamp   or.  on_settle > context.timestamp?      Let us know.  if we can have call ?

**Comment by AnanthBo** [comment]
@RupalSingla   Please provide comments on the new PR #555.      Sandeep had mentioned what logs given are enough.  as we are seller MSN.    setttle, onsettle, receiver-recon and onreceiver -recon.

**Comment by RupalSingla** [comment]
receiver_recon
- created_at and updated_at are having same timestamp , which is not possible .
- Please avoid using placeholder values.
-  "withholding_tax_gst" is given a negative value.

@AnanthBo

**Comment by RupalSingla** [comment]
please send 5 orders in the orderbook .

@AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla .  Receiver_recon >. Need clarification on created_at and updated_at are having same timestamp , which is not possible  .      could you give examples , of receiver_recon  what  it created  signifies ?  and what  updated_at signifies ?    This will help us fix   or. Can we go ahead and fix  updated_at is  created_at+1day.

**Comment by AnanthBo** [comment]
@RupalSingla ,  Pushed the latest fixes with request of 5 orders  - having normal flow & correction flow.  PR#601

**Comment by bluecypher** [comment]
#### - Please remove the old logs folder and provide only the most recent updated logs

#### - Please submit the logs as per the following test cases:

1. Flow 1: Successful reconciliation by the receiver for 5 or more transactions
2. Flow 2: Correction flow initiated by the receiver in /on_receiver_recon
3. settle/on_settle as a separate flow

**/receiver_recon**

- updated_at can't be future dated in orderbook/orders/
- settlement_timestamp in "@ondc/org/settlement_details" can't be earlier than orderbook creation timestamp (orderbook/orders/created_at)

**/settle**

- Since /settle is called by the NP, bap_id and bap_uri can't have placeholder values
- Why is the settlement_id value kept the same when settling the amount with merchants and when receiving the amount from BNP? (Settlement id and settlement_reference_no can only be the same for an individual batch settlement)

@AnanthBo

**Comment by AnanthBo** [comment]
@bluecypher    based on the earlier conversation, Rupal was insisiting  for logs as. "receiver/buyer" side.  so the last logs we provided are from  "receiver" prespective.     Can you please review with angle & approve the logs ?       Would like to have a quick call  if the above is not sufficient. or. if you need the collector side.     please.

**Comment by AnanthBo** [comment]
@bluecypher l. PR#700 has been pushed for RSF update as REceiver providing  correction and success flow.

**Comment by bluecypher** [comment]
**/receiver_recon**
- settlement_timestamp can't be earlier than orderbook created_at timestamp; orderbook is first created, amount is settled and then orderbook is updated;

**/settle**
- some attributes are missing eg: payer_address and payer_bank_code; check the contract;

@AnanthBo

**Comment by AnanthBo** [comment]
Thanks Sandeep.    PR#737 has been updated.

**Comment by bluecypher** [comment]
Invalid attributes in /settle; Check previously shared feedback, and please perform sanity checks before submitting the logs

@AnanthBo

**Comment by AnanthBo** [comment]
@bluecypher  Thanks Sandeep have reviewed and submitted.

**Comment by AnanthBo** [comment]
@bluecypher  Submitted PR #855     Please review.

**Comment by AnanthBo** [comment]
@bluecypher Submitted PR https://github.com/ONDC-Official/v1.2.0-logs/pull/855  a week ago.  Please review and let us know your comments

**Comment by AnanthBo** [comment]
@bluecypher Submitted PR https://github.com/ONDC-Official/v1.2.0-logs/pull/855 a week ago. Please review and let us know your comments

**Comment by RupalSingla** [comment]
receiver_recon :
- created_at and udpated_at timestamps can't be same in orderbook/orders.

@AnanthBo

**Comment by AnanthBo** [comment]
@RupalSingla ,           There is a 2 hour gap between the created at & updated_at for receiver_recon.    Please check the logs again please.   

  "created_at": "2024-02-16T06:13:56.148Z",
          "updated_at": "2024-02-16T08:13:56.148Z"

**Comment by RupalSingla** [comment]
Logs approved for RSF v1.0.0

@AnanthBo
