### ISSUE TITLE
Myyshop IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#358]
issue:
context/core_version must be equal to constant (1.0.0)
message/issue/order_details/items/0/quantity must be number

on_issue_status:
updated_at of last respondent_action should be the same in the message/issue/update_at in the on_issue_status
context timestamp should be greater than or equal to updated_at in on_issue

@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Fixed issues and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/427
Please review.

**Comment by Rishabh-ondc** [comment]
on_issue
- context.timestamp is the same as issue API call's context.timestamp
- complainant_actions, status need not be shared by the respondent NP
- resolution_provider is to be shared only when a resolution is provided

on_issue_status (unsolicited)
- respondent_actions.updated_at is the same for processing and resolved actions
- chat_link is optional and need not be shared if not available (avoid using placeholder values)
- gro_type should be TRANSACTION-COUNTERPARTY-NP-GRO
- resolution.gro_remarks and odr remarks need not be shared as of now for MVP implementation
- resolution.resolution_action need not be shared
- If resolution is REFUND, refund_amount is also to be shared

on_issue_status (solicited)
- respondent_actions.updated_at has changed between on_issue_status (unsolicited)
- issue.updated_at has changed between on_issue_status (unsolicited)
- issue.created_at has changed (Flow 2)

Clarifications
- on_issue_status unsolicited is shared before solicited on_issue_status call, please check

@Srinath91

**Comment by Rishabh-ondc** [comment]
Duplicate thread, @RupalSingla please close this

**Comment by sandeepshahi** [comment]
Refer https://github.com/ONDC-Official/v1.2.0-logs/issues/575 for the latest updates
