### ISSUE TITLE
MP2 TSP LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#368]
## Flow 1 (Delivery)

**/search**

- placeholder values should be avoided (in dimensions)

**/init**

- payment/collected_by is not required

**/on_init**

 - message/order/payment/type does not match the intended payment type by the logistics buyer (BAP should send NACK)

 **/update**

 - order/updated_at cannot be future dated w.r.t context/timestamp

 **/on_update**

 - items/time is missing
 - start/time/duration(average time to pickup) is missing (in /on_status as well)

 ## RTO Flow

 - similar issues as above

 **/on_confirm**

 - pickup (fulfillments/start/time/range) and delivery (fulfillments/end/time/range) time ranges are not in accordance with the TAT provided for this type of delivery

 **/on_cancel and /on_status**

 - in /items, time/duration does not match with the one provided in /on_search 

 ## Flow 3 (Cancel)

 - similar issues as above

@mherle

**Comment by mherle** [comment]
Submitted the logs again after fixing these issues in [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/385)

Ran the logvalidation utility locally for all four flows.
Output after running it for the folders (`Flow1`, `Flow1-DeferredRTS` and `Flow3`) is nil errors. 
```
{"logReport":{}}
```

Output for the RTS flow in folder `Flow2`:
```
{
  "logReport": {
    "Message": {
      "on_status_3": {
        "trckErr": "tracking should be enabled (true) for hyperlocal (Immediate Delivery)"
      },
      "on_cancel_0": {
        "rtoIdTagsErr": "rto_id 'mp2_express_f1-RTO' in fulfillments/tags does not match with the one provided in on_search 'mp2_sdd_f1-RTO' in /fulfillments",
        "rtoIdErr": "RTO id - 'mp2_express_f1-RTO' of fulfillment type 'RTO' does not match with the one provided in on_search 'mp2_sdd_f1-RTO' in /fulfillments"
      }
    }
  }
}
```
As noted earlier:
- on_status_3.trckErr is a false alert. For RTO Delivered status update, tracking need not be active.
- on_cancel_0.rtoIdTagsErr and on_cancel_0.rtoIdErr are false alerts. Log validator doesn't handle the case of multiple fulfillment options in search and seem to be trying to match the first search option to the fulfillment option.

Pls merge and review again @abhinavv245 

cc: @BLR-0118 , @bluecypher

**Comment by abhinavv245** [comment]
## All Flows

**/on_status**

- For payment type  'POST-FULFILLMENT', payment/status will be 'NOT-PAID' and payment/time/timestamp cannot be provided.

@mherle @Poornima-Aithal

**Comment by BLR-0118** [comment]
following issues to be fixed:
- removing static terms / cancellation terms for now, as this isn't enabled yet;
- adding tracking optimization params such as gps_enabled, url_enabled, url to fulfillment.tags.tracking in /on_status;
discussed with @mherle on the above; logs don't need to be resubmitted.

**Comment by mherle** [comment]
Thanks @BLR-0118
