### ISSUE TITLE
Magicpin (Tata Neu) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#406]
1. Customization flow (select):
- order.deliverySlot is invalid key;
- fulfillment.tracking can't be set by buyer app;

2. All logs to be submitted as outlined for phase 1 [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795) - only logs for flow 2 submitted for customization / normal flow and flow 3 (normal flow but not customization flow);

3. Separate /search & /on_search logs to be submitted for every category;

**Comment by BLR-0118** [comment]
@Tarosh

**Comment by BLR-0118** [comment]
Flow 1 - no logs for incremental update?
All other flows are ok for F&B (RET11) for which logs have been submitted;

With [domain separation](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.w9zlp87xdha1) by top-level categories, you'll need to submit /search & /on_search logs for other categories you plan to support;

**Comment by BLR-0118** [comment]
@tarosh3

**Comment by BLR-0118** [comment]
logs cleared for F&B;

Grocery /on_search issues:
1. np_type for Magicpin is "MSN";
2. pls remove "accept_bap_terms" as it's not yet enabled;
3. polygon serviceability should be as per what's documented in this [scenario](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.3jvvancz3alw);

**Comment by BLR-0118** [comment]
@tarosh3

**Comment by tarosh3** [comment]
@BLR-0118 

Points 1 and 2 have been resolved, and polygon serviceability has been implemented according to the documentation.

**Comment by BLR-0118** [comment]
pls reshare /on_search log for grocery, with all 3 issues above fixed
@tarosh3

**Comment by BLR-0118** [comment]
1. /on_search:
- variant group definition is incorrect (there's no name, only seq), pls check [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv) for a valid definition; 
- 2 items (3445002, 559010924) linked to variant group id (653f3103ee29da96c9484fcb) have different definitions for unitized qty (which I'm assuming will be the variant attr name missing in the definition); with this, how will the buyer app render the variant?
- polygon serviceability definition is incorrect; pls check [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.3jvvancz3alw) & [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.jgj38hso0lnk) on how it can be defined using geojson;

**Comment by BLR-0118** [comment]
@tarosh3

**Comment by BLR-0118** [comment]
Following issues need to be fixed:
- variant_group definition: attr.name should be "item.quantity.unitized.measure" for grocery (as this denotes the net qty);
- unit for polygon serviceability (type 13) should be "GeoJSON";
- can we standardize as per contract:
- item.quantity.available.count: "99" is available, "0" is out-of-stock;
- item.quantity.maximum.count: "99" means no cap per order, any other non-zero value means cap per order (e.g. "3" means buyer can't buy more than 3 of this item in an order);

**Comment by BLR-0118** [comment]
log cleared for 1.2 (RET10) (pls make sure the above issues are fixed)

**Comment by BLR-0118** [comment]
@tarosh3
