### ISSUE TITLE
ENS (Redtape) - fashion: compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#410]
1. full_catalog_on_search:
- bpp/providers.fulfillment.id should match and item.fulfillment_id & bpp/fulfillments.id;
- why are 2 variant groupings defined for the same  category?

**Comment by BLR-0118** [comment]
@NJ-Nitank

**Comment by BLR-0118** [comment]
1. /on_search:
- accept_bap_terms, collect_payment should be removed until enabled later;
- undefined variant grouping id 15767 assigned to item 111305;

Logs submitted for fashion are for different bpp_id (Redtape), hence, all logs (flows 1 to 5) need to be submitted.  Also, please enable return with reverse qc in flow 6.

**Comment by BLR-0118** [comment]
@NJ-Nitank

**Comment by NJ-Nitank** [comment]
@BLR-0118 Sir, We have submitted the logs as a TSP. Do we need to get approval for each seller app?

**Comment by NJ-Nitank** [comment]
@BLR-0118 Sir, Please review this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/481.

**Comment by NJ-Nitank** [comment]
@BLR-0118 Sir, Please review this PR for Fashion as ENS TSP, https://github.com/ONDC-Official/v1.2.0-logs/pull/504

**Comment by BLR-0118** [comment]
1. /on_search (full catalog):
- item qty unitized measure value is wrong, should indicate what's the unitary qty (e.g. 1 unit);

2. /on_search (incremental):
- pls share log for item going out of stock / becoming available (most common fashion usecase);

also, pls share logs for flow 6 (a, b) as mentioned earlier;

**Comment by BLR-0118** [comment]
@NJ-Nitank

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, I have submitted the logs as per Out of Stock item get in stock in incremental search.
Please check it 
https://github.com/ONDC-Official/v1.2.0-logs/pull/564

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, I have submitted the logs for Health & Wellness category, Please check it 
https://github.com/ONDC-Official/v1.2.0-logs/pull/599

**Comment by NJ-Nitank** [comment]
@BLR-0118 Sir, Please review the PR.

**Comment by BLR-0118** [comment]
logs cleared for RET12

**Comment by BLR-0118** [comment]
@NJ-Nitank - reopening, logs for flow 6 (a & b) need to be submitted as requested earlier;

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, flow 6-a has been submitted, please check the PR https://github.com/ONDC-Official/v1.2.0-logs/pull/759

**Comment by NJ-Nitank** [comment]
@BLR-0118 Sir, Please provide me the update on this.

**Comment by BLR-0118** [comment]
Flow 6b
=====
1. /on_update:
- fulfillment of type "Return" should have same id as the return request in /update;

2. /on_update (return picked):
- quote_trail for return seems to be merged into the cancel fulfillment;

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, we are calculating fulfillment time since we got the order so it is included the time required for pickup.

 Do I need to change the fulfillment TAT ?

> # Flow 6a
> 1. /on_confirm:
> 
> * fulfillment TAT is missing;
> * provider_tax_number is missing;
> * fulfillment start shows pickup slot (between 6th & 7th Feb) and delivery slot (between 6th & 12th Feb); since /on_select shows fulfillment TAT of 7 days, shouldn't delivery slot be between 13th & 14th Feb?
> 
> 2. /on_update (partial cancel):
> 
> * items array shows item 45340561047852, with count 1 for forward shipment fulfillment & 1 for cancel (total is 2 but /on_confirm, count is 3);
> * quote_trail has entry for tax but tax isn't in any quote so far?

**Comment by BLR-0118** [comment]
Flow 6a
=====
1. /on_confirm:
- fulfillment TAT is P7D, so if pickup slot is between 16th & 17th, delivery slot should be between 23rd to 24th, correct?

2. /on_update (partial cancel):
- quote_trail having refund of 380 is wrong as cost of item is 200 (as per /on_confirm);

3. /on_update (liquidated):
- quote has unit price of -180 for item 45340560359724: how??

Flow 6b
=====
1. /on_update (partial cancel):
- quote_trail has entry for tax, which isn't in /on_confirm quote; pls only include items that are already a part of the quote (except for additional fulfillment charges like RTO charges);

2. /on_update (return initiated):
- fulfillment id for return fulfillment should be same as return request id;

3. /on_update (return picked):
- quote_trail should be a part of the return fulfillment;

**Comment by BLR-0118** [comment]
@purushottamKj - pls resubmit logs for flow 6

**Comment by ShippuYadav** [comment]
@BLR-0118 Please check PR https://github.com/ONDC-Official/v1.2.0-logs/pull/941

**Comment by BLR-0118** [comment]
Flow 6a (merchant part cancel)
=====
1. /on_confirm:
- pickup loc is 560066, drop loc is 560056 but:
- TAT is 7 days;
- pickup slot is between 24th & 25th Feb;
- delivery slot is between 24th Feb (same time as pickup start slot) & 1st Mar;
- this isn't correct, pls provide realistic values;
2. /on_update_partial_cancel:
- reason code 005 isn't valid for part cancel;

Flow 6c (return with pickup)
=====
1. /on_update_return_approved:
- pickup location for return should be the forward shipment drop location;

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 sir please review this PR 
 https://github.com/ONDC-Official/v1.2.0-logs/pull/1015

**Comment by BLR-0118** [comment]
Flow 6a
=====
1. /on_init:
- SNP collecting prepaid payment not yet enabled; pls remove;
2. /on_confirm:
- fulfillment TAT is 7 days, start slot is 4th-5th March, shouldn't the end slot be 11th-12th March?
3. /on_update_liquidated:
- items[] should have item: 45340561047852, fulfillment: 0a4a6c37-7622-46b9-a501-2b48527f4a3e, with quantity.count = 0;

Flow 6b
=====
1. same issues as for 6a;
2. pls also share log for return failure;

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, Please check this PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1062

**Comment by BLR-0118** [comment]
@ShippuYadav - don't see this fix in above PR

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, This PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1062 is of on_search for ONDC:RET14, ONDC:RET15 and ONDC:RET16 and this PR is of fashion as per feedback
 https://github.com/ONDC-Official/v1.2.0-logs/pull/1070

**Comment by BLR-0118** [comment]
Flow 6b
=====
1. /on_update_return_picked:
- items[] needs an entry for item 45340560359724 for forward fulfillment 0a4a6c37-7622-46b9-a501-2b48527f4a3e;

2. Also, share log for return rejection (during pickup);

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir please check the **"Logs for return rejection has been added and Item object has been corrected as per feedback"**
https://github.com/ONDC-Official/v1.2.0-logs/pull/1191

**Comment by BLR-0118** [comment]
flow 6b
=====
1. /on_confirm:
- PAN no of provider (provider_tax_number) doesn't match PAN no of aggregator (within GST no identified by tax_number), hence, can't be ISN;
2. /on_update_return_picked_failed:
- items[]  is wrong: for item 45340561801516, 1 qty should be assigned to cancel fulfillment (correct), the other qty should be assigned to forward shipment fulfillment (wrong);
3. pls also make sure that for return picked, the start & end address are in return fulfillment;

**Comment by BLR-0118** [comment]
@ShippuYadav - clearing logs for v1.2.0 (RET12), but pls make sure the above is fixed;

**Comment by ShippuYadav** [comment]
@BLR-0118 Sure sir

> @ShippuYadav - clearing logs for v1.2.0 (RET12), but pls make sure the above is fixed;
