### ISSUE TITLE
Adloggs LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#43]
## Flow 1

**/search**

- /on_search/0/context/timestamp must match format "date-time"

**/on_search**

- /on_search/0/message/catalog/bpp~1providers/0/items/0/fulfillment_id must be string
- motorable distance is not recorded accurately
- for TAT <= 60M , Immediate delivery should be used in /items

**/on_init**

- /on_init/0/context/timestamp must match format "date-time"
- /on_init/0/message/order must have required property 'payment'
- /on_init/0/message/order/items/0/fulfillment_id must be equal to constant (1)

**/confirm** (LSP should send NACK for required attributes and schema errors)

- /confirm/0/message/order/items/0/fulfillment_id must be string
- /confirm/0/message/order/fulfillments/0/end/instructions must have required property 'short_desc'
- /confirm/0/message/order/payment must have required property 'collected_by'

**/on_confirm**

- /on_confirm/context/timestamp must match format "date-time"
- /on_confirm/message/order/items/fulfillment_id must be string
- /on_confirm/message/order/quote object mismatches in /confirm and /on_confirm.
- /on_confirm/message/order/fulfillments/start/time not required when ready to ship = no
- /on_confirm/message/order/fulfillments/end/time not required when ready to ship = no
- /on_confirm/message/order/fulfillments/end/instructions must have required property 'short_desc'
- /on_confirm/message/order/payment must have required property 'collected_by'
- /on_confirm/0/message/order/payment must have required property 'collected_by'

**/update**

- /update/0/message/order/fulfillments/0/end/instructions must have required property 'short_desc'
- /update/0/message/order/fulfillments/0/tags both 'state' and 'rto_action' tags are required

**/on_update**

- /on_update/context/timestamp must match format "date-time"
- /on_update/message/order/tags (bpp_terms and bap_terms) are not required
- /on_update/message/order/items/fulfillment_id must be string
- /on_update/message/order/fulfillments/start/time range and timestamp must match format "date-time"
- /on_update/message/order/fulfillments/end/time range and timestamp must match format "date-time"
- /on_update/message/order/fulfillments/end/instructions must have required property 'short_desc'
- /on_update/message/order/payment must have required property 'collected_by'
- /on_update/message/order/created_at mismatches in /confirm and /on_update

**/on_status**

- /on_status/context/timestamp must match format "date-time"
- /on_status/message/order/tags (bpp_terms and bap_terms) are not required
- /on_status/message/order/items/fulfillment_id must be string
- /on_status/message/order/fulfillments/start/time range and timestamp must match format "date-time"
- /on_status/message/order/fulfillments/end/time range and timestamp must match format "date-time"
- /on_status/message/order/payment must have required property 'collected_by'
- Pickup timestamp (fulfillments/start/time/timestamp) cannot change for fulfillment state - Order-delivered
- Pickup timestamp (fulfillments/start/time/timestamp) cannot be provided for fulfillment state - Agent-assigned"
- Delivery timestamp (fulfillments/end/time/timestamp) cannot be provided for fulfillment state - Agent-assigned"
- Delivery timestamp (fulfillments/end/time/timestamp) cannot be provided for fulfillment state - Order-picked-up"

**/track**

- /track/0/context/timestamp must match format "date-time"

**/on_track**

- /on_track/0/context/timestamp must match format "date-time"

## RTO Flow

- similar issues as above

**/on_cancel**

- Order state should be 'Cancelled' for fulfillment state - RTO-Initiated
- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Cancelled

**/on_status**

- RTO Delivery timestamp (fulfillments/end/time/timestamp) is missing for fulfillment state - RTO-Delivered",
- RTO Pickup time (fulfillments/start/time/timestamp) cannot change for fulfillment state - RTO-Delivered"

**Comment by abhinavv245** [comment]
## Order Process Flow

- context/timestamp difference between on_action and action should be within 1 seconds

## RTO Flow

**/on_status**

- /on_status/2/message/order/quote price is not matching with the total breakup price (RTO)

**/on_cancel**

- /on_cancel/0/message/order/quote price is not matching with the total breakup price
- /on_cancel/0 created_at/updated_at must not be future dated

## Buyer cancel flow

- similar issues as above

**/on_update**

- start/time/timestamp or end/time/timestamp cannot be provided in /fulfillments when fulfillment state is Pending

**on_cancel**

- /on_cancel/0 created_at/updated_at must not be future dated

**Comment by vignesh11111** [comment]
/on_cancel/0/message/order/fulfillments/0 must have required property 'vehicle'
/on_cancel/0/message/order/fulfillments/0 must have required property 'tags'

   -->  In the 1.2.0 LSP API documentation, the 'vehicle' field is now optional, and 'tags' have been removed from fulfillments. Please let me know if my understanding is incorrect. https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit

**Comment by abhinavv245** [comment]
@vignesh11111 
- vehicle can be optional. 
- for RTO flow, tags are mandatory in fulfillments, kindly check the example for on_cancel (RTO Flow) for the same.

**Comment by vignesh11111** [comment]
Thanks @abhinavv245 For your quick reply, Sure i will check on_cancel (RTO Flow)  

context/timestamp difference between on_action and action should be within 1 seconds ---> In that case, we need to check rider availability, which takes 2 or 3 seconds. Please provide any suggestions for this.

**Comment by abhinavv245** [comment]
## Buyer cancel flow

- context/timestamp difference between on_action and action should be within 1 seconds (in all Flows)

**/on_search**

- 'Immediate Delivery' should be used in categories and items for TAT<= 60 minutes (instead of 'Standard Delivery')
- motorable distance between start and end location should be correctly recorded

**/init**

- billing details should be of the logistics buyer and not the end buyer

**/confirm**

- total item weight is not matching with the order weight in linked order

@vignesh11111

**Comment by abhinavv245** [comment]
## All flows

- context/timestamp difference between /on_action and /action APIs should be within 1 sec

**/on_track**

- location.gps is incorrect (why is rider in Bangalore when the order is for Hyderbad)

## Buyer cancel flow

**/on_confirm**

- start.time.duration (average time to pickup) is missing

@vignesh11111

**Comment by abhinavv245** [comment]
## All Flows

**/on_status**

- payment/status is missing

**on_cancel(RTO)**

- in /items RTO item time/duration mismatches from the one provided in /on_search 

@vignesh11111

**Comment by BLR-0118** [comment]
1. /on_init, /on_confirm:
-cancellation_terms not yet enabled, suggest you drop this for now;

2. tracking:
- to optimize processing, pls set gps_enabled to "yes" in /on_status, so buyer app can start calling /track;
- pls send the complete payload for /on_track (as per contract);

3. /cancel:
- "006" isn't a valid cancellation code for LBNP, pls use "007" (@dgowda604);

4. /on_cancel:
- pls add precancel_state, as per contract;

5. /on_cancel (RTO):
- pls add precancel_state, as per contract;

**Comment by BLR-0118** [comment]
@vignesh11111 - pls fix the above & resubmit

**Comment by vignesh11111** [comment]
@BLR-0118 **Point number 2 - pls send the complete payload for /on_track (as per contract);**   

We have sent the entire field as available in the API contract. Tags are optional, which is why we did not send them. Pls check and confirm

**Comment by BLR-0118** [comment]
@vignesh11111 - since there are interop issues with making it optional, request to pls send this; I've updated contract to make this mandatory

**Comment by vignesh11111** [comment]
Sure I will add @BLR-0118

**Comment by vignesh11111** [comment]
If I added the configuration type as 'deferred,' is it correct that the 'code':'path' list is not mandatory in on_track tags? @BLR-0118

**Comment by BLR-0118** [comment]
deferred is for url tracking for intercity; you need to use live_poll

**Comment by vignesh11111** [comment]
Ok ,                      
                        {
                            "code": "path",
                            "list":
                                [
                                    {
                                        "code": "lat_lng",
                                        "value": "12.974002,77.613458"
                                    },
                                    {
                                        "code": "sequence",
                                        "value": "1"
                                    }
                                ]
                        },

Ok i will change it to "live_poll". Please confirm above given objects are mandatory in the tags.

**Comment by BLR-0118** [comment]
yes, there's another part for order id;

**Comment by vignesh11111** [comment]
Logs submitted

**Comment by BLR-0118** [comment]
@vignesh11111 - clearing logs for v1.2.0; pls fix 1 before deployment & respond to 2;

**Comment by vignesh11111** [comment]
Thanks for your approval. @BLR-0118 

Point 1 - Removed bpp_terms
Point 2 - Sure , they able to use url also
