### ISSUE TITLE
DIGIIT (SA: RET10) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#436]
Flow 1
====
- logs should also be generated for v1.2.0 as has been done for flows 2 onwards;
- you can provide better buyer experience using features such as variants;
- item.descriptor.code for grocery should be EAN (1:), not GTIN (3:);
- logs for incremental update to be provided;

Flow 2
====
1. /on_select:  needs to have provider.locations, fulfillment.type as documented in contract;
2. /on_init:
- remove provider_location;
- remove cancellation_terms (will be enabled in phase 2);
- remove from bpp_terms (max_liability, max_liability_cap) as this will be enabled in phase 2;
3. /on_confirm: same issues as /on_init;

Flow 3
====
1. /on_select_out of stock:
- pls use error format as documented [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

Flows 4 & 5 are wrong; pls follow the contract [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec) & [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.p49oiq6osp4) - note that with cancellation (RTO or otherwise), a separate fulfillment is created & items assigned from the forward shipment fulfillment to this new fulfillment; also, change in order value line item wise is maintained in the quote_trail for this fulfillment;

**Comment by BLR-0118** [comment]
@vignesh-arvind

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full catalog):
- most items being sent are for RET10 but Context shows RET15 (pls note that catalog has to be separated by RET codes);
- use meaningful name for variant instead of "Variant Group 1";
- attribute "Base" in variant definition is invalid;
- variant group definition attribute has to be enabled for the RET code as per [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0) & same attribute has to be defined for each item that's a part of the variant group (for buyer apps to group them for display);
- check the [sample grocery catalog](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv) for how variants are defined;
- parent_item_id "V1" for item 991 is not defined (has to match variant definition categories.id;
- unit "Number" for item 991 is invalid (has to be valid value from [this](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json) list);
- item.quantity.available.count has values "99" (in-stock) or "0" (out-of-stock); pls make sure you comply with this;
- item.quantity.maximum.count has values "99" (no order cap) or any other value identifying the order cap;
- for provider "170", serviceability defined only for "Oil & Ghee", even though there are several other categories for which items are defined;

2. /on_search (incremental catalog):
- full catalog search was for RET15 but incremental search is for RET17 for the same items in full catalog (pls use the same RET code for full & inc catalog refresh);
- scope of incremental catalog refresh is limited only to item record update, disable of provider, disable/close/open of provider location;

Flow 2
====
1. /on_select:
- how is "Next Day Delivery" having TAT of 1hr (shouldn't this be 1 day)?

2. /on_confirm:
- in /on_select, fulfillment provider_name was "Ganesh", in /on_confirm it's "freshon"?
- fulfillment.start.instructions (pickup code) shouldn't be sent to buyer app unless buyer app is providing logistics;
- both pickup & delivery codes are being set to OTP, but for OTP the authorization structure needs to be used;
- pls add provider_tax_number;

3. /on_status:
- /on_status (packed) has same message_id as /confirm?
- tracking info could be either gps (hyperlocal) or URL(intercity); since this is hyperlocal, only gps should be set;
- also set routing.type to P2P;
- all /on_status have same message_id, which is same as in /confirm; each new unsolicited message should have unique message_id, while solicited response has same message_id as request;
- agent assigned state also has to be sent in /on_status;

4. tracking is enabled as per the order flow APIs but no tracking APIs provided;

Flow 3
====
1. /on_select (out of stock):
- error.message should have attr/values in esc quotes as shown [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

Flow 4
====
1. /on_cancel:
- cancel fulfillment should have type "Cancel" (note Pascal case);
- items array should have 2 entries - 0 qty for forward shipment fulfillment & 1 qty for cancel fulfillment;
- quote_trail should have -ve value for item (& delivery charges) if cost of item (& delivery charges) are being refunded;
- quote will have the new value for order, i.e. if both item & delivery charges refunded, both should be having 0 value;
- pls add precancel_state;

Flow 5
====
1. /on_cancel:
- all issues (as above for flow 4) also apply here;
- cancelled_by should have the bpp_id as this cancellation is by seller;
- few additional attrs required in cancel_request, such as retry_count, rto_id;

Flow 6-A
======
1. part cancel by merchant requires the /on_update flow as doc in contract [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.2je0y89ymfqj);

Flow 6-B
======
1. /on_update (12) has earlier timestamp than /update (11);
2. fulfillment for return is created (with same id as return request id from /update) in Return_Initiated, with fulfillment type of Return;
3. quote is correct but quote_trail needs to follow what's mentioned for the cancel flows;

Flow 6-C
======
1. same issues as above regarding creation of return fulfillment;
2. return with pickup follows multiple steps & logs need to be shared for all these steps;

**Comment by BLR-0118** [comment]
@vignesh-arvind - pls resubmit logs for flow 1, 2, 5, 6

**Comment by vignesh-arvind** [comment]
@BLR-0118  @sandeepshahi  pls review the logs

**Comment by Jagannath-wits** [comment]
# Flow 1

### On Search Full Catalog Refresh

#### Schema Errors
- using deprecated category IDs
-"schemaErr0": "/message/catalog/bpp-1providers/0/items/11/category_id Invalid category ID found for item for on_search",
-"schemaErr1": "/message/catalog/bpp-1providers/1/items/2/category_id Invalid category ID found for item for on_search",
-"schemaErr2": "/message/catalog/bpp-1providers/1/items/3/category_id Invalid category ID found for item for on_search",
-"schemaErr3": "/message/catalog/bpp-1providers/1/items/4/category_id Invalid category ID found for item for on_search",
-"schemaErr4": "/message/catalog/bpp-1providers/1/items/5/category_id Invalid category ID found for item for on_search",
- **Schema Error 5**: providers/1/items/7 Item must have required property '@ondc/org/time_to_ship'.
- **Schema Error 6**: providers/2/items/6 Item must have required property '@ondc/org/available_on_cod'.

#### Invalid Area Code

- STD code does not match with correct area_code on /on_search.

#### Missing Origin Tag

- Origin tag fields are missing for Grocery items .

#### Item Prices

- Item prices should be greater than 0 for provider[1].items 1, 3, 5, 7, 9.

#### BPP Descriptor

- accept_bap_terms is not required in bpp/descriptor/tags for now.

#### Duplicate IDs

- Duplicate category IDs: 97-PRD-AET-578, 97-PRD-JVV-581, 97-PRD-ZCX-625 in bpp/providers[1].
- Duplicate item IDs: 1106, 1107 in bpp/providers[1].

### Search Inc Refresh

#### Intent

- **End Time Value**: /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp.

#### On Search Inc Refresh

- **BPP Fulfillments**: bpp/fulfillments sent in payload shouldn't be part of /on_search_inc_refresh api.
- **BPP Descriptor**: bpp/descriptor sent in payload shouldn't be part of /on_search_inc_refresh api.
- **Location Time Label**: location label (/bpp/providers/locations/time/label) for /on_search_inc_refresh should not be equal to /on_search_full_catalog_refresh.label.

# Flow 2

### On Init

#### Provider Tax Number

- **Provider Tax Number**: provider_tax_number must be present for on_init.

# Flow 3

### Select Out of Stock

#### Timestamp Mismatch

- **Tmpstmp**: Timestamp for /on_search api cannot be greater than or equal to /select api.

### Select

#### Timestamp Mismatch

- **Tmpstmp**: Timestamp for /on_search api cannot be greater than or equal to /select api.

### On Select

### Confirm

#### Message Order Tags

- **Message.Order.Tags[1].List**: Number of digits in tax number in message.order.tags[1].list should be 15.

#### BAP GST Tags

- **BapGstTags**: Tags/bap_terms should have valid gst number and fields in /confirm.

### On Confirm

#### Message Order Tags

- **Message.Order.Tags[1].List**: Number of digits in tax number in message.order.tags[1].list should be 15.

#### Message/Order/Tags/Bpp_Terms/Np_Type

- **Message/Order/Tags/Bpp_Terms/Np_Type**: np_type is missing in message/order/tags/bpp_terms for ON_CONFIRM.

#### Tags Bap Terms

- **Tags_Bap_Terms**: Tags should have same and valid gst_number as passed in /confirm.

### On Status Pending

- missing payload

### On Status_all

#### Schema Error

- **SchemaErr0**: /context must have required property 'ttl'.

### On Status Out For Delivery

#### Invalid Message ID

- **Invalid_Message_Id**: Message_id cannot be same for on_status.packed and on_status.out_for_delivery.


# Flow 4( why is the domain ret14 when rest are ret10)

- ** why is @ondc/org/item_id and fulfillment_id same ?**

### On Cancel

#### Schema Errors

- **SchemaErr0**: /context must have required property 'ttl'.
- **SchemaErr1**: /message/order/fulfillments/0/start/location must have required property 'id'.
- **SchemaErr2**: /message/order/fulfillments/0/start/location must have required property 'address'.
- **SchemaErr3**: /message/order/fulfillments/0/end must have required property 'person'.

#### Item Count

- **ItemCount[1]**: Item count should be 0 for /on_cancel in forward shipment.

#### Cancel Fulfillment Missing

- **CancelFulfillmentMissing**: fulfillment type cancel is missing in /on_cancel.

#### Fulfillment Mismatch

- **Fulfillment_mismatch**: The count of cancellation fulfillments is not equal to the count of forward fulfillments or invalid fulfillment id.

#### Specific Fulfillment ID

- **FfID b59da434-7851-48f3-b296-011cb6b9bb57**: fulfillment id b59da434-7851-48f3-b296-011cb6b9bb57 does not exist in /on_cancel items.fulfillment_id.

#### Missing Cancel

- **MissingCancel**: Cancel object is mandatory for on_cancel.

#### Missing Pre Cancel

- **MissingPreCancel**: Pre Cancel is mandatory for on_cancel.

# Flow 5

### On Cancel

#### Schema Error

- **SchemaErr0**: /context must have required property 'ttl'.

#### Fulfillment ID

- **FfID 5f294705-55bf-4197-9227-d9e41ea08bf1**: fulfillment id 5f294705-55bf-4197-9227-d9e41ea08bf1 does not exist in /on_cancel items.fulfillment_id.

#### Missing RTO

- **MissingRTO**: RTO object is mandatory for on_cancel.


# Flow 6-a

### On Update

#### Schema Error

- **SchemaErr0**: /message/order/fulfillments/0/start/location must have required property 'id'.

#### Timestamp Consistency

- **Context/Timestamp**: context/timestamp should be greater than message/order/updated_at timestamp.

#### Invalid Quote Trail Prices

- **InvldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm.

#### Invalid Cancellation ID

- **InvldCancellationID**: Invalid CancellationID 008 or not allowed for SNP.


# Flow 6-b

### On Update Interim
- missing payload

### On Update Approval

#### Schema Errors

- **SchemaErr0**: /message/order/fulfillments/0/start/location must have required property 'id'.

### On Update Picked

#### Schema Errors

- **SchemaErr1**: /message/order/fulfillments/0/start/location must have required property 'id'.

#### Invalid Quote Trail Prices

- **InvldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm.

### Update Settlement
- missing payload

### On Update Delivered

#### Schema Errors
- **SchemaErr1**: /message/order/fulfillments/0/start/location must have required property 'id'.

#### Invalid Quote Trail Prices

- **InvldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm.

# Flow 6-c

### On Update Interim

#### Schema Error

- **SchemaErr0**: /message/order/fulfillments/0/start/location must have required property 'id'.

#### Timestamp Consistency

- **Context/Timestamp**: context/timestamp should be greater than message/order/updated_at timestamp.

### On Update Liquidated

#### Schema Error

- **SchemaErr0**: /message/order/fulfillments/0/start/location must have required property 'id'.

#### Invalid Quote Trail Prices

- **InvldQuoteTrailPrices**: quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm.

@vignesh-arvind

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- "Size" is invalid attribute for grocery (RET10) items, pls only use the attrs in [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0) spreadsheet;
- item unitized value needs to be correctly defined, e.g. for item 1106: 
- quantity.unitized,measure.unit = "millilitre" (enum [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json));
- quantity.unitized.measure.value = "500";

**Comment by BLR-0118** [comment]
@vignesh-arvind

**Comment by vignesh-arvind** [comment]
Hi @BLR-0118 

only in Flow 1 on_search needs to be re-submitted ??, pls advice.

**Comment by JyotiSharma0711** [comment]
# Flow 1

## on_search_full_catalog_refresh

- "invalidCategoryIdOil & Ghee": "Invalid category_id (Oil & Ghee) for Grocery"
- "invalidCategoryIdCleaning & Household": "Invalid category_id (Cleaning & Household) for Grocery"
- "invalidCategoryIdKitchen Accessories": "Invalid category_id (Kitchen Accessories) for Grocery"
- "invalid_attribute[1][3]": "Invalid attribute for item with category id: Brand"
- "invalidCategoryIdStationery": "Invalid category_id (Stationery) for Grocery"
- "invalid_attribute[2][0]": "Invalid attribute for item with category id: Brand"
- "invalidCategoryIdBeverages": "Invalid category_id (Beverages) for Grocery"
- "invalidCategoryIdBeauty & Hygiene": "Invalid category_id (Beauty & Hygiene) for Grocery"
- "invalidCategoryIdBaby Care": "Invalid category_id (Baby Care) for Grocery"
- "prvdr0item5statutoryReq": "The following item/category_id is not a valid one in bpp/providers for /on_search"

-Follow this doc and update your category accordingly
https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit?gid=0#gid=0


## on_search_inc_refresh

- Provide search incremental and on_search incremental

# Flow 2

## on_select

- "fulfillment0/@ondc/org/category": "In Fulfillment0, @ondc/org/category is not a valid value in on_select and should have one of these values Immediate Delivery, Standard Delivery, Express Delivery"

## on_init

- "message.order": "'cancellation_terms' in /message/order should not be provided as those are not enabled yet"

## on_confirm

- same as init

# Flow 3, Flow 4

- same as Flow 2

# Flow 5

## on_confirm

- "context/timestamp difference between /on_confirm and /confirm should be less than 5 sec"

## on_cancel

- "invldQuoteTrailPrices": "quote_trail price and item quote price sum for on_cancel should be equal to the price as in on_confirm"
- "precancelState.updatedAt": "precancel_state.updated_at of on_cancel is not equal with the on_status_out_for_delivery order.updated_at"

# Flow 6

## on_update_part_cancel

- "quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm"

## on_status_packed

- "message/order.fulfillments/0/start/location": "Mismatch occurred while comparing 'Delivery' fulfillment object with on_confirm on key 'start/location'"

## on_status_picked

- "message/order.fulfillments/0/start/location": "Mismatch occurred while comparing 'Delivery' fulfillment object with on_confirm on key 'start/location'"
- "message/order.fulfillments/0/end/time": "Mismatch occurred while comparing 'Delivery' fulfillment object with on_confirm on key 'end/time'"

## on_status_out_for_delivery, on_status_delivered

- Same as on_status_picked

## on_update_interim_reverse_qc

- "message/order.payment/@ondc/org/settlement_details/0": "Missing payment/@ondc/org/settlement_details as compared to the previous calls or not captured correctly i.e. {\"settlement_counterparty\":\"buyer\",\"settlement_phase\":\"refund\",\"settlement_type\":\"netbanking\",\"settlement_amount\":\"735\",\"settlement_timestamp\":\"2024-07-14T03:57:18.782Z\"}"
- "message/order.fulfillments/Cancel/tags/quote_trail": "Missing fulfillments/Cancel/tags/quote_trail as compared to the previous calls"

## on_update_approval

- "returnFF/start/time/range/start": "start/time/range/start time of return fulfillment should be greater than context/timestamp of on_update_approval"

## on_update_picked

- "invldQuoteTrailPrices": "quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm"

## on_update_delivered

- "message/order.payment/@ondc/org/settlement_details/1": "Missing payment/@ondc/org/settlement_details as compared to the previous calls or not captured correctly i.e. {\"settlement_counterparty\":\"buyer\",\"settlement_phase\":\"refund\",\"settlement_type\":\"netbanking\",\"settlement_amount\":\"126\",\"settlement_timestamp\":\"2024-07-14T04:05:23.366Z\"}"
- "invldQuoteTrailPrices": "quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm"

@vignesh-arvind

**Comment by sahil-ondc** [comment]
@vignesh-arvind, Issues reported in last iteration are still not rectified and persists in latest logs, Kindly go through the previous feedback.
Also run **log validation utility** before logs submission for self iterations. 
`https://github.com/ONDC-Official/log-validation-utility`

**Comment by vignesh-arvind** [comment]
Hi @sahil-ondc ,
as we have already checked with Log validation Utility and the previous comments are resolved from our end.

**Comment by vignesh-arvind** [comment]
Hi @sahil-ondc 

As we have resolved the previous comments and tested with the log validation tool, We haven't got any error responses, except 5 secs response in Flow 2 confirm and on_confirm, could you pls confirm again ?

**Comment by sahil-ondc** [comment]
## Flow 1


### On Search
- Variants are not captured properly for the category_id  ‘02DBDDE2-2830-4DA4-ACE8-CEE8187FA5DB’, ‘B6C3D1BF-844B-412C-A435-1F6348ED5672’

### On Search Inc
- Provide search incremental and on_search incremental

## Flow 2



### On Confirm
- context/timestamp difference between /on_confirm and /confirm should be less than 5 sec


### On Status Picked
- Mismatch on key 'start/location/email’ on Delivery' fulfillment object as compared with on_confirm

### track/on_track
- Track and on_track must be provided if the tracking is true



## Flow 5
- On status RTO disposed/delivered must be provided

**Comment by sahil-ondc** [comment]
## Flow 6
### On Update Part Cancel
- Extra tags are provided in the ‘Cancel' fulfillment object on key 'tags/0'
- Cancel fulfillment id is missing in part cancel and the quantity isn’t reduced in the items
 
### On Status Out For Delivery
- Mismatch occurred while comparing 'Cancel' fulfillment object with on_update_part_cancel on key 'tags/0'
 
### On Update Interim Liquidated
- Return fulfillment id should be created at on_update_liquidated 
- Settlement Details are not carry forward in of part cancellation
 
### On Update Liquidated
- The quantity isn’t reduced in the items for liquidated item in the items
 
### On Update Interim ReverseQc
- Return fulfillment id should be created at on_update_picked
- Settlement Details are not carry forward of part cancellation and liquidation 
- Fulfillment and Quote trails are not carry forward of the the previous action calls
 
### On Update Picked
- The quantity isn’t reduced in the items for reverse_qc item in the items
- Quote_trail price and item quote price sum for on_update should be equal to the price as in on_confirm

@vignesh-arvind

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- /message/catalog/bpp~1fulfillments/2/type must be equal to one of the allowed values (Delivery,Self-Pickup)
 
 
### On Search Inc
- Message id should not be same with previous calls as it's incremental push based call
- bpp/fulfillments sent in payload should not be part of /on_search_inc_refresh api
- bpp/descriptor sent in payload should not be part of /on_search_inc_refresh api
- Many extra attributes have been sent, kindly refer to the contract for the incremental changes scenario at page no. ‘172’
- No incremental changes are observed for the given item_id : ‘1727’
 
## Flow 2 
 
### On Init
- If the settlement_type is ‘neft’, upi_address is not required 
 

 
### On Status Picked
- url_enabled is missing in the ‘tracking’ attribute
- invoice is not publically accessible
 
### On Status Delivered
- timestamp is missing for the delivery in the end object
 
## Flow 3
 
### On Select Out Of Stock
- `@ondc/org/provider_name` mismatch as compared to the on_select call
 
## Flow 5
 
### On Cancel
- It should be initiated by either seller or logistics, not by buyer
- cancellation object is missing
 
### On Status Rto Disposed/Delivered
- agent attribute is not required in the ‘Delivery’ fulfillment
- cancel request and pre-cancel state is missing in the ‘Delivery’ fulfillment
- Extra attributes like instructions which were not present in the ‘Delivery’ fulfillment which was not present in the on cancel call
- Ranges have been changed in the ‘Delivery’ fulfillment as compared to the on_cancel call
- time object is empty in ‘Rto’ fulfillment
- fulfillment type rto end/time is missing in /on_status_rto_delivered/disposed
- Instructions in ‘RTO’ fulfillment is not present in the on_cancel 
- quote_trail is missing for the ‘delivery’ in the ‘RTO’ fulfillment
 
### On Update Liquidated
- image url is not accessible in the ‘Return’ fulfillment
- settlement_details of part cancellation is not carry forwarded
 
### On Update Approval
- Why the item quantity is changed to ‘0’ from ‘1’ in the ‘Return request’ for the item_id : ‘1753’
- Settlement details are missing for the part cancellation and liquidation 
 
### On Update Picked
- invoice is not publically accessible 
- Settlement details are missing for the part cancellation and liquidation 
 
### On Update Delivered
- Settlement details are not carry forward as compared to the previous calls

@vignesh-arvind

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- No incremental changes are observed for the item_id : ‘1731’, ‘1732’
 
## Flow 2
### On Status Packed
- Mismatch occurred while comparing 'Delivery' fulfillment object with on_confirm on key 'start/location'
- Invoice doesn’t matches with the quote provided
- The tracking URL is not displaying the start and end locations along with the route.
 
### On Status Delivered
- Mismatch occurred while comparing 'Delivery' fulfillment object with on_confirm on key 'end/contact'
 
## Flow 4
### Init
- items[0].fulfillment_id mismatches for Item 1700 in /on_select and /init
- fulfillment id 8ef25aac-355b-436a-9faf-c07f7753ccea does not exist in /on_select
 
## Flow 6
### On Status Picked
- Invoice is not updated after the part cancellation
 
### On Update Liquidated
- Invalid quote_trail for ‘tax’ is added in the return_request which was not present in the quote 
 
### On Update Approval
- Return fulfillment should be created in the items in on_update_picked action call
- why the item is change from ‘1’ to ‘0’ in the ‘return_request’
 
### On Update Picked
- Invalid quote_trail for ‘tax’ is added in the return_request which was not present in the quote 

@vignesh-arvind

**Comment by shivang1131** [comment]
Estimated pickup time range can't be earlier than context/timestamp; check fulfillments/start/time/range/start.
Invalid Invoice generation. Breakup is not correctly shown.

## Flow 1
### Inc_on_search
- No Unicode characters allowed in inc_on_search.

## Flow 3
### on_select
- Flow is incorrectly submitted. The same item is suddenly in-stock after the on_select_out_of_stock call.

## Flow 4
### on_cancel
- Delivery charge cannot be applied if the item was not out for delivery.

## Flow 5

**/on_status**

- invalid invoice generation; why is the net amount 20?

**/on_cancel**

- actual pickup timestamp is missing in forward shipment: "178bdd74-fc32-483d-b9e4-6e519c4fc1b2"
- RTO pickup timestamp can't be future dated; check fulfillments/start/time/timestamp in "RTO" type
- line item with price=0 need not be provided in quote_trail

**/on_status (RTO delivered)**

- actual rto delivery timestamp is missing; delivery range need not be provided for RTO


**/on_init**

- pls add "np_type" in /tags/bpp_terms

**/on_confirm**

- estimated pickup time range can't be earlier than context/timestamp; check fulfillments/start/time/range/start

**/on_update (part cancel)**

- estimated time ranges should not change; must remain the same as provided in "Accepted" state

**/on_status**

- "routing" type should be provided before the order is picked and in the subsequent APIs

- Packed:
  - additional instructions for pickup/delivery should be provided in /instructions/long_desc
  - DCC code in /end/instructions should be provided once the order is Out for delivery
- Picked:
  - How can delivery images (end/instructions/images) be provided even before the order is delivered?
  - Invoice is incorrect; shouldn't be updated later when the order is getting returned

**/on_update**

- interim liquidated:
  - start and end instructions should not change in the forward shipment fulfillment; must remain the same for all the call
- liquidated:
  - order/created_at timestamp should not change in any call; must remain the same as in /confirm call
- interim reverse qc:
  - store location id in /fulfillments/start/location should not change
- approved:
  - reverseqc input tag is not captured correctly; value of questionnaire ("Q001") shouldn't be filled in Approved state
- picked:
  why is forward shipment instructions changing?
- delivered:
  - invalid quote trail for "tax" line item


Is catalog rejection implemented?
@vignesh-arvind

**Comment by shivang1131** [comment]
## Flow1
### on_search
- Is fssai license number valid for the merchant? none of the products are part of packaged food.
- Placeholder values of EAN code should not be provided in item.descriptor.code.

## Flow 2
### on_status packed
- Additional instructions for pickup/delivery should be provided in /instructions/long_desc
- DCC code in /end/instructions should be provided once the order is Out for delivery

### On_status picked
- Invoice has incorrect breakup.
- "routing" type should be provided before the order is picked and in the subsequent APIs

## Flow 3
Same issues as above.


## Flow 4
- Delivery charges that have been reduced to zero should also be passed in the quote trail.

## Flow 5, Flow 6
Please fix previously mentioned issues.

@vignesh-arvind

**Comment by vignesh-arvind** [comment]
Hi @shivang1131 

Actually all these comments are closed in Flow 2, 3, 4, 5 and 6   could you pls confirm again. Except flow 1 we have closed all the mentioned issues.

**Comment by shivang1131** [comment]
Hi,
The logs recently submitted still have issues. If you could please resubmit the logs.

Regards

@vignesh-arvind

**Comment by sandeepshahi** [comment]
Logs approved for v1.2 (RET 10)

@vignesh-arvind
