### ISSUE TITLE
MP2  (LSP-IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#447]
Issue :

- The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same or greater than as 'message/issue/update_at' in issue , and can u pls explain why difference in the timesatamp is that much .

@Poornima-Aithal

**Comment by mherle** [comment]
Hi @RupalSingla 

Since the issue is only from the LBNP, should we consider this as logs approved for MP2 LSP ?

Cc: @BLR-0118 @Rishabh-ondc ?

**Comment by Rishabh-ondc** [comment]
Logs cleared

@mherle

**Comment by mherle** [comment]
Thanks @Rishabh-ondc . Appreciate this

**Comment by mherle** [comment]
@bluecypher pls do close this issue, as the logs are cleared for LSP

**Comment by mherle** [comment]
@bluecypher Can you pls mark this issue as closed ?

**Comment by mherle** [comment]
@abhinavv245 Pls close this issue
