### ISSUE TITLE
Krenai (SA: RSF) - compliance checks

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#459]
timestamp for receiver_recon and on_receiver_recon cannot be same.

receiver_recon:
order.state is having wron value needs to be Completed instead of Active.
context.timestamp cannot be less than settlement_timestamp
updated_at and created_at also needs to redefined
order_recon_status": "03" is incorrect this needs to be 01 that is provisional

on_receiver_recon:
order_recon_status": "03" is incorrrect , needs to be 02

@AnchalSharma07

**Comment by RupalSingla** [comment]
timestamp for receiver_recon and on_receiver_recon cannot be same.

receiver_recon
Context.timestamp cannot be similar to settlement.timestamp
settlement_redference no missmatch .


@AnchalSharma07

**Comment by RupalSingla** [comment]
Success Flow :
payment.params.amount is less than settlement amout , so in on_receiver_recon API counterpart_recon_status needs to be 02 which means overpaid , currently its 01.


@AnchalSharma07

**Comment by RupalSingla** [comment]
Receiver_recon

- withholding_tax_gst.value needs to string .
- withholding_tax_tds.value needs to string .
- deduction_by_collector needs to be string.
- 
@AnchalSharma07

**Comment by pratikmazumdar** [comment]
### Receiver Recon 
- 'message.orderbook.orders[0].payment.params' is required
- 'message.orderbook.orders[0].payment.@ondc/org/settlement_details[0].settlement_type' must be one of [upi, neft, rtgs]
- 'message.orderbook.orders[0].payment.@ondc/org/settlement_details[0].upi_address' is required
- 'message.orderbook.orders[0].payment.param' is not allowed
- 'message.orderbook.orders[0].invoice_number' is not allowed

### On Receiver Recon
- 'message.orderbook.orders[0].recon_status' is required
- 'message.orderbook.orders[0].message' is required
- 'message.orderbook.orders[0].invoice_number' is not allowed

**Comment by pratikmazumdar** [comment]
### receiver_recon
- 'receiver_recon.message.orderbook.orders[0].payment.params.transaction_status' is required

### on_receiver_recon
- 'on_receiver_recon.message.orderbook.orders[0].invoice_no' is required
- 'on_receiver_recon.message.orderbook.orders[0].recon_status' is not allowed

@AnchalSharma07

**Comment by RupalSingla** [comment]
receiver_recon:
 timestamp for settlement is for 2024-02-20T14:21:27.601Z and updated_at is 2024-02-09T06:45:09.633Z , which means orderbook is getting updated before settlement , which is not correct approch .

@AnchalSharma07

**Comment by RupalSingla** [comment]
Logs approved for RSF for version 1.0.0 

@AnchalSharma07
