### ISSUE TITLE
Fynd RSF - compliance check 

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#460]
receiver_recon:
values inside orders.payments are empty , placeholder values are not allowed 

Correction Flow:
receiver_recon:
values inside orders.payments are empty , placeholder values are not allowed 

@tusharmoraye

**Comment by azharsayyed05** [comment]
@RupalSingla receiver_recon is received and triggered from buyer app side hence please get it fixed from BA side

**Comment by RupalSingla** [comment]
Logs cleared  @azharsayyed05
