### ISSUE TITLE
Bitsila (Grocery) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#487]
1. /on_search:
- pls remove "accept_bap_terms" until it's enabled later;
- why are you using item.quantity.unitized.measure.unit of "unit" (like F&B) instead of more applicable ones like "kilogram", etc. as per the list [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json); this will also enable definition of variants for better UX;
- attribute "tomato varinats" for item "1375527" is invalid; for definition of variants in grocery, check [this](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv) & the above point;
- same issue with item 1464703, 1464702;
- for item.category_id, can you pls use the sub-categories from [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)?

**Comment by dgowda604** [comment]
@BLR-0118 resubmitted the logs as per the review, please do check this PR -> https://github.com/ONDC-Official/v1.2.0-logs/pull/499

**Comment by BLR-0118** [comment]
only issue which needs to be fixed:
- use default values for item.quantity.available.count of "99" (in-stock), "0" (out of stock);
- for item.quantity.maximum.count, use "99" if no cap per order or non-zero value for order cap e.g. "1" means only 1 item per order;
@dgowda604 - as discussed, pls make sure this is enabled in Prod;
logs cleared for grocery (RET10)

**Comment by dgowda604** [comment]
yeah sure @BLR-0118 , thanks!
