### ISSUE TITLE
ToneTag IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#501]
issue
-   "org_name": "Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID",
-    "updated_at": "The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in issue"

  "on_issue"
-  "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with BPP ID",
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue"

 "on_issue_status": 

-   "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with BPP ID",
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[1]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status",
-    "created_at": "'created_at' should match issue's 'created_at'"

 "on_issue_status_unsolicited":

-   "igmIssueMsgId": "MessageId should not match in /issue_status and /on_issue_status(unsolicited)",
-    "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with BPP ID",
-  "created_at": "'created_at' should match issue's 'created_at'"

@jagadeeswar577

**Comment by Rishabh-ondc** [comment]
on_issue
- context.timestamp same as issue API's context.timestamp
- issue.updated_at not changed

on_issue_status (solicited)
- context.timestamp same as on_issue_status API's context.timestamp
- issue.updated_at and respondent.updated_at same as on_issue_status API's context.timestamp
- organization.org.name should have the subscriber id of the resolution provider (seller app)
- resolution.resolution_action is not required
- resolution.resolution_remarks is an incorrect attribute

@jagadeeswar577

**Comment by Rishabh-ondc** [comment]
Logs cleared.

@jagadeeswar577
