### ISSUE TITLE
ITCStore (RET13, RET18) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#541]
RET13
====
1. /on_search:
- for item CHCRMSC200, name shows "200 ml" but unitized qty shows 200gm?
- same for item CHFWVC150, CHFWVC50, CHCRMCC200, CHCRMCC58 & many such items;
- instead of sending serviceability of 50km, pls consider sending geojson polygon for city of Gurgaon?
- no plan to enable variants?

RET18
====
1. /on_search:
- same issues as above;
- attribute should also have "prescription_required" as doc [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764);

**Comment by BLR-0118** [comment]
@ITCStore - pls fix & resubmit logs

**Comment by quantummach14** [comment]
@BLR-0118 for RET:18, we have masks, handwash, and sanitizers only. prescription_required is required for these items as well?

**Comment by BLR-0118** [comment]
@quantummach14 - yes, it's mandatory for RET18 as doc [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764)

**Comment by ITCStore** [comment]
@BLR-0118 RET:18 Logs: PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/561

**Comment by BLR-0118** [comment]
@ITCStore

**Comment by ITCStore** [comment]
@BLR-0118 Updated logs for RET13 and RET18. Please review. PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/603

**Comment by ITCStore** [comment]
@BLR-0118  We have submitted updated logs on 21Jan for RET 13 and 18.Please review: PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/603

**Comment by BLR-0118** [comment]
1. /on_search (RET18):
- for items such as FDPMPRHMPR (which is a combo pack), unitized qty of 3 units would be better than adding up the volumes of each pack item;

**Comment by BLR-0118** [comment]
@ITCStore - pls check the above;
clearing logs for v1.2.0 (RET13, RET18)
