### ISSUE TITLE
Wits Adapter (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#542]
Please avoid using placeholder values in the payload. Ex - collector_app_id": "abc.collectorapp.com
Correction Flow is missing 

on_settle
Timestamp between settle and on_settle API is more than 4 months , or timestamp for  on_settle api cannot be less than settle API.

on_receiver_recon:
message_id mismatched with receiver_recon API 

@vishal-wits

**Comment by vishal-wits** [comment]
@RupalSingla 
I have resubmitted the logs, please find below URL for your reference 
https://github.com/ONDC-Official/v1.2.0-logs/pull/607

**Comment by bluecypher** [comment]
**/receiver_recon**

- settlement_counterparty should be seller-app when collected by is BAP
- settlement_timestamp can't be earlier than orderbook creation time (created_at)

## Correction Flow

**/on_receiver_recon**

- context/timestamp can't be earlier than /receiver_recon timestamp


@vishal-wits

**Comment by bluecypher** [comment]
- All retail BNPs deduct the buyer app finder fee. Settlement related calculations must include proper checks and balances.

**Comment by bluecypher** [comment]
Logs cleared for Seller App RSF v1.0.0, subject to the above in-place validations.

@vishal-wits
