### ISSUE TITLE
Pincode (Buyer App) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#545]
1. /on_search:
- for electronics, fashion, BPC, etc., the item attribute "colour" will have the hex code and "colour_name" will have the colour name as doc [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=244000021) & [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.ryf2w2abaaxw) - will this be processed?
- if additional attrs are included e.g. "brand" or "model" & variant definition based on these attributes, will it be processed?

2. Incremental catalog update:
- when will incremental push be enabled?

3. Cancellation flows:
- the logs submitted here are for 1.1; if /on_cancel uses the response as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec) & [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.p49oiq6osp4), will it be processed?

4. Categories:
- there are many approved 1.2 logs for all flows for grocery, F&B submitted by SNPs with Pincode;
- however, I've not seen anyone submitting logs with Pincode for fashion, BPC, H&K, H&W; can you pls share the /search & /on_search logs for these categories?

**Comment by BLR-0118** [comment]
@thsubaku9 - pls respond to the queries above

**Comment by thsubaku9** [comment]
Acknowledged, will update over here soon

**Comment by thsubaku9** [comment]
1. Item Attribute and Variants support feature is in the pipeline, will inform here once these values are being utilized
2. We have pull support, push support hasn't been initiated yet and will require some effort (will have to get back to you with expected timelines for this)
3. Will submit cancellation flows for 1.2 shortly
4. Please find [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/566) for other category based searches

**Comment by BLR-0118** [comment]
@thsubaku9 - buyer app logs cleared for grocery (RET10), F&B (RET11), fashion (RET12), BPC (RET13), Electronics (RET14) subject to the above being completed for consuming attribute values for variants (RET12, RET13, RET14);

**Comment by BLR-0118** [comment]
@thsubaku9: pls share the following:
- logs for RET15, RET16, RET18 for /search & /on_search;
- timeline for consuming all item attributes for different categories & variants for RET12/13/14;
- timeline for enabling incremental push;

**Comment by thsubaku9** [comment]
Acknowledge. Will update here

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET15, RET16, RET18)
