### ISSUE TITLE
Delhivery (LSP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#574]
forward flow
========
1. /on_confirm:
- also include the TAT quoted in /on_search for the item;
- no distinct tax line item?

2. /update & /on_update:
- "ready_to_ship" is being sent in /confirm & again in /update;

rto flow
=====
1. request to add precancel_state to fulfillment as doc [here](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.p3f8n3o11txs);

**Comment by BLR-0118** [comment]
@hswapnil - also pls share valid json log (with double quoted keys & values as appropriate);

**Comment by hswapnil** [comment]
@BLR-0118 please review. Issue fixed, new fulfilment status added except out-for-pickup
pr - https://github.com/ONDC-Official/v1.2.0-logs/pull/638
2. ready_to_ship we have received twice from seller, hence sent two times.

@utkarsh-v

**Comment by BLR-0118** [comment]
Forward flow
=========
1. /on_confirm:
- fulfillment.tracking is True (instead of true as in /on_init);

2. /on_status (delivered):
- delivery timestamp (fulfillment.end.time.timestamp) is earlier than pickup timestamp;

**Comment by BLR-0118** [comment]
3. No /track, /on_track APIs even though tracking is enabled;

@hswapnil - pls fix the others & make a note here;
also, share logs for tracking

**Comment by hswapnil** [comment]
@BLR-0118 please review, issues fixed. 
1. sharing json payload for on_confirm 
2. this happened due to some internal error at our end, made amends and validated logs
3. earlier we had shared the payments object same as BAP in confirm request, made necessary changes for consistency
4. added logs for on_track

@utkarsh-v

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0

**Comment by BLR-0118** [comment]
@hswapnil @utkarsh-v
