### ISSUE TITLE
MyyShopp (lokal.in) (SA) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#575]
issue_CLOSE
-  "/message/issue/issue_actions/complainant_actions/1/complainant_action must be equal to one of the allowed values (OPEN,ESCALATE,CLOSE)",
on_issue
-  "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
on_issue_status
-  "created_at": "'created_at' should match issue's 'created_at'"

@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Corrected issue and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/616

**Comment by Srinath91** [comment]
@Rishabh-ondc Fixed issue and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/895

**Comment by RupalSingla** [comment]
FLOW !

"ret_issue": {
                "respTime": "Time of creation (created_at) and time of updation for /issue api should be the same"
            },
            "ret_on_issue": {
                "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
            },
            "ret_on_issue_status": {
                "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"

@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Issues fixed and updated in PR:https://github.com/ONDC-Official/v1.2.0-logs/pull/1040

**Comment by RupalSingla** [comment]
"on_issue": {
                "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with BPP ID",
                "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
            },
            "on_issue_status": {
                "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with BPP ID",
                "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"
            },
            "ret_on_issue_status_unsolicited": {
                "igmTxnId": "transaction ID should matched in /issue and /on_issue_status(unsolicited)",
                "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with BPP ID",
                "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
                "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"
            },


@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Fixed and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/1183

**Comment by RupalSingla** [comment]
on_issue
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue"
       
on_issue_status
-  "created_at": "'created_at' should match issue's 'created_at'"

 on_issue_status_unsolicited
-  "created_at": "'created_at' should match issue's 'created_at'"

@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Issues fixed and updated in PR:https://github.com/ONDC-Official/v1.2.0-logs/pull/1288

**Comment by RupalSingla** [comment]
on_issue , on_issue_status (soli) , on_issue_status (unsoli)
- respondent_actions in all these 3 api are having different values ,updated_at  is changing every time this is not possible .

on_issue.
updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue"
"updated_at": "2024-03-21T07:50:06.377Z",   and  created_at": "2024-03-21T07:20:05.086Z",
                                                                                "updated_at": "2024-03-21T07:20:06.377Z" 

Please check the previous comments and resolve .
@Srinath91

**Comment by Srinath91** [comment]
@RupalSingla Issues fixed and updated in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/1367

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @Srinath91
