### ISSUE TITLE
Ecom Express (LSP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#577]
flow 3
====
1. request to add precancel_state to fulfillment for all cancellations (RTO or otherwise) as doc [here](https://docs.google.com/document/d/1CkfxtqyLbSQccJZyNmf9BSGzJBH13gcLOk_tywV-LBk/edit#heading=h.p3f8n3o11txs);

**Comment by BLR-0118** [comment]
@AryanSinghEcom - pls make this change & make a note here; no need to resubmit logs

**Comment by AryanSinghEcom** [comment]
@BLR-0118  Done the changes requested

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
