### ISSUE TITLE
ZRPL IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#578]
FLOW 1
 on_issue
-  "created_at": "context timestamp should be greater than or equal to updated_at in on_issue"
issue_status
-  "schemaErr0": "/message/issue_id must match format \"uuid\""
 on_issue_status
-  "schemaErr0": "/message/issue/id must match format \"uuid\"

@Rajathkunder

**Comment by Rajathkunder** [comment]
I have a doubt: In testing scenarios, flow 2 and 3 for the buyerApp involve similar scenarios. I believe it is important for the sellerApp to validate all three flows. Can we, as the buyerApp, share the results of the first two flows? Is that acceptable?
