### ISSUE TITLE
Bitsila (LBNP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#580]
1. /search:
- why aren't you using expected time to prepare for order (provider.time.duration)?

2. /confirm:
- TAT sent in /on_search should be sent (item.time);
- average pickup time sent in /search may be sent (fulfillment.start.time.duration);
- remove street from linked_order.provider.address;
- ready_to_ship is "no" but pickup code type is being sent without pickup code (fulfillment.start.instructions): this may be sent only when ready_to_ship is "yes";

3. /track:
- callback_url should be removed;

**Comment by BLR-0118** [comment]
@dgowda604 - request to pls fix the above & retest with Shadowfax; you don't need to resubmit logs as from their logs, this can be verified;

**Comment by dgowda604** [comment]
yeah sure Supriyo, thanks

**Comment by BLR-0118** [comment]
1. /confirm:
- fulfillment.tracking shouldn't be sent here (it should be sent by LSP);

2. /update:
- order.state should be removed (LSP will update with latest state);

**Comment by BLR-0118** [comment]
@dgowda604 - pls fix the issues identified above

**Comment by BLR-0118** [comment]
@dgowda604 - logs cleared for v1.2.0; pls make sure the above issues are fixed;
