### ISSUE TITLE
SellerApp (RET10, RET12, RET14, RET16) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#651]
1. /on_search (RET10):
- item.quantity.unitized.measure is wrong: in all cases, the item name shows "L" but unitized measure is in kilogram - why can't you use litre as per [this](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json) list?
- why is difference between Context.timestamp for /on_search & /search > 24 hrs? Any issue with your timestamp?

2. /on_search (RET12):
- item.quantity.unitized.measure can't be in "kilogram";
- use category_id from [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843);
- "size_chart" is required for every item;

3. /on_search (RET14):
- why define 2 locations (SANG-1000, SANG-2000) with exact same attrs?
- item.quantity.unitized.measure can't be in "kilogram";
- attribute "body" is invalid; can you use something like "form_factor"?
- pls make sure all attrs marked as mandatory [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=244000021) are provided;
- in many cases (e.g. item 383d3233), name & long_desc seem to have same info - name is supposed to have concise info on product name);

4. /on_search (RET16):
- item.quantity.unitized.measure can't be in kilogram when product name shows "PC" e.g. item 107949212 should have unitized measure of 1 unit;
- pls make sure all attrs marked as mandatory [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=2063907654) are provided;

**Comment by BLR-0118** [comment]
@rajasellerapp @Brij-SA - request you to pls fix the above & resubmit ASAP

**Comment by rajasellerapp** [comment]
Changes has been made and logs has been updated @BLR-0118

**Comment by BLR-0118** [comment]
@rajasellerapp - logs cleared for v1.2.0 for RET10, RET12, RET14, RET16

**Comment by BLR-0118** [comment]
@rajasellerapp - for RET12, the provider name shows "TT Bazar" but desc is "Sangeetha Mobiles"; pls fix this

**Comment by rajasellerapp** [comment]
Noted @BLR-0118
