### ISSUE TITLE
ENS (RET18) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#654]
1. /on_search:
- item unitized qty is incorrect: e.g. item 47794238554412 (name shows pack of 3, each 500ml) but unitized qty is 500ml; either unitized is 3 units & name shows each of 500ml (as is happening now);
- "back_image_health" is invalid enum;

**Comment by BLR-0118** [comment]
@NJ-Nitank

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir please check the latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/753

**Comment by BLR-0118** [comment]
1. /on_search:
- bpp/fulfillments.id & bpp/providers.fulfillments.id should match;
- wherever sku is a pack (e.g. item 47794238554412), unitized qty could be no of units in the pack & the name has the volume/weight of each pack unit;
- common_or_generic_name seems to be the same for all items ("Shelcal HD");

**Comment by ShippuYadav** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/819 @BLR-0118 Sir, Please check the latest log for health and wellness

**Comment by BLR-0118** [comment]
1. /on_search (full refresh):
- in case of multi-pack item, pls use item unitized qty for no of units & append the weight / volume of each unit in product name, e.g.:
- item 47794239406380: item unitized qty is "4 unit" and weight of each unit ("150g") is appended to product name;

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, weight is added with product name and no of pack is specified in unitized qty.
<img width="468" alt="Screenshot_30" src="https://github.com/ONDC-Official/v1.2.0-logs/assets/115714289/e9daec0b-46fc-455e-acc8-a5383fd87bda">
Please specify the issue, did you meant product name should be like this ?
"Closeup Everfresh+ Anti-Germ Gel Toothpaste Red Hot, 150 g (4 units x 150g each)"

**Comment by BLR-0118** [comment]
1. Full catalog refresh:
- item 47794240225580: unitized qty should be 300 g;
- item 47794238292268: unitized qty should be 80g;
- only in case of multipack, you may have unitized qty of units;
- item.descriptor.code seems to have same EAN code for all items;

**Comment by BLR-0118** [comment]
@ShippuYadav

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, Please check latest PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1000

**Comment by BLR-0118** [comment]
1. /on_search (full catalog):
- bpp/fulfillments.id should match bpp/providers.fulfillments.id & same id assigned to item.fulfillment_id;

2. /on_search (incremental catalog):
- since incremental search is pull based (start & end time provided), response has to be solicited & Context.message_id for response should match Context.message_id for incremental search request;

**Comment by BLR-0118** [comment]
@ShippuYadav - clearing logs for v1.2.0 but pls fix the above & make a note here when done

**Comment by ShippuYadav** [comment]
@BLR-0118 Sir, as you mentioned, changes has been done
