### ISSUE TITLE
Unizap (logistics buyer) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#658]
## Flow 1

**/on_init**

- message/order must have required property 'fulfillments'
- order/items/0 must have required property 'fulfillment_id'

**/confirm**

- Total order weight '3.6 does not match the total unit weight of items '0'

**/on_confirm**

- order/created_at cannot be future dated w.r.t order/updated_at

**/on_track**

- tracking/location must have required property 'updated_at'"

## RTO Flow

- similar issues 

**/on_status**

- /order must have required property 'cancellation' when the order state is 'Cancelled'

**Comment by rajib-senrysa** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/678
@abhinavv245 
Please review and approve the updated logs as per the above mentioned compliance issues.

**Comment by abhinavv245** [comment]
## All flows

**/update**

- why is DCC code changed in end/instructions, also PCC and DCC cannot be same
- linked order details may be sent only if there is a change in the weight / dim of the goods being shipped (from /confirm);

**/on_status**

- DCC code is again updated to the one in confirm (how?)

@rajib-senrysa

**Comment by BLR-0118** [comment]
LBNP logs cleared for v1.2.0
