### ISSUE TITLE
Nearshop (BAP) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#689]
on_issue_status_solicited
-   "action_err": "context.action should be on_issue_status",
-   "igmIssueMsgId": "Message  ID mismatch in /issue_status and /on_issue_status"

on_issue_status_unsolicited
-                 "schemaErr0": "/context/timestamp must match format \"date-time\"",
-                 "action_err": "context.action should be on_issue_status",
-                 "timestamp_err": "Timestamp should be in date-time format",
-                 "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"

@RonitKumarSinha

**Comment by Rishabh-ondc** [comment]
Flow 1
- Some payloads are missing, please re-share

Flow 2
on_issue_status (unsolicited)
- context.timestamp same as on_issue_status 

@RonitKumarSinha  @sudhakara11

**Comment by RonitKumarSinha** [comment]
@Rishabh-ondc we have submitted the LOGS last week with above comments fixes. Still we haven't received any feedback from ONDC team. Can you please check. 

@sudhakara11

**Comment by Rishabh-ondc** [comment]
on_issue_status (unsolicited)
- chat_link attribute is optional; need not be shared with a placeholder value if not availalbe

issue_close
- Close API call need not have other attributes apart from id, status, created_at, updated_at, rating and complainant_actions 
- issue.created_at has changed; please check

@RonitKumarSinha

**Comment by RonitKumarSinha** [comment]
@Rishabh-ondc Any update on IGM logs submitted on 6 March and Merged on 7 March

https://github.com/ONDC-Official/v1.2.0-logs/pull/1036

@sudhakara11

**Comment by RonitKumarSinha** [comment]
@Rishabh-ondc Any Update on submitted logs https://github.com/ONDC-Official/v1.2.0-logs/pull/1036

@sudhakara11

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @RonitKumarSinha  @sudhakara11
