### ISSUE TITLE
SellerApp (LBNP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#713]
Below issues are from logs submitted by Delhivery [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/Delhivery):

1. /search:
- end gps coords should have min 6 digit decimal precision;

2. /confirm:
- item TAT is required;
- PCC (fulfillment.start.instructions.code) / DCC (fulfillment.end.instructions.code) code is required;

3. suggest you drop address.door from billing, fulfillment address so that it's consistent right thru;

4. payment.type should be "POST-FULFILLMENT" as we've not yet enabled wallets (ON-ORDER);

5. pls use "ready_to_ship" = "yes" in /update for intercity shipments;

**Comment by BLR-0118** [comment]
@rajasellerapp - pls fix the above ASAP

**Comment by rajasellerapp** [comment]
4. Payment.type was requested by Delhivery to be "ON-ORDER".  We used "POST-FULFILLMENT" before.
5. Since we are creating the logistics order after the seller marks the order ready not during retail order placement. we are sending RTS - yes during confirm itself.
@BLR-0118

**Comment by rajasellerapp** [comment]
@BLR-0118 Logs has been resubmitted with xpressbee

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
