### ISSUE TITLE
Mystore (Buyer App)- compliance checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#72]
**search_full_catalog_refresh**

- /message/intent/fulfillment/end/location must have required property 'address'

**search_inc_refresh**

- /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp

**on_search_full_catalog_refresh**

- invalid pincode as per provided lat-long in /message/catalog/bpp/providers/locations/address
- message/catalog/bpp~1providers/0/fulfillments/0/contact/phone must NOT have more than 11 characters
- Either one of fixed timings (range) or split timings (both frequency and times) should be provided in /bpp/providers[0]/locations[0]/time
- serviceability construct /bpp/providers[0]/tags[0] should be defined as per the API contract

**select**

- Timestamp for /select api cannot be smaller than or equal to /on_select api

**on_select**

- invalid id: Self-Pickup-01 in delivery line item (should be a valid fulfillment_id)

**init**

- gps coordinates in fulfillments[0].end.location mismatch in /select & /init

**on_init**

- /message/order/payment must have required property '@ondc/org/buyer_app_finder_fee_type'
- /message/order/payment must have required property '@ondc/org/buyer_app_finder_fee_amount'
- /message/order/payment must have required property '@ondc/org/settlement_details'
- gps coordinates in fulfillments[0].end.location mismatch in /select & /on_init
- Quoted Price in /on_init INR 1131 does not match with the quoted price in /on_select INR 1141.00
- Discrepancies between the quote object in /on_select and /on_init
- payment settlement_details missing in /on_init

**confirm**

- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'
- /message/order/payment must have required property '@ondc/org/settlement_details'
- created_at, updated_at, email mismatches in /billing in /init and /confirm
- fulfillments[0].end.location gps is not matching with gps in /select
- Discrepancies between the quote object in /on_select and /confirm

**on_confirm**

- context/timestamp difference between /on_confirm and /confirm should be smaller than 5 sec
- fulfillments[0].end.location gps is not matching with gps in /select

**on_status**

- invalid pincode as per provided lat-long in /message/order/fulfillments/end/location/gps

@mystore-in

**Comment by mystore-in** [comment]
/message/order/payment/@ondc/org/settlement_details must have required property 'settlement_bank_account_no'
/message/order/payment/@ondc/org/settlement_details must have required property 'settlement_ifsc_code'
/message/order/payment/@ondc/org/settlement_details must have required property 'bank_name'
/message/order/payment/@ondc/org/settlement_details must have required property 'branch_name'

we haven't received in on_init from buyer side

**Comment by sharmasahil0331** [comment]
**search_full_catalog_refresh**

- search request should be 'search for city' as for full catalog refresh
```https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795```

**on_search_full_catalog_refresh**
- bpp/fulfillments and bpp/providers cannot have value as [] 'empty array'

**on_search_inc_refresh**

- provider id: CANARAADYAPROVIDER275 in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh

**on_select**

- Timestamp for /select api cannot be greater than or equal to /on_select api
- provider.id mismatches in /on_search and /on_select

**init**

- invalid area_code as per provided gps in message/order/fulfillments/end/location

**confirm**

- created_at and updated_at provided in message/catalog/billing should match /init api payload

@mystore-in

**Comment by bluecypher** [comment]
- please remove the txn id from the file names and only keep the API name while submitting the logs
- are custom menu/customization features supported by the buyer app?

## Flow 1

**/search**

- city code must be \* in case of incremental refresh
- a valid std code must be used in context/city for full catalog pull
- static terms are not a part of phase 1; placeholder link should not be provided

## Flow 2

**/init**

- door attribute is optional in /fulfillments/end/location/address
- "@ondc/org/collected_by_status" is not required in /payment

**/confirm**

- billing object can't be modified; email is not present in /init
- amount collected from buyer (/payment/params/amount) can't be more than the quote price
- invalid values of "tax_number" of bpp and bap in /tags; gstin number is provided by bpp in /on_init

## Flow 3

**/select (OOS)**

- /select (OOS) and the second /select call must be a part of the same txn; context/transaction_id must remain the same
- Why is the second /select called with the OOS item: 05OMMQ0DO3KB (and with more quantity)?

## Flow 4

**/cancel**

- "005" is not a valid BNP initiated cancellation reason code; use a valid reason code as mentioned [here](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031)


@mystore-in

**Comment by sahil-ondc** [comment]
## Flow 1

### search_inc_refresh

- city in context should be '\*' while sending search_inc_catalog request.

### on_search_inc_catalog

- /context/city in context should be '\*' while sending on_search_inc_catalog request.
- /message/catalog is missing

## Flow 2

### select

- timestamp for /on_search api cannot be greater than or equal to /select api
- context/message_id for /on_search_full_catalog_refresh and /select api cannot be same
- context/message_id for /search_full_catalog_refresh and /select api cannot be same
- locality,street and city cant be same

### On Select

- difference between context/timestamp and /on_select should be smaller than 5 seconds
- Provider.id mismatches in /on_search and /on_select

### Init

- timestamp for /on_select api cannot be greater than or equal to /init api
- Provider.locations[0].id mismatches in /select and /init.
- GPS coordinates in fulfillments[0].end.location mismatch in /select & /init.
- Address.area_code in fulfillments[0].end.location mismatch in /select & /init.

### Confirm

- /message/order/payment/@ondc1org1settlement_details/0 must have required property 'upi_address'.
- timestamp for /on_init api cannot be greater than or equal to /confirm api.
- Provider Id mismatches in /on_search and /confirm.
- Provider.locations[0].id mismatches in /on_search and /confirm.
- Key 'tax_number' mismatch: 87878987898 !== XXXXXXXXXXXXXXX.
- Fulfillment id 6389eb19-5e24-4993-a623-8201d94cf854 does not exist in /on_select.
- Order.created_at timestamp should match context.timestamp.
- Tags should have same and valid gst_number as passed in /on_init.
- Tags/bap_terms should have valid gst number and fields in /confirm.

### On Confirm

- /message/order/payment/@ondc1org1settlement_details/0 must have required property 'upi_address'.
- difference between context/timestamp and /on_confirm should be smaller than 5 seconds.
- Provider Id mismatches in /on_search and /on_confirm.
- Provider.locations[0].id mismatches in /on_search and /on_confirm.
- Key 'tax_number' mismatch: 87878987898 !== XXXXXXXXXXXXXXX.
- Fulfillment id 6389eb19-5e24-4993-a623-8201d94cf854 does not exist in /on_select.
- Store name /fulfillments[0]/start/location/descriptor/name can't change.
- Fulfillments[0].end.location gps is not matching with gps in /select.
- Fulfillments[0].end.location.address.area_code is not matching with area_code in /select.

**Comment by dharkum24** [comment]
@sahil-ondc 
seller app Logs were merged on 5 Feb Could you please review as per those and provide feedback

**Comment by BLR-0118** [comment]
1. for fashion (RET12), there are issues with Gofrugal catalog which isn't approved yet;
2. pls test & resubmit with any of the SNPs whose logs have been approved for this category: Vidyant (Shopcircuit), Fynd, SellerApp, Plotch (Craftsvilla);
3. flow 6(a & c) are required, as doc [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795);

**Comment by BLR-0118** [comment]
@dharkum24

**Comment by dharkum24** [comment]
@BLR-0118  Rajiv had a word with Nitin about Flow 6 and feature development is in progress. I have added you in that mail.

**Comment by dharkum24** [comment]
@BLR-0118 Re-submitted logs with Fynd for Fashion https://github.com/ONDC-Official/v1.2.0-logs/pull/1086

**Comment by BLR-0118** [comment]
Flow 1 (RET12, RET10)
==============
1. Since logs are only for incremental catalog pull, aren't you supporting incremental catalog push?
2. Some of the catalog attrs e.g. "colour" have invalid values e.g. "000000" instead of "#000000"; is this properly handled?
3. Since full & incremental catalogs may need to be processed concurrently, are you supporting versioning using the timestamp for provider / location / item, so you're picking the correct data update?

Flow 2
====
1. Since fashion could be intercity or hyperlocal & there are different fulfillment states for each, are you supporting processing of routing.type ("P2P" or "P2H2P") to understand what statuses to expect?

Flow 6 (return with pickup) is required for fashion, while part cancel by merchant / return with liquidation are required for grocery; what's the plan to support this?

**Comment by BLR-0118** [comment]
@dharkum24

**Comment by dharkum24** [comment]
@BLR-0118 
**Flow 1**
1. We are supporting incremental catalog push.
2. Yes we have validation for this
3. We will consume incremental after full catalog 

**Flow 2**
1. We are supporting both P2P and P2H2P

**Flow 6**
We are working on it Will submit logs by end of march

**Comment by BLR-0118** [comment]
1. Flow 1 (pt 3):
- just processing in sequence won't help; you need to check the timestamps & update the catalog accordingly e.g. full catalog update shows item in-stock (at certain timestamp) & incremental catalog update shows item out of stock (at earlier timestamp than for the full catalog update);
- since you're processing sequentially, you should store the full catalog update for the item (with the item timestamp) and when processing the incremental catalog update, match the timestamp & discard because that's an earlier timestamp;

2. Flow 2 (pt 1):
- support for both P2P/P2H2P is ok;
- however, the type of fulfillment states you're receiving is based on routing.type;
- you should ensure there aren't any skip states for either P2P/P2H2P;

**Comment by BLR-0118** [comment]
@dharkum24 - pls check the above & update your response

**Comment by asifrazastorehippo** [comment]
@BLR-0118 
**1- Flow 1 (pt 3):**  Yes absolutely this we will handle, we won't update the earlier timestamp incremental catalog, we'll discard concerns with the full catalog timestamp. We have another way also like we can trigger timely incremental after the full catalog done

**2- Flow 2 (pt 1):**   Yes absolutely, this will handled

**Comment by asifrazastorehippo** [comment]
@BLR-0118 please check the response above about your concern

**Comment by BLR-0118** [comment]
@asifrazastorehippo @dharkum24:
1. logs for flows 1 to 5 are ok for fashion, grocery;
2. if you're in additional categories, pls submit flow 1 logs for the respective categories;
3. for fashion / bpc, etc., flow 6c (return with pickup) is required; for grocery, flows 6a (part cancel by merchant), 6b (return with liquidation) are required;
4. pls submit flow 6 logs when available; until then, this will be on hold;

**Comment by dharkum24** [comment]
@BLR-0118 "if you're in additional categories, pls submit flow 1 logs for the respective categories;" For this full catalog search only?

**Comment by dharkum24** [comment]
@BLR-0118 
For "2. if you're in additional categories, pls submit flow 1 logs for the respective categories;"---**We** are not getting sellers with which we can check incremental search and submit logs. Could you please help or is it fine if we submit only full catalog search for all categories ?

**Comment by BLR-0118** [comment]
@asifrazastorehippo - ok

**Comment by dharkum24** [comment]
@BLR-0118 Submitted Flow1 Logs for supporting categories https://github.com/ONDC-Official/v1.2.0-logs/pull/1223/

**Comment by BLR-0118** [comment]
Flow 1 for RET13 - ok;

**Comment by BLR-0118** [comment]
RET14 - flow 1
=========
1. item attr "colour" value should be in hex code (i.e. "#000000" instead of "black");
2. for mobile phones, you may also want to add "colour_name" as most Apple iPhones comes up with new colour which cannot be matched to a name using standard libraries;

**Comment by BLR-0118** [comment]
RET15 - flow 1
=========
1. there are issues with Channelier logs, suggest you should test with Shopalyst

**Comment by BLR-0118** [comment]
RET16 - flow 1
========
1. Issues with logs, suggest you test with NP whose logs have been cleared (SellerApp, Shopalyst);

**Comment by BLR-0118** [comment]
RET18 - flow 1
=========
1. Issue with logs, suggest you test with NP whose logs are cleared (MedPay)

**Comment by dharkum24** [comment]
@BLR-0118 Flow 6 RET10 and RET12 submitted for review https://github.com/ONDC-Official/v1.2.0-logs/pull/1265 cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
RET13 - ok;
RET15 - ok;
RET18 - ok;
SNP logs for RET14/16 are invalid, pls resubmit with your SNP (after fixing issues here #758)

**Comment by BLR-0118** [comment]
@dharkum24

**Comment by BLR-0118** [comment]
logs for RET14/15 cleared
