### ISSUE TITLE
Digiledge (SA) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#721]
@shabirahamed

#### There are many issues in the submitted logs, Kindly run the log-validation-utility to get the issues. 

`https://github.com/ONDC-Official/log-validation-utility`

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog

- /message/catalog/bpp/providers/locations/address must have required property 'circle'
- missing properties 'other_FSSAI_license_no' and 'importer_FSSAI_license_no' in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food
- 'country' missing in /message/catalog/bpp/providers/items/tags/origin
- /message/catalog/bpp/providers/items/category_id should not have special characters 'Oil \u0026 Ghee'
- "accept_bap_terms" code should not be provided. It should be enabled when static terms are defined by the BNP and accepted by the seller app

### search_inc_catalog

- Transaction logs not provided

### on_search_inc_catalog

- remove special characters from /message/catalog/bpp/providers/items/descriptor

## Flow 3

### on_select (out-of-stock)

- error object should be exactly as per the API contract (error.message should be in the escaped quote format )
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl`

## Other Flows

### on_select

- /message/order/provider must have required property 'locations'

### on_init

- placeholder values should not be provided in 'settlement_bank_account_no', 'bank_name', 'branch_name', 'beneficiary_name', 'upi_address' in payment object
- only tax_number should be provided in tags/bpp_terms; remove all the terms related properties

### on_confirm

- only tax_number and provider_tax_number should be provided in /tags/bpp_terms; remove other terms related properties
- provider_tax_number (pan number of merchant) should be provided in /tags/bpp_terms

### on_status

- /message/order/fulfillments/0/start/instructions must have required property 'long_desc'

## Note

- /track should be provided in case of tracking enabled

@shabirahamed

**Comment by sahil-ondc** [comment]
## Flow 1

### search

- /context/action must be equal to constant (search)

### on_search_full_catalog

- /message/catalog/bpp/descriptor/tags/bpp_terms must have property np_type (ISN, MSN)
- missing properties 'other_FSSAI_license_no' and 'importer_FSSAI_license_no' in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food
- Duplicate variants provided with parent_item_id db4657df-cd28-4396-81fe-db380f46e059
- /message/catalog/bpp/providers/items should have valid category_id one of the sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0`

### on_search_inc_catalog

- context/transaction_id for /search_inc_refresh and /on_search_inc_refresh api should be same

## Flow 2

### select

- context/timestamp for /on_search api cannot be greater than or equal to /select api

### on_select

- /fulfillments[1]/@ondc/org/TAT (O2D) in /on_select can't be equal to @ondc/org/time_ship (O2S) in /on_search

### on_status

- /message/order/fulfillments/0/start/instructions must have required property 'long_desc'

## Flow 3

### on_select (out-of-stock)

- error should have valid property 'message'

## Flow 4

### on_cancel

- cancellation_terms should not be provided in phase 1

## Flow 5

- incomplete flow

@shabirahamed

**Comment by shabirahamed** [comment]
Hi Sahil,

I have a few doubts regarding that comments

Flow 1
on_search_full_catalog
missing properties 'other_FSSAI_license_no' and 'importer_FSSAI_license_no' in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food
As per ONDC RETAIL API contract, any one of the fssai_license_no is fine (Supriyo's comment in the API contract : 'these are mutually exclusive, so any one is ok')
Duplicate variants provided with parent_item_id db4657df-cd28-4396-81fe-db380f46e059
Could you please explain this Duplicate variants
/message/catalog/bpp/providers/items should have valid category_id one of the sheet
https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0
I'm sending valid category_id as per above Excell sheet.
Flow 2
on_status
/message/order/fulfillments/0/start/instructions must have required property 'long_desc'
As per ONDC RETAIL API Contract, once order/fulfillment/state is order-picked-up that time only /message/order/fulfillments/0/start/instructions/long_desc is created
Flow 5
incomplete flow
This flow is fully completed.

could you please explain
 
@sahil-ondc

**Comment by sahil-ondc** [comment]
1. ACK
2. So you have created variants on item.quantity.unitized.measure, but when I see that variants it all have same values, but idealy it should be unique (one variant with 100g, other with 200g)
3. ACK, but make sure there is no placeholder value provided. 
4. In Flow 5, there should be RTO flow as well. 

@shabirahamed

**Comment by shabirahamed** [comment]
Hi @sahil-ondc ,


could you please let us know the feedback for the DIGILEDGE Retail BPP V1.2 RET10 logs.

Please find the PR ID: https://github.com/ONDC-Official/v1.2.0-logs/pull/965

**Comment by sahil-ondc** [comment]
## Flow 1
### on_search_full_catalog_refresh
**prvdr0items0@ondc/org/statutory_reqs_prepackaged_food**: In ONDC:RET10 @ondc/org/statutory_reqs_prepackaged_food following fields are valid 'nutritional_info', 'additives_info', 'brand_owner_FSSAI_license_no','other_FSSAI_license_no', 'brand_owner_FSSAI_license_no','importer_FSSAI_license_no'; i.e ingredients_info is not required for ret 10
**prvdr1items0@ondc/org/statutory_reqs_prepackaged_food**: In ONDC:RET10 @ondc/org/statutory_reqs_prepackaged_food following fields are valid 'nutritional_info', 'additives_info', 'brand_owner_FSSAI_license_no','other_FSSAI_license_no', 'brand_owner_FSSAI_license_no','importer_FSSAI_license_no'; i.e ingredients_info is not required for ret 10

## Flow 2
### select
**areaCode**: address.area_code should be same as in /on_search

### on_status_packed
**schemaErr**: /message/order/fulfillments/0/start/instructions must have required property 'long_desc'

### on_status_out_for_delivery
**schemaErr**: /message/order/fulfillments/0/end/instructions must have required property 'long_desc'

## Flow3
### select
**areaCode**: address.area_code should be same as in /on_search

### select_out_of_stock
**txnId**: Transaction Id should be different for flow 3 after /select_out_of_stock onwards
**areaCode**: address.area_code should not be same as in /on_search

## Flow4
### cancel
**schemaErr**: /message must have required property 'descriptor'

### on_cancel
**schemaErr**: /message/order/cancellation must have required property 'reason'

## Flow5
### on_cancel
**schemaErr0**: /message/order must NOT have additional properties (documents)
precancel state is missing
**schemaErr1**: /message/order must NOT have additional properties (cancellation)


## Flow6-a
### on_update
**schemaErr0**: /message/order must have required property 'billing'

## Flow6-b
### missing

## Flow6-c
###Incomplete flow
-**item_missing**: 2db29562-2223-405d-a8bf-d2a509dc4dea is cancelled in update_liquidated but not present in on_update_liquidated
missing update_settlement call

**Comment by shabirahamed** [comment]
Hi @BLR-0118 ,

Im shabirahamed from DIGILEDGE and we are the Retail Seller App.

I have doubt regarding Retail Flow 6.

Do we need to collect Retail Flow 6 all the sections or (a,b) or (a,c) is enough

could you please help 

kindly find the Retail Flow 6 Testcase below
Flow 6:
a. Merchant cancels one of the items before pickup;
b. Buyer returns an item which seller NP accepts with liquidation;
c. Buyer returns another item which seller NP accepts with return of item;

**Comment by NishthaMonga** [comment]
## Flow 1
### on_search_full_catalog_refresh
- /message/catalog/bpp~1descriptor must have required property 'tags'
- In ONDC:RET10 @ondc/org/statutory_reqs_prepackaged_food following fields are valid 'nutritional_info', 'additives_info', 'brand_owner_FSSAI_license_no','other_FSSAI_license_no'

## Flow 2
### on_confirm
- mandatory fields like np_type,provider_tax_number,etc  missing in message/order/tags/bpp_terms for ON_CONFIRM

### on_status_packed, on_status_out_for_delivery
- /message/order/fulfillments/0/start/instructions must have required property 'long_desc'


## Flow 3
Same as Flow 2

## Flow 4
### on_cancel
- /message/order/fulfillments/0/start must have required property 'time'
- /message/order/fulfillments/0/end must have required property 'time'
- Tags are mandatory for on_cancel on cancelled state for fulfillment type delivery
- Cancel Request is mandatory for on_cancel in fulfillment type delivery
- Pre Cancel is mandatory for on_cancel
- Reason ID is mandatory field for on_cancel
- Initiated_by is mandatory field for on_cancel

## Flow 5
### on_cancel
- /message/order/fulfillments/0/start must have required property 'time'
- /message/order/fulfillments/0/end must have required property 'time'
- Tags are mandatory for on_cancel on cancelled state for fulfillment type delivery
- Cancel Request is mandatory for on_cancel in fulfillment type delivery
- Pre Cancel is mandatory for on_cancel
- Reason ID is mandatory field for on_cancel
- Initiated_by is mandatory field for on_cancel
- RTO Id is mandatory field for on_cancel

@shabirahamed

**Comment by shabirahamed** [comment]
Flow 1
on_search_full_catalog_refresh
/message/catalog/bpp~1descriptor must have required property 'tags'
Last time discussion this object is not mandatory. If buyer app sends tags object in search request then seller app has to send
In ONDC:RET10 @ondc/org/statutory_reqs_prepackaged_food following fields are valid 'nutritional_info', 'additives_info', 'brand_owner_FSSAI_license_no','other_FSSAI_license_no'
these objects are already there in the Flow 1 logs
Flow 2
on_confirm
mandatory fields like np_type,provider_tax_number,etc missing in message/order/tags/bpp_terms for ON_CONFIRM
provider_tax_number is not mandatory for MSN type seller
on_status_packed, on_status_out_for_delivery
/message/order/fulfillments/0/start/instructions must have required property 'long_desc'
Is this mandatory to send in packed and out-for-delivery state. If is not means we are sending long_desc value in order-picked-up and order-delivered state
Flow 3
on_confirm
mandatory fields like np_type,provider_tax_number,etc missing in message/order/tags/bpp_terms for ON_CONFIRM
provider_tax_number is not mandatory for MSN type seller
on_status_packed, on_status_out_for_delivery
/message/order/fulfillments/0/start/instructions must have required property 'long_desc'
Is this mandatory to send in packed and out-for-delivery state. If is not means we are sending long_desc value in order-picked-up and order-delivered state
Flow 4
on_cancel
/message/order/fulfillments/0/start must have required property 'time'
Once order is accepted then only we should send time object values
/message/order/fulfillments/0/end must have required property 'time'
Once order is accepted then only we should send time object values
Flow 5
on_cancel
/message/order/fulfillments/0/start must have required property 'time'
time object is there in the flow 5 logs
/message/order/fulfillments/0/end must have required property 'time'
time object is there in the flow 5 logs

could you please help 
@NishthaMonga

**Comment by sandeepshahi** [comment]
## Flow 1

**/on_search**

- payment collection BY SNP is not enabled; "collect_payment" object should not be provided
- schedule/holidays is missing in /locations/time
- invalid values of statutory reqs in "@ondc/org/statutory_reqs_prepackaged_food"; check for item: "73f534f7-8d4a-42aa-abe0-749deade1cf8"
- why are same images provided multiple times in /items/images;
- item and category_id mapping must be correct; eg; soap is mapped with stationery for item: "3b121d7d-6782-406d-939d-710f91d3037b"
- catalog type in /bpp/providers/tags/catalog_link is set as "inline" but remote link is still provided in type_value; why?
- min_value and catalog_link in /tags/order_value are defined twice; catalog_link is still not supported by BNPs, should not be provided

**/on_search (inc)**

- city/code must be "\*" as sent in inc. /search

## Flow 2

**/on_select**

- TAT for Delivery and Self-Pickup can't be same; should be O2D and O2S respectively
- available count should be either 0 or 99; same logic as in /on_search

**/on_init**

- provider_tax_number need not be provided here; must be provided in /on_confirm

**/on_status**

- estimated time ranges doesn't match correctly with the TAT provided; delivery TAT is 60 mins. while delivery range is provided as 2 hours
- routing and tracking information must be provided before on or before Agent-assigned state
- Order-picked-up
  - invalid invoice label "Invoice Bill" in /documents; should be "Invoice" instead

**/on_track**

- both gps and url are provided; is this intended?
- why is tracking still active after the order is delivered?

## Flow 3

**/on_select (OOS)**

- error.message is in invalid format; check contract for the correct format

## Flow 4

**/on_cancel**

- why is delivery fees still charged when the order is cancelled in pending state

**/on_status (RTO)**

- context/timestamp can't be same as in /on_cancel RTO

## Flow 6

**/on_update**

- /update payment is an FYI call; no need to provide on_update later

**/on_update (Return)**

- message_id should be unique for all unsolicited calls
- initiated_by is missing in /tags/return_request
- Return Delivered state must be provided


@shabirahamed

**Comment by sahil-ondc** [comment]
# RET18, 16, 13

## Flow 1

### on_search

- /message/catalog/bpp/providers/items must have required property '@ondc/org/return_window'
- /message/catalog/bpp/providers/items must have required property '@ondc/org/seller_pickup_return'
- item.quantity.unitized.measure.value should be greater than 0
- Holidays cannot be past 2024-03-21
- collect_payment should not be provided in bpp/descriptor/tags as part of phase 1

### on_search_inc

- Mandatory attributes not provided

# RET 15, 14

### on_search

- /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_packaged_commodities must have required property 'manufacturer_or_packer_name'
- /message/catalog/bpp/providers/items must have required property '@ondc/org/seller_pickup_return'
- Mandatory attributes not provided on item level

# RET 10

## Flow 1

### on_search

- item.quantity.maximum.count cant be 0 if item is in stock (id: 65ed219c-5eed-4440-9c70-f2548be00a57)

## Flow 2

### on_select

- /message/order/fulfillments/0/@ondc/org/TAT must match format "duration"

## Flow 4

### on_cancel

- /message/order/fulfillments pre_cancel state updated_at should be correct, when order state is last updated

## Flow 5

### on_cancel

- /message/order/fulfillments pre_cancel state updated_at should be correct, when order state is last updated

### on_status (rto-delivered)

- @ondc/org/settlement_details should have updated settlement details as refund is initated when the return is picked up

@shabirahamed

**Comment by shabirahamed** [comment]
RET 10
Flow 2
on_select
    /message/order/fulfillments/0/@ondc/org/TAT must match format "duration"
        What will be TAT format we need to send. As per the API contract TAT format is correct.

Flow 4
on_cancel
    /message/order/fulfillments pre_cancel state updated_at should be correct, when order state is last updated
         updated_at value is the same as order updated values. All the timestamp values are correct as per the contract.

Flow 5
on_cancel
    /message/order/fulfillments pre_cancel state updated_at should be correct, when order state is last updated
         updated_at value is the same as order updated values. All the timestamp values are correct as per the contract.

on_status (rto-delivered)
    @ondc/org/settlement_details should have updated settlement details as refund is initated when the return is picked up
        Buyer App is not sending refund request. Thats why its not updated in the payment object.

could you pleas help 

@sahil-ondc

**Comment by sahil-ondc** [comment]
## RET 18, RET 16, RET 15, RET 13

### on_search

- Mandatory Attribute tag fields are missing for some of the items
- item.quantity.unitized.measure.value should be greater than 0
- /message/catalog/bpp/providers/items/descriptor should have mandatory property code

## RET 14, RET 12

### on_search

- Holidays cannot be of past dates
- Mandatory Attribute tag fields are missing fro some of the items
- /message/catalog/bpp/providers/items/descriptor should have mandatory property code

## RET 11

### on_search

- /message/catalog/bpp/providers/items/@ondc/org/time_to_ship time to ship should be within PT0M-PT59M or PT1H
- /message/catalog/bpp/providers/items/tags must have required property 'code'
- /message/catalog/bpp/providers/items/tags must have required property 'list'
- item_id: cfda55ab-dc34-42fa-8ccd-5abed84faca4 should have veg_nonveg one of the 'veg', 'non_veg'or 'egg' in bpp/providers

@shabirahamed

**Comment by sahil-ondc** [comment]
# RET 10

## Flow 1

### on_search

- /context must have required property 'bpp_id'
- /context must have required property 'bpp_uri'
- /context/action must be equal to constant (on_search)
- /message/catalog/bpp/providers/items/descriptor should have required property 'code'

### on_search_inc

- /context must have required property 'bpp_id'
- /context must have required property 'bpp_uri'
- /context/action must be equal to constant (on_search)

## Flow 2, 3, 4, 5, 6
###  Again there are many issues in the submitted logs, Kindly run the log-validation-utility to get the issues.
`https://github.com/ONDC-Official/log-validation-utility`

@shabirahamed

**Comment by shabirahamed** [comment]
@BLR-0118 

Hi Supriyo,
 
Last week we have submitted our logs and verified. It is waiting for your approval

Could you please approve our logs

**Comment by sahil-ondc** [comment]
## RET 11

### on_search (full catalog)

- Does categories (customizations, variants) supported ?
- /message/catalog/bpp/providers/items/@ondc/org/time_to_ship time to ship should be within PT0M-PT59M or PT1H (for RET11)
- /message/catalog/bpp/providers/items should have veg_nonveg one of the 'veg', 'non_veg'or 'egg'
- email provided in @ondc/org/contact_details_consumer_care should not be placeholder

### on_search (inc catalog)

- Same as on_search (full catalog)
- Similar Item as in /on_search_full_catalog_refresh api call, item id- bf0eff06-8a40-429a-8ffc-2b3cf256bfae (items should only be provided in on_search_inc in case of any change in delta)
- @ondc/org/fssai_license_no should not be provided in on_search

## RET 18

### on_search (full catalog)

- /message/catalog/bpp/providers/items/tags should have mandatory attributes as per the sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=2063907654`
- item.quantity.unitized.measure.value should be greater than 0 (id: dae77001-61e7-41a4-a2a6-4047375ff4c5)

### on_search (inc catalog)

- Same as on_search (full catalog)
- Similar Item as in /on_search_full_catalog_refresh api call, item id- 063804d5-263d-4c37-9592-1b75436bb3c6 (items should only be provided in on_search_inc in case of any change in delta)
- @ondc/org/fssai_license_no should not be provided in on_search

## RET 12, RET 13, RET 14, RET 15, RET 16

### on_search (full catalog)

- /message/catalog/bpp/providers/items/tags should have mandatory attributes as per the sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=2063907654`

@shabirahamed

**Comment by BLR-0118** [comment]
RET10
====
Flow 1:
1. /on_search:
- most (though not all) products in catalog are branded, so why is EAN no not provided for these?
- for all "Rice and Rice Products", multiple_products_name_number_or_qty = 15: means what?
2. /on_search_inc:
- use case shows price (ok) & MRP (very rare) changing: why not show a useful use case for item going out of stock / coming into inventory?

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- /on_search (item 1da4bbe6-21f3-43ee-b7cf-a3a3b97c1ff1) shows max count as 3 but here it's changed to 104: means?

2. /on_status:
- fulfillment.start.instructions are instructions for pickup & since seller is handling fulfillment, it's not relevant here;
- routing.type should be sent before fulfillment states start changing;

3. /track & /on_track:
- fulfillment.tracking is false, so how's /on_track sending gps coords?

**Comment by BLR-0118** [comment]
flow 3 - ok

**Comment by BLR-0118** [comment]
Flow 4
1. /on_cancel:
- cancellation happens at fulfillment state pending; curious why delivery & packing charges aren't refunded?

**Comment by BLR-0118** [comment]
@shabirahamed - reviewed flows 1 to 4; will share comments on 5 & 6

**Comment by shabirahamed** [comment]
> # RET10
> Flow 1:
> 
> 1. /on_search:
> 
> * most (though not all) products in catalog are branded, so why is EAN no not provided for these?
 - Currently we are sending item.descriptor.code was (5:)  for testing. In real case it will be the exact value
> * for all "Rice and Rice Products", multiple_products_name_number_or_qty = 15: means what?
 - For testing we have given like that

> 2. /on_search_inc:
> 
> * use case shows price (ok) & MRP (very rare) changing: why not show a useful use case for item going out of stock / coming into inventory?
- Whenever the items values has been changed and incremental response has been sent to the Buyer App

could you please help

**Comment by shabirahamed** [comment]
> Flow 4
> 
> 1. /on_cancel:
> 
> * cancellation happens at fulfillment state pending; curious why delivery & packing charges aren't refunded?

- Flow 4, do we have to reduce delivery/packing charges in the order.quote?(sandeep has told that he will let us know). Thats why we havent added those part

**Comment by shabirahamed** [comment]
> # Flow 2
> 1. /on_select:
> 
> * /on_search (item 1da4bbe6-21f3-43ee-b7cf-a3a3b97c1ff1) shows max count as 3 but here it's changed to 104: means?
- on_select max count should have an updated count. Because that product count has been updated. 
> 2. /on_status:
> 
> * fulfillment.start.instructions are instructions for pickup & since seller is handling fulfillment, it's not relevant here;
> * routing.type should be sent before fulfillment states start changing;
> 
> 3. /track & /on_track:
> 
> * fulfillment.tracking is false, so how's /on_track sending gps coords?

- For above on_status and /track & /on_track are similar to the Flow 3 (on_status and /track & /on_track)json format. 
- Could you please let me know Is there any changes need to add.

**Comment by BLR-0118** [comment]
Flow 5
====
1. /on_status*:
- fulfillment.tracking is false but gps_enabled is being set to "yes": for what?

**Comment by BLR-0118** [comment]
Flow 6
====
1. on_update_partial_cancel & /on_confirm have same message_id;
2. All /on_update have same message_id;

**Comment by BLR-0118** [comment]
@shabirahamed - pls fix all the above & resubmit for all flows (except 3);

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select - in /on_search, the max per order is "3" but changed to "104" in /on_select?? Don't think you're using this correctly;
2. /on_status - pickup instructions are for the rider who picks up the order for delivery i.e. from seller's own fleet or from LSP fleet (if using on-network logistics); this need not be sent to the buyer app, unless buyer app is handling fulfillment (which isn't the case here);
3. /on_track:
- fulfillment.tracking is false which means tracking not available for this fulfillment; if buyer app calls /track, you should return appropriate error code;

**Comment by BLR-0118** [comment]
@shabirahamed - response to your pts for flow 2

**Comment by shabirahamed** [comment]
> # Flow 2
> 1. /on_select:
> 
> * /on_search (item 1da4bbe6-21f3-43ee-b7cf-a3a3b97c1ff1) shows max count as 3 but here it's changed to 104: means?
- on_select max count should have an updated count. Because that product count has been updated. 
> 2. /on_status:
> 
> * fulfillment.start.instructions are instructions for pickup & since seller is handling fulfillment, it's not relevant here;
> * routing.type should be sent before fulfillment states start changing;
- Sandeep has told me routing.type object mandatory once agent-Assigned state. As Like that only we have implemented
> 
> 3. /track & /on_track:
> 
> * fulfillment.tracking is false, so how's /on_track sending gps coords?

- For above on_status and /track & /on_track are similar to the Other Flows (on_status and /track & /on_track)json format. 
- Could you please let me know Is there any changes need to add.

**Comment by shabirahamed** [comment]
> # Flow 2
> 1. /on_select - in /on_search, the max per order is "3" but changed to "104" in /on_select?? Don't think you're using this correctly;
> 2. /on_status - pickup instructions are for the rider who picks up the order for delivery i.e. from seller's own fleet or from LSP fleet (if using on-network logistics); this need not be sent to the buyer app, unless buyer app is handling fulfillment (which isn't the case here);
- Seller is doing the delivery part in that case what we need to do. Is it mandatory or not to send pckup details. Last time we got the comments like pikup details mandatory to send. Thats why we have implemented like that
> 3. /on_track:
> 
> * fulfillment.tracking is false which means tracking not available for this fulfillment; if buyer app calls /track, you should return appropriate error code;

**Comment by BLR-0118** [comment]
Flow 1 & 2
=======
1. /on_search:
- non-standard item descriptor code for catalog items (GTIN);
- pls provide proper definition for variant_group;

2. /on_select:
- item.quantity.maximum.count isn't being used properly;

3. /on_status*:
- all post-confirm APIs are supposed to return the complete audit trail;
- /on_confirm has fulfillment.tracking as false, this is changed to true in Agent-assigned and then becomes false again;
- routing.type is set in Agent-assigned but then disappears afterward;
- fulfillment.start.instructions are pickup instructions and should be sent here only if buyer app is handling fulfillment, which isn't the case here;
- if tracking is not available, /track should behave as per contract;

Flow 5
====
1. /on_cancel_rto_initiated:
- has same message_id as /on_confirm;

Flow 6
====
1. All /on_update for return have same message_id;

**Comment by BLR-0118** [comment]
@shabirahamed - request you to pls fix **all** issues above & resubmit;

**Comment by shabirahamed** [comment]
> # Flow 1 & 2
> 1. /on_search:
> 
> * non-standard item descriptor code for catalog items (GTIN);
> * pls provide proper definition for variant_group;
> 
> 2. /on_select:
> 
> * item.quantity.maximum.count isn't being used properly;
- It should be fixed count right. 
-
> 3. /on_status*:
> 
> * all post-confirm APIs are supposed to return the complete audit trail;
- What are all the details need to add. Because I have tested with log Validation tool from there no issue and Sandeep has verified the same.
> * /on_confirm has fulfillment.tracking as false, this is changed to true in Agent-assigned and then becomes false again;
- As sandeep told, once order state is agant-assigned we have to send tracking value true and after that is delivered we have to send tracking value false.
> * routing.type is set in Agent-assigned but then disappears afterward;
 - routing.type value is there and have checked that. It will be there always
> * fulfillment.start.instructions are pickup instructions and should be sent here only if buyer app is handling fulfillment, which isn't the case here;
- As of now we dont need to send if fulfillment.type is Buyer-Delivery then we have to send. Is it correct sir.
> * if tracking is not available, /track should behave as per contract;
 - As per the API contract only track api has been made and response also.
> 
> # Flow 5
> 1. /on_cancel_rto_initiated:
> 
> * has same message_id as /on_confirm;
> 
> # Flow 6
> 1. All /on_update for return have same message_id;

- All on_update message_id should be the same update return delivered. Like that only we eceived the comments while testing our logs.
- for partial cancel on_update message_id wont be the same but rest of the on_update message_ids are same. 

could you please help 

@BLR-0118

**Comment by shabirahamed** [comment]
Dear Supriyo,

please help us with correct our understanding.

Flow 1 & 2:
/on_search:
* non-standard item descriptor code for catalog items (GTIN);
  - In the submitted log for RET10, we dont have a product with GTIN number. could you please explain more about from the comment. what is the expectation from us.
* pls provide proper definition for variant_group;
  - Do you mean to provide real values for varient_group

/on_select:
item.quantity.maximum.count isn't being used properly;
 - Does it mean that maximum count available to purchase.
 
/on_status:
* all post-confirm APIs are supposed to return the complete audit trail;
  - Please explain with an example I haven't understood the comment. In aidit trail what are things to be include
* /on_confirm has fulfillment.tracking as false, this is changed to true in Agent-assigned and then becomes false again;
  - Our understanding as follows:
    1. When an order is created if Seller is arranging for logistics(off-network) then untill logistic agent is assigned fulfillment.tracking will be false in /on_confirm API.
    2. When a logistic provider is assigned for the seller for the order, /on_status API fulfillment.tracking is set to true.
    3. Once the order is delivered by the agent the fulfillmnet.tracking will be set to false.
  - Is our understanding correct. What are we supposed to send in the log. Please let us know
* routing.type is set in Agent-assigned but then disappears afterward;
  - In the submitted log, routing.type object is there inside order.fulfillments json.
  - Please let us know where its disappears
* fulfillment.start.instructions are pickup instructions and should be sent here only if buyer app is handling fulfillment, which isn't the case here;
  - As per the API contract, there is no condition that fulfillment.start.instructions should be used only for Buyer-App. But in the on_status api contract it is present.
* if tracking is not available, /track should behave as per contract;
  - Our understanding is If tracking is true then we are sending tracking details in on_track API else sending error code 40005 in on_track 
  - please let us know our understanding is correct.
 
Flow 5:
/on_cancel_rto_initiated:
* has same message_id as /on_confirm;
  - We'll fix this issue

Flow 6:
* All /on_update for return have same message_id;
  - Our understanding is As per the API contract we should send same message_id for the return items in every on_update API call and in the submitted log also we are sending the same.
  - Does it mean that we should create new message_id for every on_update API call
  - Since V1.2 is backward compatable for V1.1. Our understanding is mandate that on_update unsolicited resquest message_ids are same.

Please help help us to clarify the above doubt.


@BLR-0118  @sandeepshahi

**Comment by BLR-0118** [comment]
@shabirahamed - comments inline

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full):
- categories.id (used for variant / custom group ids) can be max 12 chars alphanumeric;
- for item 46044711-1897-4953-8961-956ac826e0ca & others, multiple_products_name_number_or_qty of 15 means - 15 packs of 1 kg atta??
-  mismatch in serviceability definition between old (circle radius) & new (serviceability tags);

**Comment by shabirahamed** [comment]
> # Flow 1
> 1. /on_search (full):
> 
> * categories.id (used for variant / custom group ids) can be max 12 chars alphanumeric;
 - In the API contract, there is no conditions for the Id validation
> * for item 46044711-1897-4953-8961-956ac826e0ca & others, multiple_products_name_number_or_qty of 15 means - 15 packs of 1 kg atta??
 - Currently we are sending the product count or weight values.
> * mismatch in serviceability definition between old (circle radius) & new (serviceability tags);
 - Last time i received the comments from Sahil like `/message/catalog/bpp/providers/locations/address must have required property 'circle'` 
 - I have asked In case of PAN-INDIA serviceability, he told that you can send this circle as dummy for now. later you can remove. 
 - thats why we are sending those circle value. Do we need to send it or we can ignore?

could you please help 

@BLR-0118

**Comment by BLR-0118** [comment]
flow 3 - ok;

**Comment by BLR-0118** [comment]
Flow 4
====
1. /cancel & /on_cancel have diff message_id; otherwise, looks ok;

**Comment by BLR-0118** [comment]
flow 5 - ok;

**Comment by BLR-0118** [comment]
flow 6 - ok;
