### ISSUE TITLE
Xpressbees (LSP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#732]
@siddharthnarayanXpressbees - there are several issues with the LBNP (preprod-ondc.viranc.com/p/v1/store) with which you've submitted logs; can you pls test with one of the other inter-city LBNPs like SellerApp & submit? If you need contact details, pls ping me

**Comment by BLR-0118** [comment]
also, do you support deferred ready_to_ship thru /update?
@siddharthnarayanXpressbees

**Comment by siddharthnarayanXpressbees** [comment]
yes we support,  ready_to_ship in /update
@BLR-0118

**Comment by BLR-0118** [comment]
Flow 3
====
1. /on_status (rto initiated):
- cancellation.reasons.id is invalid (should be cancellation.reason.id);

2. Since XB fulfillments are P2H2P, are you supporting the intercity fulfillment states?

**Comment by BLR-0118** [comment]
@siddharthnarayanXpressbees

**Comment by BLR-0118** [comment]
@siddharthnarayanXpressbees - for cancellation (RTO or otherwise), you need to use /on_cancel; if LBNP sends /status, the/on_status will have the order details as per your logs;
clearing logs for v1.2.0
