### ISSUE TITLE
Ola LSP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#749]
## All Flows

**/search**

- Use payment.type as "POST-FULFILLMENT" as this is what's enabled for now;

**/on_init**

- remove static terms / cancellation terms for now, as this isn't enabled yet;
- remove all null value objects and additional attributes in fulfillments/start and end location

**/on_confirm**

- why is tax line item removed from quote breakup
- fulfillments/start/time/duration is missing
- items/time is required (S2D TAT)
- fulfillments/tags (ready to ship is missing)

**/on_status**

- may add tracking optimization params such as gps_enabled, url_enabled, url to 
  fulfillment.tags.tracking in /on_status;
- context/timestamp for fulfillment states - Order-delivered and Order picked up cannot be same (Flow 1)
- for RTO fulfillment, start and end location is not required (also why is start and end location for RTO same as Delivery?)

**/on_cancel**

- Another fulfillment of type RTO will be added
- fulfillments/tags (rto_event) are missing for fulfillment/type = Delivery 
- pre cancel state may be provided in fulfillments/tags

Note: All issues should be checked across all APIs and fixed if applicable

@karthykb

**Comment by abhinavv245** [comment]
**/on_search**

- /items must have required property 'parent_item_id'

**/on_cancel**

- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Cancelled
- Pickup and Delivery time range is missing for fulfillment type 'Delivery'
- fulfillments/tags are required in case of RTO (rto_event, pre_cancel_state)
- delivery timestamp cannot be provided for fulfillment state - RTO-Initiated

**/on_status**

- status update for RTO-Initiated is not required as provided in /on_cancel

@karthykb Kindly resolve the issues identified above and resubmit the logs.

**Comment by karthykb** [comment]
@abhinavv245 we will check, the below issue is got fixed
PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/777

/search

Use payment.type as "POST-FULFILLMENT" as this is what's enabled for now;
/on_init

remove static terms / cancellation terms for now, as this isn't enabled yet;
remove all null value objects and additional attributes in fulfillments/start and end location
/on_confirm

why is tax line item removed from quote breakup
fulfillments/start/time/duration is missing
items/time is required (S2D TAT)
fulfillments/tags (ready to ship is missing)
/on_status

may add tracking optimization params such as gps_enabled, url_enabled, url to
fulfillment.tags.tracking in /on_status;
context/timestamp for fulfillment states - Order-delivered and Order picked up cannot be same (Flow 1)
for RTO fulfillment, start and end location is not required (also why is start and end location for RTO same as Delivery?)
/on_cancel

Another fulfillment of type RTO will be added
fulfillments/tags (rto_event) are missing for fulfillment/type = Delivery
pre cancel state may be provided in fulfillments/tags

**Comment by abhinavv245** [comment]
@karthykb Please fix all the issues and submit the logs thereafter.

**Comment by karthykb** [comment]
@abhinavv245 we have fixed all the open issues and resubmitted our logs here https://github.com/ONDC-Official/v1.2.0-logs/pull/791

**Comment by abhinavv245** [comment]
**/confirm**

- Total order weight '0.5 does not match the total unit weight of items '1'"
- start/instructions/code '2' is for merchant order number (use appropriate value for the same(max 6 alphanumeric))

**/on_confirm**

- why has start/duration (average time to pickup) changed

**/on_cancel**

- fulfillments/tags/precancel_state/updated_at is the time at which this state (Out-for-delivery)was updated in the system.
- cancellation/reason/id in order/tags does not match with the one provided in fulfillments/tags/rto_event

**/on_status**

- fulfillments/start/time/duration is missing (for type 'Delivery')

@karthykb

**Comment by karthykb** [comment]
checking @abhinavv245

**Comment by karthykb** [comment]
@abhinavv245 what is the next step here to go live

**Comment by abhinavv245** [comment]
## Flow 1

- Incorrect Flow as per context/timestamps - (on_update,on_search,search,confirm,on_confirm,update,init,on_init,on_status)

## Flow 2

- Incorrect Flow as per context/timestamps - (on_search,search,init,on_init,confirm,on_confirm,on_cancel,update,on_update,on_status)

**/on_cancel**

- RTO Pickup (fulfillments/start/time/timestamp) time cannot be future dated for fulfillment state- RTO-Initiated
- Pickup timestamp (fulfillments/start/time/timestamp) is missing for fulfillment state - Cancelled

**/on_status**

- RTO Pickup time (fulfillments/start/time/timestamp) cannot change for fulfillment state - RTO-Delivered

Note: Multiple timestamp issues identified. Please use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) and rectify the same.

@karthykb

**Comment by karthykb** [comment]
Okay, checking @abhinavv245

**Comment by abhinavv245** [comment]
**on_search,on_init,/on_confirm**

- remove static terms (bpp_terms) and cancellation terms as they are not enabled yet

**/on_cancel**

- fulfillments/start/instructions have changed for fulfillment type 'Delivery'
- In fulfillments/tags- precancel_state/updated_at is the time when this pre_cancel state was updated in the system (is not recorded correctly in Flow 2 (should reflect the timestamp recorded in fulfillments for this state in /on_status), missing in Flow 3)
- In /items, time/duration for RTO line item does not match the one provided in catalog in /on_search
- use appropriate cancellation reason id for triggering RTO

**/track,on_track**

- tracking apis should be implemented
- also add tracking.tags.order, tracking.tags.config;

@karthykb

**Comment by karthykb** [comment]
@abhinavv245 can you pls verify the logistics logs, as we have resubmitted all the timestamp issue. We want to go live if there is no pi blocker for logistics 1.2

**Comment by abhinavv245** [comment]
@karthykb have you checked the above feedback?

**Comment by karthykb** [comment]
@abhinavv245 got it. will look into this

on_search,on_init,/on_confirm

remove static terms (bpp_terms) and cancellation terms as they are not enabled yet
/on_cancel

fulfillments/start/instructions have changed for fulfillment type 'Delivery'
In fulfillments/tags- precancel_state/updated_at is the time when this pre_cancel state was updated in the system (is not recorded correctly in Flow 2 (should reflect the timestamp recorded in fulfillments for this state in /on_status), missing in Flow 3)
In /items, time/duration for RTO line item does not match the one provided in catalog in /on_search
use appropriate cancellation reason id for triggering RTO
In case of buyer cancellation before pickup, logistics buyer won't be liable for any charges, hence quote price (delivery charges) should be updated to zero in that case.

/track,on_track

tracking apis should be implemented
also add tracking.tags.order, tracking.tags.config;

**Comment by karthykb** [comment]
@abhinavv245 tracking is optional, right?

**Comment by abhinavv245** [comment]
@karthykb mandatory in v1.2 for hyperlocal

**Comment by karthykb** [comment]
@abhinavv245 we have all the LSP comments and have few questions


1. Post agent assigned before pick up, if we get cancellation, in that scenario how much money should we need to deduct. There should be some fee, which we are already defining in the cancellation terms.(Because the driver partner is already on the way to pick up location), hence it can't be Zero

2. Please check your 2nd last comment "fulfillments/tags/precancel_state/updated_at is the time at which this state (Out-for-delivery)was updated in the system." which is contradicting to your last comment 3 days ago "In fulfillments/tags- precancel_state/updated_at missing in Flow 3" --> For now we have added it.

**Comment by BLR-0118** [comment]
Flow 1
====
1. pls remove bpp_terms from /on_init & cancellation_terms from /on_cancel as this isn't enabled yet; any fees that you want to charge for cancellation should show in the quote in the Order object from /on_cancel;
2. /on_track shows tracking type as "live_poll" (which means thru gps coordinates) but in /on_status, you're setting both gps_enabled & url_enabled to "yes"; isn't this contradictory?

**Comment by BLR-0118** [comment]
@karthykb - I'm clearing your logs but pls fix the above issues; will plan a coordinated rollout of 1.2.0 across all LSPs & LBNPs sometime mid next week

**Comment by karthykb** [comment]
Thanks. We have added buyer app flow for log verification as well
