### ISSUE TITLE
Mystore (Seller App: RET10, RET12) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#758]
## Flow 1

**search (full pull)**

- invalid catalog pull; search by city must be initiated

**/search (inc)**

- txn id can't be the same as in full catalog pull

**/on_search**

- gps lat/long must have a minimum decimal precision of 6 digits in /locations
- invalid schema; locations[]/times is not a valid attribute; use the log validation utility before submission;
- invalid variants defined; separate SKU in /items must be created for each variant
- invalid unitized measure value; Men's suit should not be measured in grams
- invalid attributes: quantity/available/measure and quantity/maximum/measure
- invalid codes defined in items/tags/attribute; check the contract for enums of code and example value
- all the mandatory attributes in /tags/attribute must be provided for an item as per the category_id
- invalid serviceability defined for category id "grocery"; shouldn't be a part of RET12 domain
- invalid variant definition in /categories; attr path should be defined correctly; check the contract

**/on_search (inc)**

- payload must be provided for verification

## Flow 2

**/select**

- select an alternative delivery address distinct from the seller's location

**/on_select**

- provider_location is not a valid attribute; remove from all the subsequent calls too
- provider/locations must be provided
- delivery TAT ("@ondc/org/TAT") can't be the same as time_to_ship provided in /on_search

**/on_init**

- /order/tags/rto_action is not valid;
- tax_number must be provided in /tags/bpp_terms

**/on_confirm**

- callback response must not take long;
- provider_tax_number and tax_number must be provided in /tags/bpp_terms

**/on_status**

- all the fulfillment states must be provided for verification
- estimated delivery time ranges must also be provided in /fulfillments/end/time/range
- actual delivery timestamp (/fulfillments/end/time/timestamp) in Order-delivered state can't be the same as pickup timestamp

**/track**

- /track must be supported if tracking is set as true in all the APIs

## Flow 3

- similar issues as above

**/on_select (OOS)**

- error/message should be in the correct JSON stringified format as mentioned in the contract
- fulfillment category ("@ondc/org/category") is inconsistent; Express Delivery and Standard Delivery are being used with same TAT;
- multiple fulfillments should be created for 36 quantity of men's suit;

## Flow 4

- similar issues as above

**/on_cancel**

- invalid cancellation flow; a new fulfillment must be created and all the items must be assigned to that fulfillment; check the contract

## Flow 5

- similar issues as above
- Invalid RTO flow; check the contract for details

## Flow 6

- must be submitted for verification

@dharkum24

**Comment by BLR-0118** [comment]
@dharkum24 - pls submit logs for flows 6(a & c) as doc [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795), without which logs for RET12 can't be reviewed

**Comment by dharkum24** [comment]
@BLR-0118 Rajiv had word with Nitin about Flow 6 for which development is in progress. Submitted logs as per conversation. Adding you in mail

**Comment by sandeepshahi** [comment]
# RET10

## Flow 1

**/search (full/inc pull)**

- The BAP ID is of the Reference Buyer App, but the search seems not to be initiated from the Reference App.

**/on_search**

- "net_quantity_or_measure_of_commodity_in_pkg" and "imported_product_country_of_origin" attributes are not required in "@ondc/org/statutory_reqs_packaged_commodities"
- store timings as per the new construct must be provided in /bpp/providers/tags/timing

## Flow 2

**/on_select**

- price of item: "sku-SKU-7HUBNVBCEXFK" doesn't match with the price in full catalog; (incremental refresh was sent 2 hours later)

**/on_status**

- Packed, Out-for-delivery states are missing
- updated_at can't be future dated
- Invoice must be provided once the order is picked

## Flow 4

**/on_cancel**

- why is delivery fee being charged even when the order is cancelled pre shipment
- updated_at should be correctly updated

## Flow 5

**/on_cancel (RTO)**

- RTO delivered/disposed status change must be provided through /on_status
- forward pickup timestamp is missing in /fulfillments
- updated_at should be correctly updated
- RTO delivery taxes should also be provided in quote_trail

# RET12

- similar issues as above

**/on_search**

- serviceability for grocery categories shouldn't be provided in fashion catalog;
- variant groupings are invalid; fabric, brand, and size_chart are defined in the group attribute, but the variants have the same values for these attributes


@dharkum24

**Comment by asifrazastorehippo** [comment]
@sandeepshahi Could you please clarify
Why variant groupings are invalid, variant can only have size differences too let say (L, XL) and other attributes may have same value?

**Comment by BLR-0118** [comment]
RET12 logs
=======
Flow 1:
1. /on_search_full_catalog:
- for item.tags.attribute:
- colour should have hex value (as in contract [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.gxyup4yxvpx6));
- values for diff attrs (gender, fabric) should be in lower case as per the enums [here](https://github.com/ONDC-Official/protocol-network-extension/tree/main/enums/retail);

**Comment by asifrazastorehippo** [comment]
@BLR-0118 @sandeepshahi logs resubmitted with all mentioned changes above, please review for Both Grocery and Fashion

**Comment by dharkum24** [comment]
PR for All logs for Grocery and search for Fashion https://github.com/ONDC-Official/v1.2.0-logs/pull/1142

**Comment by BLR-0118** [comment]
for RET10:
=======
Flow 1
====
1. /on_search_full_catalog:
- following items have same EAN code (item.descriptor.code): sku-SKU-BFKPCMODDAMV, sku-SKU-L47YTJHTAGX_, sku-SKU-YCADHZ9UCC2W; is this intentional?
- no EAN code for these items (sku-SKU-7HUBNVBCEXFK, sku-SKU-L3LONF73Q9X9)?
2. /on_search_incremental:
- pls share use case relevant to grocery: item going out of stock;

Flow 2
====
1. /on_select:
- what logic is used to calculate TAT of 4 days for delivery from store (pin code 122018) to buyer (122003)?

2. /on_status:
- fulfillment.state is Pending, so why is invoice being added here? (typically, this would be at Order-picked-up as there won't be part cancellations after that; invoice with doc link is being added at Order-picked-up);

3. All /on_status APIs:
- are all fulfillment states supported?
- to distinguish between P2P & P2H2P states, routing.type should be a part of the /on_status payload;
- even though tracking is true in /on_confirm (means available), no tracking logs?
- to indicate tracking has been enabled, gps_enabled or url_enabled/url should be set in /on_status;

Flow 3
====
1. /on_select:
- for item sku-SKU-BFKPCMODDAMV: qty is 9, unit price is 450, so total price (unit price * qty) is 0??

Flow 5
====
1. /on_cancel_rto_initiated:
- curious why there's no tax on forward shipment fulfillment, but there's a tax on RTO fulfillment;
- in quote_trail, for delivery tax, use type of "tax" (with rto fulfillment id);

Flow 6
====
- part cancel by merchant (6a) & return with liquidation (6b) are required for grocery; pls submit when available;

**Comment by BLR-0118** [comment]
@dharkum24 @asifrazastorehippo

**Comment by asifrazastorehippo** [comment]
**Flow 1**
1- Concern regarding EAN - As these are dummy products and it is optional too so we added the same, this won't happen in the actual catalog if the seller is putting for different products but by default, it is not required

2- Grocery Items out of stock  - It can be out-of-stock, items like cashews, almonds, etc.. if there is high demand and the seller is giving a discount. In our scenario in 1.1 also happening but in 1.1 incremental is not supported

**Flow 2**
1- Logic of TAT - As this is a dummy seller, the calculation is based on shipping + delivery (2+2).  The shipment is off-network for this flow of the order. 
2- order invoice - handled, won't go in Pending and with proper doc
3- Tracking - Handled we'll send tracking URL if we are sending tracking as true 

**Flow 3**
1- As on_select is an out-of-stock domain error the item quantity is the quantity that can be fulfilled and the unit price is 450 but the total price is 0 because of out-of-stock


**Flow 5**
1- Forward fulfillment tax - This flow we have made through on_network LSP we haven't got tax in forward so we haven't sent that, we got in RTO at that time we sent RTO Tax
2- Type Tax - Fixed changed type from delivery to tax in case of tax in RTO

**Comment by asifrazastorehippo** [comment]
@BLR-0118 please check the response above about your concern

**Comment by BLR-0118** [comment]
Fashion (RET12):
===========
1. /on_search (full catalog):
- in most cases, size_chart will point to an image; what would size_chart in variant definition mean??
- check this data sampling:
- item sku-SKU-3HJDMHIV8DTP: 10 shirts for 100 rupees?
- item sku-SKU-H9X8K8HOJRVG: 1000 jeans for 100 rupees?
- Can we have some realistic data?

**Comment by BLR-0118** [comment]
@asifrazastorehippo - pls see comments inline for grocery; also, resubmit fashion catalog logs

**Comment by asifrazastorehippo** [comment]
@BLR-0118 Sure will submit catalog logs of Fashion once again, do we need to submit the entire logs till flow 5, or which we submit earlier for Fashion and now Grocery logs also reviewed that work? 
And will consider the inline comments of Grocery which you have mentioned

**Comment by BLR-0118** [comment]
@asifrazastorehippo - pls submit logs for whatever is requested: fashion (flow 1, 6c), grocery (see comments above)

**Comment by dharkum24** [comment]
@BLR-0118 Logs for Fashion Flow 1 and Grocery Flow 3 has been submitted. In grocery all inline comments have been addressed https://github.com/ONDC-Official/v1.2.0-logs/pull/1186. cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
RET10 - flow 3
=========
1. /on_status:
- pls also add routing.type to indicate whether shipment is P2P (hyperlocal) or P2H2P (intercity);
- based on whether routing.type is set to hyperlocal or intercity, all fulfillment states, corresponding to this, must be sent;
- suggest you set tracking attributes when order is ready to be tracked (setting url_enabled to "yes" in order accepted state will not give good user experience as URL may show 500 error on buyer app);
- fulfillment.start.instructions are pickup instructions for the LSP & need not be shown here (unless buyer app is handling logistics);

**Comment by BLR-0118** [comment]
@asifrazastorehippo:
- RET12 flow 1 logs ok;
- RET10: pls resubmit for flow 3;
- RET12 logs will be cleared after the flows are verified for RET10;

**Comment by asifrazastorehippo** [comment]
@BLR-0118 
route.type added as suggested and as per type on_status we have sent 
tracking URL - handled 
instruction - removed

**Comment by dharkum24** [comment]
PR for Flow 3 is https://github.com/ONDC-Official/v1.2.0-logs/pull/1199 @BLR-0118 cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
Flow 3 (grocery):
- TAT is 4 days for delivering between pincodes 122018 & 122018?
- pickup time slot shows same day, so this time is entirely S2D;
- suggest you have proper logic in place to calculate TAT as this is a promise to the buyer;
- everything else ok;

Flow 1 (RET12) - ok;

**Comment by BLR-0118** [comment]
@dharkum24 @asifrazastorehippo - RET10/12 flows 1-5 are ok (see comments above for enhancements you need to build in); what's the status of flow 6 logs (you'd said end-March)?

**Comment by dharkum24** [comment]
@BLR-0118  Logs for Flow 6 submitted for review https://github.com/ONDC-Official/v1.2.0-logs/pull/1283 cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
RET13 (BPC):
1. pls use proper unitized measure for items (gram / millilitre / litre);

RET14 (Electronics):
1. all mandatory attrs have to be provided as per [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=244000021) sheet;

RET15 (Appliances):
1. all mandatory attrs have to provided as per the above sheet;

RET16 - ok;

RET18 (H&W):
1. pls use proper unitized measure for items (millilitre / litre / gram);

**Comment by BLR-0118** [comment]
@dharkum24 - pls fix above & resubmit

**Comment by BLR-0118** [comment]
RET10 - flow 6
=========
1. 6a - ok;
2. 6b (/on_update_liquidated):
- items[] needs to have an entry for item sku-SKU-7HUBNVBCEXFK, for return fulfillment 660d3e0bf162879d4d62a4dd, with count 1;

**Comment by BLR-0118** [comment]
@dharkum24 - pls check above & fix

**Comment by BLR-0118** [comment]
RET12 - flow6c (return with pickup)
=======================
1. No /on_update for return initiated?
2. /on_update_return_approved:
- pls remove reverseqc_input as this isn't reqd here (not a case of BNP doing fulfillment);
- pls add end location for return fulfillment;
- for return, start & end locations is typically the reverse of forward shipment (i.e. return fulfillment starts from buyer locn & ends at seller locn / warehouse);
3. /on_update_return_picked:
- pls see pt 2 above for RET10 - flow 6;

**Comment by BLR-0118** [comment]
@dharkum24 - pls check above & fix;

**Comment by BLR-0118** [comment]
RET13 - flow 1: ok;

**Comment by BLR-0118** [comment]
RET14 - flow 1
=========
1. for item sku-SKU-3QJT3Z9OJCI: weight should be in gram, length/breadth/height in cm; pls remove the unit from attr value;
2. same for items sku-SKU-QFYSE_HSHYE,

**Comment by BLR-0118** [comment]
RET15 - flow 1
=========
1. key "width" is invalid - should this be length?
2. for items sku-SKU-NZJ96ZTSXYF, sku-SKU-DV-ZLEJANBX: same issue as in RET14;

**Comment by BLR-0118** [comment]
RET18 - flow 1
=========
1. item sku-SKU-NCPD8FFSMAG says "100 ml, pack of 2": shouldn't unitized measure be 200ml then?

**Comment by dharkum24** [comment]
@BLR-0118 submitted PR for above issues https://github.com/ONDC-Official/v1.2.0-logs/pull/1421

cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
@dharkum24 - checked return flow (6c):
- for return fulfillment, start (i.e. buyer address) should be the end for forward shipment fulfillment & end is store or warehouse address provided by merchant;
- everything else ok, so pls fix this asap;

**Comment by dharkum24** [comment]
@BLR-0118 Submitted PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1536 for FLow6c  cc:- @asifrazastorehippo

**Comment by BLR-0118** [comment]
flow 6c fixed;

**Comment by dharkum24** [comment]
@BLR-0118 FLOW1 submitted for AGR10 PR :- https://github.com/ONDC-Official/v1.2.0-logs/pull/1573 cc:- @asifrazastorehippo
