### ISSUE TITLE
Paytm BAP (RSF) - compliance checks

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#770]
For all the three flows 
- payments.params.amout needs to be a string .
- withholding_tax_gs.value needs to be a string.
- withholding_tax_tds.value needs to be a string.
- deduction_by_collector.value needs to be a string.

Please chexck the schema properly 

@deepalibansal_bitbucket

**Comment by bluecypher** [comment]
- Pls share the logs as per the following test case scenarios:
  1. Successful reconciliation by the receiver for 5 or more transactions
  2. Underpaid/Overpaid flow initiated by the receiver in /on_receiver_recon
- Why are there different settlement statuses for the same order ID?

**/receiver_recon**

- "@ondc/org/withholding_amount" can't be the same as withholding_tax_gst/value; actual amount and gst tax can't be same
- why are 2 settlement objects created in "@ondc/org/settlement_details" with same settlement timestamp but different settlment reference no.
- payer_name and payer_address are missing in "payerdetails"
- "settlement_reference_no" in /orders[] doesn't match with settlement_reference in any of the settlement details object in "@ondc/org/settlement_details"
- created_at and udpated_at timestamps can't be same in orderbook/orders
- settlement_timestamp in "@ondc/org/settlement_details" can't be earlier than created_at timestamp; orderbook is created first (created_at), amount is settled(settlement_timestamp) and then orderbook is updated (updated_at)

**/on_receiver_recon**

- order_recon_status must be "02" (Final)

**Comment by aravind3s** [comment]
@bluecypher - Some clarifications regarding certain points. Others we are fixing and sending the logs back.

/receiver_recon

- why are 2 settlement objects created in "@ondc/org/settlement_details" with same settlement timestamp but different settlment reference no. ---->> We have multiple settlement being done for a single order. This was discussed with @rishabh-ondc  where in we were advised to send multiple settlement objects in receiver_recon

- payer_name and payer_address are missing in "payerdetails" ---->> These are optional and hence were not sent as per the latest contract discussion with @Rishabh

- created_at and udpated_at timestamps can't be same in orderbook/orders --->> We as a buyer app send the receiver_recon and in this case created_at and updated_at will be same. This was again discussed with @rishabh

- settlement_timestamp in "@ondc/org/settlement_details" can't be earlier than created_at timestamp; orderbook is created first (created_at), amount is settled(settlement_timestamp) and then orderbook is updated (updated_at) -------->>In our discussed,  we were told that created_at  shouldn't be the order created time rather the time we send the orderbook. In our case when the payout is done, a different orderbook is created which is different from our order registry.
