### ISSUE TITLE
Jubilant (SA) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#775]
issue
-  "respTime": "Time of creation (created_at) and time of updation for /issue api should be the same"

on_issue_status

- "schemaErr0": "/message/issue/created_at must be string",
-  "schemaErr1": "/message/issue/updated_at must be string",
-   "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[1] mismatched with domain in context",
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[1]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status",
-  created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"

@ishanparasher-jublfood

**Comment by ishanparasher-jublfood** [comment]
Changes merged in PR : https://github.com/ONDC-Official/v1.2.0-logs/pull/870

**Comment by RupalSingla** [comment]
Flow 1
issue
- paylaod seems to be a of a different complaint, please check
on_issue
- PROCESSING action should come once only as of now for the MVP implementation
- updated_by.org.name should have the domain code as well
- respondent_actions.updated_at should be less than or equal to issue.updated_at
on_issue_status
- issue.created_at has changed
- resolution_provider object is incomplete, please check the API contract for the same
Flow 2
on_issue
- issue.created_at has changed
on_issue_status IN PROGRESS
- respondent_actions.short_desc and updated_at should not change
- issue.created_at has changed
on_issue_status RESOLVED
- resolution object is incomplete
- issue.created_at has changed
- resolution_provider object is incomplete, please check the API contract for the same

@ishanparasher-jublfood

**Comment by ishanparasher-jublfood** [comment]
Updated PR with feedback fixes : https://github.com/ONDC-Official/v1.2.0-logs/pull/960

**Comment by Rishabh-ondc** [comment]
on_issue
- context.timestamp is greater than issue.updated_at; please check
- resolution_provider.respondent_info.resolution_support must have the 'gros' object

on_issue_status_IN_PROGRESS
- respondent_actions.short_desc and updated_at should not change for already provided actions 

on_issue_status_RESOLVED
- respondent_actions.short_desc and updated_at should not change for already provided actions 
- resolution_support.gros missing

@ishanparasher-jublfood

**Comment by ishanparasher-jublfood** [comment]
PR with feedback changes : 
https://github.com/ONDC-Official/v1.2.0-logs/pull/1026

**Comment by RupalSingla** [comment]
issue:
   "respTime": "Time of creation (created_at) and time of updation for /issue api should be the same"
      
on_issue:
-  "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue"

 on_issue_status

-                 "updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[1]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue_status",
-                 "created_at": "'created_at' should match issue's 'created_at'"


@ishanparasher-jublfood

**Comment by RupalSingla** [comment]
Logs approved for version @ishanparasher-jublfood
