### ISSUE TITLE
Wits RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#795]
Success:

-  Message_id missmatched with on_receiver_recon
- timestamp for receiver and on  receiver_recon are same , which is not possible, should be a certain difference in timestamp

@vishal-wits

**Comment by bluecypher** [comment]
Closing the duplicate issue board. Refer https://github.com/ONDC-Official/v1.2.0-logs/issues/542 for the updates.
