### ISSUE TITLE
Udyamwell - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#810]
**/search**

- CityCode 080 should match the city for the fulfillment start location 500024, 040
- Use payment.type as "POST-FULFILLMENT" as this is what's enabled for now;

**/confirm**

- fulfillments/start/time/duration is missing

**/update**

- linked order details may be sent only if there is a change in the weight / dim of the goods being shipped (from /confirm);
- message/updated_at is not required

**/track and /on_track**

- tracking request should be sent

@udyamwell1

**Comment by udyamwell1** [comment]
We have worked on these suggestions and updated the logistic logs. @abhinavv245

**Comment by BLR-0118** [comment]
@udyamwell1 - pls resubmit with any other LSP in hyperlocal (MP2 or Shadowfax); there are issues with our ref LSP app because of which your logs can't be cleared

**Comment by udyamwell1** [comment]
@BLR-0118 sir, as per your suggestion we have tested with MP2 and resubmitted the logs. Please review it. https://github.com/ONDC-Official/v1.2.0-logs/pull/1126

**Comment by BLR-0118** [comment]
@udyamwell1 - are you planning hyperlocal or intercity using on-network logistics? Test data shows intercity (in /search - start & end area_code are different) but all flows are hyperlocal (from MP2);

Pls note that hyperlocal & intercity have different fulfillment states & several features work only for hyperlocal or intercity:
- order prep time (in /search) relevant only for hyperlocal;
- inline_check_for_rider (in /on_init) relevant only for hyperlocal;
- AWB / EBN no, shipping label relevant only for intercity;

**Comment by udyamwell1** [comment]
Dear Sir,

We have planning to focus  on intercity operations using on-network
logistics. Following your previous suggestion, we conducted tests with MP2.
However, moving forward, we will implement your latest recommendation and
conduct testing with intercity logistics providers such as Ecom.

Thank you for your guidance.
Regards,
Akash

**Comment by BLR-0118** [comment]
Hi @udyamwell1, pls test once with any of the intercity LSPs (Delhivery / Ecom / Shiprocket) & resubmit logs; there are lots of nuances in intercity logistics on-network, so it's advisable to have this tested before going to Prod;

**Comment by udyamwell1** [comment]
Sure sir, we will do that. And resubmit the logs.
Thanks!

**Comment by udyamwell1** [comment]
@BLR-0118 We have tested with intercity LSP. Please review our logs. @abhinavv245

**Comment by abhinavv245** [comment]
## Flow 1

**/search**

- why is Express Delivery (By Air) sought for delivery within Bengaluru
- Order preparation time (provider/time/duration) should be according to the Delivery Category
- For intercity orders, choose start and end location accordingly 

## Flow 2

- similar issues

**/update**

- Pickup code is not required for P2H2P shipments as shipping label is provided by LSP

## Flow 3

- similar issues 

**/cancel**

- '003' is not a valid cancellation reason code to be used by LBNP (use code for TAT breach)

Note: Also ensure all the previous feedback is incorporated in the updated logs.

@udyamwell1

**Comment by BLR-0118** [comment]
1. weight/dimensions for package should be correctly defined as shipping cost for intercity is based on this;
2. flow 3 - /on_cancel - cancelled_by should be bap_id since cancellation was initiated by LBNP;

@udyamwell1 - clearing logs for v1.2.0 (LBNP), but pls make sure the above are handled in Prod;
