### ISSUE TITLE
Tipplr (Seller App: RSF) - Compliance Checks

### ISSUE THREAD

**Issue by pratikmazumdar** [ONDC-Official/v1.2.0-logs#825]
###   receiver_recon:

- 'receiver_recon.message.orderbook.orders[0].payment.@ondc/org/settlement_details[0].settlement_ifsc_code' must be a valid bank account number.
- 'receiver_recon.message.orderbook.orders[0].payerdetails.payer_name' must contain characters, spaces, and '-'.
- 'receiver_recon.message.orderbook.orders[0].receiver_app_uri' is not allowed.
- 'receiver_recon.message.orderbook.orders[1].payment.@ondc/org/settlement_details[0].settlement_ifsc_code' must be a valid bank account number.

- 'receiver_recon.message.orderbook.orders[1].payerdetails.payer_name' must contain characters, spaces, and '-'.
- 'receiver_recon.message.orderbook.orders[1].receiver_app_uri' is not allowed.
- 'receiver_recon.message.orderbook.orders' must contain 5 items.

###    on_receiver_recon:
- 'on_receiver_recon.message.orderbook.orders[0].order_recon_status' must be [02].
- 'on_receiver_recon.message.orderbook.orders[0].diff_amount' is not allowed.
- 'on_receiver_recon.message.orderbook.orders[1].order_recon_status' must be [02].
- 'on_receiver_recon.message.orderbook.orders[1].diff_amount' is not allowed.

**Comment by punithrj26** [comment]
hi @pratikmazumdar ,

Have corrected the flow as per mentioned by you.
Please verify them. the pr is #850 .
Thanks.

**Comment by RupalSingla** [comment]
Message_id mismatchedbetween receiver and on_receiver recon APi's 

@punithrj26

**Comment by punithrj26** [comment]
Hi @RupalSingla,
Have corrected as mentioned by you.
Please verify them. The pr is #979.
Thank you.

**Comment by RupalSingla** [comment]
Correction/
on_receiver_recon.json :
 - "message.orderbook.orders[].counterpart_message" is not allowed
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03



@punithrj26

**Comment by punithrj26** [comment]
@RupalSingla 
Have corrected as mentioned by you.
Please verify them. The pr is #1087 
Thank you.

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @punithrj26

**Comment by punithrj26** [comment]
Hi @RupalSingla ,
Thanks for the update, We appreciate it.
