### ISSUE TITLE
Shopalyst (RET10, RET12, RET13, RET15, RET16, RET18) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#830]
RET10
====
Flow 1 (full refresh)
============
1. /on_search:
- variant name can be made more descriptive;
- accept_bap_terms will be valid only after static terms are enabled;
- item available count has values "99" (means - in stock), "0" (means - out of stock); what does "1740" mean?
- item max count has values "99" (means - no cap per order), any other value (means - cap per order); does "1740" mean buyer can't buy more than 1740 units of the item?
- item.descriptor.short_desc, long_desc is null in some cases (e.g. item CFE856AAB62A2D728439DB1972302FEB_44025155322115_default);
- bpp/fulfillments.id & bpp/providers.fulfillments.id should match;
- statutory_reqs_prepackaged_food (or equivalent as per the taxonomy sheet [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)) not provided;

2. /on_search (variant definition):
- variant definition for item has attribute for "size" (which overlaps with item unitized qty):
- this is why we don't have attribute for size in grocery taxonomy;
- for multi-pack items, item unitized qty can have the pack size (e.g. 6 unit) & unit weight can be appended to item name;
- any freebie (e.g. 120 g rice cake) can also be a part of item description;
- this will make grocery variant definitions consistent across all NPs;

**Comment by BLR-0118** [comment]
Flow 1 (inc refresh)
============
1. Inc refresh only supports full item record update, enable/disable of provider, enable/disable/open/close of provider location (store);

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- pls add provider.locations.id, fulfillment.type;

2. /on_init:
- pls add provider.locations.id;

3. /on_confirm:
- pls add fulfillment TAT (this shows in all /on_status APIs);
- pls add start.location.address;
- while both pickup & delivery slots are optional, only delivery slot is provided (but no pickup slot); any reason?
- anything added to order here should also persist thru the /on_status calls;

4. /on_status:
- /on_confirm has correct start.location.id, start.location.descriptor.name but here, id is showing in start.location.descriptor.name but no id; why?
- pls add fulfillment.tags.routing.type for buyer apps to interprete statuses based on P2H2P or P2P;

5. /on_status (packed):
- fulfillment tracking was "false" in /on_confirm & /on_status but became true here?
- pls remove provider_location;

6. /on_status (in transit):
- pickup time was correctly provided in 5 above but is missing here; shouldn't this be persisted to the order (like invoice)?

7. tracking:
- not clear if tracking is enabled (see above); if enabled, track APIs should also be available;
- to optimize processing of tracking by buyer apps, you should also set fulfillment.tags.url_enabled, fulfillment.tags.url (whenever tracking is enabled);

**Comment by BLR-0118** [comment]
Flow 3
====
1. /on_select:
- can't see out of stock scenario;
- error message should be codified as per format [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

**Comment by BLR-0118** [comment]
Flow 5
====
1. /on_cancel:
- additional attrs like "retry_count", "rto_id" are required for RTO flow;
- pls also add precancel_state;

**Comment by BLR-0118** [comment]
Flow 6c (return with pickup)
==================
1. on_update.json_1707710799056:
- how is qty negative (-1) for one of the items in items[]?

2. for return with pickup:
- for "Return_Approved", the pickup time slot is provided & for "Return_Picked", the pickup time is provided;
- for "Return_Delivered", the delivery time is also provided;

**Comment by BLR-0118** [comment]
@kishorgandham - pls see issues above; if you need to discuss any of these, let's connect, otherwise, pls fix & update here; don't need to resubmit logs;

**Comment by BLR-0118** [comment]
RET14
====
1. /on_search (full catalog):
- pls use correct category_id e.g "Smart Watch" instead of "Smart Watches";
- pls provide all attrs marked as mandatory, e.g. for "Earphone", model is also reqd;
- value for attr "colour" should be the hex code & the name can be provided in "colour_name";

**Comment by BLR-0118** [comment]
@kishorgandham - issues for RET14 above, also most fixes made for RET10 will apply here as well;

**Comment by kishorgandham** [comment]
@BLR-0118 we implemented fixes for all the issues mentioned above except for the one point related to max order quantity. 
In our implementation max-order-quantity can be set by seller. If it is set, we send it on /on_search. Ex: a seller can set the max-order-quantity as 1 for a discounted item indicating a max of one unit can be ordered in an order. If this is not set. we send the max order quantity same as the available inventory.

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET10, RET14)

**Comment by BLR-0118** [comment]
@kishorgandham - can you pls check if each of the above issues have been fixed? as discussed, issues mentioned for flow 2 don't seem to be fixed from [Airpay logs](https://github.com/ONDC-Official/v1.2.0-logs/blob/master/airpay/Myfitness/Flow6_05_03_24/on_select.json);

**Comment by BLR-0118** [comment]
@kishorgandham - same issue with /on_init

**Comment by BLR-0118** [comment]
from logs submitted by Airpay [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/airpay/Myfitness) (tested on 8th Mar):

Flow 1
====
1. /on_search (full catalog):
- none of the issues mentioned above are fixed;

Flow 6
====
1. tracking is enabled but note above (under flow 2) for tracking not enabled;
2. /on_status_packed, /on_status_order_delivered are in 1.1.0 (while others are in 1.2.0); why?
3. /on_update_return_initiated:
- fulfillment.id for Return fulfillment should match return request id from buyer app;
4. /on_update_approved:
- once return is approved (for pickup), the start location & pickup time slot needs to be provided for the return fulfillment;

**Comment by BLR-0118** [comment]
@kishorgandham - request you to pls fix the above;

**Comment by BLR-0118** [comment]
from logs [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/airpay/Myfitness/Flow6):
1. /on_select:
- item.quantity.available.count value not as per contract (99 - in-stock, 0 - out of stock);
- item.quantity.maximum.count value may not be as per contract (99 - no cap per order, any other value - cap per order);
2. /on_init, /on_confirm:
- tax_number, provider_tax_number to be provided under bpp_terms;
3. /on_status_out_for_pickup:
- scenario shown here is wrong: order is packed, invoice attached & then part cancel of item happening before Out-for-pickup;
- part cancel of item should happen before order is packed;
4. All /on_status APIs:
- since tracking is enabled (in /on_confirm), you should also set url_enabled & url when order is trackable;
5. /on_update_refund_liquidation:
- settlement_timestamp has spaces, is invalid;
6. /on_update_after_return_approval:
- when Return_Approved, start location, pickup timeslot is required to be provided;

**Comment by BLR-0118** [comment]
RET13
====
1. /full_on_search:
- item.tags.attribute.size is invalid; pls stick to attributes as defined [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=983332432), otherwise buyer apps won't be able to process;
- e.g. for item 00248AB2865EF8083A2A7BABA5B356BE_43459927703811_default, "500 ml" should go into item.quantity.unitized.measure (which is missing) & the variant definition accordingly modified;
- for item 00819A6ED71A1956C8771C047892098C_43459784638723_default, max/available qty defined as "81", which isn't compliant with contract;
- in bpp/providers.tags.timing, "types" is invalid key (should be "type"), value "all is invalid (should be "All");

**Comment by BLR-0118** [comment]
@kishorgandham - feedback on RET13 above; hope all other issues reported have been fixed?

**Comment by BLR-0118** [comment]
@kishorgandham - above issues for RET10 still not resolved in latest Airpay logs [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/airpay/Myfitness/Flow6_25_03_24);

**Comment by kishorgandham** [comment]
@BLR-0118 re-submitted the RET13 full catalog push logs per feedback.

**Comment by BLR-0118** [comment]
RET12
====
1. item.quantity.unitized.measure missing for all items; in this case, it should be unit - "unit", value - "1";
2. bpp/providers.tags.timing has invalid keys "types" - should be "type" & value should be "All";

RET13
====
1. bpp/providers.tags.timing has invalid keys "types" - should be "type" & value should be "All";

RET15
====
1. item.unitized.quantity.measure missing for all items;
2. bpp/providers.tags.timing has invalid keys "types" - should be "type" & value should be "All";

RET16
====
1. item.unitized.quantity.measure missing for all items;
2. bpp/providers.tags.timing has invalid keys "types" - should be "type" & value should be "All";

RET18
====
1. since variant is defined on unitized qty measure, won't it be better if you put the actual weight / volume there e.g. item 670E51102A754DB9BA9FA1BB68A507F4_44089680331011_default can have unitized qty of 800 mg (instead of 2 units), item 05D407D60650F2A95B8CF0294AEB3E76_44089712017667_default can have unitized qty of 250 ml (instead of 1 unit)?
2. item.tags.attribute should also have mandatory attr "prescription_required";
3. bpp/providers.tags.timing has invalid keys "types" - should be "type" & value should be "All";

**Comment by BLR-0118** [comment]
@kishorgandham - pls check the above & have them fixed;
I'll go ahead & have your RET codes created but this will fail in Prod (if the above issues aren't fixed);
