### ISSUE TITLE
Vidyant (Shopcircuit) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#835]
issue : 

- "schemaErr0": "/context/core_version must be equal to constant (1.0.0)",
- "schemaErr1": "/message/issue/complainant_info/contact/phone must NOT have more than 11 characters",
- "org_name": "Organization's Name for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with BAP ID",
- "org_domain": "Domain of organization for /issue api in message/issue/issue_actions/complainant_actions/[0] mismatched with domain in context",
- "created_at": "context timestamp should be greater than or equal to updated_at in issue",
- "Phn": "Phone Number for /issue api is not in the valid Range"

on_issue:
- "org_name": "Organization's Name for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with BPP ID",
- "org_domain": "Domain of organization for /on_issue api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context"

on_issue_status
-  "org_name": "Organization's Name for /on_issue_status api in message/issue/issue_actions/respondent_actions/[0] mismatched with BPP ID",
- "org_domain": "Domain of organization for /on_issue_status api in message/issue/issue_actions/respondent_actions/[0] mismatched with domain in context",
- "created_at": "context timestamp should be greater than or equal to updated_at in on_issue_status"

Flow 2 - issue related regarding fulfillment is missing

@AtitiTranzita

**Comment by AtitiTranzita** [comment]
Please find PR link below which is in response for above compliance check:
https://github.com/ONDC-Official/v1.2.0-logs/pull/840

@RupalSingla

**Comment by Rishabh-ondc** [comment]
Clarifications
- issue_close call need not have all the attributes, just the id, status, rating and complainant_actions trail is required
- In on_issue_status_4, issue.updated_at should not change if there is no change in the trail of actions

Logs cleared

@AtitiTranzita

**Comment by AtitiTranzita** [comment]
Fixed the mentioned points [here](https://github.com/ONDC-Official/v1.2.0-logs/pull/1011)

@Rishabh-ondc - We are good to close this thread.
