### ISSUE TITLE
Wits Adapter (SA: RET18) - compliance checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#85]
**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/0 must have required property 'tags'
- /message/catalog/bpp~1providers/0/fulfillments/0 must have required property 'id'
- /message/catalog/bpp~1providers/0/fulfillments/0 must have required property 'type'

**on_search_inc_refresh**

- provider id: 6585R in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh

**on_select**

- /message/order/quote/price/value must be string
- context/timestamp difference between /on_select and /select should be smaller than 5 sec
- invalid id: 1 in delivery line item (should be a valid fulfillment_id)

**init**

- value of address.name, address.building and address.locality should be unique

**on_init**

- context/timestamp difference between /on_init and /init should be smaller than 5 sec
- Discrepancies between the quote object in /on_select and /on_init

**confirm**

- /message/order must have required property 'tags'
- /message/order/provider must have required property 'locations'
- order.created_at timestamp should match context.timestamp
- fulfillments[0].end.person object is missing
- mismatches in /billing in /init and /confirm

**on_confirm**

- context/timestamp difference between /on_confirm and /confirm should be smaller than 5 sec
- order.created_at timestamp mismatches in /confirm and /on_confirm
- created_at, tax_number, updated_at mismatches in /billing in /confirm and /on_confirm
- Discrepancies between the quote object /on_select and /on_confirm
- payment object mismatches in /confirm & /on_confirm

**on_status**

- /context/action must be equal to constant (on_status)
- /message/order must have required property 'created_at'
- /message/order must have required property 'updated_at'
- /message/order/provider must have required property 'locations'
- /message/order/items/0 must have required property 'fulfillment_id'
- /message/order/billing must have required property 'address'
- /message/order/billing must have required property 'phone'
- /message/order/billing must have required property 'created_at'
- /message/order/billing must have required property 'updated_at'
- /message/order/fulfillments/0 must have required property '@ondc/org/provider_name'
- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'

**common**

- /message/order must have required property 'tags'
- /message/order/provider must have required property 'locations'
- /message/order/quote/breakup/0/@ondc~1org~1title_type must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)
- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

@SinghSukhchain25

**Comment by sharmasahil0331** [comment]
**search_full_catalog_refresh**

- transaction_id and message id can't be same

**on_search_full_catalog_refresh**

- transaction_id and message id can't be same
- @ondc/org/contact_details_consumer_care should be in the format "name,email,contactno" in /bpp/providers[0]/items

**search_inc_refresh**

- search_inc_refresh Transaction logs not submitted

**on_search_inc_refresh**

- on_search_inc_refresh Transaction logs not submitted

**confirm**

- /message/order/payment/@ondc/org/settlement_details/0 must have required property 'upi_address' in case of upi payment
- Tags should have same and valid gst_number as passed in /on_init

**on_confirm**

- /message/order/fulfillments/0/start must have required property 'time'
- /message/order/fulfillments/0/end must have required property 'time'
- /message/order/payment/@ondc/org/settlement_details/0 must have required property 'upi_address'
- Order Id mismatches in /confirm and /on_confirm

**on_status**

- /message/order/fulfillments/0/start/time must have required property 'range'

@SinghSukhchain25

**Comment by sahil-ondc** [comment]
## Flow 1

**search_full_catalog_refresh**

- transaction_id and message id can't be same

**on_search_full_catalog_refresh**

- transaction_id and message id can't be same
- @ondc/org/contact_details_consumer_care should be in the format \"name,email,contactno\" in /bpp/providers[0]/items

## Other Flows

**on_init**

- quote issues
  - Key length mismatch for breakup.0.item
  - Key length mismatch for breakup.1.item
  - Key 'ttl' mismatch: P1D !== PT60M

**confirm**

- billing object mismatch Key length mismatch for address

**on_confirm**

- context/timestamp difference between /on_confirm and /confirm should be smaller than 5 sec

**on_status**

- /message/order/fulfillments/0/start/time must have required property 'range'
- /message/order/fulfillments/0/end must have required property 'time'


@SinghSukhchain25

**Comment by sahil-ondc** [comment]
## Flow 1

## search_full_catalog_refresh

- /context/city cannot be '\*' in full catalog refresh

## on_search_full_catalog_refresh

- /context/city cannot be '\*' in full catalog refresh
- /context/timestamp cannot be greater than or equal to /context/timestamp of /search call
- /message/catalog/bpp/fulfillments should be same as fulfillments provided in /message/catalog/bpp/providers (all fulfillments cannot have value 'F1')
- invalid ttl format provided in /message/catalog/bpp/providers (it should be ISO8601 duration format)
- /message/catalog/bpp/providers/locations/time/schedule/holidays cannot be past dated, should be only future date
- /message/catalog/bpp/providers/items/descriptor/code should be unique code for item which will be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others;
- /message/catalog/bpp/providers/items/category_id should be one of provided in sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764`
- /message/catalog/bpp/providers/items/@ondc/org/time_to_ship should be in ISO8601 duration format
- missing properties 'mfg_license_no', 'multiple_products_name_number_or_qty', 'expiry_date' in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_packaged_commodities
- invalid attributes provided 'gender', 'colour', 'size', 'brand', 'size_chart', 'fabric' in /message/catalog/bpp/providers/items/tags/attributes
- missing required attributes 'brand', and 'Prescription Required' in /message/catalog/bpp/providers/items/tags/attributes
- /message/catalog/bpp/providers/items should only have parent_item_id in case of variants
- /message/catalog/bpp/descriptor short_desc and long_desc should not have placeholder values

### on_search_inc_refresh

- missing properties 'mfg_license_no', 'multiple_products_name_number_or_qty', 'expiry_date' in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_packaged_commodities
- invalid attributes provided 'gender', 'colour', 'size', 'brand', 'size_chart', 'fabric' in /message/catalog/bpp/providers/items/tags/attributes
- missing required attributes 'brand', and 'Prescription Required' in /message/catalog/bpp/providers/items/tags/attributes
- /message/catalog/bpp/providers/items should only have parent_item_id in case of variants
- /message/catalog/bpp/providers/items/descriptor/code should be unique code for item which will be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others;
- /message/catalog/bpp/providers/items/category_id should be one of provided in sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764`

## Other Flows

### select

- /context/city cannot be '\*'
- Select request not as per the compliance requirement (Buyer selects multiple items (> 1 qty for each item) for checkout)
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

### on_select

- /context/city cannot be '\*'
- invalid title provided in /message/order/quote/breakup/item

### on_init

- /context/city cannot be '\*'
- tracking true was provided in /on_select in /message/order/fulfillments/end, how is it false in /on_init /message/order/fulfillments/end
- /message/order/provider_location should not be provided (Deprecated)
- Buyer app finder fee can't change in /on_init, in /search it was provided as '4', how it changed in on_init

### on_confirm

- again tracking is changed to true (why tracking is changing this frequently)

### on_status (in-progress)

- /message/order/updated_at should not be greater than /context/timestamp
- /message/order/fulfillments/start should have pickup timestamp

### on_status (completed)

- /message/order/updated_at should not be greater than /context/timestamp

## Note

- /context/city cannot be '\*'
- You have provided 'Delivery', 'Self-Pickup', 'Delivery and Self-Pickup' as fulfillment options, does hoop supports self-pickup

@SinghSukhchain25

**Comment by nishthamongaondc** [comment]
### Shopify Retail Logs
## Flow 1

### on_search_full_catalog_refresh
- /message/catalog/bpp~1descriptor must have required property 'tags'
- /message/catalog/bpp~1providers/0/items/0/descriptor/code item/descriptor/code should be in this format - \"type:code\" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others"
- "transaction_id and message id can't be same
- @ondc/org/contact_details_consumer_care should be in the format \"name,email,contactno\" in /bpp/providers[0]/items

## Flow 2

### on_init
- parent_item_id missing in /message/order/quote/breakup.1.item
- Key 'ttl' mismatch: P1D !== PT60M
- Tags should have valid gst number and fields in /on_init

### on_confirm
- 'upi_address' missing in /message/order/payment/@ondc~1org~1settlement_details/0
- context/timestamp difference between /on_confirm and /confirm should be less than 5 sec
- parent_item_id missing in /message/order/quote/breakup.1.item
- Key /message/order/quote/breakup.1.title mismatch: Jeans !== Short Sleve T shirt
- Key /message/order/quote/breakup.2.@ondc/org/item_id' mismatch: F1 !== 1
- Key /message/order/quote/breakup.2.price.value' mismatch: 10.00 !== 10

### on_status_pending
- range missing in /message/order/fulfillments/0/start/time
- 'time' missing in message/order/fulfillments/0/end

### on_status_delivered
- Message_id cannot be same for on_status.pending and on_status.picked

### on_status_picked
- Message_id cannot be same for on_status.pending and on_status.picked

## Note

- Flow 5 missing

@SinghSukhchain25 

## Magento Retail Logs
## Flow 1

### on_search_full_catalog_refresh
- "transaction_id and message id can't be same
- 'tags' missing in /message/catalog/bpp~1descriptor
- /message/catalog/bpp~1providers/0/time/label must be equal to one of the allowed values (enable,disable)
- /message/catalog/bpp~1providers/0/items/0/descriptor/code item/descriptor/code should be in this format - \"type:code\" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- /message/catalog/bpp~1providers/0/items/0/quantity/available/count available/count must be equal to one of the allowed values i.e 99(if in stock) or 0(if not in stock)
- transaction_id and message id can't be same
- fulfillment_id in /bpp/providers[0]/items[7] should map to one of the fulfillments id in bpp/fulfillments
- category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id

### Incremental search and on_search missing

## Flow 2

### on_select
- provider.id mismatches in /on_search and /on_select
- invalid fulfillment_id

### on_init
- gps coordinates in fulfillments[0].end.location mismatch in /select & /on_init
- address.area_code in fulfillments[0].end.location mismatch in /select & /on_init
- ttl mismatch: P1D !== P7D
- Key length mismatch for breakup.0.item

### on_confirm
- /message/order/fulfillments/0/state/descriptor/code must be equal to constant (Pending)
- order.created_at timestamp mismatches in /confirm and /on_confirm
- Provider Id mismatches in /on_search and /on_confirm
- provider.locations[0].id mismatches in /on_search and /on_confirm
- Key length mismatch for root (tax_number)
- default fulfillments state is missing in /on_confirm
- store name  /fulfillments[0]/start/location/descriptor/name can't change
- fulfillments[0].end.location gps is not matching with gps in /select
- Key length mismatch for breakup.0.item
- 

### on_status_pending missing

### on_status_delivered
- City code mismatch in /search and /on_status
- fulfillments/state should be Order-picked-up for /on_status_pending

## Note

- on select  out of stock logs missing

@vishal-wits

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- placeholders values should be avoided in the catalog; eg: short_desc, long_desc in bpp/descriptor
- seller must be located in the same city for which full catalog search is initiated (search is for bengaluru while seller is located in Punjab)
- unitized measure is not captured correctly; item description shows different unit; eg: for item id: "44255485853926", description shows 300ml whereas unitized measure is set as 1 unit;
- item and category_id mapping seem incorrect; every item is mapped with "Mental Wellness" category

**/on_search (inc)**

- invalid attribute "back_image_health" for code type in /tags/image; should be "back_image" instead
- back image url seems invalid; pls avoid sending placeholder values
- mapping of category id should not be changed in incremental; the serviceability construct is missing for the newly defined category

## Flow 2

**/on_select**

- item prices must be tax inclusive for the selected items in BPC category in /quote/breakup; Why are taxes applied on top of the prices?

**/on_init**

- type, collected_by, uri, tl_method, status, settlement_basis, settlement_window, withholding_amount in /payment should only be provided when BPP is collecting prepaid

**/on_confirm**

- provider_tax_number should also be provided in /tags/bpp_terms
- delivery TAT (@ondc/org/TAT) must be provided in /fulfillments
- @ondc/org/buyer_app_finder_fee_type should be "percent" (p in lower case)

**/on_status**

- unsolicited call to notify "Packed" state is missing;
- @ondc/org/buyer_app_finder_fee_type should be "percent" (p in lower case)

## Flow 3, 4

- similar issues as above

## Flow 5

- similar issues as above

**/on_status (RTO-Disposed)**

- precancel_state should not change
- order/updated_at should be updated correctly

## Flow 6

- similar issues as above

**/on_update (part cancel)**

- order created_at & updated_at are not captured correctly
- adjustment in delivery charges should also be captured in quote_trail

**/on_update (interim)**

- actual delivery timestamp for forward shipment can't be earlier than /update request for return

**/on_update (return picked)**

- actual return pickup timestamp can't be future dated

**/on_update (return delivered)**

- message_id should be unique
- actual return delivery timestamp can't be future dated
- settlment trail must be maintained and details received in /update (FYI Refund) must be appended to the settlement_details list in /payment/"@ondc/org/settlement_details"

**/on_update (Liquidate)**

- message_id should be unique
- returned items must be mapped to the return type fulfillment in /items


@vishal-wits

**Comment by bluecypher** [comment]
## Flow 2

**/confirm**

- invalid length of gstin number of bap; SNP must respond with a NACK

**/on_confirm**

- np_type must also be provided in /tags/bpp_terms

**/on_status**

- packed state: estimated pickup time range can't be earlier than context timestamp
- invoice should be provided once the order is picked

## Flow 5

**/on_status (Order-picked-up)**

- estimated delivery time range is incorrect; end time can't be < start time

**/on_cancel**

- fulfillment state of forward shipment ("c2159125-6cd3-4b0d-95a0-b4c340371d1d") should be "Cancelled"

**/on_status (RTO-Disposed)**

- context/message_id should be unique; applicable for all the unsolicited calls
- fulfillment state of forward shipment ("c2159125-6cd3-4b0d-95a0-b4c340371d1d") should be "Cancelled"

## Flow 6

- Entire flow (a,b,c) must be tested for a single order with multiple items

**/on_update (return delivered)**

- return delivery timestamp is missing in /fulfillments for type = "Return"



@vishal-wits

**Comment by diwanshi-thewitslab** [comment]
@bluecypher, 

1. invalid length of gstin number of bap; SNP must respond with a NACK

This is something which we are getting from reference buyer application, so for testing and log generation purposes we have removed that validation, but in prod that will be in place. with validation we are unable to move further. 

Can we ignore that and resubmit ?

**Comment by sandeepshahi** [comment]
# RET18

- Are variants supported?

**/on_search**

- changes in incremental must be reflected in the full pull later

## Flow 2

**/on_status**

- routing info must be provided in /fulfillments/tags on or before Agent-assigned state
- provided invoice link must be accessible

## Flow 3

**/on_select**

- unit price of item must be non zero for OOS item; the total price and count will be 0

## Flow 4

**/on_cancel**

- precancel_state is not captured correctly;

## Flow 5

**/on_cancel**

- invalid id: "rto"; should be the fulfillment id of new RTO fulfillment created; check quote/breakup and quote_trail
- for RTO taxes in quote/breakup, tags must be present to specify fulfillment level taxes
- quote_trail/type is invalid for adjustement in forward delivery charges; should be "delivery" instead of "item"

**/on_status (RTO)**

- similar issues as in on_cancel

## Flow 6

**/on_update (ReverseQC)**

- Questionnaire may be provided in reverseqc_input
- settlement details must be appended for reverse qc(if received)


@diwanshi-thewitslab

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- what's the point of using UUIDs for fulfillment ids here? It only needs to be unique within the scope of fulfillment for the catalog;
- pls restrict gps coords to 6 decimals;
- isn't EAN available for these items? they seem like branded products;
- for item 44255488442598: returnable true, cancellable false => means?

2. /on_search_inc:
- pls share inc update **after** the full catalog;

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- fulfillment.provider_name should be name of seller/LSP who's fulfilling the order;
- is there some logic for calculating TAT of 60 min? (while this looks ok, distance between store & buyer locn is about 30 mins, time to pack is 15 min, so in another 15 min, the rider has to pickup & handle the last mile delivery);

2. /on_confirm, /on_status:
- for buyer apps to process hyperlocal vs intercity orders, pls set routing.type to P2P (hyperlocal), P2H2P (intercity), whenever the order is accepted;

**Comment by BLR-0118** [comment]
Flow 6
====
6a (part cancel) & b (return with liquidation) - ok;
6c (return with pickup) - pls remove reverseqc_input (not yet enabled);

**Comment by BLR-0118** [comment]
flow 1
====
1. /on_search:
- what does ttl of "P3DL" mean?

2. /on_search_inc:
- item 44255485853927 is updated to 0 avail / max qty wef 08:40:00.022Z and same record (with same timestamp) shows item in stock; which is the latest record in this case, considering that buyer apps use this timestamp for versioning?

**Comment by BLR-0118** [comment]
flow 2 - ok;

**Comment by BLR-0118** [comment]
flow 5
====
1. /on_cancel:
- initiated_by should have bpp_id;
- curious why delivery charge is being refunded, when additional rto charge is levied?

**Comment by BLR-0118** [comment]
@witslab-nikita - I'm clearing logs for v1.2.0, but pls make sure the above issues are fixed & status updated here;

**Comment by witslab-nikita** [comment]
@BLR-0118 Sure, will make sure these issues will be fixed. 

@BLR-0118 @sandeepshahi @sahil-ondc @nishthamongaondc Thanks for all your feedbacks and clearance of logs.
