### ISSUE TITLE
EkSecond (LBNP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#857]
1. it seems retail logs & some logistics logs have been resubmitted; however, difficult to figure out, hence can't review;
2. logs have to be generated for test scenarios [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1670900093);

**Comment by BLR-0118** [comment]
@NajeebMohammed

**Comment by BLR-0118** [comment]
Flow 2
====
1. /init:
- where is provider.locations.id populated from? It isn't in /on_search;

2. /confirm:
- "return to origin " is invalid (no space at the end);
- item_id in quote.breakup doesn't match what's sent in /on_init (both id, price);

3. /update (with OTP) to be provided;
4. cancel APIs required (solicited, unsolicited);
5. track APIs required;

**Comment by BLR-0118** [comment]
@NajeebMohammed - this needs to be resubmitted

**Comment by BLR-0118** [comment]
1. /search:
- holidays should be future dated (compared to Context.timestamp date);

2. /confirm:
- rto_action."return_to_origin " is invalid (no extra space at end);

3. /update:
- Context.timestamp for /update is earlier than /on_confirm: how?
- order prep time in /search (provider.time.duration) is 15 min & diff between /search & /update timestamp is few millisecs; pls make sure this is consistent in Prod;

4. Pls also share logs for /on_update;

5. Pls share logs for /cancel, /on_cancel (both cancellation by buyer, RTO by LSP);

**Comment by BLR-0118** [comment]
@NajeebMohammed - pls address the above on priority

**Comment by BLR-0118** [comment]
Flow 2
====
1. payment.type is "POST-FULFILLMENT" in /search & /init but changed to "ON-ORDER" in /confirm?
2. /update:
- value of PCC (fulfillment.start.instructions.short_desc) is max 6 alphanumeric as per contract;
3. /cancel:
- reason code "005" can't be used by LBNP;
4. /on_cancel:
- since cancellation initiated by LBNP, cancelled_by should be bap_id (subscriber id for LBNP);
- rto_event.sub_reason_id is invalid key;
- this is not yours but pls ask LSN to fix;

Flow 2 (buyer app cancel TAT breach)
====
1. /cancel:
- reason code "006" can't be used by LBNP;
2. /on_cancel:
- since cancellation initiated by LBNP, cancelled_by should be bap_id (subscriber id for LBNP);
- this is not yours but pls ask LSN to fix;

**Comment by BLR-0118** [comment]
@NajeebMohammed - pls fix & resubmit

**Comment by NajeebMohammed** [comment]
> * this is not yours but pls ask LSN to fix;

We have asked LSN to fix this.

**Comment by NajeebMohammed** [comment]
> * reason code "005" can't be used by LBNP;

When order cancelled by merchant, what should be the cancellation_reason_id to Logistics Seller np?

**Comment by BLR-0118** [comment]
Flow 2
====
1. /confirm:
- /on_init has quote for item (immediate_delivery-PT1H30M) as 1 & tax of 0;
- /confirm shows the quote as 5. How??

2. /confirm (with ready_to_ship "no") & /update (with ready to ship "yes") have same timestamp; if so, ready_to_ship could have been sent as "yes" in /confirm;

**Comment by BLR-0118** [comment]
@NajeebMohammed - I'm clearing your logs but pls make sure 1 above is fixed
