### ISSUE TITLE
Kiko Live (RET10) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#858]
Flow 1
====
1. /on_search (full refresh):
- pls remove accept_bap_terms (will be enabled with static terms);
- locations.address: pls use correct values for locality, street (as buyer apps use this to display the merchants on category landing page;
- for items, you need to provide the statutory reqs in statutory_reqs_prepackaged_food (both text attrs & back_image will help);
- for item 65c34bc1352a39b540f6dd01, parent_item_id is defined (however, the variant definition corresponding to this isn't available);
- pls also add store timings as per the new format (in bpp/providers.tags) as doc [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv);

2. /on_search (incr):
- are you supporting both push & pull?
- common scenarios for grocery such as inventory / price update also need to be supported;

Flow 2
====
1. /on_select:
- item avail qty has values "99" (in stock), "0" (out of stock); what does "13" mean?
- item max qty has values "99" (no order cap) or any other value (signifying order cap); "13" means max of 13 qty per order?

2. /on_init:
- remove provider_location (deprecated);
- remove bpp_collect (for seller collecting payment, not yet enabled);

3. /on_confirm:
- fulfillment TAT was 24 hrs in /on_select but 90 min here; means?
- pls also add provider_tax_number;
- fulfillment.start.location shows "A, " for locality & should match what's in /on_search (see above);

4. tracking needs to be supported for hyperlocal orders; to optimize tracking processing by buyer apps, pls also set routing.type, gps_enabled or (url_enabled, url) in /on_status as doc in the contract;
5. invoice typically added at order pickup, since merchant cancellations can happen prior to that;

Flow 3
====
1. /on_select (out of stock):
- quote.price.value doesn't add up to the quote.breakup[].price.value;
- error message should be as per the format [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

**Comment by BLR-0118** [comment]
Flow 4
====
1. /on_cancel:
- items[] should have qty 0 for forward shipment fulfillment & the original qty assigned to cancel fulfillment;
- forward shipment fulfillment state should become "Cancelled";
- cancel_request, precancel_state to be added to forward shipment fulfillment;
- it looks like seller is refunding the cost of the items but not the delivery / convenience charges, etc; in that case, the full cost of the items should be in quote_trail (-480, -4800);
- quote.price.value doesn't add up to quote.breakup[].price.value;
- cancelled_by should have the unique id of whoever initiated the cancellation (bap_id if buyer NP initiated, bpp_id if seller NP initiated or bpp_id of LSP if you're using on-network logistics & cancellation was initiated by LSP);

Flow 5
====
- same issues as above;

Flow 6
====
1. /on_update (partial cancel):
- has same message_id as /on_confirm;
- same issues as for flow 4 above;

2. /on_update (return initiated):
- fulfillment id for return fulfillment should be same as return request id from buyer app;

3. /on_update (liquidated):
- has same message_id as /on_update (return initiated);
- no quote_trail?
- same issues as for flow 4 above;

**Comment by BLR-0118** [comment]
@vijendrapatidar - pls fix everything & make a note here; also, resubmit logs for flow 6;

**Comment by vijendrakiko** [comment]
@BLR-0118 Thanks for your feedback.
I will fix the above issues and resubmit them again.

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full catalog):
- use correct unit for item unitized qty from [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json), e.g. item 65bc8a50dd2fbfc824b428b7, unit should be "millilitre" (as mentioned in name);
- same with item 65c34ab5352a39b540f6d57c;
- config for variant_group is not required;

Flow 2
====
1. /on_select:
- fulfillment provider name should be name of store or LSP;

2. /on_init:
- pls remove cancellation_terms (yet to be enabled);

3. /on_status (pickup):
- pls add routing.type;
- also make sure all states, based on routing.type are sent: hyperlocal (P2P), intercity (P2H2P);

Flow 4 & 5
=======
1. /on_cancel:
- location id "Location-6386154b42674fabf7bdabf4" is invalid; should be "location-6386154b42674fabf7bdabf4" (lowercase l);
- pls add cancel_request, precancel_state;

Flow 6
====
1. /on_update (part cancel):
- quote_trail for item *6d57c should be -180 as cancelled qty is 2;
- message_id same as /on_confirm?

2. /on_update (liquidated):
- quote_trail required for return fulfillment;
- interim state Return_Initiated skipped?

**Comment by BLR-0118** [comment]
@vijendrakiko - pls fix the above & resubmit only for flow 5 & 6

**Comment by BLR-0118** [comment]
Flow 4
====
1. /on_confirm:
- fulfillment TAT is 24 hrs, but why is pickup slot with duration of 18hrs (02:39-20:39), while delivery slot with duration of 6 hrs (20:39-02:39); you need to have meaningful time slots, which shows TAT of 24 hrs;

Flow 5
====
1. /on_cancel:
- cancelled_by should have bpp_id, not bpp_uri;
- precancel_state is Pending, which means order hasn't even been packed; in this scenario, there's no RTO (hence, reason code 011 is not valid); RTO happens when order has been picked up & cannot be delivered to buyer for whatever reason;
- few additional attrs reqd in cancel_request, such as retry_count, rto_id, etc;

Flow 6 - ok;

**Comment by BLR-0118** [comment]
@vijendrakiko - pls fix & resubmit for flow 5

**Comment by Gururaj-KikoLive** [comment]
Hi @BLR-0118 We need clarification on the following -

1. Flow 4 - We have extended the shop's open timings for 24 HRS, in case of late-night orders. This gives the seller time to process the orders the next day until the second half. We have noticed that the seller may take some time to process the orders, but once they are packed, they are delivered immediately in the hyperlocal area. Therefore, we have allowed for 18 hours for out-for-delivery and 6 hours for delivery of products.

2. Flow 5 - precancel_state is Pending: As checked in the reason code file we found compatible error code '998' which indicates Order confirmation failure before it's ready to ship or packed. Please confirm the same.

**Comment by BLR-0118** [comment]
Flow 5
====
1. /on_cancel: there are issues with quote & quote_trail
- pls note that quote in /on_confirm is frozen and any delta changes (either to the line items or new line items specifically for RTO) should be in quote_trail e.g.
- /on_confirm has following line items in quote:
- item id *428b7 (7 Up): price - 70, qty - 2;
- item id *3f22 (Amul ghee): price - 4800, qty - 2;
- item id *abf4 (delivery charge): price - 10;
- item id *abf4 (convenience fee): price - 172.75;

due to RTO, you're refunding the cost of 7-Up, Amul ghee: thus, quote_trail will have -ve values for the prices above & quote will have this zero'd (**this is correct**);

if you're no refunding delivery charge, convenience fee, you don't need to do anything more (**this isn't correct**);

if you're adding new charge for RTO, you can add this (both to quote & quote_trail):
- item id: *abf4-RTO (RTO fulfillment), price: <RTO delivery charge>

**Comment by BLR-0118** [comment]
@vijendrakiko @Gururaj-KikoLive - can you pls fix this & share only the /on_cancel so I can clear your logs

**Comment by BLR-0118** [comment]
clarified with Kiko Live & they're fixing;
clearing logs for v1.2.0

**Comment by BLR-0118** [comment]
I can see following issues (from logs [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/ref-buyer-RET10-11-12-13-14/RET10)):

Flow 1
====
1. /on_search:
- for item 65bcf1988bef71377b3f3f22, unitized qty should be "5 litre" instead of "5 kg";

Flow 2
====
1. /onstatus*:
- to allow the buyer app to distinguish between hyperlocal & intercity orders, pls send routing.type as "P2P" (hyperlocal) or "P2H2P" (intercity);

Flow 4
====
1. oncancel:
- cancel_request should only be in the forward shipment fulfillment (fulfillment-6386154b42674fabf7bdabf4) which is getting cancelled, not the logical Cancel fulfillment (Cancel-fulfillment-6386154b42674fabf7bdabf4) created for the purpose of audit trail;
- state.descriptor.code for forward shipment fulfillment (above) should be "Cancelled", not "Pending";
- delivery charge has become 0 (from 20) & misc has become 0 (from 3); however, there are no refund (-ve) entries for this in quote_trail;

Flow 5
====
1. oncancel:
- following is invalid (pls remove):
-         "tags": {
          "cancellation_reason_id": "004"
        },

Flow 6
====
1. onupdate1:
- same message_id as /confirm;
- initiated_by should have bpp_id (not bpp_uri);

2. onupdate2 & onupdate3 have same message_id;

**Comment by BLR-0118** [comment]
@Gururaj-KikoLive - pls check issues above & have it fixed ASAP

**Comment by Gururaj-KikoLive** [comment]
Hi @BLR-0118 Yes we are working on it, 

Do we need to resubmit all flows?

**Comment by BLR-0118** [comment]
@Gururaj-KikoLive - pls fix all the above & make a note here for all points; pls don't resubmit any logs

**Comment by Gururaj-KikoLive** [comment]
Hi @BLR-0118 Please check below 

Flow 2
/onstatus*:

- to allow the buyer app to distinguish between hyperlocal & intercity orders, pls send routing.type as "P2P" (hyperlocal) or "P2H2P" (intercity); -- done

Flow 4

- state.descriptor.code for forward shipment fulfillment (above) should be "Cancelled", not "Pending"; -- done
- delivery charge has become 0 (from 20) & misc has become 0 (from 3); however, there are no refund (-ve) entries for this in quote_trail; -- done

Flow 6
onupdate1:
- same message_id as /confirm; -- done
- initiated_by should have bpp_id (not bpp_uri); - done
- onupdate2 & onupdate3 have same message_id; -- done

**Comment by BLR-0118** [comment]
@Gururaj-KikoLive - what about the issues for flow 1 & 5?
