### ISSUE TITLE
NDHGO (RET10) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#859]
Flow 1
====
1. /on_search (full catalog):
- remove accept_bap_terms (until static terms are enabled);
- pls use proper street, locality (instead of complete address) in locations.address as this is displayed by buyer apps in the CLP;
- for item MTMyNjIyXzc5ODM0OTBfM19Q, descriptor.code isn't an EAN code;
- use non-deprecated category id from this [list](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0);
- item unitized qty should be correctly defined e.g. for item MTMyNjIyXzc5ODM0OTBfM19Q (milk shake), unitized qty should be a volumetric measure (millilitre, litre);
- for item MTMyNjIyXzgwNTI4NjFfM19Q, name shows "100 g" but unitized qty is "1 unit"?
- pls add store timings in new format (under "timing");

2. /on_search (incremental):
- only full item update supported;
- for provider - disable, location - disable / close / open supported;

Flow 2
====
1. /on_select:
- provider.locations required;

2. /on_init:
- provider_location to be removed;
- provider.locations to be added;

3. /on_confirm:
- fulfillment TAT to be added;

4. /on_status (all):
- invoice to be added at order pickup (not earlier) since merchant cancellations may happen prior to that;
- fulfillment tracking was false in /on_confirm but true in /on_status APIs; however, no tracking logs provided;
- to optimize tracking processing by buyer apps, pls add routing.type, gps_enabled or (url_enabled, url) in /on_status when tracking has actually been enabled;

**Comment by BLR-0118** [comment]
Flow 4
====
1. /on_cancel:
- precancel_state required;

Flow 5
====
1. /on_cancel:
- same issues as above;
- additional attrs are required in cancel_request as per contract;

Flow 6
====
flows a & b to be provided for RET10

**Comment by BLR-0118** [comment]
@rajib-senrysa - pls fix & resubmit for flows 1, 4, 5, 6

**Comment by rajib-senrysa** [comment]
@BLR-0118 Can you clarify what are the additional attrs required in cancel_request for Flow 5?  Except precancel_state. We will include that.

**Comment by bmonish** [comment]
@BLR-0118 We have submitted logs correcting the given feedback and for flow 6. Kindly please review.

**Comment by BLR-0118** [comment]
@rajib-senrysa - pls fix all issues above & resubmit for flow 6

**Comment by rajib-senrysa** [comment]
@BLR-0118 

### Need two clarifications:

1. `/update_settlement can't have same message_id as this;` Since this is a BAP issue, can we ignore this?
2. For Flow 5, `Rto-Initiated` will be sent in `/on_cancel` correct. After that when should the `Rto-Disposed` be sent in an unsolicited `/on_status` or `/on_cancel`?

**Comment by rajib-senrysa** [comment]
@BLR-0118 Have fixed the issues and resubmitted flow 6.

Kindly check and review.

**Comment by rajib-senrysa** [comment]
@BLR-0118 Any update on this?

**Comment by BLR-0118** [comment]
@rajib-senrysa - clearing logs for v1.2.0
