### ISSUE TITLE
Plotch (RET11) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#861]
Flow 1
====
1. /on_search (full catalog):
- category_id should be "F&B" for all items in RET11;
- item type is required for all F&B items;
- what does return window of "P1fCancellableD" mean??
- when item price is 0 (1121371253), either default_selection or upper/lower should be providedfor buyer apps to display on product listing page;
- make-to-order product, such as item 1121371254, has return window of 12 days; how to interprete this??
- "multiselect" is invalid value for input;
- MSN/ISN self-declaration not available?
- polygon serviceability has to be supported by buyer app for F&B;

2. /on_search (incr catalog):
- incr catalog refresh seems to be a copy of full catalog refresh;
- as per contract, only full item updates / new item(s), provider disable, location disable/close/open are supported;

Flow 2
====
1. /select, /on_select:
- provider address is in pin code 400052, with serviceability radius of 5km; how's a request for quote from pincode 110085 even serviceable?

2. /on_init:
- from where is bap_terms.tax_number getting populated?

3. /on_status (order picked up):
- this has delivery time, but no pickup time?
- fulfillment objects duplicated for same id;

4. tracking is true in /on_confirm & all /on_status APIs but no tracking API logs?

Flow 3 - no logs??

Flow 4
====
1. /on_cancel:
- items array here is different from /on_confirm?
- same with quote;

Flow 5 - no logs;

**Comment by BLR-0118** [comment]
Flow 6
====
1. merchant cancel:
- items[], quote_trail are incomplete and / or invalid;

2. part return:
- return request is invalid as only the entire make-to-order product can be returned;

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by dileswarp** [comment]
@BLR-0118 Sir Please review our pr and share the feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/980

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- remove accept_bap_terms, collect_payment (not yet enabled);
- item type required for all F&B items;
- how can return window be 1 day for F&B items?
- return window of P0D means what?
- curious how default_selection value for item 1121371253 has been defined (since no customization defined as default selection for its custom group);

2. /on_search (location close):
- requires start & (optional) end time;

Flow 2
====
1. /on_select:
- parent_item_id, item type reqd for all items in items[];
- store name in /on_search is "ONDC hypermart" but fulfillment provider name is "Aniket Lad"?
- fulfillment category should be "Immediate Delivery";
- no tax line items in quote?

2. /on_track:
- path is invalid (same gps coords repeated twice);
- also add order, config to tracking.tags;

Flow 3
====
1. /on_select shows error for item oos; however, since there's change in cart, another /select has to be sent;

Flow 4
====
1. /on_confirm has 0 delivery charge in quote but this is missing in /on_cancel quote;

Flow 6
====
1. return with liquidation should include base item & customizations in same return request;

**Comment by BLR-0118** [comment]
@dileswarp - pls resubmit for flows 1, 3, 6

**Comment by dileswarp** [comment]
@BLR-0118 Sir, Please review our logs as per feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1007

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full catalog):
- item 1121371253, with base price of 0 has default selection price / max price of 25 / 100 respectively;
- however, price for default selection for custom group vLei170368 (used to customize item) is 30 / 30;
- how's the default selection price derived?

Flow 3
====
1. /on_select (out of stock):
- every item / customization must have the tax line item in quote;
- errors should show cases where customization is out of stock;

2. transaction_id for /select & /select (in stock) should be the same;

can't review flow 6 with above issues;

**Comment by BLR-0118** [comment]
@dileswarp - pls fix above issues & resubmit complete flow 6 where above fixes can be verified

**Comment by dileswarp** [comment]
@BLR-0118 Sir, Please review our updated PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1059

**Comment by BLR-0118** [comment]
Flow 1
====
1. /full_catalog_refresh:
- veg / non veg / egg is mandatory for all F&B items;
- pls share example of polygon (geojson) serviceability;

2. Not clear how the buyer app handles processing of concurrent full & incremental catalog refresh?

Flow 6
====
1. /select:
- item type should be sent for all F&B items (with or without customizations);

2. /on_select:
- tax should be sent for all F&B items (incl for 0 price);
- pls share payload where mandatory customization is out of stock;

3. /confirm:
- shows TAT of 4 days while /on_confirm has TAT of 60 min; which is correct?

4. /on_confirm:
- no pickup / delivery slot was provided in /on_confirm but is in /merchant_cancel; TAT promised is 60 min but from the delivery slot (14:37 to 15:07) & Context.timestamp of 13:37, delivery may take up to 90 mins??

5. /merchant_cancel:
- quote_trail to have entries only when there is delta change in quote for corresponding entry;

6. /on_status:
- mapping of fulfillment states to order state is incorrect;

7. /return_request for make-to-order product should include both items & customizations; accordingly, this is invalid.

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by BLR-0118** [comment]
Flow 6
====
1. /select:
- item 1121778964 not defined in catalog;
- fulfillment_id is assigned in /on_select, not in /select;

2. mismatch between /select & /on_select:
- all items in /select are not in /on_select; if items are out-of-stock, they should be shown accordingly;
- in one case, only a customization (1121371257) is in quote & items[], but not the corresponding base item 1121371254;

@dileswarp - fundamental issues with pre-order flow; pls resubmit the following:
Flow 1, Flow 6 (including item & customization out-of-stock, part cancel, return with liquidation);

**Comment by dileswarp** [comment]
@BLR-0118 Sir Please review our PR and share you are feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1319

**Comment by sandeepshahi** [comment]
## Flow 1

**/on_search**

- tags/type is optional for standalone (non-customizable) SKUs; applicable for all the subsequent APIs
- value of default_selection price should be in string format
- upper/lower range and "defalut_selection" must be provided for customizable items

**/on_init**

- provider_tax_number and np_type should be provided in /tags/bpp_terms

**/on_confirm**

- "@ondc/org/withholding_amount", "@ondc/org/settlement_window" and "@ondc/org/settlement_basis" should be provided by collector

**/on_status**

- tracking info must be provided in /fulfillments/tags on or before agent assigned state
- fulfillments/end/person/name should not change; check /confirm call

**/on_update (Return)**

- initiated_by should also be added to /tags/return_request for customization: 1121371259
- item with price=0 need not be provided in quote_trail; only the quote line items with adjusted values should be present


@dileswarp

**Comment by dileswarp** [comment]
@sandeepshahi Please review log and share feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1438

**Comment by BLR-0118** [comment]
as per note 3 weeks back: "fundamental issues with pre-order flow; pls resubmit the following:
Flow 1, Flow 6 (including item & customization out-of-stock, part cancel, return with liquidation);"

since then, you've submitted flow 1 & 6 3 weeks back, flow 1 & 2 4 days back; which one should I check so I can verify if the above is fixed?

@dileswarp

**Comment by dileswarp** [comment]
@BLR-0118 SIr, 
flow 1 and flow 6 (including item & customisation out-of-stock, part cancel, return with liquidation) was reviewed by @sandeepshahi  the pr was  https://github.com/ONDC-Official/v1.2.0-logs/pull/1319 and shared the feedback last week. accordingly we fixed the issues and resubmitted the  PR 4 days back is https://github.com/ONDC-Official/v1.2.0-logs/pull/1438 which is flow 1 and flow 6 only, flow2 typo mistake.

**Comment by BLR-0118** [comment]
@dileswarp - I don't see item & customization out-of-stock in Flow 6?

**Comment by dileswarp** [comment]
@BLR-0118 Sir;
Please review the below PR, we sent the customization out-of-stock in flow 6,

https://github.com/ONDC-Official/v1.2.0-logs/pull/1319

  "error": {
        "message": "[{\"dynamic_item_id\":\"115637142\",\"item_id\":\"1121371254\",\"error\":\"40002\"},{\"dynamic_item_id\":\"115637142\",\"customization_id\":\"1121403900\",\"customization_group_id\":\"vLei170368\",\"error\":\"40002\"}]",
        "code": "40002",
        "type": "DOMAIN-ERROR"
    }

**Comment by dileswarp** [comment]
@BLR-0118 Sir Please review our PR https://github.com/ONDC-Official/v1.2.0-logs/pull/1483

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- custom_group config shows max of 6, but only 5 customizations defined in catalog;

Flow 6
====
1. /customisation_out_of_stock_on_select: error.message is invalid:
- doesn't include the customization id 121403900 for dynamic item id 117545964;
- extra escaping characters may give validation errors in some languages;

2. bpp_terms sent in /on_init is showing as bap_terms in /confirm, which is not correct;
3. not sure where the bap_terms in /on_confirm is from as it's not in /confirm;
4. part cancel & return flows - ok;
5. haven't seen your track & /on_track;

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0
