### ISSUE TITLE
Airpay (BA: RET10) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#863]
# RET:10

### search_full_catalog_refresh

- context/transaction_id and context/message_id can't be same

### select

- /message/order/fulfillments/0/end/location/gps The gps co-ordinates should be precise atleast upto 6 digits after decimal
- context/transaction_id and context/message_id can't be same
- context/city code mismatch in /search and /select

### init

- /message/order/billing/address/building must be string
- /message/order/fulfillments/0/id must NOT have fewer than 1 characters
- /message/order/fulfillments/0/end/location/gps The gps co-ordinates should be precise atleast upto 6 digits after decimal
- /message/order/provider/id mismatches in /select and /init
- value of address.name, address.building and address.locality should be unique

### confirm

- /message/order/billing/address/building must be string
- /message/order/billing/email must match format 'email'
- /message/order/fulfillments/0/end/contact/email must match format 'email'
- /message/order/fulfillments/0/end/location/address/building must be string
- /message/order/quote/breakup/1 must have required property '@ondc/org/item_id'
- context/city code mismatch in /search and /confirm
- Number of digits in tax number in message.order.tags[0].list should be 15
- fulfillment id b92382281e6309320be6d4d853e3e2d3_1 does not exist in /on_select
- fulfillments[0].end.location.address.area_code is not matching with area_code in /select

@jayesh-airpay

**Comment by bluecypher** [comment]
#### Please remove previously submitted logs and only provide the latest logs

## Flow 1

**/search (inc)**

- txn id and message id in /context can't be the same
- request to stop the incremental refresh must be submitted for verification

## Flow 2

**/init**

- fulfillments/id can't change; should be the same as provided in /on_select
- tax_number in billing is optional; placeholder value should not be provided

**/on_init**

- provider/locations is missing; provider_location is deprecated; BNP must respond with a NACK
- buyer app finder fee is changed to 0 percent; Is this accepted by BNP?
- fulfillment_id is missing in /items; BNP must respond with a NACK

**/confirm**

- context/transaction_id and payment/params/transaction_id can't be the same
- invalid placeholder value of tax_number in bpp_terms; not provided by SNP in /on_init

**/track**

- track API must be supported

## Flow 3

- missing txn flow; share all the logs as per the scenario

## Flow 4

**/cancel**

- message/descriptor is only required in case of fulfillment level cancellation; provide fulfillment id is also invalid

## Flow 5

- invalid RTO flow; submit the logs as per the scenario

## Flow 6

**/on_update (part cancel)**

- cancel_request tag object missing in /tags for cancelled fulfillment; multiple issues in other payloads from SNP;

**/update**

- check the contract for schema; order state, /items and /provider are not required,
- payment settlement details should be provided only when refund triggering state is received from the SNP; update_target will be "payment"


@jayesh-airpay

**Comment by sahil-ondc** [comment]
## Flow 2

### init

- /message/order/billing/tax_number should not have placeholder value

### confirm

- /message/order/id Should be alphanumeric upto 32 letters max
- payment settlement_details mismatch in /on_init & /confirm
- billing object mismatch in /init and /confirm

## Flow 4

### cancel

- /message/descriptor/short_desc should not contain placeholder values

## Flow 5, Flow 6

- /update refund information call missing

@jayesh-airpay

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search

- 'accept_bap_terms' should not be provided as part of Phase 1
- STD code does not match with correct area_code on /on_search
- Timestamp for item[40] can't be greater than context.timestamp

- (BNP should add validation for above all)

## Flow 2

### select

- multiple items with multiple quantity should be selected as per the roll out sheet
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

## Flow 3

- in Flow 3, multiple items should be selected, and positive flow should be provided for the item which is in stock

## common

### confirm

- /message/order/tags must be array

@jayesh-airpay

**Comment by BLR-0118** [comment]
following issues need to be fixed:
1. /confirm:
- as noted above, message.order.tags should be array;
- BNP GST no to be exchanged with SNP (as doc in contract);

2. /update (return request):
- format for return request is wrong;
- order.state, order.items[] should be removed;
- order settlement details are sent in separate request from return request;

**Comment by BLR-0118** [comment]
@jayesh-airpay

**Comment by BLR-0118** [comment]
Flow 6:
1. /on_status logs incomplete:
- some are 1.1 (/on_status_packed, /on_status_delivered), others 1.2;
- /on_status_order_picked_up & /on_status_in_transit are the same file but copied twice & named differently;
2. All logs for flows 6b & c are not provided & in many cases duplicates:
- /on_update_rejected, /on_update_return_approved, /on_update_refund seem to be the same file with different timestamps;
- complete flows for return with liquidation & return with pickup are required;

**Comment by BLR-0118** [comment]
@jayesh-airpay @amultamse

**Comment by BLR-0118** [comment]
Flow 6:
1. /confirm:
- no bpp_terms.tax_number was sent in /on_init, so where is this getting populated from here?

**Comment by BLR-0118** [comment]
@jayesh-airpay @amultamse - pls fix the above & make a note here;

**Comment by BLR-0118** [comment]
Flow 6
====
1. /confirm:
- BAP is required to send their GST no in bap_terms.tax_number;
2. /update (for liquidation, approval):
- remove parent_item_id (only reqd for make-to-order items in F&B);

@amultamse - I'm clearing the logs, but pls make sure the above are fixed;

**Comment by BLR-0118** [comment]
@amultamse - I'm clearing your logs for RET13 / RET18 but pls make sure ([these](https://github.com/ONDC-Official/v1.2.0-logs/issues/830) issues reported for Shopalyst won't impact you when fixed);
