### ISSUE TITLE
Dehaat IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#888]
FLOW 1 :
Incomplete flow - In flow 1 there are few missing api's such as issue status solicited ,on_issue_status and issue_close .

Flow 2 for issue fulfilment is missing

@vivek-sharma1

**Comment by skdeep12** [comment]
@RupalSingla Please share the links for flows. We haven't come across `issue_close` api.

**Comment by skdeep12** [comment]
@sandeepshahi there has been no update on this, please guide us towards Correct documents

**Comment by RupalSingla** [comment]
on_issue:
"updated_at": "The 'updated_at' of message/issue/issue_action/respondent_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in on_issue",
  "created_at": "'created_at' should match issue's 'created_at'"

on_issue_status:
created_at": "'created_at' should match issue's 'created_at'

on_issue_status_unsolicited
created_at": "'created_at' should match issue's 'created_at'

@skdeep12

**Comment by RupalSingla** [comment]
Kindly verify the logs once by the utility
 @skdeep12

**Comment by RupalSingla** [comment]
Logs approved @skdeep12
