### ISSUE TITLE
MP2 (LBNP) - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#91]
## Delivered Flow

- null values to be removed

**/on_search**

- /on_search/0/context/core_version must be equal to constant (1.2.0)
- /on_search/0/message/catalog must NOT have additional properties (bpp/fulfillments)
- /on_search/0/message/catalog/bpp/providers/0 must have required property 'fulfillments'
- /on_search/0/message/catalog/bpp/providers/0/categories/time must have required property 'timestamp'
- /on_search/0/message/catalog/bpp/providers/items/time/timestamp must match format "date"
- For Next Day Delivery, TAT date should be the next date i.e. 2023-10-19

**/init**

- /init/0/message/order/billing/tax_number should be valid
- Provider with id 'OLA Mobility' does not exist in the catalog provided in /on_search
- Item Id 'ola_express' does not exist in /on_search

**/on_confirm**

- /on_confirm/0/message/order/fulfillments/0/start/instructions must be object
- /on_confirm/0/message/order/fulfillments/0/end/instructions must be object
- /on_confirm/0/message/order/payment @ondc/org/collection_amount is required only for payment/type 'ON-FULFILLMENT'
- /on_confirm/0/message/order/payment/@ondc/org/settlement_details must be array (null values to be removed)

**/on_update**

- /on_update/0/message/order/provider/locations must be array
- /on_update/0/message/order/items/0/fulfillment_id must be equal to constant (ola_express_f1)
- /on_update/0/message/order/fulfillments/0/end/instructions must have required property 'short_desc'
- /on_update/0/message/order/payment @ondc/org/collection_amount is required only for payment/type 'ON-FULFILLMENT'
- /on_update/0/message/order/payment/@ondc/org/settlement_details must be array
- order/updated_at cannot be future dated w.r.t context/timestamp

**/on_track**

- /on_track/0 time/timestamp or updated_at in /location cannot be future dated w.r.t context/timestamp

## RTO Flow

- similar issues as above

**/on_cancel**

- Message Id cannot be same for different sets of APIs (same as confirm) (buyer app should handle)

**/on_status**

- Message Id cannot be same for different sets of APIs (same for agent assigned and order picked up)(buyer app should handle)

## Cancel Flow

**/on_search**

- /on_search/0/context/timestamp must match format "date-time"

@Poornima-Aithal

**Comment by BLR-0118** [comment]
following issues to be fixed:
1. removing static terms / cancellation terms for now, as this isn't enabled yet;
2. adding tracking optimization params such as gps_enabled, url_enabled, url to fulfillment.tags.tracking in /on_status;
discussed with @mherle on the above; logs don't need to be resubmitted.

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0

**Comment by mherle** [comment]
Thanks @BLR-0118 .

**Comment by mherle** [comment]
@abhinavv245 and @BLR-0118 

have rerun the log validation utility and now I see no validation failures: 
```Flow1
{}
Flow1-DeferredRTS
{}
Flow2
{}
Flow3
{}```

Please review

**Comment by abhinavv245** [comment]
## Flow 1

**/search**

- Order prep time & category should be consistent in /search (for order prep time 30 mins, Same Day Delivery or Immediate Delivery may be used)

**/init**

- fulfillments/start and end location/address and contact information should not be same

**/confirm**

- linked_order/items/0/price/value order price mismatches from /search
- PCC code enum 2 is the merchant order number
        
## RTO Flow

**/on_cancel**

- 'precancel_state' tag/s required in /fulfillments/tags

@Poornima-Aithal @mherle

**Comment by mherle** [comment]
Fixed the above issues (including the on_cancel issue from the LSP) via this [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/1519).

Pls review again @abhinavv245 

cc: @Poornima-Aithal

**Comment by BLR-0118** [comment]
@mherle - logs cleared for v1.2.0;
