### ISSUE TITLE
More Retail (IGM) - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#921]
FLOW 2 is missing ,  which is basically issue raised related to an item 

@Chinmaya M G

**Comment by chinmaya1920** [comment]
Hi @RupalSingla 

The Flow 2 logs submitted in the [PR](https://github.com/ONDC-Official/v1.2.0-logs/pull/945). Please Check it

**Comment by RupalSingla** [comment]
on_issue :
message.issue.resolution_provider is not needed .

On_issue_status :
timestamp for respondant action is changing for respondant action processing.
short descr cannot change 

on_issue_ststus:
message.issue.resolution_provider.respondent_info.gros is not requires 

@chinmaya1920

**Comment by RupalSingla** [comment]
logs cleared for version 1.0.0 @chinmaya1920
