### ISSUE TITLE
Growthfalcons (LBNP) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#925]
1. /search:
- order prep time (provider.time.duration) is required for hyperlocal;

2. /cancel:
- reason code "006" isn't valid for LBNP; pls use "007" for TAT breach;

**Comment by BLR-0118** [comment]
@SandeepGF - I'm clearing the logs for v1.2, but pls fix the above;

**Comment by SandeepGF** [comment]
Sure @BLR-0118
