### ISSUE TITLE
Vidyant (Shopcircuit) (SA) RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#928]
Flow 1
message.orderbook.orders.state should be "completed " not created 
created_at and updated_at cannot have same timestamp

Minimum 5 orders needs to be there in the orderbook

@AtitiTranzita

**Comment by AtitiTranzita** [comment]
Hi Rupal,
We have addressed the mentioned issues and created new PR [here](https://github.com/ONDC-Official/v1.2.0-logs/pull/930).
Please verify it.

@RupalSingla

**Comment by AtitiTranzita** [comment]
Hi Rupal,
We have addressed the mentioned issues and created new PR [here](https://github.com/ONDC-Official/v1.2.0-logs/pull/957)
Please verify it.

@RupalSingla

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@AtitiTranzita
