### ISSUE TITLE
Plotch (RET10/12/13/14/15/16/18) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#950]
## Flow 1

**/on_search**

- "np_type" must be provided in bpp/descriptor/tags/bpp_terms
- use the non-deprecated category_id in /items
- either one of "@ondc/org/statutory_reqs_prepackaged_food" or "@ondc/org/statutory_reqs_packaged_commodities" is required as per the category_id; check the protocol key mapping [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)
- invalid tag group attribute in /items/tags; the list of codes are already covered as part of statutory reqs
- unitized measure should be correctly captured;
- vairant group must be defined based on the unitized measure for weight based variants
- seller's location must be the same for which search by city was intiated; search is for std:080 (bengaluru) but the seller is from Mumbai

**/on_search (inc)**

- full catalog details need not be sent as part of incremental refresh; pls check the contract for the schema
- "\_id" is not a valid attribute; should not be sent over the network
- only delta incremental changes should be provided in incremental pull

## Flow 2

**/on_select**

- fulfillment_id is same as in /on_search; how are multiple fulfillment supported?
- delivery charges line item must be provided in quote/breakup with prices = 0 (in case of free delivery)

**/on_init**

- invalid length of tax_number in bpp_terms; should be 15 digit GSTIN

**/on_status**

- delivery TAT is of 4 days but estimated delivery time range exceeds this TAT

**/track**

- must be supported if tracking is set as true

## Flow 3

- complete scenario must be submitted; multiple items must be selected and available items must be processed for order

**/on_select (OOS)**

- error.message is invalid (unable to parse); escape sequence is not used correctly

## Flow 4

**/cancel**

- invalid schema; descriptor should only be used in case of fulfillment level cancellation;
- value of descriptor/name is incorrect;
- fulfillment id in descriptor/short_desc is incorrect; should be the id of the fulfillment to be cancelled

**/on_cancel**

- quote_trail should be provided in the cancelled fulfillment
- cancel_request need not be provided in /tags for fulfillment type: Cancel; already added in the previous forward shipment fulfillment (in case of full order cancellation)

## Flow 5

- invalid RTO flow; RTO must be initiated with fulfillment type= "RTO"; RTO must be intiated through /on_cancel and later delivered/disposed info should be provided through /on_status

@dileswarp

**Comment by BLR-0118** [comment]
Flow 1
====
1. pls address issues identified for RET11 logs;
2. when max radial distance of earth is around 6000km, what does radial distance of 5000 km mean?

Can you pls run in this flow:
Flow 1:
Full catalog refresh;
incremental item update (out of stock, price change);
Flow 2;

**Comment by BLR-0118** [comment]
@dileswarp - pls fix issues identified for RET11 logs, run using the above flow & resubmit for flow 1 & 2;

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- use most accurate unitized unit, i.e. "kilogram" instead of "gram" for the catalog items;

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by dileswarp** [comment]
@BLR-0118 Sir, Please review the updated PR of search https://github.com/ONDC-Official/v1.2.0-logs/pull/1060

**Comment by sandeepshahi** [comment]
**/on_search**

- invalid serviceability defined in bpp/providers/tags; for type 10, radial unit must be provided
- avoid using placeholder values in statutory reqs (eg: fssai license no); 
-  for above point, either one of the statutory reqs ("@ondc/org/statutory_reqs_packaged_commodities" or "@ondc/org/statutory_reqs_prepackaged_food") is required as per the mapping [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)
- "imported_product_country_of_origin" is a deprecated attribute in "@ondc/org/statutory_reqs_prepackaged_food"; already captured in /items/tags/origin


@dileswarp

**Comment by dileswarp** [comment]
@sandeepshahi Please review our PR , and share the feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1187

/on_search

invalid serviceability defined in bpp/providers/tags; for type 10, radial unit must be provided: Done
avoid using placeholder values in statutory reqs (eg: fssai license no); On prod clients fssai will be configured.
for above point, either one of the statutory reqs ("@ondc/org/statutory_reqs_packaged_commodities" or "@ondc/org/statutory_reqs_prepackaged_food") is required as per the mapping here: Fixed

"imported_product_country_of_origin" is a deprecated attribute in "@ondc/org/statutory_reqs_prepackaged_food"; already captured in /items/tags/origin: Done

**Comment by BLR-0118** [comment]
1. /on_search:
-item.descriptor.code is required;

2. pls also share incremental catalog updates for common grocery use-cases: item in / out of stock, price changes;

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by dileswarp** [comment]
@BLR-0118 SIr, Resubmitted the log, Please review and share you are feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1198

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET10)

**Comment by BLR-0118** [comment]
RET13 - flow 1
=========
1. item.tags.attribute can only have attributes in [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=983332432) list;
2. "weight" should go into item.quantity.unitized.measure;

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET14)

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET15)

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET16)

**Comment by BLR-0118** [comment]
RET18 - flow 1
=========
1. item.tags.attribute can only have the attributes in [this](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764) list;
2. weight should be in item.quantity.unitized.measure;

**Comment by BLR-0118** [comment]
@dileswarp - pls fix & resubmit for RET13/18

**Comment by dileswarp** [comment]
@BLR-0118 Sir, Please review the updated pr for RET 13 and 18 https://github.com/ONDC-Official/v1.2.0-logs/issues/950

**Comment by sandeepshahi** [comment]
### Please test the logs with a different counterparty NP

## RET13

**/on_search**

- serviceability radius of 5000 km is not feasible; use realistic values
- relative path in the variant group is not defined correctly;
- Self-Pickup is not defined in bpp/providers/fulfillments/

## RET18

- invalid attribute weight in /item/tags/attribute; unit weight is captured in quantity/unitized/measure
- relative path in the variant group is not defined correctly;
- Self-Pickup is not defined in bpp/providers/fulfillments/


@dileswarp

**Comment by dileswarp** [comment]
@sandeepshahi Please review and share the feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1468 for RET 13 and RET 18

**Comment by dileswarp** [comment]
@sandeepshahi Please review our log, and share feedback https://github.com/ONDC-Official/v1.2.0-logs/pull/1531

**Comment by BLR-0118** [comment]
RET13/18
======
1. what's the purpose of variant definition if it's assigned to only 1 item?
2. why is EAN code not being used for all branded items in BPC, H&W?

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by BLR-0118** [comment]
1. pls check the data you submitted for RET13/18: parent_item_id is assigned to only 1 item;
2. you should follow the contract examples to see what code is used for each category: for branded products, EAN is used by everyone;

**Comment by dileswarp** [comment]
@BLR-0118 

Hello Sir;

1. pls check the data you submitted for RET13/18: parent_item_id is assigned to only 1 item;

RET-13
We have shared the data of 3 products, one is simple product with id "1123554120" and another is varaint product, where we can verify the "parent_item_id": "1123554121", is assigned to two product with id's 1123554121 , 1123554122.\

RET-18
We have shared the data of 3 products, one is simple product with id "1123617559" and another is varaint product, where we can verify the "parent_item_id": "1123617560", is assigned to two product with id's 1123617560 , 1123617561.

2. you should follow the contract examples to see what code is used for each category: for branded products, EAN is used by everyone;

We verified the given products in websites like Amazon, Snapdeal, Tatacliq. GTIN is not mentioned anywhere. 
That's why we used the code 5(others).

**Comment by BLR-0118** [comment]
logs cleared for RET13/18 for v1.2.0;
