### ISSUE TITLE
More Retail (RSF) — compliance checks

### ISSUE THREAD

**Issue by sandeepshahi** [ONDC-Official/v1.2.0-logs#973]
Please submit the logs as per the following test case scenarios:

1. Successful reconciliation by the receiver for 5 or more transactions
2. Correction flow initiated by the receiver in /on_receiver_recon

For logs, both /receiver_recon and /on_receiver_recon are mandatory.

@chinmaya1920 @rahul-repository

**Comment by RupalSingla** [comment]
Receiver_recon

- settlement_timestamp , timestamp for orderbook cretaion-created_at and updated_at cannot have same values

on_receiver_recon:

- message.orderbook.orders.counterparty_recon_status or all the 5 orders are having different code values that are underpaid /overpaid/paid which is not possible ,it should be of one type

@chinmaya1920 
@rahul-repository

**Comment by extedcouD** [comment]
More retail

correction/on_receiver_recon.json :
 - "message.orderbook.orders" must contain at least 5 orders
 - All counterparty_recon_status values must be 01 or if they none of them are 01 they can be 02 or 03


correction/receiver_recon.json :
 - "message.orderbook.orders[].payerdetails.payer_account_no" must be a string
 - "message.orderbook.orders" must contain at least 5 orders

success/receiver_recon.json :
 - "message.orderbook.orders[].payerdetails.payer_account_no" must be a string
 
@chinmaya1920
@rahul-repository

**Comment by chinmaya1920** [comment]
Hi @extedcouD 

Can you check the #1084 for the above points mentioned?

**Comment by rudransh-ondc** [comment]
correction-flow/on_receiver_recon.json :
 - "message.orderbook.orders[0].state" is required
 - "message.orderbook.orders[0].provider" is required
 - "message.orderbook.orders[0].payment" is required
 - "message.orderbook.orders[0].withholding_tax_gst" is required
 - "message.orderbook.orders[0].withholding_tax_tds" is required
 - "message.orderbook.orders[0].deduction_by_collector" is required
 - "message.orderbook.orders[0].payerdetails" is required
 - "message.orderbook.orders[0].settlement_reason_code" is required
 - "message.orderbook.orders[0].recon_status" is required
 - "message.orderbook.orders[0].created_at" is required
 - "message.orderbook.orders[0].updated_at" is required
 - "message.orderbook.orders[0].counterparty_diff_amount" is not allowed
 - "message.orderbook.orders[0].counterparty_recon_status" is not allowed

@chinmaya1920
@rahul-repository

**Comment by chinmaya1920** [comment]
Hi @rudransh-ondc 

But the above keys for on_reciever_recon that you mentioned as required are not mentioned in [API Documentation](https://docs.google.com/document/d/1ubUPAWpbbUJ4vG2h5TQ74srZBjYjrO0P/edit#heading=h.44sinio)
can you confirm this?

**Comment by chinmaya1920** [comment]
Hi @RupalSingla 
As you mentioned Logs cleared for version 1.0.0 
Can this issue be closed?

**Comment by DivyakantSwarnkar01** [comment]
Do I Need to Upload JSON of Core  Software, IGM and RSF Here for Verification ?
Kindly Reply to -- DivyakantSwarnkar@gmail.com
