### ISSUE TITLE
Ecomm Express RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#977]
Flow 1:

Receiver_recon:
Bap_id and Bpp_id cannot be same 
On_receiver_recon:
Schema error : order_recon_status value is missing in the payload

Flow 2:

Receiver_recon:
Bap_id and Bpp_id cannot be same 
On_receiver_recon:
Schema error : order_recon_status value is missing in the payload

@AryanSinghEcom

**Comment by AryanSinghEcom** [comment]
Will update the value of timestamp in receiver_recon

What should be the value in "@ondc/org/buyer_app_finder_fee_type"  here?

**Comment by RupalSingla** [comment]
Logs approved for RSF v1.0.0.
