### ISSUE TITLE
MaasErp (SA)	RSF - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#978]
Flow 1:

Receiver_recon:
The value provided for "message.orderbook.orders.payment.@ondc\/org\/settlement_window_status" in the payload is incorrect.
payment object is having wrong values , please check the payload once 

@techopendhi

**Comment by RupalSingla** [comment]
- message.orderbook.orders.payment.settlement_timestamp and message.orderbook.orders.created_at are having same values which is not possible , as settlement happens after the orderbook got created
@techopendhi

**Comment by extedcouD** [comment]
MaasErp

Flow-1
on_receiver_recon.json :
 - "message.orderbook.orders[].counterparty_diff_amount.value" must be a number

receiver_recon.json :
 - "message.orderbook.orders[].payment.uri" must be a valid uri
 - "message.orderbook.orders[].payment.@ondc/org/collected_by_status" is not allowed to be empty

Flow-2
on_receiver_recon.json :
 - "message.orderbook.orders[].counterparty_diff_amount.value" must be a number

receiver_recon.json :
 - "message.orderbook.orders[].payment.uri" must be a valid uri
 - "message.orderbook.orders[].payment.@ondc/org/collected_by_status" is not allowed to be empty

@techopendhi

**Comment by RupalSingla** [comment]
logs cleared for version 1.0.0 @techopendhi
