### ISSUE TITLE
Chattybao (RET11/18) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#985]
1. /on_search:
- catalog should include customizations (pls follow the test scenarios exactly as doc [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795));
- category_id should be "F&B";

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search_full_catalog:
- why is message_id different from /search?
- you need valid 14-digit FSSAI no in prod;
- not clear why the config for custom group (min/max/seq) is being repeated inside the corresponding item, even though values are exactly same;
- not clear purpose of repeating timing for each custom menu, even though it's same as store timing?

2. incremental catalog:
- hope you're supporting common use-cases such as stores temporarily closed;
- incremental push also supported (as in grocery), right?

Flow 2
====
1. /on_select:
- quote.price should be rounded to 2 decimals & match quote.breakup[].price;
- somehow, this is correct in /on_init;

2. /on_init:
- provider_tax_number is store PAN no;

3. /on_confirm:
- fulfillment provider name was "Chattybao logistics" in /on_select, changed to restaurant name here: which is correct?
- fulfillment.start.instructions not required here since that's between seller (which is handling fulfillment) & their delivery partner;
- fulfillment TAT is 90 min, Context.timestamp is 07:59:49, pickup time slot is 07:59:49-08:29:49, delivery time slot is 07:59:49-08:59:49:
- so, order is accepted (in /on_confirm) at 07:59:49 and is ready to be picked up? What does time_to_ship of 30 min defined in the catalog mean then?
- pls calculate correct pickup & delivery time slots considering order prep time & TAT promised;

4. others:
- fulfillment tracking is true but no tracking APIs?
- to allow the buyer app to differentiate hyperlocal & intercity fulfillment states, you need to set routing.type to P2P (for hyperlocal);
- to optimize track processing on buyer app, pls set gps_enabled to "yes" when tracking has been enabled;

Flow 3
====
1. /on_select_out_of_stock:
- pls share example where customization(s) for an item are out of stock;

Flow 5
====
1. /on_cancel_RTO:
- RTO delivery/disposed time is provided at rto initiation itself?
- surprising that all item costs are being refunded & only delivery charge isn't being refunded; in F&B, since items aren't resaleable, curious why you've handled this way?
- for RTO, pls also provide start & end locations, as applicable;

Flow 6
====
- pls share logs for 6a & 6c on the same order;

**Comment by BLR-0118** [comment]
@venkat77777 - pls fix the above & resubmit logs for flows 2/5/6

**Comment by venkat77777** [comment]
@BLR-0118  
```surprising that all item costs are being refunded & only delivery charge isn't being refunded; in F&B, since items aren't resaleable, curious why you've handled this way?```

We wanted to deduct 100% of the amount as cancellation charges for rto cancellation. But we were not passing cancellation_terms in on_init as you instructed. So how do we do this?

**Comment by venkat77777** [comment]
@BLR-0118 ```for RTO, pls also provide start & end locations, as applicable;```

for RTO disposal, start and end locations are not applicable, right? as rider is not returning the order to merchant? Also RTO-Inititated doesn't have location as well

**Comment by venkat77777** [comment]
@BLR-0118 
```fulfillment tracking is true but no tracking APIs?``` have included them in flow 5.

```to optimize track processing on buyer app, pls set gps_enabled to "yes" when tracking has been enabled;``` It is already done like that
`{
              "code": "tracking",
              "list": [
                {
                  "code": "gps_enabled",
                  "value": "yes"
                },`

```fulfillment TAT is 90 min, Context.timestamp is 07:59:49, pickup time slot is 07:59:49-08:29:49, delivery time slot is 07:59:49-08:59:49:
so, order is accepted (in /on_confirm) at 07:59:49 and is ready to be picked up? What does time_to_ship of 30 min defined in the catalog mean then?
pls calculate correct pickup & delivery time slots considering order prep time & TAT promised;```

As we created and processing these orders in test environment for logs capturing purpose, we could not wait 30 minutes or so to make the times correct. However In production these times will be applied and will be proper.

**Comment by venkat77777** [comment]
@BLR-0118 
```/on_init:
provider_tax_number is store PAN no;``` do we need to pass it? is it mandatory?

**Comment by BLR-0118** [comment]
RET18 - flow 1
=========
1. pls use proper unitized measure for all items e.g. for shampoo / facewash, it should be in millilitre / litre;

**Comment by BLR-0118** [comment]
@venkat77777

**Comment by BLR-0118** [comment]
RET11 - flow 1 (logs [here](https://github.com/ONDC-Official/v1.2.0-logs/tree/master/Mappls-Buyer-App/Customization))
=========
1. /on_search:
- fssai no is of 14 digits;
- definition of custom menu is invalid - CM0 to CM8 point to parent_category_id of "F&B", which isn't a valid custom menu item (definition should be hierarchical, generally up to 3 levels, & items linked to the leaf level of the hierarchy);
- all custom groups have max config of "99" & custom group configs are repeated in the item definition; to optimize, you can override the custom menu config at item level (only if different from the custom_group definition in bpp/providers.categories);
- can't figure out which make to order item is being shown e.g. item for "Paneer Butter Masala" has customizations "Paneer Butter Masala", "Pan Butter Masala Half", "Paneer Butter Masala Full" and all customizable items have similar definition;
- request you to use real life examples with proper definitions & configurations and handling both use cases - base item with 0 & non-zero price;
- considering that item id is unique within the scope of provider, what's the point of using such long ids?

2. pls share incremental response log;

Flow 2
====
1. /select:
- pls comply with the limit of 12 chars for parent_item_id (representing dynamic item id);

2. /on_select:
- what does quote.ttl of 4 days mean?

3. /on_confirm:
- curious how the pickup & delivery slots are calculated:
a. /on_confirm timestamp is 11:51:34 and order is accepted here;
b. fulfillment TAT is 90 min, which means delivery time should be 11:51:34 + 90 min = 13:21:34 (approx);
c. time to ship (as per catalog is 30 min) - means order won't be ready before 11:51:34 + 30 min = 12:21:34 (approx);
d. pickup slot is 11:51:34 - 12:21:34 and delivery slot is 11:51:34 - 12:51:34: this doesn't make any sense;

4. /on_status_accepted:
- order is accepted in /on_confirm, what's the purpose of generating another /on_status event for this?

5. /on_status_order_delivered shows delivery time as 11:59:36 and /on_status_solicited_delivered shows as 12:05:38; which is correct??

6. tracking is enabled for fulfillment & routing.type also set but no /track & /on_track?

**Comment by BLR-0118** [comment]
Flow 3
====
1. /select_after_removing_out_of_stock & /select_with_out of stock should have same transaction id;
2. /on_select_with out of stock:
- error.message format is invalid (for make-to-order items, dynamic_item_id should also be included);

**Comment by BLR-0118** [comment]
Flow 4
====
1. /cancel timestamp is 17:43:29, /on_cancel timestamp is 12:13:29:
a. looks like an issue with /cancel timestamp;
b. SNP should NACK this request, considering ttl of 30 secs;

2. /on_confirm timestamp is 12:13:17 & order is accepted in /on_confirm; /cancel timestamp is 17:43:29 (almost 5 1/2 hrs later): related to 1 above;

3. /on_cancel:
- quote_trail is missing for C1;
a. order should have been delivered by now, considering promised TAT of 90min;
b. only reason why order should be cancelled now is if order isn't yet delivered, so why not use reason code 006?

**Comment by BLR-0118** [comment]
Flow 5
====
1. /on_status_out_for_delivery:
- quote.price.value should have max 2 decimals & match sigma(quote.breakup[].price.value);
2. /on_cancel & RTO:
- start & end locations for F1-RTO to be provided;
- precancel_state.updated_at should show timestamp for "Out-for-delivery", not for /on_cancel;

**Comment by BLR-0118** [comment]
@venkat77777 - pls fix & resubmit all logs from 1 to 6;

**Comment by venkat77777** [comment]
- definition of custom menu is invalid - CM0 to CM8 point to parent_category_id of "F&B", which isn't a valid custom menu item (definition should be hierarchical, generally up to 3 levels, & items linked to the leaf level of the hierarchy);
```We didn't have parent_category_id as F&B earlier, was passing empty string like mentioned in the contract doc. But we received feedback saying it is mandatory and required `**Schema Error **: /message/catalog/bpp~1providers/0/categories/1 must have required property 'parent_category_id'`, 
and I don't think i understand completely when you say definition should be hierarchical and items linked to leaf level of the hierarchy. Need some better understanding of this```

- all custom groups have max config of "99" & custom group configs are repeated in the item definition; to optimize, you can override the custom menu config at item level (only if different from the custom_group definition in bpp/providers.categories);
```This requires some clarification as we don't have `config` applied at item level or custom_menu level`, If you are talking about max available quantity of items 99 is enough and not required of mentioning it in custom_group?```


- can't figure out which make to order item is being shown e.g. item for "Paneer Butter Masala" has customizations "Paneer Butter Masala", "Pan Butter Masala Half", "Paneer Butter Masala Full" and all customizable items have similar definition;
```We converted variants into customizations as per your suggestion, as the items are just variants, all the customization has similar definition```

- request you to use real life examples with proper definitions & configurations and handling both use cases - base item with 0 & non-zero price;
```Again, as we don't have customizations in our system at all, we modified variants into customizations, hence we can say that base item with non-zero price scenario will not occur for our catalog```

- considering that item id is unique within the scope of provider, what's the point of using such long ids?
```We are using thos long ids internally to map them to base item, variant item etc as they are stored in different tables```

**Comment by venkat77777** [comment]
> # Flow 5
> 2. /on_cancel & RTO:
> 
> * start & end locations for F1-RTO to be provided;

F1-RTO disposal start & end locations are not required, right? I have checked in the contract doc, there also start & end locations are not mentioned

**Comment by venkat77777** [comment]
@BLR-0118 waiting for your reply on the above comments

**Comment by BLR-0118** [comment]
@venkat77777 - I've already added my comments inline

**Comment by venkat77777** [comment]
@BLR-0118 
```SG: you may use it for your internal mapping but pls send shorter ids over protocol (not more than 12 chars alpha-numeric);```

For Item Ids there's no length restriction mentioned in the contract document, right? There's a restriction for custom_groups where it is no more than 12 chars alpha-numeric.

All our item ids are uuids and are common across providers so we combine item id with provider id and pass

**Comment by venkat77777** [comment]
@BLR-0118 
```SG: I suggest you check how custom menus show in Pincode/Paytm/Zomato/Swiggy & how you can click on custom menu and go directly to the item;```

I have checked them and have checked mine also with ondc preprod buyer app, i can open menu, see the list and clicking on item on the menu, we are going directly to the item as you mentioned.

you can verify the same from [here](https://buyer-app-preprod-v2.ondc.org/application/brand?brandId=ondc-seller-preprod.chattybao.com/ondc_ONDC:RET11_MxBP2YIbdEmMcVM64qEvN1&outletId=ondc-seller-preprod.chattybao.com/ondc_ONDC:RET11_MxBP2YIbdEmMcVM64qEvN1_757ddd80-970f-11ed-9d55-49678f9cbdaa)

**Comment by venkat77777** [comment]
@BLR-0118 we have implemented the customizations by converting variants into customizations. As we have converted them ourselves and we don't allow our merchants for customizations except variants, we'll only have one customization flow that is base item with 0 price.

Can we connect over a call to get these confusion cleared so that we can move forward? As it is already been delayed

**Comment by BLR-0118** [comment]
@venkat77777 - pls check logs for EkSecond / Uengage to see how they've defined custom menus / customizations, etc; these are available in this GitHub repo

**Comment by BLR-0118** [comment]
RET11
====
1. /on_search_full_catalog (checked for provider MEsLvp1E5N-HX72m3e4KyL):
- store timings are from 1100-2100, while custom menu timings are from 0900-2100; if intent is to have custom menu display at all times during store hours, you don't even need to define custom menu timings;
- custom group definitions (min/max/seq) is being duplicated inside the item definition that is customized using the custom group e.g. item 22e8e640-900c-11ee-9add-594f1f59b51a:MEsLvp1E5N-HX72m3e4KyL has custom group defn for CG1 duplicated inside this item;
- for the above item, price is 0 but default selection price range is 202/269; not sure how this was derived as couldn't find any default customization for this custom group;
- what does "15" for item available qty mean?
- does "15" for item max qty mean buyer can't buy > 15 of these items/

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- item 934f9300-0089-11ef-89a4-e3845de3dd1c:MxBP2YIbdEmMcVM64qEvN1:BIN has price 0 in /on_search, but quote shows price of 200?

2. /on_status_pending:
- order acceptance is at 13:36:22, order prep time (time_to_ship) is 30 min, so order can't be ready before 14:06:22;
- pickup slot is 13:36-14:06, while delivery slot is 14:06-14:06, which means if order is picked up at 14:06, it'll also be delivered at 14:06?

3. /on_track:
- payload needs to be complete;
- tracking.location.time.timestamp is invalid;

Flow 3
====
1. /on_select_out_of_stock:
- you need to show cases where customized item is out of stock;

**Comment by BLR-0118** [comment]
@venkat77777 - flows 1 to 3 reviewed & the above issues to be fixed;
pls resubmit all logs;

**Comment by BLR-0118** [comment]
RET18
====
1. pls use proper unitized measure e.g. item 60671fb0-681f-11ee-93f0-f51608bbeb64:MA14KebUOL-rKF6j1P4Elw (shampoo) should have unitized measure in millilitre/litre, item b5b09420-681e-11ee-93f0-f51608bbeb64:MA14KebUOL-rKF6j1P4Elw should have unitized measure of 30 millilitre as per product desc;

**Comment by BLR-0118** [comment]
@venkat77777 - RET18 feedback above

**Comment by venkat77777** [comment]
> # Flow 2
> 1. /on_select:
> 
> * item 934f9300-0089-11ef-89a4-e3845de3dd1c:MxBP2YIbdEmMcVM64qEvN1:BIN has price 0 in /on_search, but quote shows price of 200?
>  ```This is incorrect, the above mentioned item has price 200 in on_search```
> 2. /on_status_pending:
> 
> * order acceptance is at 13:36:22, order prep time (time_to_ship) is 30 min, so order can't be ready before 14:06:22;
> * pickup slot is 13:36-14:06, while delivery slot is 14:06-14:06, which means if order is picked up at 14:06, it'll also be delivered at 14:06?
>  ```As I mentioned earlier, these timings are only for capturring logs, we cannot capture each flow for an hour, right? This was not an issue when we submit RET10 logs. In real time, the timings will be proper like mentioned in the ranges. But in test environment we cannot expect to follow the timings as these are not real orders, right?```
> 3. /on_track:
> 
> * payload needs to be complete;
> * tracking.location.time.timestamp is invalid;
> ```This is an issue, I'll check```
> # Flow 3
> 1. /on_select_out_of_stock:
> 
> * you need to show cases where customized item is out of stock;
> ```Will check this```

**Comment by venkat77777** [comment]
> # RET11
> 1. /on_search_full_catalog (checked for provider MEsLvp1E5N-HX72m3e4KyL):
> 
> * store timings are from 1100-2100, while custom menu timings are from 0900-2100; if intent is to have custom menu display at all times during store hours, you don't even need to define custom menu timings;
```Will remove custom menu timings```
> * custom group definitions (min/max/seq) is being duplicated inside the item definition that is customized using the custom group e.g. item 22e8e640-900c-11ee-9add-594f1f59b51a:MEsLvp1E5N-HX72m3e4KyL has custom group defn for CG1 duplicated inside this item;
```Okay, will remove item level custom group definition, we assumed that we had to mention it at item level too```
> * for the above item, price is 0 but default selection price range is 202/269; not sure how this was derived as couldn't find any default customization for this custom group;
```Will remove the default selection if price is 0, it is a mistake from our side```
> * what does "15" for item available qty mean?
> * does "15" for item max qty mean buyer can't buy > 15 of these items/
> ```That is correct, we don't have definitive amount of quantity available for each item. So we were passing 99(Unlimited) first, but as per your comment in previous logs feedback, we changed it to 15, meaning only 15 quantity available for user to order```

**Comment by BLR-0118** [comment]
RET11
====
1. /on_search:
- item available/max qty of "15" means what?
- item 2027f0b0-008a-11ef-89a4-e3845de3dd1c:MEsLvp1E5N-HX72m3e4KyL:BIN has default selection, which isn't required unless base price for this item is 0;
- also, default selection prices quoted are wrong: should be the price for the default customization for corresponding custom group;
- for provider MEsLvp1E5N-HX72m3e4KyL, several custom groups have max of "15" in config; however, there aren't that many customizations for these custom groups;

**Comment by BLR-0118** [comment]
2. logic for assigning ids for item & customizations can be improved - what's the point of encoding provider id inside item id & then base item & provider id inside customization id? this is poor design and not reusable;
3. bpp/providers.locations[].address shows state as "Lucknow"?

Flow 2
====
1. quote.ttl was 1 day in /on_select, changed to 4 days in /on_init?
2. /on_confirm:
- on what basis are pickup & delivery slots provided here, when order isn't yet accepted?
- after order is accepted, you need to make sure pickup & delivery slots align with TAT & time_to_ship e.g.:
- order is accepted at 12 noon; time_to_ship (/on_search) is 30 mins => order ready for pickup at 12:30 + S2D TAT should give the delivery slot;

3. /on_track:
- payload should be complete;

**Comment by BLR-0118** [comment]
flow 3 - ok;

**Comment by BLR-0118** [comment]
flow 4 - ok;

**Comment by BLR-0118** [comment]
flow 5
====
1. /on_cancel_rto:
- pls add start & end locations for rto fulfillment;
- no quote trail: means no refund? then, why was a new quote line item with 0 value added for rto fulfillment?

**Comment by BLR-0118** [comment]
flow 6 - ok;

**Comment by BLR-0118** [comment]
@venkat77777 - pls resubmit for flows 1, 2, 5;

**Comment by venkat77777** [comment]
`logic for assigning ids for item & customizations can be improved - what's the point of encoding provider id inside item id & then base item & provider id inside customization id? this is poor design and not reusable;`

@BLR-0118 in our current system, we have master catalog items which will have same id across multiple providers. So to identify a product from merchant, we have appended provider id. Similar reason for customization too.

We are restructuring our system soon, this design will changes in near future. Please accept as it is for now

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- all catalog items have max qty count of 10 - is the intent to cap count of each item at 10? For few items, looks ok but across the board raises questions;
- "max" config for CG1/CG2/CG3 for provider MEsLvp1E5N-HX72m3e4KyL is incorrect (max is 1 but there are 2 customizations assigned to each of these);
- for some items e.g. 2027f0b0-008a-11ef-89a4-e3845de3dd1c:MEsLvp1E5N-HX72m3e4KyL:BIN, both base price & upper/lower values provided (any reason);
- lots of catalog items should be in the form of custom groups for a much better UX, e.g.:
- 8ef48520-8ead-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Rogan Josh Chaap 300ml;
- ebe9b5f0-8f72-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Plain Nan Single;
- 0dd62f30-8f6a-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Chicken Hakka Noodles Half;
- d6258e30-8e99-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Chicken Malai Tikka 8pcs Full;
+ lots of others;

Flow 2
====
1. /on_select:
- item available/max qty in on_search is 99/10 (see pt above) but here it changes to 15/15: means what??

2. /on_status:
- pickup time is 07:20:41 (/on_status_picked), which becomes 07:21:24 (/on_status_out_for_delivery) & remains same in /on_status_delivered: which is the correct pickup time?

Flow 5
====
1. I hope you're closing RTO (didn't see RTO-Disposed / RTO-Delivered) with end location & timestamp;

**Comment by venkat77777** [comment]
> # Flow 1
> 1. /on_search:
> 
> * all catalog items have max qty count of 10 - is the intent to cap count of each item at 10? For few items, looks ok but across the board raises questions;

Yes, that's the intent in order to avoid bulk ordering and also to avoid issues from bulk order deliveries. We will internally build different max quantity for items as an enhancement, at the right time.

> * "max" config for CG1/CG2/CG3 for provider MEsLvp1E5N-HX72m3e4KyL is incorrect (max is 1 but there are 2 customizations assigned to each of these);

We'll fix this issue

> * for some items e.g. 2027f0b0-008a-11ef-89a4-e3845de3dd1c:MEsLvp1E5N-HX72m3e4KyL:BIN, both base price & upper/lower values provided (any reason);

We'll fix this

> * lots of catalog items should be in the form of custom groups for a much better UX, e.g.:
> * 8ef48520-8ead-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Rogan Josh Chaap 300ml;
> * ebe9b5f0-8f72-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Plain Nan Single;
> * 0dd62f30-8f6a-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Chicken Hakka Noodles Half;
> * d6258e30-8e99-11ee-a44f-050b3bd1670d:MEsLvp1E5N-HX72m3e4KyL - Chicken Malai Tikka 8pcs Full;
> 
> * lots of others;
> 
Yes, that's correct. This is the dummy catalog. In production you won't see any products like this as proper QC is done for merchant catalogue before taking merchant live.


> # Flow 2
> 1. /on_select:
> 
> * item available/max qty in on_search is 99/10 (see pt above) but here it changes to 15/15: means what??

Sorry. Missed this. We'll fix this.

> 
> 2. /on_status:
> 
> * pickup time is 07:20:41 (/on_status_picked), which becomes 07:21:24 (/on_status_out_for_delivery) & remains same in /on_status_delivered: which is the correct pickup time?
> 

Will check and fix this

> # Flow 5
> 1. I hope you're closing RTO (didn't see RTO-Disposed / RTO-Delivered) with end location & timestamp;

Yes. We are closing RTO and sending to buyer app as unsolicited on_status_cancelled with RTO-Disposed. You can find on_status_cancelled.json in Flow 5 with RTO-Disposed.

**Comment by BLR-0118** [comment]
@venkat77777 - logs cleared for RET11, subject to above issues being fixed before deploying in Prod;
